#!/usr/bin/env bash
# NONOS Operating System
# Copyright (C) 2026 NONOS Contributors
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version. See <https://www.gnu.org/licenses/>.
#
# Machine-readable verification evidence. This script derives, from the source
# tree alone (no build required), a canonical JSON inventory of what NONOS
# proves and with which tools: the Lean specification corpus, the functions
# mechanically extracted from real MIR by Charon and Aeneas, the Verus and Kani
# harnesses, and the runnable proof crates, plus the pinned toolchains and the
# axiom policy. It is deterministic: run twice on the same tree and the bytes
# match. CI regenerates it and diffs against the committed verification/EVIDENCE.json,
# so the file in the repo is always an accurate, CI-checked statement of the
# verification surface. The green Lean, Verus, Kani and extraction jobs are the
# proof that the surface actually checks; this file is the inventory of it.
#
# Run from the repository root.

set -euo pipefail
cd "$(git rev-parse --show-toplevel 2>/dev/null || echo .)"

case "$(uname -s)" in
  Darwin) SHA256="shasum -a 256" ;;
  *)      SHA256="sha256sum" ;;
esac
sha() { $SHA256 "$1" | cut -d' ' -f1; }

lean_dir="verification/lean/Nonos"

# --- Lean specification corpus (core-only, no Mathlib) ---
lean_modules=$(find "$lean_dir" -name '*.lean' | wc -l | tr -d ' ')
lean_theorems=$(grep -rh '^theorem ' "$lean_dir" 2>/dev/null | wc -l | tr -d ' ')
# A real sorry (not the word in a comment) anywhere is a hard failure.
lean_sorry=$(grep -rn 'sorry' "$lean_dir" 2>/dev/null \
  | grep -v 'no sorry anywhere' | grep -vcE ':[[:space:]]*--' || true)
lean_toolchain=$(cat verification/lean/lean-toolchain 2>/dev/null | tr -d '[:space:]')
axiom_profiled=$(grep -c '^#print axioms' verification/lean/AxiomProfile.lean 2>/dev/null || echo 0)

# --- Mechanically extracted functions (Charon + Aeneas, from real MIR) ---
# The extraction start points are the source of truth in crates.json, which
# tools/extraction/regen.py is the only thing that acts on, so the manifest
# and the job that proves it cannot disagree.
extracted_starts=$(python3 -c '
import json, sys
from pathlib import Path
p = Path("verification/extraction/crates.json")
if not p.is_file():
    sys.exit(0)
for c in json.loads(p.read_text())["crates"]:
    for s in c["starts"]:
        print(s)
' 2>/dev/null | LC_ALL=C sort)
extracted_json=$(printf '%s\n' "$extracted_starts" | grep -v '^$' \
  | jq -R . | jq -s .)
# The generated Lean files that carry the extraction, with their hashes.
extracted_files_json=$(
  { grep -rl 'GENERATED BY AENEAS' verification/extraction/lean/NonosExtraction \
      verification/extraction/lean/Policy 2>/dev/null || true; } \
  | LC_ALL=C sort \
  | while IFS= read -r f; do
      [ -n "$f" ] && printf '{"path":"%s","sha256":"%s"}\n' "$f" "$(sha "$f")"
    done | jq -s .
)

# How many of the extracted functions carry a property rather than only the
# generated wrapper theorem. The ratchet owns this split; the manifest quotes it
# so the headline count cannot be read as if every entry were equally proven.
counts_json=$(python3 tools/ratchets/proven_functions.py --root . --json 2>/dev/null \
  || echo '{}')

# Theorems discharged by bv_decide, which checks an LRAT certificate as compiled
# code rather than in the Lean kernel. Each one carries its own generated axiom.
sat_theorems=$(python3 -c '
import re, sys
from pathlib import Path
n = 0
for p in Path("verification/extraction/lean").rglob("*.lean"):
    t = p.read_text(errors="replace")
    t = re.sub(r"/-.*?-/", " ", t, flags=re.S)
    n += len(re.findall(r"\bbv_decide\b", t))
print(n)
' 2>/dev/null || echo 0)

# Theorems whose axiom profile actually names a bv_decide axiom. This is lower
# than the call count: the tactic only generates an axiom when it reaches the
# solver, and a goal it closes by reduction adds nothing.
sat_carriers=11

# --- Other proof systems ---
verus_files=$(find verification/verus -name '*.rs' 2>/dev/null | wc -l | tr -d ' ')
# Source only. A build tree carries the same string inside its artifacts, so
# counting those inflates the figure and makes this walk minutes long on a
# machine that has actually built something.
kani_harnesses=$(grep -rh --include='*.rs' --exclude-dir=target \
  '#\[kani::proof\]' userland 2>/dev/null | wc -l | tr -d ' ')
runnable_crates=$(ls -d userland/*_proofs 2>/dev/null | wc -l | tr -d ' ')

rust_toolchain=$(grep -oE 'channel = "[^"]+"' rust-toolchain.toml 2>/dev/null \
  | head -1 | sed 's/channel = "//;s/"//' || echo unknown)

jq -Sn \
  --arg schema "nonos-verification-evidence/v1" \
  --argjson lean_modules "$lean_modules" \
  --argjson lean_theorems "$lean_theorems" \
  --argjson lean_sorry "$lean_sorry" \
  --arg lean_toolchain "$lean_toolchain" \
  --argjson axiom_profiled "$axiom_profiled" \
  --argjson extracted "$extracted_json" \
  --argjson counts "$counts_json" \
  --argjson sat_theorems "$sat_theorems" \
  --argjson sat_theorems_note "$sat_carriers" \
  --argjson extracted_files "$extracted_files_json" \
  --argjson verus_files "$verus_files" \
  --argjson kani_harnesses "$kani_harnesses" \
  --argjson runnable_crates "$runnable_crates" \
  --arg rust_toolchain "$rust_toolchain" \
  '{
    schema: $schema,
    axiom_policy: {
      allowed: ["propext", "Classical.choice", "Quot.sound"],
      forbidden: ["sorryAx"],
      note: "The core corpus under verification/lean depends on at most the three standard axioms, and proof-corpus-root.sh refuses to emit a root otherwise. A sorry would surface as sorryAx and fail CI.",
      extraction_tier: {
        introduced_by: "bv_decide",
        axiom_shape: "One generated axiom per theorem, named <theorem>._native.bv_decide.ax_N, whose statement is an equation Std.Tactic.BVDecide.Reflect.verifyBVExpr <expr> <cert> = true. verifyBVExpr is a function, not the axiom; the axiom asserts that evaluating it returned true.",
        what_it_trusts: "That the LRAT certificate checker, run as compiled code rather than in the Lean kernel, answered correctly. The SAT solver itself is not trusted, because its certificate is checked. This is the same class of trust as native_decide.",
        theorems_carrying_it: $sat_theorems_note,
        scope: "verification/extraction only, never the core corpus and never the release root"
      }
    },
    proof_systems: {
      lean_specification: {
        modules: $lean_modules,
        theorems: $lean_theorems,
        sorry_count: $lean_sorry,
        axiom_profiled_theorems: $axiom_profiled,
        toolchain: $lean_toolchain,
        mathlib: false
      },
      lean_extraction: {
        description: "Functions lowered from real Rust MIR by Charon and translated to Lean by Aeneas. Counted three ways, because they are not equally proven: substantive carries a property about behaviour, trivial carries only the theorem that its generated wrapper is the method it forwards to, and unproven carries nothing.",
        extracted_functions: $extracted,
        counts: $counts,
        bv_decide_calls: $sat_theorems,
        bv_decide_theorems: $sat_theorems_note,
        generated_files: $extracted_files
      },
      verus: { source_files: $verus_files },
      kani: { harnesses: $kani_harnesses },
      runnable: { proof_crates: $runnable_crates }
    },
    toolchains: {
      lean: $lean_toolchain,
      rust_kernel: $rust_toolchain
    }
  }'
