/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

Specification-level security theorems, verified by Lean 4. Each is refined onto
the code that actually runs by the Verus / Kani / runnable proofs elsewhere in
`verification` and the `*_proofs` crates, so the abstract model is connected to
the implementation rather than standing apart from it. `Secure` composes the
per-operation lemmas into one invariant that holds after every trace.
-/

import Nonos.Answer
import Nonos.AntiRollback
import Nonos.AntiRollbackState
import Nonos.ApBringup
import Nonos.ArchiveStreams
import Nonos.ArgvBounds
import Nonos.Assurance
import Nonos.AttestBinding
import Nonos.Attestation
import Nonos.Authorization
import Nonos.Barrier
import Nonos.Bitmap
import Nonos.BlockIO
import Nonos.BootImage
import Nonos.Bounds
import Nonos.Buddy
import Nonos.CapMask
import Nonos.CapTable
import Nonos.CapToken
import Nonos.Capability
import Nonos.CapabilityBits
import Nonos.CcmpReplay
import Nonos.Cow
import Nonos.Crypto
import Nonos.CryptoGf256
import Nonos.CryptoKeccakAddr
import Nonos.CryptoKeccakPad
import Nonos.CryptoLowS
import Nonos.CryptoRfc6979
import Nonos.CryptoSecretValid
import Nonos.Delegation
import Nonos.DemandPaging
import Nonos.Dhcp
import Nonos.Dispatch
import Nonos.DmaMap
import Nonos.DnsAutomap
import Nonos.ElfPhdr
import Nonos.ElfReloc
import Nonos.Endpoint
import Nonos.Epoch
import Nonos.Fairness
import Nonos.Fd
import Nonos.FdAlloc
import Nonos.ForeignBoundary
import Nonos.FpuState
import Nonos.FrameNoAlias
import Nonos.FramebufferSwap
import Nonos.Futex
import Nonos.GateLayers
import Nonos.GsiRouting
import Nonos.GuestLayout
import Nonos.Heap
import Nonos.ImageCeiling
import Nonos.ImageStaging
import Nonos.InputConsumer
import Nonos.Interval
import Nonos.Iommu
import Nonos.Ipc
import Nonos.IrqBind
import Nonos.Isolation
import Nonos.KeyLifecycle
import Nonos.KeyringCustody
import Nonos.LoadProtect
import Nonos.Loader
import Nonos.LocalSign
import Nonos.MemGrant
import Nonos.Mmio
import Nonos.MsixExclusion
import Nonos.MultiSig
import Nonos.Mutex
import Nonos.NetParse
import Nonos.NonInterference
import Nonos.Nonce
import Nonos.PageDescriptor
import Nonos.PageTable
import Nonos.Paging
import Nonos.Path
import Nonos.PciCmdWrite
import Nonos.PerCpuAsid
import Nonos.PidAlloc
import Nonos.PodBound
import Nonos.Priority
import Nonos.Provenance
import Nonos.Quota
import Nonos.Reachability
import Nonos.Reaper
import Nonos.Refcount
import Nonos.ReplyAuthorization
import Nonos.ReplyCorrelation
import Nonos.Rflags
import Nonos.Ring
import Nonos.Rng
import Nonos.Rwlock
import Nonos.Scheduler
import Nonos.Secure
import Nonos.SeedCustody
import Nonos.Semaphore
import Nonos.Seqlock
import Nonos.ServiceRegisterAuth
import Nonos.ServiceRegistry
import Nonos.Signal
import Nonos.SigningKey
import Nonos.Spawn
import Nonos.SpawnCaps
import Nonos.Spinlock
import Nonos.Stark.AssociationSet
import Nonos.Stark.Attest
import Nonos.Stark.AttestSoundness
import Nonos.Stark.Blinding
import Nonos.Stark.BootChain
import Nonos.Stark.CapabilityBinding
import Nonos.Stark.ChallengeDrawing
import Nonos.Stark.Commitment
import Nonos.Stark.Constraint
import Nonos.Stark.ContextBinding
import Nonos.Stark.ContextLayout
import Nonos.Stark.CopyConstraint
import Nonos.Stark.DomainSeparation
import Nonos.Stark.Enrollment
import Nonos.Stark.Extension
import Nonos.Stark.FeeRouter
import Nonos.Stark.FiatShamir
import Nonos.Stark.Field
import Nonos.Stark.FieldBound
import Nonos.Stark.Fold
import Nonos.Stark.Fri
import Nonos.Stark.IndexBits
import Nonos.Stark.Instance
import Nonos.Stark.Lookup
import Nonos.Stark.Measurement
import Nonos.Stark.Membership
import Nonos.Stark.Merkle
import Nonos.Stark.NullifierSet
import Nonos.Stark.Permutation
import Nonos.Stark.PolicyEpoch
import Nonos.Stark.Polynomial
import Nonos.Stark.Pool
import Nonos.Stark.ProofOfWork
import Nonos.Stark.QueryIndex
import Nonos.Stark.RootConsistency
import Nonos.Stark.RootWindow
import Nonos.Stark.RunningSum
import Nonos.Stark.Serialization
import Nonos.Stark.Soundness
import Nonos.Stark.Staking
import Nonos.Stark.Trailer
import Nonos.Stark.Transcript
import Nonos.StationAddress
import Nonos.StoreRoot
import Nonos.Syscall
import Nonos.SyscallRoute
import Nonos.Tcp
import Nonos.Ticket
import Nonos.Timer
import Nonos.TimerLiveness
import Nonos.Tlb
import Nonos.TokenBucket
import Nonos.TrapEntry
import Nonos.UsbHid
import Nonos.UserCopy
import Nonos.UserWalk
import Nonos.Vfs
import Nonos.Vma
import Nonos.WalletCallerPid
import Nonos.WalletCustodyOwner
import Nonos.WalletEip1559
import Nonos.WalletFormatApr
import Nonos.WalletFormatNox
import Nonos.WalletGwei
import Nonos.WalletHdRecover
import Nonos.WalletHex
import Nonos.WalletImportWipe
import Nonos.WalletNonceReplay
import Nonos.WalletNoxApr
import Nonos.WalletNoxCalldata
import Nonos.WalletParseWord
import Nonos.WalletQuantity
import Nonos.WalletRlp
import Nonos.WalletSeedSeal
import Nonos.WalletShortAddr
import Nonos.WalletTxEnvelope
import Nonos.Wpa2Handshake
import Nonos.ZeroState
import Nonos.Zeroization
import Nonos.Zeroize
