// NONOS Operating System (AGPL-3.0-or-later)

pub mod idt;

pub use idt::{InterruptFrame, IRQ_BASE, VEC_BREAKPOINT, VEC_DEBUG, VEC_DIVIDE_ERROR, VEC_DOUBLE_FAULT, VEC_GENERAL_PROTECTION, VEC_NMI, VEC_PAGE_FAULT};
