/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

fadt_boot, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.AcpiTablesFadtFadtBoot

open Aeneas Aeneas.Std Result
open nonos_x_acpi_tables_fadt_fadt_boot

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.AcpiTablesFadtFadtBoot

/-! ### The forwarding functions add nothing -/

theorem the_fadt_has_8042_wrapper_is_its_method (a : arch.x86_64.acpi.tables.fadt.fadt_struct.Fadt) :
    fadt_has_8042 a = arch.x86_64.acpi.tables.fadt.fadt_boot.Fadt.has_8042 a := rfl

theorem the_fadt_has_legacy_devices_wrapper_is_its_method (a : arch.x86_64.acpi.tables.fadt.fadt_struct.Fadt) :
    fadt_has_legacy_devices a = arch.x86_64.acpi.tables.fadt.fadt_boot.Fadt.has_legacy_devices a := rfl

theorem the_fadt_has_vga_wrapper_is_its_method (a : arch.x86_64.acpi.tables.fadt.fadt_struct.Fadt) :
    fadt_has_vga a = arch.x86_64.acpi.tables.fadt.fadt_boot.Fadt.has_vga a := rfl

theorem the_fadt_has_msi_wrapper_is_its_method (a : arch.x86_64.acpi.tables.fadt.fadt_struct.Fadt) :
    fadt_has_msi a = arch.x86_64.acpi.tables.fadt.fadt_boot.Fadt.has_msi a := rfl

theorem the_fadt_has_cmos_rtc_wrapper_is_its_method (a : arch.x86_64.acpi.tables.fadt.fadt_struct.Fadt) :
    fadt_has_cmos_rtc a = arch.x86_64.acpi.tables.fadt.fadt_boot.Fadt.has_cmos_rtc a := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.AcpiTablesFadtFadtBoot.the_fadt_has_8042_wrapper_is_its_method
#print axioms NonosExtraction.AcpiTablesFadtFadtBoot.the_fadt_has_legacy_devices_wrapper_is_its_method
#print axioms NonosExtraction.AcpiTablesFadtFadtBoot.the_fadt_has_vga_wrapper_is_its_method
#print axioms NonosExtraction.AcpiTablesFadtFadtBoot.the_fadt_has_msi_wrapper_is_its_method
#print axioms NonosExtraction.AcpiTablesFadtFadtBoot.the_fadt_has_cmos_rtc_wrapper_is_its_method

end NonosExtraction.AcpiTablesFadtFadtBoot
