/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

fadt_methods, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.AcpiTablesFadtFadtMethods

open Aeneas Aeneas.Std Result
open nonos_x_acpi_tables_fadt_fadt_methods

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.AcpiTablesFadtFadtMethods

/-! ### The forwarding functions add nothing -/

theorem the_fadt_has_reset_register_wrapper_is_its_method (a : arch.x86_64.acpi.tables.fadt.fadt_struct.Fadt) :
    fadt_has_reset_register a = arch.x86_64.acpi.tables.fadt.fadt_methods.Fadt.has_reset_register a := rfl

theorem the_fadt_is_hw_reduced_wrapper_is_its_method (a : arch.x86_64.acpi.tables.fadt.fadt_struct.Fadt) :
    fadt_is_hw_reduced a = arch.x86_64.acpi.tables.fadt.fadt_methods.Fadt.is_hw_reduced a := rfl

theorem the_fadt_is_pm_timer_32bit_wrapper_is_its_method (a : arch.x86_64.acpi.tables.fadt.fadt_struct.Fadt) :
    fadt_is_pm_timer_32bit a = arch.x86_64.acpi.tables.fadt.fadt_methods.Fadt.is_pm_timer_32bit a := rfl

theorem the_fadt_supports_low_power_s0_wrapper_is_its_method (a : arch.x86_64.acpi.tables.fadt.fadt_struct.Fadt) :
    fadt_supports_low_power_s0 a = arch.x86_64.acpi.tables.fadt.fadt_methods.Fadt.supports_low_power_s0 a := rfl

theorem the_fadt_sci_interrupt_wrapper_is_its_method (a : arch.x86_64.acpi.tables.fadt.fadt_struct.Fadt) :
    fadt_sci_interrupt a = arch.x86_64.acpi.tables.fadt.fadt_methods.Fadt.sci_interrupt a := rfl

theorem the_fadt_c2_latency_us_wrapper_is_its_method (a : arch.x86_64.acpi.tables.fadt.fadt_struct.Fadt) :
    fadt_c2_latency_us a = arch.x86_64.acpi.tables.fadt.fadt_methods.Fadt.c2_latency_us a := rfl

theorem the_fadt_c3_latency_us_wrapper_is_its_method (a : arch.x86_64.acpi.tables.fadt.fadt_struct.Fadt) :
    fadt_c3_latency_us a = arch.x86_64.acpi.tables.fadt.fadt_methods.Fadt.c3_latency_us a := rfl

theorem the_fadt_supports_c2_wrapper_is_its_method (a : arch.x86_64.acpi.tables.fadt.fadt_struct.Fadt) :
    fadt_supports_c2 a = arch.x86_64.acpi.tables.fadt.fadt_methods.Fadt.supports_c2 a := rfl

theorem the_fadt_supports_c3_wrapper_is_its_method (a : arch.x86_64.acpi.tables.fadt.fadt_struct.Fadt) :
    fadt_supports_c3 a = arch.x86_64.acpi.tables.fadt.fadt_methods.Fadt.supports_c3 a := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.AcpiTablesFadtFadtMethods.the_fadt_has_reset_register_wrapper_is_its_method
#print axioms NonosExtraction.AcpiTablesFadtFadtMethods.the_fadt_is_hw_reduced_wrapper_is_its_method
#print axioms NonosExtraction.AcpiTablesFadtFadtMethods.the_fadt_is_pm_timer_32bit_wrapper_is_its_method
#print axioms NonosExtraction.AcpiTablesFadtFadtMethods.the_fadt_supports_low_power_s0_wrapper_is_its_method
#print axioms NonosExtraction.AcpiTablesFadtFadtMethods.the_fadt_sci_interrupt_wrapper_is_its_method
#print axioms NonosExtraction.AcpiTablesFadtFadtMethods.the_fadt_c2_latency_us_wrapper_is_its_method
#print axioms NonosExtraction.AcpiTablesFadtFadtMethods.the_fadt_c3_latency_us_wrapper_is_its_method
#print axioms NonosExtraction.AcpiTablesFadtFadtMethods.the_fadt_supports_c2_wrapper_is_its_method
#print axioms NonosExtraction.AcpiTablesFadtFadtMethods.the_fadt_supports_c3_wrapper_is_its_method

end NonosExtraction.AcpiTablesFadtFadtMethods
