-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [nonos_x_acpi_tables_madt_interrupt]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace nonos_x_acpi_tables_madt_interrupt

/-- [nonos_x_acpi_tables_madt_interrupt::arch::x86_64::acpi::tables::madt::header::MadtEntryHeader]
    Source: 'src/arch/x86_64/acpi/tables/madt/../../../../../../../../../../src/arch/x86_64/acpi/tables/madt/header.rs', lines 51:0-54:1
    Visibility: public -/
structure arch.x86_64.acpi.tables.madt.header.MadtEntryHeader where
  entry_type : Std.U8
  length : Std.U8

/-- [nonos_x_acpi_tables_madt_interrupt::arch::x86_64::acpi::tables::madt::interrupt::MadtInterruptOverride]
    Source: 'src/arch/x86_64/acpi/tables/madt/../../../../../../../../../../src/arch/x86_64/acpi/tables/madt/interrupt.rs', lines 21:0-27:1
    Visibility: public -/
structure arch.x86_64.acpi.tables.madt.interrupt.MadtInterruptOverride where
  header : arch.x86_64.acpi.tables.madt.header.MadtEntryHeader
  bus : Std.U8
  source : Std.U8
  gsi : Std.U32
  flags : Std.U16

/-- [nonos_x_acpi_tables_madt_interrupt::arch::x86_64::acpi::tables::madt::interrupt::{nonos_x_acpi_tables_madt_interrupt::arch::x86_64::acpi::tables::madt::interrupt::MadtInterruptOverride}::POLARITY_MASK]
    Source: 'src/arch/x86_64/acpi/tables/madt/../../../../../../../../../../src/arch/x86_64/acpi/tables/madt/interrupt.rs', lines 30:4-30:40
    Visibility: public -/
@[global_simps, irreducible]
def arch.x86_64.acpi.tables.madt.interrupt.MadtInterruptOverride.POLARITY_MASK
  : Std.U16 :=
  3#u16

/-- [nonos_x_acpi_tables_madt_interrupt::arch::x86_64::acpi::tables::madt::interrupt::{nonos_x_acpi_tables_madt_interrupt::arch::x86_64::acpi::tables::madt::interrupt::MadtInterruptOverride}::TRIGGER_MASK]
    Source: 'src/arch/x86_64/acpi/tables/madt/../../../../../../../../../../src/arch/x86_64/acpi/tables/madt/interrupt.rs', lines 31:4-31:39
    Visibility: public -/
@[global_simps, irreducible]
def arch.x86_64.acpi.tables.madt.interrupt.MadtInterruptOverride.TRIGGER_MASK
  : Std.U16 :=
  12#u16

/-- [nonos_x_acpi_tables_madt_interrupt::arch::x86_64::acpi::tables::madt::interrupt::{nonos_x_acpi_tables_madt_interrupt::arch::x86_64::acpi::tables::madt::interrupt::MadtInterruptOverride}::TRIGGER_SHIFT]
    Source: 'src/arch/x86_64/acpi/tables/madt/../../../../../../../../../../src/arch/x86_64/acpi/tables/madt/interrupt.rs', lines 32:4-32:37
    Visibility: public -/
@[global_simps, irreducible]
def arch.x86_64.acpi.tables.madt.interrupt.MadtInterruptOverride.TRIGGER_SHIFT
  : Std.U16 :=
  2#u16

/-- [nonos_x_acpi_tables_madt_interrupt::arch::x86_64::acpi::tables::madt::interrupt::{nonos_x_acpi_tables_madt_interrupt::arch::x86_64::acpi::tables::madt::interrupt::MadtInterruptOverride}::polarity]:
    Source: 'src/arch/x86_64/acpi/tables/madt/../../../../../../../../../../src/arch/x86_64/acpi/tables/madt/interrupt.rs', lines 34:4-36:5
    Visibility: public -/
def arch.x86_64.acpi.tables.madt.interrupt.MadtInterruptOverride.polarity
  (self : arch.x86_64.acpi.tables.madt.interrupt.MadtInterruptOverride) :
  Result Std.U8
  := do
  let i ←
    lift (self.flags &&&
      arch.x86_64.acpi.tables.madt.interrupt.MadtInterruptOverride.POLARITY_MASK)
  ok (UScalar.cast .U8 i)

/-- [nonos_x_acpi_tables_madt_interrupt::arch::x86_64::acpi::tables::madt::interrupt::{nonos_x_acpi_tables_madt_interrupt::arch::x86_64::acpi::tables::madt::interrupt::MadtInterruptOverride}::trigger_mode]:
    Source: 'src/arch/x86_64/acpi/tables/madt/../../../../../../../../../../src/arch/x86_64/acpi/tables/madt/interrupt.rs', lines 38:4-40:5
    Visibility: public -/
def arch.x86_64.acpi.tables.madt.interrupt.MadtInterruptOverride.trigger_mode
  (self : arch.x86_64.acpi.tables.madt.interrupt.MadtInterruptOverride) :
  Result Std.U8
  := do
  let i ←
    lift (self.flags &&&
      arch.x86_64.acpi.tables.madt.interrupt.MadtInterruptOverride.TRIGGER_MASK)
  let i1 ←
    i >>>
      arch.x86_64.acpi.tables.madt.interrupt.MadtInterruptOverride.TRIGGER_SHIFT
  ok (UScalar.cast .U8 i1)

/-- [nonos_x_acpi_tables_madt_interrupt::arch::x86_64::acpi::tables::madt::interrupt::{nonos_x_acpi_tables_madt_interrupt::arch::x86_64::acpi::tables::madt::interrupt::MadtInterruptOverride}::is_active_low]:
    Source: 'src/arch/x86_64/acpi/tables/madt/../../../../../../../../../../src/arch/x86_64/acpi/tables/madt/interrupt.rs', lines 42:4-44:5
    Visibility: public -/
def arch.x86_64.acpi.tables.madt.interrupt.MadtInterruptOverride.is_active_low
  (self : arch.x86_64.acpi.tables.madt.interrupt.MadtInterruptOverride) :
  Result Bool
  := do
  let i ←
    arch.x86_64.acpi.tables.madt.interrupt.MadtInterruptOverride.polarity self
  ok (i = 3#u8)

/-- [nonos_x_acpi_tables_madt_interrupt::arch::x86_64::acpi::tables::madt::interrupt::{nonos_x_acpi_tables_madt_interrupt::arch::x86_64::acpi::tables::madt::interrupt::MadtInterruptOverride}::is_level_triggered]:
    Source: 'src/arch/x86_64/acpi/tables/madt/../../../../../../../../../../src/arch/x86_64/acpi/tables/madt/interrupt.rs', lines 46:4-48:5
    Visibility: public -/
def
  arch.x86_64.acpi.tables.madt.interrupt.MadtInterruptOverride.is_level_triggered
  (self : arch.x86_64.acpi.tables.madt.interrupt.MadtInterruptOverride) :
  Result Bool
  := do
  let i ←
    arch.x86_64.acpi.tables.madt.interrupt.MadtInterruptOverride.trigger_mode
      self
  ok (i = 3#u8)

/-- [nonos_x_acpi_tables_madt_interrupt::arch::x86_64::acpi::tables::madt::interrupt::{nonos_x_acpi_tables_madt_interrupt::arch::x86_64::acpi::tables::madt::interrupt::MadtInterruptOverride}::is_edge_triggered]:
    Source: 'src/arch/x86_64/acpi/tables/madt/../../../../../../../../../../src/arch/x86_64/acpi/tables/madt/interrupt.rs', lines 50:4-52:5
    Visibility: public -/
def
  arch.x86_64.acpi.tables.madt.interrupt.MadtInterruptOverride.is_edge_triggered
  (self : arch.x86_64.acpi.tables.madt.interrupt.MadtInterruptOverride) :
  Result Bool
  := do
  let i ←
    arch.x86_64.acpi.tables.madt.interrupt.MadtInterruptOverride.trigger_mode
      self
  ok (i = 1#u8)

/-- [nonos_x_acpi_tables_madt_interrupt::arch::x86_64::acpi::tables::madt::interrupt::{nonos_x_acpi_tables_madt_interrupt::arch::x86_64::acpi::tables::madt::interrupt::MadtInterruptOverride}::is_active_high]:
    Source: 'src/arch/x86_64/acpi/tables/madt/../../../../../../../../../../src/arch/x86_64/acpi/tables/madt/interrupt.rs', lines 54:4-56:5
    Visibility: public -/
def arch.x86_64.acpi.tables.madt.interrupt.MadtInterruptOverride.is_active_high
  (self : arch.x86_64.acpi.tables.madt.interrupt.MadtInterruptOverride) :
  Result Bool
  := do
  let i ←
    arch.x86_64.acpi.tables.madt.interrupt.MadtInterruptOverride.polarity self
  ok (i = 1#u8)

/-- [nonos_x_acpi_tables_madt_interrupt::arch::x86_64::acpi::tables::madt::interrupt::MadtNmiSource]
    Source: 'src/arch/x86_64/acpi/tables/madt/../../../../../../../../../../src/arch/x86_64/acpi/tables/madt/interrupt.rs', lines 61:0-65:1
    Visibility: public -/
structure arch.x86_64.acpi.tables.madt.interrupt.MadtNmiSource where
  header : arch.x86_64.acpi.tables.madt.header.MadtEntryHeader
  flags : Std.U16
  gsi : Std.U32

/-- [nonos_x_acpi_tables_madt_interrupt::arch::x86_64::acpi::tables::madt::interrupt::{nonos_x_acpi_tables_madt_interrupt::arch::x86_64::acpi::tables::madt::interrupt::MadtNmiSource}::polarity]:
    Source: 'src/arch/x86_64/acpi/tables/madt/../../../../../../../../../../src/arch/x86_64/acpi/tables/madt/interrupt.rs', lines 68:4-70:5
    Visibility: public -/
def arch.x86_64.acpi.tables.madt.interrupt.MadtNmiSource.polarity
  (self : arch.x86_64.acpi.tables.madt.interrupt.MadtNmiSource) :
  Result Std.U8
  := do
  let i ← lift (self.flags &&& 3#u16)
  ok (UScalar.cast .U8 i)

/-- [nonos_x_acpi_tables_madt_interrupt::arch::x86_64::acpi::tables::madt::interrupt::{nonos_x_acpi_tables_madt_interrupt::arch::x86_64::acpi::tables::madt::interrupt::MadtNmiSource}::trigger_mode]:
    Source: 'src/arch/x86_64/acpi/tables/madt/../../../../../../../../../../src/arch/x86_64/acpi/tables/madt/interrupt.rs', lines 72:4-74:5
    Visibility: public -/
def arch.x86_64.acpi.tables.madt.interrupt.MadtNmiSource.trigger_mode
  (self : arch.x86_64.acpi.tables.madt.interrupt.MadtNmiSource) :
  Result Std.U8
  := do
  let i ← self.flags >>> 2#i32
  let i1 ← lift (i &&& 3#u16)
  ok (UScalar.cast .U8 i1)

/-- [nonos_x_acpi_tables_madt_interrupt::madtinterruptoverride_polarity]:
    Source: 'src/lib.rs', lines 11:0-13:1
    Visibility: public -/
def madtinterruptoverride_polarity
  (this : arch.x86_64.acpi.tables.madt.interrupt.MadtInterruptOverride) :
  Result Std.U8
  := do
  arch.x86_64.acpi.tables.madt.interrupt.MadtInterruptOverride.polarity this

/-- [nonos_x_acpi_tables_madt_interrupt::madtinterruptoverride_trigger_mode]:
    Source: 'src/lib.rs', lines 15:0-17:1
    Visibility: public -/
def madtinterruptoverride_trigger_mode
  (this : arch.x86_64.acpi.tables.madt.interrupt.MadtInterruptOverride) :
  Result Std.U8
  := do
  arch.x86_64.acpi.tables.madt.interrupt.MadtInterruptOverride.trigger_mode
    this

/-- [nonos_x_acpi_tables_madt_interrupt::madtinterruptoverride_is_active_low]:
    Source: 'src/lib.rs', lines 19:0-21:1
    Visibility: public -/
def madtinterruptoverride_is_active_low
  (this : arch.x86_64.acpi.tables.madt.interrupt.MadtInterruptOverride) :
  Result Bool
  := do
  arch.x86_64.acpi.tables.madt.interrupt.MadtInterruptOverride.is_active_low
    this

/-- [nonos_x_acpi_tables_madt_interrupt::madtinterruptoverride_is_level_triggered]:
    Source: 'src/lib.rs', lines 23:0-25:1
    Visibility: public -/
def madtinterruptoverride_is_level_triggered
  (this : arch.x86_64.acpi.tables.madt.interrupt.MadtInterruptOverride) :
  Result Bool
  := do
  arch.x86_64.acpi.tables.madt.interrupt.MadtInterruptOverride.is_level_triggered
    this

/-- [nonos_x_acpi_tables_madt_interrupt::madtinterruptoverride_is_edge_triggered]:
    Source: 'src/lib.rs', lines 27:0-29:1
    Visibility: public -/
def madtinterruptoverride_is_edge_triggered
  (this : arch.x86_64.acpi.tables.madt.interrupt.MadtInterruptOverride) :
  Result Bool
  := do
  arch.x86_64.acpi.tables.madt.interrupt.MadtInterruptOverride.is_edge_triggered
    this

/-- [nonos_x_acpi_tables_madt_interrupt::madtinterruptoverride_is_active_high]:
    Source: 'src/lib.rs', lines 31:0-33:1
    Visibility: public -/
def madtinterruptoverride_is_active_high
  (this : arch.x86_64.acpi.tables.madt.interrupt.MadtInterruptOverride) :
  Result Bool
  := do
  arch.x86_64.acpi.tables.madt.interrupt.MadtInterruptOverride.is_active_high
    this

/-- [nonos_x_acpi_tables_madt_interrupt::madtnmisource_polarity]:
    Source: 'src/lib.rs', lines 35:0-37:1
    Visibility: public -/
def madtnmisource_polarity
  (this : arch.x86_64.acpi.tables.madt.interrupt.MadtNmiSource) :
  Result Std.U8
  := do
  arch.x86_64.acpi.tables.madt.interrupt.MadtNmiSource.polarity this

/-- [nonos_x_acpi_tables_madt_interrupt::madtnmisource_trigger_mode]:
    Source: 'src/lib.rs', lines 39:0-41:1
    Visibility: public -/
def madtnmisource_trigger_mode
  (this : arch.x86_64.acpi.tables.madt.interrupt.MadtNmiSource) :
  Result Std.U8
  := do
  arch.x86_64.acpi.tables.madt.interrupt.MadtNmiSource.trigger_mode this

end nonos_x_acpi_tables_madt_interrupt
