/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

interrupt, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.AcpiTablesMadtInterrupt

open Aeneas Aeneas.Std Result
open nonos_x_acpi_tables_madt_interrupt

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.AcpiTablesMadtInterrupt

/-! ### The forwarding functions add nothing -/

theorem the_madtinterruptoverride_polarity_wrapper_is_its_method (a : arch.x86_64.acpi.tables.madt.interrupt.MadtInterruptOverride) :
    madtinterruptoverride_polarity a = arch.x86_64.acpi.tables.madt.interrupt.MadtInterruptOverride.polarity a := rfl

theorem the_madtinterruptoverride_trigger_mode_wrapper_is_its_method (a : arch.x86_64.acpi.tables.madt.interrupt.MadtInterruptOverride) :
    madtinterruptoverride_trigger_mode a = arch.x86_64.acpi.tables.madt.interrupt.MadtInterruptOverride.trigger_mode a := rfl

theorem the_madtinterruptoverride_is_active_low_wrapper_is_its_method (a : arch.x86_64.acpi.tables.madt.interrupt.MadtInterruptOverride) :
    madtinterruptoverride_is_active_low a = arch.x86_64.acpi.tables.madt.interrupt.MadtInterruptOverride.is_active_low a := rfl

theorem the_madtinterruptoverride_is_level_triggered_wrapper_is_its_method (a : arch.x86_64.acpi.tables.madt.interrupt.MadtInterruptOverride) :
    madtinterruptoverride_is_level_triggered a = arch.x86_64.acpi.tables.madt.interrupt.MadtInterruptOverride.is_level_triggered a := rfl

theorem the_madtinterruptoverride_is_edge_triggered_wrapper_is_its_method (a : arch.x86_64.acpi.tables.madt.interrupt.MadtInterruptOverride) :
    madtinterruptoverride_is_edge_triggered a = arch.x86_64.acpi.tables.madt.interrupt.MadtInterruptOverride.is_edge_triggered a := rfl

theorem the_madtinterruptoverride_is_active_high_wrapper_is_its_method (a : arch.x86_64.acpi.tables.madt.interrupt.MadtInterruptOverride) :
    madtinterruptoverride_is_active_high a = arch.x86_64.acpi.tables.madt.interrupt.MadtInterruptOverride.is_active_high a := rfl

theorem the_madtnmisource_polarity_wrapper_is_its_method (a : arch.x86_64.acpi.tables.madt.interrupt.MadtNmiSource) :
    madtnmisource_polarity a = arch.x86_64.acpi.tables.madt.interrupt.MadtNmiSource.polarity a := rfl

theorem the_madtnmisource_trigger_mode_wrapper_is_its_method (a : arch.x86_64.acpi.tables.madt.interrupt.MadtNmiSource) :
    madtnmisource_trigger_mode a = arch.x86_64.acpi.tables.madt.interrupt.MadtNmiSource.trigger_mode a := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.AcpiTablesMadtInterrupt.the_madtinterruptoverride_polarity_wrapper_is_its_method
#print axioms NonosExtraction.AcpiTablesMadtInterrupt.the_madtinterruptoverride_trigger_mode_wrapper_is_its_method
#print axioms NonosExtraction.AcpiTablesMadtInterrupt.the_madtinterruptoverride_is_active_low_wrapper_is_its_method
#print axioms NonosExtraction.AcpiTablesMadtInterrupt.the_madtinterruptoverride_is_level_triggered_wrapper_is_its_method
#print axioms NonosExtraction.AcpiTablesMadtInterrupt.the_madtinterruptoverride_is_edge_triggered_wrapper_is_its_method
#print axioms NonosExtraction.AcpiTablesMadtInterrupt.the_madtinterruptoverride_is_active_high_wrapper_is_its_method
#print axioms NonosExtraction.AcpiTablesMadtInterrupt.the_madtnmisource_polarity_wrapper_is_its_method
#print axioms NonosExtraction.AcpiTablesMadtInterrupt.the_madtnmisource_trigger_mode_wrapper_is_its_method

end NonosExtraction.AcpiTablesMadtInterrupt
