/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

generic_address, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.AcpiTablesSdtGenericAddress

open Aeneas Aeneas.Std Result
open nonos_x_acpi_tables_sdt_generic_address

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.AcpiTablesSdtGenericAddress

/-! ### The forwarding functions add nothing -/

theorem the_genericaddress_empty_wrapper_is_its_method :
    genericaddress_empty = arch.x86_64.acpi.tables.sdt.generic_address.GenericAddress.empty := rfl

theorem the_genericaddress_is_valid_wrapper_is_its_method (a : arch.x86_64.acpi.tables.sdt.generic_address.GenericAddress) :
    genericaddress_is_valid a = arch.x86_64.acpi.tables.sdt.generic_address.GenericAddress.is_valid a := rfl

theorem the_genericaddress_is_memory_wrapper_is_its_method (a : arch.x86_64.acpi.tables.sdt.generic_address.GenericAddress) :
    genericaddress_is_memory a = arch.x86_64.acpi.tables.sdt.generic_address.GenericAddress.is_memory a := rfl

theorem the_genericaddress_is_io_wrapper_is_its_method (a : arch.x86_64.acpi.tables.sdt.generic_address.GenericAddress) :
    genericaddress_is_io a = arch.x86_64.acpi.tables.sdt.generic_address.GenericAddress.is_io a := rfl

theorem the_genericaddress_access_bytes_wrapper_is_its_method (a : arch.x86_64.acpi.tables.sdt.generic_address.GenericAddress) :
    genericaddress_access_bytes a = arch.x86_64.acpi.tables.sdt.generic_address.GenericAddress.access_bytes a := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.AcpiTablesSdtGenericAddress.the_genericaddress_empty_wrapper_is_its_method
#print axioms NonosExtraction.AcpiTablesSdtGenericAddress.the_genericaddress_is_valid_wrapper_is_its_method
#print axioms NonosExtraction.AcpiTablesSdtGenericAddress.the_genericaddress_is_memory_wrapper_is_its_method
#print axioms NonosExtraction.AcpiTablesSdtGenericAddress.the_genericaddress_is_io_wrapper_is_its_method
#print axioms NonosExtraction.AcpiTablesSdtGenericAddress.the_genericaddress_access_bytes_wrapper_is_its_method

end NonosExtraction.AcpiTablesSdtGenericAddress
