/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

x2apic_nmi, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.AcpiTablesMadtX2apicNmi

open Aeneas Aeneas.Std Result
open nonos_x_acpi_tables_madt_x2apic_nmi

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.AcpiTablesMadtX2apicNmi

/-! ### The forwarding functions add nothing -/

theorem the_madtlocalx2apicnmi_applies_to_all_wrapper_is_its_method (a : arch.x86_64.acpi.tables.madt.x2apic_nmi.MadtLocalX2ApicNmi) :
    madtlocalx2apicnmi_applies_to_all a = arch.x86_64.acpi.tables.madt.x2apic_nmi.MadtLocalX2ApicNmi.applies_to_all a := rfl

theorem the_madtlocalx2apicnmi_polarity_wrapper_is_its_method (a : arch.x86_64.acpi.tables.madt.x2apic_nmi.MadtLocalX2ApicNmi) :
    madtlocalx2apicnmi_polarity a = arch.x86_64.acpi.tables.madt.x2apic_nmi.MadtLocalX2ApicNmi.polarity a := rfl

theorem the_madtlocalx2apicnmi_trigger_mode_wrapper_is_its_method (a : arch.x86_64.acpi.tables.madt.x2apic_nmi.MadtLocalX2ApicNmi) :
    madtlocalx2apicnmi_trigger_mode a = arch.x86_64.acpi.tables.madt.x2apic_nmi.MadtLocalX2ApicNmi.trigger_mode a := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.AcpiTablesMadtX2apicNmi.the_madtlocalx2apicnmi_applies_to_all_wrapper_is_its_method
#print axioms NonosExtraction.AcpiTablesMadtX2apicNmi.the_madtlocalx2apicnmi_polarity_wrapper_is_its_method
#print axioms NonosExtraction.AcpiTablesMadtX2apicNmi.the_madtlocalx2apicnmi_trigger_mode_wrapper_is_its_method

end NonosExtraction.AcpiTablesMadtX2apicNmi
