-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [nonos_x_acpi_tables_fadt_fadt_methods]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace nonos_x_acpi_tables_fadt_fadt_methods

/-- [nonos_x_acpi_tables_fadt_fadt_methods::arch::x86_64::acpi::tables::sdt::generic_address::GenericAddress]
    Source: 'src/arch/x86_64/acpi/tables/../../../../../../../../../src/arch/x86_64/acpi/tables/sdt/generic_address.rs', lines 21:0-27:1
    Visibility: public -/
structure arch.x86_64.acpi.tables.sdt.generic_address.GenericAddress where
  address_space : Std.U8
  bit_width : Std.U8
  bit_offset : Std.U8
  access_size : Std.U8
  address : Std.U64

/-- [nonos_x_acpi_tables_fadt_fadt_methods::arch::x86_64::acpi::tables::sdt::generic_address::{nonos_x_acpi_tables_fadt_fadt_methods::arch::x86_64::acpi::tables::sdt::generic_address::GenericAddress}::is_valid]:
    Source: 'src/arch/x86_64/acpi/tables/../../../../../../../../../src/arch/x86_64/acpi/tables/sdt/generic_address.rs', lines 34:4-36:5
    Visibility: public -/
def arch.x86_64.acpi.tables.sdt.generic_address.GenericAddress.is_valid
  (self : arch.x86_64.acpi.tables.sdt.generic_address.GenericAddress) :
  Result Bool
  := do
  ok (self.address != 0#u64)

/-- [nonos_x_acpi_tables_fadt_fadt_methods::arch::x86_64::acpi::tables::sdt::header::SdtHeader]
    Source: 'src/arch/x86_64/acpi/tables/../../../../../../../../../src/arch/x86_64/acpi/tables/sdt/header.rs', lines 22:0-32:1
    Visibility: public -/
structure arch.x86_64.acpi.tables.sdt.header.SdtHeader where
  signature : Std.U32
  length : Std.U32
  revision : Std.U8
  checksum : Std.U8
  oem_id : Array Std.U8 6#usize
  oem_table_id : Array Std.U8 8#usize
  oem_revision : Std.U32
  creator_id : Std.U32
  creator_revision : Std.U32

/-- [nonos_x_acpi_tables_fadt_fadt_methods::arch::x86_64::acpi::tables::fadt::flags::fadt_flags::RESET_REG_SUP]
    Source: 'src/arch/x86_64/acpi/tables/fadt/../../../../../../../../../../src/arch/x86_64/acpi/tables/fadt/flags.rs', lines 28:4-28:43
    Visibility: public -/
@[global_simps, irreducible]
def arch.x86_64.acpi.tables.fadt.flags.fadt_flags.RESET_REG_SUP
  : Result Std.U32 :=
  1#u32 <<< 10#i32

/-- [nonos_x_acpi_tables_fadt_fadt_methods::arch::x86_64::acpi::tables::fadt::fadt_struct::Fadt]
    Source: 'src/arch/x86_64/acpi/tables/fadt/../../../../../../../../../../src/arch/x86_64/acpi/tables/fadt/fadt_struct.rs', lines 21:0-78:1
    Visibility: public -/
structure arch.x86_64.acpi.tables.fadt.fadt_struct.Fadt where
  header : arch.x86_64.acpi.tables.sdt.header.SdtHeader
  firmware_ctrl : Std.U32
  dsdt : Std.U32
  reserved1 : Std.U8
  preferred_pm_profile : Std.U8
  sci_interrupt : Std.U16
  smi_command_port : Std.U32
  acpi_enable : Std.U8
  acpi_disable : Std.U8
  s4bios_req : Std.U8
  pstate_control : Std.U8
  pm1a_event_block : Std.U32
  pm1b_event_block : Std.U32
  pm1a_control_block : Std.U32
  pm1b_control_block : Std.U32
  pm2_control_block : Std.U32
  pm_timer_block : Std.U32
  gpe0_block : Std.U32
  gpe1_block : Std.U32
  pm1_event_length : Std.U8
  pm1_control_length : Std.U8
  pm2_control_length : Std.U8
  pm_timer_length : Std.U8
  gpe0_length : Std.U8
  gpe1_length : Std.U8
  gpe1_base : Std.U8
  cst_control : Std.U8
  c2_latency : Std.U16
  c3_latency : Std.U16
  flush_size : Std.U16
  flush_stride : Std.U16
  duty_offset : Std.U8
  duty_width : Std.U8
  day_alarm : Std.U8
  month_alarm : Std.U8
  century : Std.U8
  boot_architecture_flags : Std.U16
  reserved2 : Std.U8
  flags : Std.U32
  reset_reg : arch.x86_64.acpi.tables.sdt.generic_address.GenericAddress
  reset_value : Std.U8
  arm_boot_arch : Std.U16
  fadt_minor_version : Std.U8
  x_firmware_ctrl : Std.U64
  x_dsdt : Std.U64
  x_pm1a_event_block :
    arch.x86_64.acpi.tables.sdt.generic_address.GenericAddress
  x_pm1b_event_block :
    arch.x86_64.acpi.tables.sdt.generic_address.GenericAddress
  x_pm1a_control_block :
    arch.x86_64.acpi.tables.sdt.generic_address.GenericAddress
  x_pm1b_control_block :
    arch.x86_64.acpi.tables.sdt.generic_address.GenericAddress
  x_pm2_control_block :
    arch.x86_64.acpi.tables.sdt.generic_address.GenericAddress
  x_pm_timer_block : arch.x86_64.acpi.tables.sdt.generic_address.GenericAddress
  x_gpe0_block : arch.x86_64.acpi.tables.sdt.generic_address.GenericAddress
  x_gpe1_block : arch.x86_64.acpi.tables.sdt.generic_address.GenericAddress
  sleep_control_reg :
    arch.x86_64.acpi.tables.sdt.generic_address.GenericAddress
  sleep_status_reg : arch.x86_64.acpi.tables.sdt.generic_address.GenericAddress
  hypervisor_vendor_id : Std.U64

/-- [nonos_x_acpi_tables_fadt_fadt_methods::arch::x86_64::acpi::tables::fadt::fadt_methods::{nonos_x_acpi_tables_fadt_fadt_methods::arch::x86_64::acpi::tables::fadt::fadt_struct::Fadt}::has_reset_register]:
    Source: 'src/arch/x86_64/acpi/tables/fadt/../../../../../../../../../../src/arch/x86_64/acpi/tables/fadt/fadt_methods.rs', lines 25:4-27:5
    Visibility: public -/
def arch.x86_64.acpi.tables.fadt.fadt_methods.Fadt.has_reset_register
  (self : arch.x86_64.acpi.tables.fadt.fadt_struct.Fadt) : Result Bool := do
  let i ← arch.x86_64.acpi.tables.fadt.flags.fadt_flags.RESET_REG_SUP
  let i1 ← lift (self.flags &&& i)
  if i1 != 0#u32
  then
    arch.x86_64.acpi.tables.sdt.generic_address.GenericAddress.is_valid
      self.reset_reg
  else ok false

/-- [nonos_x_acpi_tables_fadt_fadt_methods::arch::x86_64::acpi::tables::fadt::flags::fadt_flags::HW_REDUCED_ACPI]
    Source: 'src/arch/x86_64/acpi/tables/fadt/../../../../../../../../../../src/arch/x86_64/acpi/tables/fadt/flags.rs', lines 38:4-38:45
    Visibility: public -/
@[global_simps, irreducible]
def arch.x86_64.acpi.tables.fadt.flags.fadt_flags.HW_REDUCED_ACPI
  : Result Std.U32 :=
  1#u32 <<< 20#i32

/-- [nonos_x_acpi_tables_fadt_fadt_methods::arch::x86_64::acpi::tables::fadt::fadt_methods::{nonos_x_acpi_tables_fadt_fadt_methods::arch::x86_64::acpi::tables::fadt::fadt_struct::Fadt}::is_hw_reduced]:
    Source: 'src/arch/x86_64/acpi/tables/fadt/../../../../../../../../../../src/arch/x86_64/acpi/tables/fadt/fadt_methods.rs', lines 28:4-30:5
    Visibility: public -/
def arch.x86_64.acpi.tables.fadt.fadt_methods.Fadt.is_hw_reduced
  (self : arch.x86_64.acpi.tables.fadt.fadt_struct.Fadt) : Result Bool := do
  let i ← arch.x86_64.acpi.tables.fadt.flags.fadt_flags.HW_REDUCED_ACPI
  let i1 ← lift (self.flags &&& i)
  ok (i1 != 0#u32)

/-- [nonos_x_acpi_tables_fadt_fadt_methods::arch::x86_64::acpi::tables::fadt::flags::fadt_flags::TMR_VAL_EXT]
    Source: 'src/arch/x86_64/acpi/tables/fadt/../../../../../../../../../../src/arch/x86_64/acpi/tables/fadt/flags.rs', lines 26:4-26:40
    Visibility: public -/
@[global_simps, irreducible]
def arch.x86_64.acpi.tables.fadt.flags.fadt_flags.TMR_VAL_EXT
  : Result Std.U32 :=
  1#u32 <<< 8#i32

/-- [nonos_x_acpi_tables_fadt_fadt_methods::arch::x86_64::acpi::tables::fadt::fadt_methods::{nonos_x_acpi_tables_fadt_fadt_methods::arch::x86_64::acpi::tables::fadt::fadt_struct::Fadt}::is_pm_timer_32bit]:
    Source: 'src/arch/x86_64/acpi/tables/fadt/../../../../../../../../../../src/arch/x86_64/acpi/tables/fadt/fadt_methods.rs', lines 31:4-33:5
    Visibility: public -/
def arch.x86_64.acpi.tables.fadt.fadt_methods.Fadt.is_pm_timer_32bit
  (self : arch.x86_64.acpi.tables.fadt.fadt_struct.Fadt) : Result Bool := do
  let i ← arch.x86_64.acpi.tables.fadt.flags.fadt_flags.TMR_VAL_EXT
  let i1 ← lift (self.flags &&& i)
  ok (i1 != 0#u32)

/-- [nonos_x_acpi_tables_fadt_fadt_methods::arch::x86_64::acpi::tables::fadt::flags::fadt_flags::LOW_POWER_S0]
    Source: 'src/arch/x86_64/acpi/tables/fadt/../../../../../../../../../../src/arch/x86_64/acpi/tables/fadt/flags.rs', lines 39:4-39:42
    Visibility: public -/
@[global_simps, irreducible]
def arch.x86_64.acpi.tables.fadt.flags.fadt_flags.LOW_POWER_S0
  : Result Std.U32 :=
  1#u32 <<< 21#i32

/-- [nonos_x_acpi_tables_fadt_fadt_methods::arch::x86_64::acpi::tables::fadt::fadt_methods::{nonos_x_acpi_tables_fadt_fadt_methods::arch::x86_64::acpi::tables::fadt::fadt_struct::Fadt}::supports_low_power_s0]:
    Source: 'src/arch/x86_64/acpi/tables/fadt/../../../../../../../../../../src/arch/x86_64/acpi/tables/fadt/fadt_methods.rs', lines 34:4-36:5
    Visibility: public -/
def arch.x86_64.acpi.tables.fadt.fadt_methods.Fadt.supports_low_power_s0
  (self : arch.x86_64.acpi.tables.fadt.fadt_struct.Fadt) : Result Bool := do
  let i ← arch.x86_64.acpi.tables.fadt.flags.fadt_flags.LOW_POWER_S0
  let i1 ← lift (self.flags &&& i)
  ok (i1 != 0#u32)

/-- [nonos_x_acpi_tables_fadt_fadt_methods::arch::x86_64::acpi::tables::fadt::fadt_methods::{nonos_x_acpi_tables_fadt_fadt_methods::arch::x86_64::acpi::tables::fadt::fadt_struct::Fadt}::sci_interrupt]:
    Source: 'src/arch/x86_64/acpi/tables/fadt/../../../../../../../../../../src/arch/x86_64/acpi/tables/fadt/fadt_methods.rs', lines 40:4-42:5
    Visibility: public -/
def arch.x86_64.acpi.tables.fadt.fadt_methods.Fadt.sci_interrupt
  (self : arch.x86_64.acpi.tables.fadt.fadt_struct.Fadt) : Result Std.U16 := do
  ok self.sci_interrupt

/-- [nonos_x_acpi_tables_fadt_fadt_methods::arch::x86_64::acpi::tables::fadt::fadt_methods::{nonos_x_acpi_tables_fadt_fadt_methods::arch::x86_64::acpi::tables::fadt::fadt_struct::Fadt}::c2_latency_us]:
    Source: 'src/arch/x86_64/acpi/tables/fadt/../../../../../../../../../../src/arch/x86_64/acpi/tables/fadt/fadt_methods.rs', lines 43:4-45:5
    Visibility: public -/
def arch.x86_64.acpi.tables.fadt.fadt_methods.Fadt.c2_latency_us
  (self : arch.x86_64.acpi.tables.fadt.fadt_struct.Fadt) : Result Std.U16 := do
  ok self.c2_latency

/-- [nonos_x_acpi_tables_fadt_fadt_methods::arch::x86_64::acpi::tables::fadt::fadt_methods::{nonos_x_acpi_tables_fadt_fadt_methods::arch::x86_64::acpi::tables::fadt::fadt_struct::Fadt}::c3_latency_us]:
    Source: 'src/arch/x86_64/acpi/tables/fadt/../../../../../../../../../../src/arch/x86_64/acpi/tables/fadt/fadt_methods.rs', lines 46:4-48:5
    Visibility: public -/
def arch.x86_64.acpi.tables.fadt.fadt_methods.Fadt.c3_latency_us
  (self : arch.x86_64.acpi.tables.fadt.fadt_struct.Fadt) : Result Std.U16 := do
  ok self.c3_latency

/-- [nonos_x_acpi_tables_fadt_fadt_methods::arch::x86_64::acpi::tables::fadt::fadt_methods::{nonos_x_acpi_tables_fadt_fadt_methods::arch::x86_64::acpi::tables::fadt::fadt_struct::Fadt}::supports_c2]:
    Source: 'src/arch/x86_64/acpi/tables/fadt/../../../../../../../../../../src/arch/x86_64/acpi/tables/fadt/fadt_methods.rs', lines 49:4-51:5
    Visibility: public -/
def arch.x86_64.acpi.tables.fadt.fadt_methods.Fadt.supports_c2
  (self : arch.x86_64.acpi.tables.fadt.fadt_struct.Fadt) : Result Bool := do
  ok (self.c2_latency <= 100#u16)

/-- [nonos_x_acpi_tables_fadt_fadt_methods::arch::x86_64::acpi::tables::fadt::fadt_methods::{nonos_x_acpi_tables_fadt_fadt_methods::arch::x86_64::acpi::tables::fadt::fadt_struct::Fadt}::supports_c3]:
    Source: 'src/arch/x86_64/acpi/tables/fadt/../../../../../../../../../../src/arch/x86_64/acpi/tables/fadt/fadt_methods.rs', lines 52:4-54:5
    Visibility: public -/
def arch.x86_64.acpi.tables.fadt.fadt_methods.Fadt.supports_c3
  (self : arch.x86_64.acpi.tables.fadt.fadt_struct.Fadt) : Result Bool := do
  ok (self.c3_latency <= 1000#u16)

/-- [nonos_x_acpi_tables_fadt_fadt_methods::fadt_has_reset_register]:
    Source: 'src/lib.rs', lines 11:0-13:1
    Visibility: public -/
def fadt_has_reset_register
  (this : arch.x86_64.acpi.tables.fadt.fadt_struct.Fadt) : Result Bool := do
  arch.x86_64.acpi.tables.fadt.fadt_methods.Fadt.has_reset_register this

/-- [nonos_x_acpi_tables_fadt_fadt_methods::fadt_is_hw_reduced]:
    Source: 'src/lib.rs', lines 15:0-17:1
    Visibility: public -/
def fadt_is_hw_reduced
  (this : arch.x86_64.acpi.tables.fadt.fadt_struct.Fadt) : Result Bool := do
  arch.x86_64.acpi.tables.fadt.fadt_methods.Fadt.is_hw_reduced this

/-- [nonos_x_acpi_tables_fadt_fadt_methods::fadt_is_pm_timer_32bit]:
    Source: 'src/lib.rs', lines 19:0-21:1
    Visibility: public -/
def fadt_is_pm_timer_32bit
  (this : arch.x86_64.acpi.tables.fadt.fadt_struct.Fadt) : Result Bool := do
  arch.x86_64.acpi.tables.fadt.fadt_methods.Fadt.is_pm_timer_32bit this

/-- [nonos_x_acpi_tables_fadt_fadt_methods::fadt_supports_low_power_s0]:
    Source: 'src/lib.rs', lines 23:0-25:1
    Visibility: public -/
def fadt_supports_low_power_s0
  (this : arch.x86_64.acpi.tables.fadt.fadt_struct.Fadt) : Result Bool := do
  arch.x86_64.acpi.tables.fadt.fadt_methods.Fadt.supports_low_power_s0 this

/-- [nonos_x_acpi_tables_fadt_fadt_methods::fadt_sci_interrupt]:
    Source: 'src/lib.rs', lines 27:0-29:1
    Visibility: public -/
def fadt_sci_interrupt
  (this : arch.x86_64.acpi.tables.fadt.fadt_struct.Fadt) : Result Std.U16 := do
  arch.x86_64.acpi.tables.fadt.fadt_methods.Fadt.sci_interrupt this

/-- [nonos_x_acpi_tables_fadt_fadt_methods::fadt_c2_latency_us]:
    Source: 'src/lib.rs', lines 31:0-33:1
    Visibility: public -/
def fadt_c2_latency_us
  (this : arch.x86_64.acpi.tables.fadt.fadt_struct.Fadt) : Result Std.U16 := do
  arch.x86_64.acpi.tables.fadt.fadt_methods.Fadt.c2_latency_us this

/-- [nonos_x_acpi_tables_fadt_fadt_methods::fadt_c3_latency_us]:
    Source: 'src/lib.rs', lines 35:0-37:1
    Visibility: public -/
def fadt_c3_latency_us
  (this : arch.x86_64.acpi.tables.fadt.fadt_struct.Fadt) : Result Std.U16 := do
  arch.x86_64.acpi.tables.fadt.fadt_methods.Fadt.c3_latency_us this

/-- [nonos_x_acpi_tables_fadt_fadt_methods::fadt_supports_c2]:
    Source: 'src/lib.rs', lines 39:0-41:1
    Visibility: public -/
def fadt_supports_c2
  (this : arch.x86_64.acpi.tables.fadt.fadt_struct.Fadt) : Result Bool := do
  arch.x86_64.acpi.tables.fadt.fadt_methods.Fadt.supports_c2 this

/-- [nonos_x_acpi_tables_fadt_fadt_methods::fadt_supports_c3]:
    Source: 'src/lib.rs', lines 43:0-45:1
    Visibility: public -/
def fadt_supports_c3
  (this : arch.x86_64.acpi.tables.fadt.fadt_struct.Fadt) : Result Bool := do
  arch.x86_64.acpi.tables.fadt.fadt_methods.Fadt.supports_c3 this

end nonos_x_acpi_tables_fadt_fadt_methods
