/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

phys, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.AddrPhys

open Aeneas Aeneas.Std Result
open nonos_x_addr_phys

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.AddrPhys

/-! ### The forwarding functions add nothing -/

theorem the_physaddr_new_wrapper_is_its_method (a : Std.U64) :
    physaddr_new a = phys.PhysAddr.new a := rfl

theorem the_physaddr_zero_wrapper_is_its_method :
    physaddr_zero = phys.PhysAddr.zero := rfl

theorem the_physaddr_as_u64_wrapper_is_its_method (a : phys.PhysAddr) :
    physaddr_as_u64 a = phys.PhysAddr.as_u64 a := rfl

theorem the_physaddr_as_usize_wrapper_is_its_method (a : phys.PhysAddr) :
    physaddr_as_usize a = phys.PhysAddr.as_usize a := rfl

theorem the_physaddr_is_null_wrapper_is_its_method (a : phys.PhysAddr) :
    physaddr_is_null a = phys.PhysAddr.is_null a := rfl

theorem the_physaddr_is_aligned_wrapper_is_its_method (a : phys.PhysAddr) (b : Std.U64) :
    physaddr_is_aligned a b = phys.PhysAddr.is_aligned a b := rfl

theorem the_physaddr_align_down_wrapper_is_its_method (a : phys.PhysAddr) (b : Std.U64) :
    physaddr_align_down a b = phys.PhysAddr.align_down a b := rfl

theorem the_physaddr_align_up_wrapper_is_its_method (a : phys.PhysAddr) (b : Std.U64) :
    physaddr_align_up a b = phys.PhysAddr.align_up a b := rfl


/-! ### Alignment

    Three functions decide alignment for every physical address in the kernel,
    and they do not agree with each other.

    `is_aligned` asks `addr % align == 0`, which is the right question for any
    alignment. `align_down` and `align_up` clear low bits with `!(align - 1)`,
    which answers a different question unless `align` is a power of two. Nothing
    in the type says it has to be.

    The kernel builds with `overflow-checks = true` and `panic = "abort"`, so
    the checked arithmetic below is faithful: where the extracted function fails,
    the shipping kernel halts. That is a controlled halt rather than silent
    corruption, which is the trade the profile comment argues for, but it is
    still a halt reachable from an address and an alignment.
-/

/-- The disagreement, at the smallest witness. Aligning ten down to a multiple
    of three gives eight, and `is_aligned` then says eight is not aligned to
    three. Both functions are reachable from the same call site with the same
    argument, and a caller that aligns and then checks gets told no. -/
theorem aligning_down_can_produce_an_unaligned_address :
    physaddr_align_down 10#u64 3#u64 = ok 8#u64 ∧
    physaddr_is_aligned 8#u64 3#u64 = ok false := by
  refine ⟨?_, ?_⟩ <;> rfl

/-- On a power of two the two do agree, which is the case every caller in the
    kernel actually passes and the reason this has never been noticed. -/
theorem on_a_power_of_two_they_agree :
    physaddr_align_down 10#u64 4#u64 = ok 8#u64 ∧
    physaddr_is_aligned 8#u64 4#u64 = ok true := by
  refine ⟨?_, ?_⟩ <;> rfl

/-- An alignment of zero is not refused, it halts the machine. `align - 1`
    underflows, and under this profile an underflow aborts. `is_aligned` handles
    the same argument by answering false, so the three functions disagree about
    zero as well. -/
theorem an_alignment_of_zero_halts_rather_than_refusing :
    physaddr_is_aligned 4096#u64 0#u64 = ok false ∧
    physaddr_align_down 4096#u64 0#u64 = fail Error.integerOverflow := by
  refine ⟨rfl, rfl⟩

/-- Aligning up near the top of the address space halts too, because the sum
    overflows before the mask is applied. The witness is an address one page
    below the top, aligned to a page, which is an ordinary thing to ask for at
    the end of a memory map. -/
theorem aligning_up_near_the_top_halts :
    physaddr_align_up 0xFFFFFFFFFFFFF001#u64 4096#u64 = fail Error.integerOverflow := by
  rfl

/-- Away from the top it behaves, so the halt is a boundary case and not a
    broken function. -/
theorem aligning_up_in_the_ordinary_range :
    physaddr_align_up 4097#u64 4096#u64 = ok 8192#u64 ∧
    physaddr_align_up 4096#u64 4096#u64 = ok 4096#u64 := by
  refine ⟨rfl, rfl⟩

/-- Aligning down never moves an address upward, for every address, on a page
    alignment. This is the property callers rely on when they align a base down
    to find the page containing it. -/
theorem aligning_down_is_the_mask (a : Std.U64) :
    physaddr_align_down a 4096#u64 = ok (a &&& 0xFFFFFFFFFFFFF000#u64) := by
  rfl

/-- And clearing those bits never moves an address upward, for every word. This
    is the property a caller relies on when it aligns a base down to find the
    page containing it. -/
theorem masking_down_never_moves_up (a : BitVec 64) :
    (a &&& 0xFFFFFFFFFFFFF000#64) ≤ a := by
  bv_decide

/-! ### The trivial readers

    `new` and `as_u64` are each other's inverse, which is what makes the newtype
    free: nothing is lost by carrying an address as a `PhysAddr` rather than a
    word. -/

theorem the_newtype_round_trips (w : Std.U64) :
    (do let a ← physaddr_new w; physaddr_as_u64 a) = ok w := by rfl

theorem zero_is_null_and_nothing_else :
    (do let a ← physaddr_zero; physaddr_is_null a) = ok true ∧
    physaddr_is_null 1#u64 = ok false := by
  refine ⟨rfl, rfl⟩

/-! ### Axiom profile -/

#print axioms NonosExtraction.AddrPhys.aligning_down_can_produce_an_unaligned_address
#print axioms NonosExtraction.AddrPhys.on_a_power_of_two_they_agree
#print axioms NonosExtraction.AddrPhys.an_alignment_of_zero_halts_rather_than_refusing
#print axioms NonosExtraction.AddrPhys.aligning_up_near_the_top_halts
#print axioms NonosExtraction.AddrPhys.aligning_up_in_the_ordinary_range
#print axioms NonosExtraction.AddrPhys.aligning_down_is_the_mask
#print axioms NonosExtraction.AddrPhys.masking_down_never_moves_up
#print axioms NonosExtraction.AddrPhys.the_newtype_round_trips
#print axioms NonosExtraction.AddrPhys.zero_is_null_and_nothing_else
#print axioms NonosExtraction.AddrPhys.the_physaddr_new_wrapper_is_its_method
#print axioms NonosExtraction.AddrPhys.the_physaddr_zero_wrapper_is_its_method
#print axioms NonosExtraction.AddrPhys.the_physaddr_as_u64_wrapper_is_its_method
#print axioms NonosExtraction.AddrPhys.the_physaddr_as_usize_wrapper_is_its_method
#print axioms NonosExtraction.AddrPhys.the_physaddr_is_null_wrapper_is_its_method
#print axioms NonosExtraction.AddrPhys.the_physaddr_is_aligned_wrapper_is_its_method
#print axioms NonosExtraction.AddrPhys.the_physaddr_align_down_wrapper_is_its_method
#print axioms NonosExtraction.AddrPhys.the_physaddr_align_up_wrapper_is_its_method

end NonosExtraction.AddrPhys
