/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

virt, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.AddrVirt

open Aeneas Aeneas.Std Result
open nonos_x_addr_virt

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.AddrVirt

/-! ### The forwarding functions add nothing -/

theorem the_virtaddr_new_wrapper_is_its_method (a : Std.U64) :
    virtaddr_new a = virt.VirtAddr.new a := rfl

theorem the_virtaddr_zero_wrapper_is_its_method :
    virtaddr_zero = virt.VirtAddr.zero := rfl

theorem the_virtaddr_as_u64_wrapper_is_its_method (a : virt.VirtAddr) :
    virtaddr_as_u64 a = virt.VirtAddr.as_u64 a := rfl

theorem the_virtaddr_as_usize_wrapper_is_its_method (a : virt.VirtAddr) :
    virtaddr_as_usize a = virt.VirtAddr.as_usize a := rfl

theorem the_virtaddr_is_null_wrapper_is_its_method (a : virt.VirtAddr) :
    virtaddr_is_null a = virt.VirtAddr.is_null a := rfl

theorem the_virtaddr_is_aligned_wrapper_is_its_method (a : virt.VirtAddr) (b : Std.U64) :
    virtaddr_is_aligned a b = virt.VirtAddr.is_aligned a b := rfl

theorem the_virtaddr_align_down_wrapper_is_its_method (a : virt.VirtAddr) (b : Std.U64) :
    virtaddr_align_down a b = virt.VirtAddr.align_down a b := rfl

theorem the_virtaddr_align_up_wrapper_is_its_method (a : virt.VirtAddr) (b : Std.U64) :
    virtaddr_align_up a b = virt.VirtAddr.align_up a b := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.AddrVirt.the_virtaddr_new_wrapper_is_its_method
#print axioms NonosExtraction.AddrVirt.the_virtaddr_zero_wrapper_is_its_method
#print axioms NonosExtraction.AddrVirt.the_virtaddr_as_u64_wrapper_is_its_method
#print axioms NonosExtraction.AddrVirt.the_virtaddr_as_usize_wrapper_is_its_method
#print axioms NonosExtraction.AddrVirt.the_virtaddr_is_null_wrapper_is_its_method
#print axioms NonosExtraction.AddrVirt.the_virtaddr_is_aligned_wrapper_is_its_method
#print axioms NonosExtraction.AddrVirt.the_virtaddr_align_down_wrapper_is_its_method
#print axioms NonosExtraction.AddrVirt.the_virtaddr_align_up_wrapper_is_its_method

end NonosExtraction.AddrVirt
