-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [nonos_align]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace nonos_align

/-- [nonos_align::boot_memory::align_up]:
    Source: 'src/../../../../src/memory/boot_memory/manager/helpers.rs', lines 18:0-35:1 -/
def boot_memory.align_up
  (value : Std.U64) (align : Std.U64) : Result Std.U64 := do
  if align = 0#u64
  then ok value
  else
    let i ← align - 1#u64
    let i1 ← lift (align &&& i)
    if i1 != 0#u64
    then ok value
    else
      let o ← lift (U64.checked_add value i)
      match o with
      | none => ok value
      | some sum => let i2 ← lift (~~~ i)
                    ok (sum &&& i2)

/-- [nonos_align::boot_memory::align_down]:
    Source: 'src/../../../../src/memory/boot_memory/manager/helpers.rs', lines 38:0-43:1 -/
def boot_memory.align_down
  (value : Std.U64) (align : Std.U64) : Result Std.U64 := do
  if align = 0#u64
  then ok value
  else
    let i ← align - 1#u64
    let i1 ← lift (align &&& i)
    if i1 != 0#u64
    then ok value
    else let i2 ← lift (~~~ i)
         ok (value &&& i2)

/-- [nonos_align::buddy_alloc::align_up]:
    Source: 'src/../../../../src/memory/buddy_alloc/allocator/utils.rs', lines 15:0-30:1
    Visibility: public -/
def buddy_alloc.align_up
  (value : Std.Usize) (align : Std.Usize) : Result Std.Usize := do
  if align = 0#usize
  then ok value
  else
    let i ← align - 1#usize
    let i1 ← lift (align &&& i)
    if i1 != 0#usize
    then ok value
    else
      let o ← lift (Usize.checked_add value i)
      match o with
      | none => ok value
      | some v => let i2 ← lift (~~~ i)
                  ok (v &&& i2)

/-- [nonos_align::layout_outer::manager::align::align_down]:
    Source: 'src/layout_outer/manager/../../../../../../src/memory/layout/manager/align.rs', lines 20:0-25:1
    Visibility: public -/
def layout_outer.manager.align.align_down
  (x : Std.U64) (a : Std.U64) : Result Std.U64 := do
  if a = 0#u64
  then ok x
  else
    let i ← a - 1#u64
    let i1 ← lift (a &&& i)
    if i1 != 0#u64
    then ok x
    else let i2 ← lift (~~~ i)
         ok (x &&& i2)

/-- [nonos_align::layout_outer::manager::align::align_up]:
    Source: 'src/layout_outer/manager/../../../../../../src/memory/layout/manager/align.rs', lines 27:0-32:1
    Visibility: public -/
def layout_outer.manager.align.align_up
  (x : Std.U64) (a : Std.U64) : Result Std.U64 := do
  if a = 0#u64
  then ok x
  else
    let i ← a - 1#u64
    let i1 ← lift (a &&& i)
    if i1 != 0#u64
    then ok x
    else
      let i2 ← x + a
      let i3 ← i2 - 1#u64
      let i4 ← lift (~~~ i)
      ok (i3 &&& i4)

/-- [nonos_align::boot_align_up]:
    Source: 'src/lib.rs', lines 18:0-20:1
    Visibility: public -/
def boot_align_up (value : Std.U64) (align : Std.U64) : Result Std.U64 := do
  boot_memory.align_up value align

/-- [nonos_align::boot_align_down]:
    Source: 'src/lib.rs', lines 22:0-24:1
    Visibility: public -/
def boot_align_down (value : Std.U64) (align : Std.U64) : Result Std.U64 := do
  boot_memory.align_down value align

/-- [nonos_align::buddy_align_up]:
    Source: 'src/lib.rs', lines 26:0-28:1
    Visibility: public -/
def buddy_align_up
  (value : Std.Usize) (align : Std.Usize) : Result Std.Usize := do
  buddy_alloc.align_up value align

/-- [nonos_align::layout_align_up]:
    Source: 'src/lib.rs', lines 30:0-32:1
    Visibility: public -/
def layout_align_up (x : Std.U64) (a : Std.U64) : Result Std.U64 := do
  layout_outer.manager.align.align_up x a

/-- [nonos_align::layout_align_down]:
    Source: 'src/lib.rs', lines 34:0-36:1
    Visibility: public -/
def layout_align_down (x : Std.U64) (a : Std.U64) : Result Std.U64 := do
  layout_outer.manager.align.align_down x a

/-- [nonos_align::phys_outer::helpers::align_up]:
    Source: 'src/phys_outer/../../../../../src/memory/phys/constants/helpers.rs', lines 20:0-25:1
    Visibility: public -/
def phys_outer.helpers.align_up
  (value : Std.U64) (align : Std.U64) : Result Std.U64 := do
  if align = 0#u64
  then ok value
  else
    let i ← value + align
    let i1 ← i - 1#u64
    let i2 ← i1 / align
    i2 * align

/-- [nonos_align::phys_align_up]:
    Source: 'src/lib.rs', lines 38:0-40:1
    Visibility: public -/
def phys_align_up (value : Std.U64) (align : Std.U64) : Result Std.U64 := do
  phys_outer.helpers.align_up value align

/-- [nonos_align::phys_outer::helpers::align_down]:
    Source: 'src/phys_outer/../../../../../src/memory/phys/constants/helpers.rs', lines 28:0-33:1
    Visibility: public -/
def phys_outer.helpers.align_down
  (value : Std.U64) (align : Std.U64) : Result Std.U64 := do
  if align = 0#u64
  then ok value
  else let i ← value / align
       i * align

/-- [nonos_align::phys_align_down]:
    Source: 'src/lib.rs', lines 42:0-44:1
    Visibility: public -/
def phys_align_down (value : Std.U64) (align : Std.U64) : Result Std.U64 := do
  phys_outer.helpers.align_down value align

end nonos_align
