/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

types, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.AmlTypes

open Aeneas Aeneas.Std Result
open nonos_x_aml_types

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.AmlTypes

/-! ### The forwarding functions add nothing -/

theorem the_lpsscontroller_is_valid_wrapper_is_its_method (a : types.lpss_controller.LpssController) :
    lpsscontroller_is_valid a = types.lpss_controller.LpssController.is_valid a := rfl

theorem the_gpiocontroller_is_valid_wrapper_is_its_method (a : types.gpio_controller.GpioController) :
    gpiocontroller_is_valid a = types.gpio_controller.GpioController.is_valid a := rfl

/-! ### A controller is kept only with a usable MMIO window

    `enumerate_i2c_controllers` pushes a
    controller onto its result exactly when `is_valid` holds, and the drivers
    that follow map the window it names. The theorems below establish that
    `is_valid` holds exactly when both the MMIO base and the MMIO size are
    nonzero, that a zero base or a zero size is refused whatever the other
    field says, that the smallest nonzero window is accepted, and that the
    interrupt and identity fields play no part. They cannot establish that the
    window is backed by real device memory, nor anything about the AML parsing
    that fills these fields, which is not extracted.
-/

/-- The I2C controller check is the conjunction of a nonzero base and a nonzero
size. -/
theorem lpsscontroller_is_valid_iff_base_and_size_are_nonzero (c : types.lpss_controller.LpssController) :
    lpsscontroller_is_valid c = ok (decide (c.mmio_base.val ≠ 0 ∧ c.mmio_size.val ≠ 0)) := by
  unfold lpsscontroller_is_valid types.lpss_controller.LpssController.is_valid
  by_cases hb : c.mmio_base = 0#u64
  · simp [hb]
  · have hbv : c.mmio_base.val ≠ 0 := fun h => hb (UScalar.eq_of_val_eq (by rw [h]; rfl))
    by_cases hs : c.mmio_size = 0#u32
    · simp [hb, hs]
    · have hsv : c.mmio_size.val ≠ 0 := fun h => hs (UScalar.eq_of_val_eq (by rw [h]; rfl))
      simp [hb, hs, hbv, hsv]

/-- A zero-length I2C window is refused even at a nonzero base. -/
theorem lpsscontroller_is_valid_refuses_a_zero_size (c : types.lpss_controller.LpssController)
    (hs : c.mmio_size = 0#u32) : lpsscontroller_is_valid c = ok false := by
  rw [lpsscontroller_is_valid_iff_base_and_size_are_nonzero, hs]
  simp

/-- An I2C window at base zero is refused whatever its size. -/
theorem lpsscontroller_is_valid_refuses_a_zero_base (c : types.lpss_controller.LpssController)
    (hb : c.mmio_base = 0#u64) : lpsscontroller_is_valid c = ok false := by
  rw [lpsscontroller_is_valid_iff_base_and_size_are_nonzero, hb]
  simp

/-- The smallest nonzero I2C window, one byte at address one, is accepted. -/
theorem lpsscontroller_is_valid_accepts_the_smallest_window
    (c : types.lpss_controller.LpssController) (hb : c.mmio_base = 1#u64) (hs : c.mmio_size = 1#u32) :
    lpsscontroller_is_valid c = ok true := by
  rw [lpsscontroller_is_valid_iff_base_and_size_are_nonzero, hb, hs]
  simp

/-- The interrupt fields do not enter into the I2C check: a controller without
an interrupt is kept or dropped exactly as the same window with one. -/
theorem lpsscontroller_is_valid_ignores_the_interrupt (c : types.lpss_controller.LpssController)
    (b : Bool) (q : Std.U32) :
    lpsscontroller_is_valid { c with has_irq := b, irq := q } = lpsscontroller_is_valid c := by
  rw [lpsscontroller_is_valid_iff_base_and_size_are_nonzero,
    lpsscontroller_is_valid_iff_base_and_size_are_nonzero]

/-! ### A GPIO controller is kept with a window or a way to compute one

    `enumerate_gpio_controllers` keeps a controller exactly when `is_valid`
    holds. A controller is usable once `_CRS` gave it a community window, or
    once it names sideband port ids its windows can be computed from at
    SBREG_BAR (Sunrise Point and later). The theorems below establish that a
    window alone is enough, that without one the sideband ids decide, and that
    a controller with neither is refused. They say nothing about whether the
    windows are real device memory, nor about the AML parsing that fills them,
    which is not extracted.
-/

/-- A controller with at least one community window is kept. -/
theorem gpiocontroller_is_valid_with_a_window (c : types.gpio_controller.GpioController)
    (h : c.window_count > 0#usize) : gpiocontroller_is_valid c = ok true := by
  unfold gpiocontroller_is_valid types.gpio_controller.GpioController.is_valid
  rw [if_pos h]

/-- Without a window, the sideband port ids decide. -/
theorem gpiocontroller_is_valid_without_a_window (c : types.gpio_controller.GpioController)
    (h : ¬ c.window_count > 0#usize) :
    gpiocontroller_is_valid c = ok (decide (c.pid_count > 0#usize)) := by
  unfold gpiocontroller_is_valid types.gpio_controller.GpioController.is_valid
  rw [if_neg h]

/-- A controller with no window and no sideband ids is refused. -/
theorem gpiocontroller_is_valid_refuses_neither (c : types.gpio_controller.GpioController)
    (hw : ¬ c.window_count > 0#usize) (hp : ¬ c.pid_count > 0#usize) :
    gpiocontroller_is_valid c = ok false := by
  rw [gpiocontroller_is_valid_without_a_window c hw]
  simp [hp]

/-! ### Axiom profile -/

#print axioms NonosExtraction.AmlTypes.the_lpsscontroller_is_valid_wrapper_is_its_method
#print axioms NonosExtraction.AmlTypes.the_gpiocontroller_is_valid_wrapper_is_its_method
#print axioms NonosExtraction.AmlTypes.lpsscontroller_is_valid_iff_base_and_size_are_nonzero
#print axioms NonosExtraction.AmlTypes.lpsscontroller_is_valid_refuses_a_zero_size
#print axioms NonosExtraction.AmlTypes.lpsscontroller_is_valid_refuses_a_zero_base
#print axioms NonosExtraction.AmlTypes.lpsscontroller_is_valid_accepts_the_smallest_window
#print axioms NonosExtraction.AmlTypes.lpsscontroller_is_valid_ignores_the_interrupt
#print axioms NonosExtraction.AmlTypes.gpiocontroller_is_valid_with_a_window
#print axioms NonosExtraction.AmlTypes.gpiocontroller_is_valid_without_a_window
#print axioms NonosExtraction.AmlTypes.gpiocontroller_is_valid_refuses_neither

end NonosExtraction.AmlTypes
