/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

entry_base, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.ArchX8664GdtEntryBase

open Aeneas Aeneas.Std Result
open nonos_x_arch_x86_64_gdt_entry_base

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.ArchX8664GdtEntryBase

/-! ### The forwarding functions add nothing -/

theorem the_gdtentry_null_wrapper_is_its_method :
    gdtentry_null = arch.x86_64.gdt.entry_base.GdtEntry.null := rfl

theorem the_gdtentry_new_wrapper_is_its_method (a : Std.U32) (b : Std.U32) (c : Std.U8) (d : Std.U8) :
    gdtentry_new a b c d = arch.x86_64.gdt.entry_base.GdtEntry.new a b c d := rfl

theorem the_gdtentry_is_present_wrapper_is_its_method (a : arch.x86_64.gdt.entry_base.GdtEntry) :
    gdtentry_is_present a = arch.x86_64.gdt.entry_base.GdtEntry.is_present a := rfl

theorem the_gdtentry_dpl_wrapper_is_its_method (a : arch.x86_64.gdt.entry_base.GdtEntry) :
    gdtentry_dpl a = arch.x86_64.gdt.entry_base.GdtEntry.dpl a := rfl

theorem the_gdtentry_is_code_wrapper_is_its_method (a : arch.x86_64.gdt.entry_base.GdtEntry) :
    gdtentry_is_code a = arch.x86_64.gdt.entry_base.GdtEntry.is_code a := rfl

theorem the_gdtentry_is_long_mode_wrapper_is_its_method (a : arch.x86_64.gdt.entry_base.GdtEntry) :
    gdtentry_is_long_mode a = arch.x86_64.gdt.entry_base.GdtEntry.is_long_mode a := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.ArchX8664GdtEntryBase.the_gdtentry_null_wrapper_is_its_method
#print axioms NonosExtraction.ArchX8664GdtEntryBase.the_gdtentry_new_wrapper_is_its_method
#print axioms NonosExtraction.ArchX8664GdtEntryBase.the_gdtentry_is_present_wrapper_is_its_method
#print axioms NonosExtraction.ArchX8664GdtEntryBase.the_gdtentry_dpl_wrapper_is_its_method
#print axioms NonosExtraction.ArchX8664GdtEntryBase.the_gdtentry_is_code_wrapper_is_its_method
#print axioms NonosExtraction.ArchX8664GdtEntryBase.the_gdtentry_is_long_mode_wrapper_is_its_method

end NonosExtraction.ArchX8664GdtEntryBase
