-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [nonos_x_arch_aarch64_fpu_slot]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace nonos_x_arch_aarch64_fpu_slot

/-- [nonos_x_arch_aarch64_fpu_slot::arch::aarch64::fpu::context::FpSimdContext]
    Source: 'src/arch/aarch64/fpu/../../../../../../../../src/arch/aarch64/fpu/context.rs', lines 19:0-24:1
    Visibility: public -/
structure arch.aarch64.fpu.context.FpSimdContext where
  q : Array Std.U128 32#usize
  fpsr : Std.U32
  fpcr : Std.U32
  _pad : Array Std.U32 2#usize

/-- [nonos_x_arch_aarch64_fpu_slot::arch::aarch64::fpu::context::{nonos_x_arch_aarch64_fpu_slot::arch::aarch64::fpu::context::FpSimdContext}::zeroed]:
    Source: 'src/arch/aarch64/fpu/../../../../../../../../src/arch/aarch64/fpu/context.rs', lines 27:4-29:5
    Visibility: public -/
def arch.aarch64.fpu.context.FpSimdContext.zeroed
  : Result arch.aarch64.fpu.context.FpSimdContext := do
  let a := Array.repeat 32#usize 0#u128
  let a1 := Array.repeat 2#usize 0#u32
  ok { q := a, fpsr := 0#u32, fpcr := 0#u32, _pad := a1 }

/-- [nonos_x_arch_aarch64_fpu_slot::arch::aarch64::fpu::slot::FpSimdSlot]
    Source: 'src/arch/aarch64/fpu/../../../../../../../../src/arch/aarch64/fpu/slot.rs', lines 20:0-25:1
    Visibility: public -/
structure arch.aarch64.fpu.slot.FpSimdSlot where
  ctx : arch.aarch64.fpu.context.FpSimdContext
  valid : Bool
  enabled : Bool
  dirty : Bool

/-- [nonos_x_arch_aarch64_fpu_slot::arch::aarch64::fpu::slot::{nonos_x_arch_aarch64_fpu_slot::arch::aarch64::fpu::slot::FpSimdSlot}::zeroed]:
    Source: 'src/arch/aarch64/fpu/../../../../../../../../src/arch/aarch64/fpu/slot.rs', lines 28:4-30:5
    Visibility: public -/
def arch.aarch64.fpu.slot.FpSimdSlot.zeroed
  : Result arch.aarch64.fpu.slot.FpSimdSlot := do
  let fsc ← arch.aarch64.fpu.context.FpSimdContext.zeroed
  ok { ctx := fsc, valid := false, enabled := false, dirty := false }

/-- [nonos_x_arch_aarch64_fpu_slot::fpsimdslot_zeroed]:
    Source: 'src/lib.rs', lines 11:0-13:1
    Visibility: public -/
def fpsimdslot_zeroed : Result arch.aarch64.fpu.slot.FpSimdSlot := do
  arch.aarch64.fpu.slot.FpSimdSlot.zeroed

end nonos_x_arch_aarch64_fpu_slot
