/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

table, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.ArchX8664IdtTable

open Aeneas Aeneas.Std Result
open nonos_x_arch_x86_64_idt_table

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.ArchX8664IdtTable

/-! ### The forwarding functions add nothing -/

theorem the_idt_new_wrapper_is_its_method :
    idt_new = arch.x86_64.idt.table.Idt.new := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.ArchX8664IdtTable.the_idt_new_wrapper_is_its_method

end NonosExtraction.ArchX8664IdtTable
