/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

types, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.ArchX8664SerialTypes

open Aeneas Aeneas.Std Result
open nonos_x_arch_x86_64_serial_types

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.ArchX8664SerialTypes

/-! ### The forwarding functions add nothing -/

theorem the_baudrate_divisor_wrapper_is_its_method (a : arch.x86_64.serial.types.BaudRate) :
    baudrate_divisor a = arch.x86_64.serial.types.BaudRate.divisor a := rfl

theorem the_baudrate_from_divisor_wrapper_is_its_method (a : Std.U16) :
    baudrate_from_divisor a = arch.x86_64.serial.types.BaudRate.from_divisor a := rfl

theorem the_baudrate_as_u32_wrapper_is_its_method (a : arch.x86_64.serial.types.BaudRate) :
    baudrate_as_u32 a = arch.x86_64.serial.types.BaudRate.as_u32 a := rfl

theorem the_databits_as_u8_wrapper_is_its_method (a : arch.x86_64.serial.types.DataBits) :
    databits_as_u8 a = arch.x86_64.serial.types.DataBits.as_u8 a := rfl

theorem the_databits_bits_wrapper_is_its_method (a : arch.x86_64.serial.types.DataBits) :
    databits_bits a = arch.x86_64.serial.types.DataBits.bits a := rfl

theorem the_parity_as_u8_wrapper_is_its_method (a : arch.x86_64.serial.types.Parity) :
    parity_as_u8 a = arch.x86_64.serial.types.Parity.as_u8 a := rfl

theorem the_stopbits_as_u8_wrapper_is_its_method (a : arch.x86_64.serial.types.StopBits) :
    stopbits_as_u8 a = arch.x86_64.serial.types.StopBits.as_u8 a := rfl

theorem the_serialconfig_with_fifo_wrapper_is_its_method (a : arch.x86_64.serial.types.SerialConfig) (b : Bool) :
    serialconfig_with_fifo a b = arch.x86_64.serial.types.SerialConfig.with_fifo a b := rfl

theorem the_serialconfig_with_interrupts_wrapper_is_its_method (a : arch.x86_64.serial.types.SerialConfig) (b : Bool) :
    serialconfig_with_interrupts a b = arch.x86_64.serial.types.SerialConfig.with_interrupts a b := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.ArchX8664SerialTypes.the_baudrate_divisor_wrapper_is_its_method
#print axioms NonosExtraction.ArchX8664SerialTypes.the_baudrate_from_divisor_wrapper_is_its_method
#print axioms NonosExtraction.ArchX8664SerialTypes.the_baudrate_as_u32_wrapper_is_its_method
#print axioms NonosExtraction.ArchX8664SerialTypes.the_databits_as_u8_wrapper_is_its_method
#print axioms NonosExtraction.ArchX8664SerialTypes.the_databits_bits_wrapper_is_its_method
#print axioms NonosExtraction.ArchX8664SerialTypes.the_parity_as_u8_wrapper_is_its_method
#print axioms NonosExtraction.ArchX8664SerialTypes.the_stopbits_as_u8_wrapper_is_its_method
#print axioms NonosExtraction.ArchX8664SerialTypes.the_serialconfig_with_fifo_wrapper_is_its_method
#print axioms NonosExtraction.ArchX8664SerialTypes.the_serialconfig_with_interrupts_wrapper_is_its_method

end NonosExtraction.ArchX8664SerialTypes
