/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

entry_idt, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.ArchX8664IdtEntryIdt

open Aeneas Aeneas.Std Result
open nonos_x_arch_x86_64_idt_entry_idt

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.ArchX8664IdtEntryIdt

/-! ### The forwarding functions add nothing -/

theorem the_idtentry_empty_wrapper_is_its_method :
    idtentry_empty = arch.x86_64.idt.entry_idt.IdtEntry.empty := rfl

theorem the_idtentry_is_present_wrapper_is_its_method (a : arch.x86_64.idt.entry_idt.IdtEntry) :
    idtentry_is_present a = arch.x86_64.idt.entry_idt.IdtEntry.is_present a := rfl

theorem the_idtentry_handler_wrapper_is_its_method (a : arch.x86_64.idt.entry_idt.IdtEntry) :
    idtentry_handler a = arch.x86_64.idt.entry_idt.IdtEntry.handler a := rfl

theorem the_idtentry_ist_wrapper_is_its_method (a : arch.x86_64.idt.entry_idt.IdtEntry) :
    idtentry_ist a = arch.x86_64.idt.entry_idt.IdtEntry.impl.ist a := rfl

theorem the_idtentry_dpl_wrapper_is_its_method (a : arch.x86_64.idt.entry_idt.IdtEntry) :
    idtentry_dpl a = arch.x86_64.idt.entry_idt.IdtEntry.dpl a := rfl

theorem the_idtentry_is_trap_wrapper_is_its_method (a : arch.x86_64.idt.entry_idt.IdtEntry) :
    idtentry_is_trap a = arch.x86_64.idt.entry_idt.IdtEntry.is_trap a := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.ArchX8664IdtEntryIdt.the_idtentry_empty_wrapper_is_its_method
#print axioms NonosExtraction.ArchX8664IdtEntryIdt.the_idtentry_is_present_wrapper_is_its_method
#print axioms NonosExtraction.ArchX8664IdtEntryIdt.the_idtentry_handler_wrapper_is_its_method
#print axioms NonosExtraction.ArchX8664IdtEntryIdt.the_idtentry_ist_wrapper_is_its_method
#print axioms NonosExtraction.ArchX8664IdtEntryIdt.the_idtentry_dpl_wrapper_is_its_method
#print axioms NonosExtraction.ArchX8664IdtEntryIdt.the_idtentry_is_trap_wrapper_is_its_method

end NonosExtraction.ArchX8664IdtEntryIdt
