/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

tss_entry, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.ArchX8664GdtTssEntry

open Aeneas Aeneas.Std Result
open nonos_x_arch_x86_64_gdt_tss_entry

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.ArchX8664GdtTssEntry

/-! ### The forwarding functions add nothing -/

theorem the_tssentry_empty_wrapper_is_its_method :
    tssentry_empty = arch.x86_64.gdt.tss_entry.TssEntry.empty := rfl

theorem the_tssentry_new_wrapper_is_its_method (a : Std.U64) (b : Std.U32) :
    tssentry_new a b = arch.x86_64.gdt.tss_entry.TssEntry.new a b := rfl

theorem the_tssentry_base_wrapper_is_its_method (a : arch.x86_64.gdt.tss_entry.TssEntry) :
    tssentry_base a = arch.x86_64.gdt.tss_entry.TssEntry.base a := rfl

theorem the_tssentry_is_busy_wrapper_is_its_method (a : arch.x86_64.gdt.tss_entry.TssEntry) :
    tssentry_is_busy a = arch.x86_64.gdt.tss_entry.TssEntry.is_busy a := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.ArchX8664GdtTssEntry.the_tssentry_empty_wrapper_is_its_method
#print axioms NonosExtraction.ArchX8664GdtTssEntry.the_tssentry_new_wrapper_is_its_method
#print axioms NonosExtraction.ArchX8664GdtTssEntry.the_tssentry_base_wrapper_is_its_method
#print axioms NonosExtraction.ArchX8664GdtTssEntry.the_tssentry_is_busy_wrapper_is_its_method

end NonosExtraction.ArchX8664GdtTssEntry
