/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

scalarmult, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.AsymmetricEd25519PointScalarmult

open Aeneas Aeneas.Std Result
open nonos_x_asymmetric_ed25519_point_scalarmult

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.AsymmetricEd25519PointScalarmult

/-! ### The forwarding functions add nothing -/

theorem the_ct_byte_mask_wrapper_is_its_method (a : Std.U8) :
    ct_byte_mask a = crypto.asymmetric.ed25519.point.scalarmult.ct_byte_mask a := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.AsymmetricEd25519PointScalarmult.the_ct_byte_mask_wrapper_is_its_method

end NonosExtraction.AsymmetricEd25519PointScalarmult
