/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

flags, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.AttributesFlags

open Aeneas Aeneas.Std Result
open nonos_x_attributes_flags

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.AttributesFlags

/-! ### The forwarding functions add nothing -/

theorem the_pteflags_new_wrapper_is_its_method :
    pteflags_new = flags.PteFlags.new := rfl

theorem the_pteflags_from_bits_wrapper_is_its_method (a : Std.U64) :
    pteflags_from_bits a = flags.PteFlags.from_bits a := rfl

theorem the_pteflags_valid_wrapper_is_its_method (a : flags.PteFlags) :
    pteflags_valid a = flags.PteFlags.valid a := rfl

theorem the_pteflags_readable_wrapper_is_its_method (a : flags.PteFlags) :
    pteflags_readable a = flags.PteFlags.readable a := rfl

theorem the_pteflags_writable_wrapper_is_its_method (a : flags.PteFlags) :
    pteflags_writable a = flags.PteFlags.writable a := rfl

theorem the_pteflags_executable_wrapper_is_its_method (a : flags.PteFlags) :
    pteflags_executable a = flags.PteFlags.executable a := rfl

theorem the_pteflags_user_wrapper_is_its_method (a : flags.PteFlags) :
    pteflags_user a = flags.PteFlags.user a := rfl

theorem the_pteflags_global_wrapper_is_its_method (a : flags.PteFlags) :
    pteflags_global a = flags.PteFlags.global a := rfl

theorem the_pteflags_accessed_wrapper_is_its_method (a : flags.PteFlags) :
    pteflags_accessed a = flags.PteFlags.accessed a := rfl

theorem the_pteflags_dirty_wrapper_is_its_method (a : flags.PteFlags) :
    pteflags_dirty a = flags.PteFlags.dirty a := rfl

theorem the_pteflags_bits_wrapper_is_its_method (a : flags.PteFlags) :
    pteflags_bits a = flags.PteFlags.bits a := rfl

theorem the_pteflags_is_valid_wrapper_is_its_method (a : flags.PteFlags) :
    pteflags_is_valid a = flags.PteFlags.is_valid a := rfl

theorem the_pteflags_is_leaf_wrapper_is_its_method (a : flags.PteFlags) :
    pteflags_is_leaf a = flags.PteFlags.is_leaf a := rfl

theorem the_pteflags_is_readable_wrapper_is_its_method (a : flags.PteFlags) :
    pteflags_is_readable a = flags.PteFlags.is_readable a := rfl

theorem the_pteflags_is_writable_wrapper_is_its_method (a : flags.PteFlags) :
    pteflags_is_writable a = flags.PteFlags.is_writable a := rfl

theorem the_pteflags_is_executable_wrapper_is_its_method (a : flags.PteFlags) :
    pteflags_is_executable a = flags.PteFlags.is_executable a := rfl

theorem the_pteflags_is_user_wrapper_is_its_method (a : flags.PteFlags) :
    pteflags_is_user a = flags.PteFlags.is_user a := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.AttributesFlags.the_pteflags_new_wrapper_is_its_method
#print axioms NonosExtraction.AttributesFlags.the_pteflags_from_bits_wrapper_is_its_method
#print axioms NonosExtraction.AttributesFlags.the_pteflags_valid_wrapper_is_its_method
#print axioms NonosExtraction.AttributesFlags.the_pteflags_readable_wrapper_is_its_method
#print axioms NonosExtraction.AttributesFlags.the_pteflags_writable_wrapper_is_its_method
#print axioms NonosExtraction.AttributesFlags.the_pteflags_executable_wrapper_is_its_method
#print axioms NonosExtraction.AttributesFlags.the_pteflags_user_wrapper_is_its_method
#print axioms NonosExtraction.AttributesFlags.the_pteflags_global_wrapper_is_its_method
#print axioms NonosExtraction.AttributesFlags.the_pteflags_accessed_wrapper_is_its_method
#print axioms NonosExtraction.AttributesFlags.the_pteflags_dirty_wrapper_is_its_method
#print axioms NonosExtraction.AttributesFlags.the_pteflags_bits_wrapper_is_its_method
#print axioms NonosExtraction.AttributesFlags.the_pteflags_is_valid_wrapper_is_its_method
#print axioms NonosExtraction.AttributesFlags.the_pteflags_is_leaf_wrapper_is_its_method
#print axioms NonosExtraction.AttributesFlags.the_pteflags_is_readable_wrapper_is_its_method
#print axioms NonosExtraction.AttributesFlags.the_pteflags_is_writable_wrapper_is_its_method
#print axioms NonosExtraction.AttributesFlags.the_pteflags_is_executable_wrapper_is_its_method
#print axioms NonosExtraction.AttributesFlags.the_pteflags_is_user_wrapper_is_its_method

end NonosExtraction.AttributesFlags
