-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [nonos_x_boot_types_context]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace nonos_x_boot_types_context

/-- [nonos_x_boot_types_context::types_context::ExceptionContext]
    Source: 'src/../../../../../src/arch/x86_64/boot/types_context.rs', lines 19:0-42:1
    Visibility: public -/
structure types_context.ExceptionContext where
  r15 : Std.U64
  r14 : Std.U64
  r13 : Std.U64
  r12 : Std.U64
  r11 : Std.U64
  r10 : Std.U64
  r9 : Std.U64
  r8 : Std.U64
  rbp : Std.U64
  rdi : Std.U64
  rsi : Std.U64
  rdx : Std.U64
  rcx : Std.U64
  rbx : Std.U64
  rax : Std.U64
  vector : Std.U64
  error_code : Std.U64
  rip : Std.U64
  cs : Std.U64
  rflags : Std.U64
  rsp : Std.U64
  ss : Std.U64

/-- [nonos_x_boot_types_context::types_context::{nonos_x_boot_types_context::types_context::ExceptionContext}::instruction_pointer]:
    Source: 'src/../../../../../src/arch/x86_64/boot/types_context.rs', lines 45:4-47:5
    Visibility: public -/
def types_context.ExceptionContext.instruction_pointer
  (self : types_context.ExceptionContext) : Result Std.U64 := do
  ok self.rip

/-- [nonos_x_boot_types_context::types_context::{nonos_x_boot_types_context::types_context::ExceptionContext}::stack_pointer]:
    Source: 'src/../../../../../src/arch/x86_64/boot/types_context.rs', lines 48:4-50:5
    Visibility: public -/
def types_context.ExceptionContext.stack_pointer
  (self : types_context.ExceptionContext) : Result Std.U64 := do
  ok self.rsp

/-- [nonos_x_boot_types_context::types_context::{nonos_x_boot_types_context::types_context::ExceptionContext}::code_segment]:
    Source: 'src/../../../../../src/arch/x86_64/boot/types_context.rs', lines 51:4-53:5
    Visibility: public -/
def types_context.ExceptionContext.code_segment
  (self : types_context.ExceptionContext) : Result Std.U64 := do
  ok self.cs

/-- [nonos_x_boot_types_context::types_context::{nonos_x_boot_types_context::types_context::ExceptionContext}::is_user_mode]:
    Source: 'src/../../../../../src/arch/x86_64/boot/types_context.rs', lines 54:4-56:5
    Visibility: public -/
def types_context.ExceptionContext.is_user_mode
  (self : types_context.ExceptionContext) : Result Bool := do
  let i ← lift (self.cs &&& 3#u64)
  ok (i = 3#u64)

/-- [nonos_x_boot_types_context::types_context::{nonos_x_boot_types_context::types_context::ExceptionContext}::is_kernel_mode]:
    Source: 'src/../../../../../src/arch/x86_64/boot/types_context.rs', lines 57:4-59:5
    Visibility: public -/
def types_context.ExceptionContext.is_kernel_mode
  (self : types_context.ExceptionContext) : Result Bool := do
  let i ← lift (self.cs &&& 3#u64)
  ok (i = 0#u64)

/-- [nonos_x_boot_types_context::types_context::{nonos_x_boot_types_context::types_context::ExceptionContext}::has_error_code]:
    Source: 'src/../../../../../src/arch/x86_64/boot/types_context.rs', lines 60:4-62:5
    Visibility: public -/
def types_context.ExceptionContext.has_error_code
  (self : types_context.ExceptionContext) : Result Bool := do
  match self.vector with
  | 8#uscalar => ok true
  | 10#uscalar => ok true
  | 11#uscalar => ok true
  | 12#uscalar => ok true
  | 13#uscalar => ok true
  | 14#uscalar => ok true
  | 17#uscalar => ok true
  | 21#uscalar => ok true
  | 29#uscalar => ok true
  | 30#uscalar => ok true
  | _ => ok false

/-- [nonos_x_boot_types_context::exceptioncontext_instruction_pointer]:
    Source: 'src/lib.rs', lines 10:0-12:1
    Visibility: public -/
def exceptioncontext_instruction_pointer
  (this : types_context.ExceptionContext) : Result Std.U64 := do
  types_context.ExceptionContext.instruction_pointer this

/-- [nonos_x_boot_types_context::exceptioncontext_stack_pointer]:
    Source: 'src/lib.rs', lines 14:0-16:1
    Visibility: public -/
def exceptioncontext_stack_pointer
  (this : types_context.ExceptionContext) : Result Std.U64 := do
  types_context.ExceptionContext.stack_pointer this

/-- [nonos_x_boot_types_context::exceptioncontext_code_segment]:
    Source: 'src/lib.rs', lines 18:0-20:1
    Visibility: public -/
def exceptioncontext_code_segment
  (this : types_context.ExceptionContext) : Result Std.U64 := do
  types_context.ExceptionContext.code_segment this

/-- [nonos_x_boot_types_context::exceptioncontext_is_user_mode]:
    Source: 'src/lib.rs', lines 22:0-24:1
    Visibility: public -/
def exceptioncontext_is_user_mode
  (this : types_context.ExceptionContext) : Result Bool := do
  types_context.ExceptionContext.is_user_mode this

/-- [nonos_x_boot_types_context::exceptioncontext_is_kernel_mode]:
    Source: 'src/lib.rs', lines 26:0-28:1
    Visibility: public -/
def exceptioncontext_is_kernel_mode
  (this : types_context.ExceptionContext) : Result Bool := do
  types_context.ExceptionContext.is_kernel_mode this

/-- [nonos_x_boot_types_context::exceptioncontext_has_error_code]:
    Source: 'src/lib.rs', lines 30:0-32:1
    Visibility: public -/
def exceptioncontext_has_error_code
  (this : types_context.ExceptionContext) : Result Bool := do
  types_context.ExceptionContext.has_error_code this

end nonos_x_boot_types_context
