-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [nonos_x_boot_handoff_types_framebuffer]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace nonos_x_boot_handoff_types_framebuffer

/-- [nonos_x_boot_handoff_types_framebuffer::boot::handoff::types::framebuffer::FramebufferInfo]
    Source: 'src/boot/handoff/types/../../../../../../../../src/boot/handoff/types/framebuffer.rs', lines 21:0-31:1
    Visibility: public -/
structure boot.handoff.types.framebuffer.FramebufferInfo where
  ptr : Std.U64
  size : Std.U64
  width : Std.U32
  height : Std.U32
  stride : Std.U32
  pixel_format : Std.U32
  cursor_y : Std.U32
  reserved : Std.U32

/-- [nonos_x_boot_handoff_types_framebuffer::boot::handoff::types::framebuffer::{nonos_x_boot_handoff_types_framebuffer::boot::handoff::types::framebuffer::FramebufferInfo}::is_valid]:
    Source: 'src/boot/handoff/types/../../../../../../../../src/boot/handoff/types/framebuffer.rs', lines 35:4-37:5
    Visibility: public -/
def boot.handoff.types.framebuffer.FramebufferInfo.is_valid
  (self : boot.handoff.types.framebuffer.FramebufferInfo) : Result Bool := do
  if self.ptr != 0#u64
  then
    if self.width > 0#u32
    then if self.height > 0#u32
         then ok (self.stride > 0#u32)
         else ok false
    else ok false
  else ok false

/-- [nonos_x_boot_handoff_types_framebuffer::boot::handoff::types::framebuffer::{nonos_x_boot_handoff_types_framebuffer::boot::handoff::types::framebuffer::FramebufferInfo}::bytes_per_pixel]:
    Source: 'src/boot/handoff/types/../../../../../../../../src/boot/handoff/types/framebuffer.rs', lines 40:4-46:5
    Visibility: public -/
def boot.handoff.types.framebuffer.FramebufferInfo.bytes_per_pixel
  (self : boot.handoff.types.framebuffer.FramebufferInfo) :
  Result Std.U32
  := do
  match self.pixel_format with
  | 0#uscalar => ok 3#u32
  | 1#uscalar => ok 3#u32
  | 2#uscalar => ok 4#u32
  | 3#uscalar => ok 4#u32
  | _ => ok 4#u32

/-- [nonos_x_boot_handoff_types_framebuffer::framebufferinfo_is_valid]:
    Source: 'src/lib.rs', lines 11:0-13:1
    Visibility: public -/
def framebufferinfo_is_valid
  (this : boot.handoff.types.framebuffer.FramebufferInfo) : Result Bool := do
  boot.handoff.types.framebuffer.FramebufferInfo.is_valid this

/-- [nonos_x_boot_handoff_types_framebuffer::framebufferinfo_bytes_per_pixel]:
    Source: 'src/lib.rs', lines 15:0-17:1
    Visibility: public -/
def framebufferinfo_bytes_per_pixel
  (this : boot.handoff.types.framebuffer.FramebufferInfo) :
  Result Std.U32
  := do
  boot.handoff.types.framebuffer.FramebufferInfo.bytes_per_pixel this

end nonos_x_boot_handoff_types_framebuffer
