-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [nonos_x_bti_pad]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace nonos_x_bti_pad

/-- [nonos_x_bti_pad::pad::is_bti_landing_pad]:
    Source: 'src/../../../../../src/arch/aarch64/security/bti/pad.rs', lines 27:0-29:1
    Visibility: public -/
def pad.is_bti_landing_pad (instruction : Std.U32) : Result Bool := do
  match instruction with
  | 3573752927#uscalar => ok true
  | 3573752991#uscalar => ok true
  | 3573753055#uscalar => ok true
  | 3573752639#uscalar => ok true
  | 3573752703#uscalar => ok true
  | _ => ok false

/-- [nonos_x_bti_pad::is_bti_landing_pad]:
    Source: 'src/lib.rs', lines 10:0-12:1
    Visibility: public -/
def is_bti_landing_pad (instruction : Std.U32) : Result Bool := do
  pad.is_bti_landing_pad instruction

end nonos_x_bti_pad
