/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

stats, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.BuddyTypesStats

open Aeneas Aeneas.Std Result
open nonos_x_buddy_types_stats

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.BuddyTypesStats

/-! ### The forwarding functions add nothing -/

theorem the_allocstats_new_wrapper_is_its_method :
    allocstats_new = stats.AllocStats.new := rfl

theorem the_allocstats_free_memory_wrapper_is_its_method (a : stats.AllocStats) (b : Std.U64) :
    allocstats_free_memory a b = stats.AllocStats.free_memory a b := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.BuddyTypesStats.the_allocstats_new_wrapper_is_its_method
#print axioms NonosExtraction.BuddyTypesStats.the_allocstats_free_memory_wrapper_is_its_method

end NonosExtraction.BuddyTypesStats
