/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

chain, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.CapabilitiesChainChain

open Aeneas Aeneas.Std Result
open nonos_x_capabilities_chain_chain

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.CapabilitiesChainChain

/-! ### The forwarding functions add nothing -/

theorem the_capabilitychain_empty_wrapper_is_its_method :
    capabilitychain_empty = capabilities.chain.chain.CapabilityChain.empty := rfl

theorem the_capabilitychain_len_wrapper_is_its_method (a : capabilities.chain.chain.CapabilityChain) :
    capabilitychain_len a = capabilities.chain.chain.CapabilityChain.len a := rfl

theorem the_capabilitychain_is_empty_wrapper_is_its_method (a : capabilities.chain.chain.CapabilityChain) :
    capabilitychain_is_empty a = capabilities.chain.chain.CapabilityChain.is_empty a := rfl

theorem the_capabilitychain_max_depth_wrapper_is_its_method :
    capabilitychain_max_depth = capabilities.chain.chain.CapabilityChain.max_depth := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.CapabilitiesChainChain.the_capabilitychain_empty_wrapper_is_its_method
#print axioms NonosExtraction.CapabilitiesChainChain.the_capabilitychain_len_wrapper_is_its_method
#print axioms NonosExtraction.CapabilitiesChainChain.the_capabilitychain_is_empty_wrapper_is_its_method
#print axioms NonosExtraction.CapabilitiesChainChain.the_capabilitychain_max_depth_wrapper_is_its_method

end NonosExtraction.CapabilitiesChainChain
