-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [nonos_x_cap_fault]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace nonos_x_cap_fault

/-- [nonos_x_cap_fault::fault::fault_recording_offset]:
    Source: 'src/../../../../../src/arch/x86_64/iommu/regs/cap/fault.rs', lines 18:0-20:1
    Visibility: public -/
def fault.fault_recording_offset (cap : Std.U64) : Result Std.Usize := do
  let i ← cap >>> 24#i32
  let i1 ← lift (i &&& 1023#u64)
  let i2 ← lift (UScalar.cast .Usize i1)
  i2 * 16#usize

/-- [nonos_x_cap_fault::fault::fault_recording_count]:
    Source: 'src/../../../../../src/arch/x86_64/iommu/regs/cap/fault.rs', lines 23:0-25:1
    Visibility: public -/
def fault.fault_recording_count (cap : Std.U64) : Result Std.U16 := do
  let i ← cap >>> 40#i32
  let i1 ← lift (i &&& 255#u64)
  let i2 ← lift (UScalar.cast .U16 i1)
  i2 + 1#u16

/-- [nonos_x_cap_fault::fault_recording_offset]:
    Source: 'src/lib.rs', lines 10:0-12:1
    Visibility: public -/
def fault_recording_offset (cap : Std.U64) : Result Std.Usize := do
  fault.fault_recording_offset cap

/-- [nonos_x_cap_fault::fault_recording_count]:
    Source: 'src/lib.rs', lines 14:0-16:1
    Visibility: public -/
def fault_recording_count (cap : Std.U64) : Result Std.U16 := do
  fault.fault_recording_count cap

end nonos_x_cap_fault
