/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

buf, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.CensusBuf

open Aeneas Aeneas.Std Result
open nonos_x_census_buf

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.CensusBuf

/-! ### The forwarding functions add nothing -/

theorem the_linebuf_new_wrapper_is_its_method :
    linebuf_new = buf.LineBuf.new := rfl

/-! ### A new line buffer is empty and in bounds

    `put`, `hex` and `dec` write `data[len]` only while `len < 100`, and
    `as_str` slices `data[..len]`. Both rely on `len` never exceeding the
    storage, and a fresh buffer is expected to start with nothing in it. The
    theorem below says `new` establishes that: the length is zero, strictly
    below the storage length of 100, and every byte is zero. The writers and
    `as_str` are not extracted, so the invariant is shown to hold at birth, not
    to be preserved.
-/

/-- A new buffer has length zero, room for all 100 bytes, and zeroed storage,
    so its first `put` writes `data[0]` and its `as_str` is the empty string. -/
theorem linebuf_new_is_empty_with_zeroed_storage :
    ∃ b, linebuf_new = ok b ∧ b.len.val = 0 ∧
      b.data.val = List.replicate 100 0#u8 ∧ b.len.val < b.data.val.length := by
  refine ⟨_, rfl, rfl, rfl, ?_⟩
  decide

/-! ### Axiom profile -/

#print axioms NonosExtraction.CensusBuf.the_linebuf_new_wrapper_is_its_method
#print axioms NonosExtraction.CensusBuf.linebuf_new_is_empty_with_zeroed_storage

end NonosExtraction.CensusBuf
