/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

error, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.ChainError

open Aeneas Aeneas.Std Result
open nonos_x_chain_error

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.ChainError

/-! ### The forwarding functions add nothing -/

theorem the_chainerror_is_recoverable_wrapper_is_its_method (a : error.ChainError) :
    chainerror_is_recoverable a = error.ChainError.is_recoverable a := rfl

/-! ### Only expiry and absence are worth retrying

A capability-chain check that fails with a recoverable error invites the caller
to refresh and try again; one that fails with an unrecoverable error means the
chain itself is bad. These theorems establish that `is_recoverable` answers for
every error, answers `true` exactly for `ExpiredToken` and
`CapabilityNotFound`, and so never reports a forged signature (`InvalidToken`),
a broken delegation link, an over-deep chain or an empty chain as retryable.

They cannot establish that the verifier raises the right variant for a given
chain: the verifier is not in this crate.
-/

/-- `chainerror_is_recoverable` always answers, and answers `true` exactly for
    an expired token or a missing capability. -/
theorem chainerror_is_recoverable_exactly_for_expiry_and_absence (e : error.ChainError) :
    ∃ b, chainerror_is_recoverable e = ok b ∧
      (b = true ↔ ((∃ i, e = .ExpiredToken i) ∨ e = .CapabilityNotFound)) := by
  unfold chainerror_is_recoverable error.ChainError.is_recoverable
  cases e <;> simp

/-- No integrity failure is ever reported as retryable by
    `chainerror_is_recoverable`. -/
theorem chainerror_is_recoverable_refuses_every_integrity_failure (i d m : Std.Usize) :
    chainerror_is_recoverable (.InvalidToken i) = ok false ∧
    chainerror_is_recoverable (.BrokenLink i) = ok false ∧
    chainerror_is_recoverable (.TooDeep d m) = ok false ∧
    chainerror_is_recoverable .EmptyChain = ok false :=
  ⟨rfl, rfl, rfl, rfl⟩

/-! ### Axiom profile -/

#print axioms NonosExtraction.ChainError.the_chainerror_is_recoverable_wrapper_is_its_method

#print axioms NonosExtraction.ChainError.chainerror_is_recoverable_exactly_for_expiry_and_absence
#print axioms NonosExtraction.ChainError.chainerror_is_recoverable_refuses_every_integrity_failure

end NonosExtraction.ChainError
