/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

days, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.CivilDays

open Aeneas Aeneas.Std Result
open nonos_x_civil_days

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.CivilDays

/-! ### The forwarding functions add nothing -/

theorem the_is_leap_year_wrapper_is_its_method (a : Std.U16) :
    is_leap_year a = days.is_leap_year a := rfl

theorem the_days_in_month_wrapper_is_its_method (a : Std.U16) (b : Std.U8) :
    days_in_month a b = days.days_in_month a b := rfl

theorem the_days_in_year_wrapper_is_its_method (a : Std.U16) :
    days_in_year a = days.days_in_year a := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.CivilDays.the_is_leap_year_wrapper_is_its_method
#print axioms NonosExtraction.CivilDays.the_days_in_month_wrapper_is_its_method
#print axioms NonosExtraction.CivilDays.the_days_in_year_wrapper_is_its_method

end NonosExtraction.CivilDays
