/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

mode, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.CoherencyMode

open Aeneas Aeneas.Std Result
open nonos_x_coherency_mode

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.CoherencyMode

/-! ### The forwarding functions add nothing -/

theorem the_coherency_from_bool_wrapper_is_its_method (a : Bool) :
    coherency_from_bool a = mode.Coherency.from_bool a := rfl

theorem the_coherency_is_coherent_wrapper_is_its_method (a : mode.Coherency) :
    coherency_is_coherent a = mode.Coherency.is_coherent a := rfl

theorem the_coherency_requires_cache_maintenance_wrapper_is_its_method (a : mode.Coherency) :
    coherency_requires_cache_maintenance a = mode.Coherency.requires_cache_maintenance a := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.CoherencyMode.the_coherency_from_bool_wrapper_is_its_method
#print axioms NonosExtraction.CoherencyMode.the_coherency_is_coherent_wrapper_is_its_method
#print axioms NonosExtraction.CoherencyMode.the_coherency_requires_cache_maintenance_wrapper_is_its_method

end NonosExtraction.CoherencyMode
