-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [nonos_x_constants_address_packing]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace nonos_x_constants_address_packing

/-- [nonos_x_constants_address_packing::address_packing::pci_config_address]:
    Source: 'src/../../../../../src/drivers/pci/constants/address_packing.rs', lines 18:0-24:1
    Visibility: public -/
def address_packing.pci_config_address
  (bus : Std.U8) (device : Std.U8) (function : Std.U8) (offset : Std.U8) :
  Result Std.U32
  := do
  let i ← 1#u32 <<< 31#i32
  let i1 ← lift (UScalar.cast .U32 bus)
  let i2 ← i1 <<< 16#i32
  let i3 ← lift (i ||| i2)
  let i4 ← lift (device &&& 31#u8)
  let i5 ← lift (UScalar.cast .U32 i4)
  let i6 ← i5 <<< 11#i32
  let i7 ← lift (i3 ||| i6)
  let i8 ← lift (function &&& 7#u8)
  let i9 ← lift (UScalar.cast .U32 i8)
  let i10 ← i9 <<< 8#i32
  let i11 ← lift (i7 ||| i10)
  let i12 ← lift (UScalar.cast .U32 offset)
  let i13 ← lift (i12 &&& 252#u32)
  ok (i11 ||| i13)

/-- [nonos_x_constants_address_packing::pci_config_address]:
    Source: 'src/lib.rs', lines 10:0-12:1
    Visibility: public -/
def pci_config_address
  (bus : Std.U8) (device : Std.U8) (function : Std.U8) (offset : Std.U8) :
  Result Std.U32
  := do
  address_packing.pci_config_address bus device function offset

end nonos_x_constants_address_packing
