/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

section, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.CoreSection
import NonosExtraction.Bits

open Aeneas Aeneas.Std Result
open nonos_x_core_section

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.CoreSection

/-! ### The forwarding functions add nothing -/

theorem the_parsedsection_is_alloc_wrapper_is_its_method (a : section.ParsedSection) :
    parsedsection_is_alloc a = section.ParsedSection.is_alloc a := rfl

theorem the_parsedsection_is_symtab_wrapper_is_its_method (a : section.ParsedSection) :
    parsedsection_is_symtab a = section.ParsedSection.is_symtab a := rfl

theorem the_parsedsection_is_strtab_wrapper_is_its_method (a : section.ParsedSection) :
    parsedsection_is_strtab a = section.ParsedSection.is_strtab a := rfl

theorem the_parsedsection_is_rela_wrapper_is_its_method (a : section.ParsedSection) :
    parsedsection_is_rela a = section.ParsedSection.is_rela a := rfl

/-! ### Each classifier answers exactly the gABI question it names

The loader's `ParsedSection` answers four questions about a section header, and
the theorems here pin each answer to the ELF gABI value the kernel names in
`elf::types::constants`: `SHF_ALLOC = 1 << 1` in `shdr_flags`, and
`SHT_SYMTAB = 2`, `SHT_STRTAB = 3`, `SHT_RELA = 4`, `SHT_REL = 9` and
`SHT_DYNSYM = 11` in `shdr_type`. `is_alloc` reads bit 1 of the flags word and
no other bit, so a section that is only writable or only executable is not
allocated. The three type classifiers read the type word alone, and hit exactly
their values: no two of them hold for one section, `SHT_REL` (whose entries have
no addend) is never taken for `SHT_RELA`, and `is_symtab` holds for the full
symbol table only, not for the dynamic one.

`is_symtab` used to accept `SHT_DYNSYM` as well, so `ElfLoader::get_symbol_table`,
which returns the first section for which it holds, returned `.dynsym` on an
image that places it before `.symtab`; `get_dynsym` exists for that section. The
loader methods that iterate over sections are not extracted, so the theorems
below cannot state what `get_symbol_table` returns; they state only the
predicate it filters by. The kernel literals are restated
here as numerals because the constants module is not extracted.
-/

/-- The allocation test is bit 1 of the flags word (gABI `SHF_ALLOC`) and nothing
    else: neither `SHF_WRITE` (bit 0), nor `SHF_EXECINSTR` (bit 2), nor any higher
    flag bit changes the answer. -/
theorem parsedsection_is_alloc_reads_exactly_the_shf_alloc_bit (s : section.ParsedSection) :
    parsedsection_is_alloc s = ok (s.flags.val.testBit 1) := by
  unfold parsedsection_is_alloc section.ParsedSection.is_alloc
  simp only [lift, bind_tc_ok]
  rw [Bits.reads_bit s.flags 2#u64 0#u64 1 (by rfl) (by rfl)]

/-- A section flagged writable and executable but not `SHF_ALLOC` (flags `0x5`)
    is not allocated, and the bare `SHF_ALLOC` word `0x2` is. -/
theorem parsedsection_is_alloc_refuses_write_exec_and_accepts_alloc
    (s : section.ParsedSection) :
    parsedsection_is_alloc { s with flags := 5#u64 } = ok false ∧
    parsedsection_is_alloc { s with flags := 2#u64 } = ok true := by
  rw [parsedsection_is_alloc_reads_exactly_the_shf_alloc_bit,
    parsedsection_is_alloc_reads_exactly_the_shf_alloc_bit]
  have h5 : ((5 : Nat).testBit 1) = false := by decide
  have h2 : ((2 : Nat).testBit 1) = true := by decide
  exact ⟨congrArg ok h5, congrArg ok h2⟩

/-- A section counts as a symbol table exactly when its type is `SHT_SYMTAB`
    (2). -/
theorem parsedsection_is_symtab_holds_exactly_for_type_two
    (s : section.ParsedSection) :
    parsedsection_is_symtab s = ok true ↔ s.section_type.val = 2 := by
  unfold parsedsection_is_symtab section.ParsedSection.is_symtab
  have h2 : s.section_type = 2#u32 ↔ s.section_type.val = 2 :=
    ⟨fun h => by rw [h]; rfl, fun h => UScalar.eq_of_val_eq (by rw [h]; rfl)⟩
  simp only [ok.injEq, decide_eq_true_eq]
  exact h2

/-- A dynamic symbol table (`SHT_DYNSYM`, 11) does not pass `is_symtab`, whatever
    its name, flags or placement. It used to. -/
theorem parsedsection_is_symtab_refuses_a_dynamic_symbol_table (s : section.ParsedSection) :
    parsedsection_is_symtab { s with section_type := 11#u32 } = ok false := by
  unfold parsedsection_is_symtab section.ParsedSection.is_symtab
  rfl

/-- A section is a string table exactly when its type is `SHT_STRTAB` (3). -/
theorem parsedsection_is_strtab_holds_exactly_for_type_three (s : section.ParsedSection) :
    parsedsection_is_strtab s = ok true ↔ s.section_type.val = 3 := by
  unfold parsedsection_is_strtab section.ParsedSection.is_strtab
  simp only [ok.injEq, decide_eq_true_eq]
  exact ⟨fun h => by rw [h]; rfl, fun h => UScalar.eq_of_val_eq (by rw [h]; rfl)⟩

/-- The string table test reads the type word alone: two sections with the same
    type get the same answer, whatever their names, flags, addresses or sizes. -/
theorem parsedsection_is_strtab_depends_only_on_the_type
    (s t : section.ParsedSection) (h : s.section_type = t.section_type) :
    parsedsection_is_strtab s = parsedsection_is_strtab t := by
  unfold parsedsection_is_strtab section.ParsedSection.is_strtab
  rw [h]

/-- A section is a RELA relocation table exactly when its type is `SHT_RELA` (4). -/
theorem parsedsection_is_rela_holds_exactly_for_type_four (s : section.ParsedSection) :
    parsedsection_is_rela s = ok true ↔ s.section_type.val = 4 := by
  unfold parsedsection_is_rela section.ParsedSection.is_rela
  simp only [ok.injEq, decide_eq_true_eq]
  exact ⟨fun h => by rw [h]; rfl, fun h => UScalar.eq_of_val_eq (by rw [h]; rfl)⟩

/-- An `SHT_REL` section (type 9), whose 16 byte entries carry no addend, is never
    taken for a 24 byte `SHT_RELA` table. -/
theorem parsedsection_is_rela_refuses_rel_sections (s : section.ParsedSection) :
    parsedsection_is_rela { s with section_type := 9#u32 } = ok false := by
  unfold parsedsection_is_rela section.ParsedSection.is_rela
  rfl

/-- The three type classifiers never overlap: a symbol table is neither a string
    table nor a RELA table, and a string table is not a RELA table. -/
theorem parsedsection_is_symtab_is_strtab_and_is_rela_are_disjoint
    (s : section.ParsedSection) :
    (parsedsection_is_symtab s = ok true → parsedsection_is_strtab s = ok false ∧
        parsedsection_is_rela s = ok false) ∧
    (parsedsection_is_strtab s = ok true → parsedsection_is_rela s = ok false) := by
  have hs := parsedsection_is_symtab_holds_exactly_for_type_two s
  have ht := parsedsection_is_strtab_holds_exactly_for_type_three s
  have hr := parsedsection_is_rela_holds_exactly_for_type_four s
  have bt : ∀ b : Bool, (ok b : Result Bool) = ok false ↔ ¬ (ok b : Result Bool) = ok true := by
    intro b; cases b <;> simp
  have et : parsedsection_is_strtab s = ok (decide (s.section_type = 3#u32)) := rfl
  have er : parsedsection_is_rela s = ok (decide (s.section_type = 4#u32)) := rfl
  refine ⟨fun h => ?_, fun h => ?_⟩
  · have := hs.mp h
    refine ⟨?_, ?_⟩
    · rw [et, bt, ← et, ht]; omega
    · rw [er, bt, ← er, hr]; omega
  · have := ht.mp h
    rw [er, bt, ← er, hr]; omega

/-! ### Axiom profile -/

#print axioms NonosExtraction.CoreSection.the_parsedsection_is_alloc_wrapper_is_its_method
#print axioms NonosExtraction.CoreSection.the_parsedsection_is_symtab_wrapper_is_its_method
#print axioms NonosExtraction.CoreSection.the_parsedsection_is_strtab_wrapper_is_its_method
#print axioms NonosExtraction.CoreSection.the_parsedsection_is_rela_wrapper_is_its_method
#print axioms NonosExtraction.CoreSection.parsedsection_is_alloc_reads_exactly_the_shf_alloc_bit
#print axioms NonosExtraction.CoreSection.parsedsection_is_alloc_refuses_write_exec_and_accepts_alloc
#print axioms NonosExtraction.CoreSection.parsedsection_is_symtab_holds_exactly_for_type_two
#print axioms NonosExtraction.CoreSection.parsedsection_is_symtab_refuses_a_dynamic_symbol_table
#print axioms NonosExtraction.CoreSection.parsedsection_is_strtab_holds_exactly_for_type_three
#print axioms NonosExtraction.CoreSection.parsedsection_is_strtab_depends_only_on_the_type
#print axioms NonosExtraction.CoreSection.parsedsection_is_rela_holds_exactly_for_type_four
#print axioms NonosExtraction.CoreSection.parsedsection_is_rela_refuses_rel_sections
#print axioms NonosExtraction.CoreSection.parsedsection_is_symtab_is_strtab_and_is_rela_are_disjoint

end NonosExtraction.CoreSection
