-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [nonos_x_cpu_cache_assoc]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace nonos_x_cpu_cache_assoc

/-- [nonos_x_cpu_cache_assoc::cache_assoc::decode_l2_assoc]:
    Source: 'src/../../../../../src/arch/x86_64/cpu/cache_assoc.rs', lines 17:0-33:1
    Visibility: public -/
def cache_assoc.decode_l2_assoc (encoded : Std.U8) : Result Std.U16 := do
  match encoded with
  | 0#uscalar => ok 0#u16
  | 1#uscalar => ok 1#u16
  | 2#uscalar => ok 2#u16
  | 4#uscalar => ok 4#u16
  | 6#uscalar => ok 8#u16
  | 8#uscalar => ok 16#u16
  | 10#uscalar => ok 32#u16
  | 11#uscalar => ok 48#u16
  | 12#uscalar => ok 64#u16
  | 13#uscalar => ok 96#u16
  | 14#uscalar => ok 128#u16
  | 15#uscalar => ok 0#u16
  | _ => ok 0#u16

/-- [nonos_x_cpu_cache_assoc::decode_l2_assoc]:
    Source: 'src/lib.rs', lines 10:0-12:1
    Visibility: public -/
def decode_l2_assoc (encoded : Std.U8) : Result Std.U16 := do
  cache_assoc.decode_l2_assoc encoded

end nonos_x_cpu_cache_assoc
