/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

stats, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.DataStats

open Aeneas Aeneas.Std Result
open nonos_x_data_stats

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.DataStats

/-! ### The forwarding functions add nothing -/

theorem the_acpistats_new_wrapper_is_its_method :
    acpistats_new = stats.AcpiStats.new := rfl

/-! ### The ACPI statistics start from zero

    The parser's `STATS` static is initialised with `AcpiStats::new()` and every
    field is then only incremented as tables are found. This theorem says that
    each of the seven counters starts at zero, so each later reading is a count
    of events rather than an offset from some initial value. It cannot say
    anything about the static or the lock around it, which Aeneas leaves opaque. -/

/-- Every counter of a new `AcpiStats` is zero. -/
theorem acpistats_new_starts_every_counter_at_zero :
    ∃ s, acpistats_new = ok s ∧
      s.tables_found.val = 0 ∧ s.processors_found.val = 0 ∧ s.ioapics_found.val = 0 ∧
      s.overrides_found.val = 0 ∧ s.numa_nodes.val = 0 ∧ s.pcie_segments.val = 0 ∧
      s.parse_errors.val = 0 :=
  ⟨_, rfl, rfl, rfl, rfl, rfl, rfl, rfl, rfl⟩

/-! ### Axiom profile -/

#print axioms NonosExtraction.DataStats.the_acpistats_new_wrapper_is_its_method
#print axioms NonosExtraction.DataStats.acpistats_new_starts_every_counter_at_zero

end NonosExtraction.DataStats
