-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [nonos_x_data_stats]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace nonos_x_data_stats

/-- [nonos_x_data_stats::stats::AcpiStats]
    Source: 'src/../../../../../src/arch/x86_64/acpi/data/stats.rs', lines 18:0-26:1
    Visibility: public -/
structure stats.AcpiStats where
  tables_found : Std.U32
  processors_found : Std.U32
  ioapics_found : Std.U32
  overrides_found : Std.U32
  numa_nodes : Std.U32
  pcie_segments : Std.U32
  parse_errors : Std.U32

/-- [nonos_x_data_stats::stats::{nonos_x_data_stats::stats::AcpiStats}::new]:
    Source: 'src/../../../../../src/arch/x86_64/acpi/data/stats.rs', lines 29:4-39:5
    Visibility: public -/
def stats.AcpiStats.new : Result stats.AcpiStats := do
  ok
    {
      tables_found := 0#u32,
      processors_found := 0#u32,
      ioapics_found := 0#u32,
      overrides_found := 0#u32,
      numa_nodes := 0#u32,
      pcie_segments := 0#u32,
      parse_errors := 0#u32
    }

/-- [nonos_x_data_stats::acpistats_new]:
    Source: 'src/lib.rs', lines 10:0-12:1
    Visibility: public -/
def acpistats_new : Result stats.AcpiStats := do
  stats.AcpiStats.new

end nonos_x_data_stats
