/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

ioapic, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.DataIoapic

open Aeneas Aeneas.Std Result
open nonos_x_data_ioapic

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.DataIoapic

/-! ### The forwarding functions add nothing -/

theorem the_ioapicinfo_gsi_max_wrapper_is_its_method (a : ioapic.IoApicInfo) :
    ioapicinfo_gsi_max a = ioapic.IoApicInfo.gsi_max a := rfl

/-! ### The last interrupt line of an I/O APIC

    `gsi_max` names the last global system interrupt of a chip as its base plus
    twenty three, which assumes the twenty four redirection entries of the
    common part. The base is copied from the firmware's MADT entry unchecked,
    and the sum used to overflow for a base in the top twenty three values of a
    `u32`, which halted the kernel with overflow checks on. It now saturates at
    `u32::MAX`: these theorems say it never fails, returns the base plus twenty
    three whenever that fits and `u32::MAX` otherwise. They cannot say that twenty four is the
    chip's real entry count: the interrupt tier reads that from the version
    register instead, and no caller of `gsi_max` exists under `src/` today. -/

/-- `gsi_max` never fails and is the base plus twenty three, saturated at
    `u32::MAX`. -/
theorem ioapicinfo_gsi_max_is_the_base_plus_twenty_three_saturated (i : ioapic.IoApicInfo) :
    ∃ r, ioapicinfo_gsi_max i = ok r ∧ r.val = min (2 ^ 32 - 1) (i.gsi_base.val + 23) := by
  unfold ioapicinfo_gsi_max ioapic.IoApicInfo.gsi_max
  refine ⟨_, rfl, ?_⟩
  simp only [core.num.U32.saturating_add, UScalar.saturating_add, UScalar.val, UScalar.max]
  rw [BitVec.toNat_ofNat]
  show min (2 ^ 32 - 1) _ % 2 ^ 32 = _
  exact Nat.mod_eq_of_lt (by omega)

/-- A base up to `0xFFFFFFE8` gives the line twenty three above it. -/
theorem ioapicinfo_gsi_max_is_the_base_plus_twenty_three (i : ioapic.IoApicInfo)
    (h : i.gsi_base.val ≤ 0xFFFFFFE8) :
    ∃ r, ioapicinfo_gsi_max i = ok r ∧ r.val = i.gsi_base.val + 23 := by
  obtain ⟨r, hr, hv⟩ := ioapicinfo_gsi_max_is_the_base_plus_twenty_three_saturated i
  exact ⟨r, hr, by omega⟩

/-- A base above `0xFFFFFFE8` gives `u32::MAX` rather than halting. -/
theorem ioapicinfo_gsi_max_saturates_on_a_base_in_the_top_twenty_three
    (i : ioapic.IoApicInfo) (h : 0xFFFFFFE8 < i.gsi_base.val) :
    ∃ r, ioapicinfo_gsi_max i = ok r ∧ r.val = 2 ^ 32 - 1 := by
  obtain ⟨r, hr, hv⟩ := ioapicinfo_gsi_max_is_the_base_plus_twenty_three_saturated i
  exact ⟨r, hr, by omega⟩

/-! ### Axiom profile -/

#print axioms NonosExtraction.DataIoapic.the_ioapicinfo_gsi_max_wrapper_is_its_method
#print axioms NonosExtraction.DataIoapic.ioapicinfo_gsi_max_is_the_base_plus_twenty_three_saturated
#print axioms NonosExtraction.DataIoapic.ioapicinfo_gsi_max_is_the_base_plus_twenty_three
#print axioms NonosExtraction.DataIoapic.ioapicinfo_gsi_max_saturates_on_a_base_in_the_top_twenty_three

end NonosExtraction.DataIoapic
