/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

interrupt, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.DataInterrupt

open Aeneas Aeneas.Std Result
open nonos_x_data_interrupt

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.DataInterrupt

/-! ### The forwarding functions add nothing -/

theorem the_interruptoverride_is_active_low_wrapper_is_its_method (a : interrupt.InterruptOverride) :
    interruptoverride_is_active_low a = interrupt.InterruptOverride.is_active_low a := rfl

theorem the_interruptoverride_is_level_triggered_wrapper_is_its_method (a : interrupt.InterruptOverride) :
    interruptoverride_is_level_triggered a = interrupt.InterruptOverride.is_level_triggered a := rfl

theorem the_nmiconfig_applies_to_all_wrapper_is_its_method (a : interrupt.NmiConfig) :
    nmiconfig_applies_to_all a = interrupt.NmiConfig.applies_to_all a := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.DataInterrupt.the_interruptoverride_is_active_low_wrapper_is_its_method
#print axioms NonosExtraction.DataInterrupt.the_interruptoverride_is_level_triggered_wrapper_is_its_method
#print axioms NonosExtraction.DataInterrupt.the_nmiconfig_applies_to_all_wrapper_is_its_method

end NonosExtraction.DataInterrupt
