/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

unsupported, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.DescriptorUnsupported

open Aeneas Aeneas.Std Result
open nonos_x_descriptor_unsupported

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.DescriptorUnsupported

/-! ### The forwarding functions add nothing -/

theorem the_leaf_wrapper_is_its_method (a : Std.U64) (b : Std.U64) :
    leaf a b = unsupported.leaf a b := rfl

theorem the_table_wrapper_is_its_method (a : Std.U64) (b : Bool) :
    table a b = unsupported.table a b := rfl

theorem the_is_present_wrapper_is_its_method (a : Std.U64) :
    is_present a = unsupported.is_present a := rfl

theorem the_is_block_wrapper_is_its_method (a : Std.U64) :
    is_block a = unsupported.is_block a := rfl

theorem the_address_wrapper_is_its_method (a : Std.U64) :
    address a = unsupported.address a := rfl

theorem the_is_writable_wrapper_is_its_method (a : Std.U64) :
    is_writable a = unsupported.is_writable a := rfl

theorem the_is_executable_wrapper_is_its_method (a : Std.U64) :
    is_executable a = unsupported.is_executable a := rfl

theorem the_is_user_wrapper_is_its_method (a : Std.U64) :
    is_user a = unsupported.is_user a := rfl

theorem the_table_grants_user_wrapper_is_its_method (a : Std.U64) :
    table_grants_user a = unsupported.table_grants_user a := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.DescriptorUnsupported.the_leaf_wrapper_is_its_method
#print axioms NonosExtraction.DescriptorUnsupported.the_table_wrapper_is_its_method
#print axioms NonosExtraction.DescriptorUnsupported.the_is_present_wrapper_is_its_method
#print axioms NonosExtraction.DescriptorUnsupported.the_is_block_wrapper_is_its_method
#print axioms NonosExtraction.DescriptorUnsupported.the_address_wrapper_is_its_method
#print axioms NonosExtraction.DescriptorUnsupported.the_is_writable_wrapper_is_its_method
#print axioms NonosExtraction.DescriptorUnsupported.the_is_executable_wrapper_is_its_method
#print axioms NonosExtraction.DescriptorUnsupported.the_is_user_wrapper_is_its_method
#print axioms NonosExtraction.DescriptorUnsupported.the_table_grants_user_wrapper_is_its_method

end NonosExtraction.DescriptorUnsupported
