/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

device, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.DistributorDevice

open Aeneas Aeneas.Std Result
open nonos_x_distributor_device

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.DistributorDevice

/-! ### The forwarding functions add nothing -/

theorem the_gicdistributor_new_wrapper_is_its_method (a : Std.U64) :
    gicdistributor_new a = device.GicDistributor.new a := rfl

/-! ### The distributor frame is where the firmware put it

    `new` records the base address it is given without masking, rounding or
    offsetting it, so every register access the driver makes is relative to the
    address the device tree or ACPI table reported. The theorems cannot say that
    the address is a valid, mapped distributor frame; that comes from the firmware
    tables and the MMIO mapping, neither of which is extracted.
-/

/-- The constructed distributor keeps the base exactly as given. -/
theorem gicdistributor_new_keeps_the_firmware_base (b : Std.U64) :
    ∃ d, gicdistributor_new b = ok d ∧ d.base = b := ⟨_, rfl, rfl⟩

/-- Different bases give different devices, so two frames are never collapsed
    onto one. -/
theorem gicdistributor_new_tells_bases_apart (a b : Std.U64) (h : gicdistributor_new a = gicdistributor_new b) : a = b := by
  simpa [gicdistributor_new, device.GicDistributor.new] using h

/-! ### Axiom profile -/

#print axioms NonosExtraction.DistributorDevice.the_gicdistributor_new_wrapper_is_its_method

#print axioms NonosExtraction.DistributorDevice.gicdistributor_new_keeps_the_firmware_base
#print axioms NonosExtraction.DistributorDevice.gicdistributor_new_tells_bases_apart

end NonosExtraction.DistributorDevice
