/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

device_class, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.DriversPciStatsDeviceClass

open Aeneas Aeneas.Std Result
open nonos_x_drivers_pci_stats_device_class

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.DriversPciStatsDeviceClass

/-! ### The forwarding functions add nothing -/

theorem the_deviceclassstats_new_wrapper_is_its_method :
    deviceclassstats_new = drivers.pci.stats.device_class.DeviceClassStats.new := rfl

theorem the_deviceclassstats_total_wrapper_is_its_method (a : drivers.pci.stats.device_class.DeviceClassStats) :
    deviceclassstats_total a = drivers.pci.stats.device_class.DeviceClassStats.total a := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.DriversPciStatsDeviceClass.the_deviceclassstats_new_wrapper_is_its_method
#print axioms NonosExtraction.DriversPciStatsDeviceClass.the_deviceclassstats_total_wrapper_is_its_method

end NonosExtraction.DriversPciStatsDeviceClass
