/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

msi, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.DriversPciTypesMsi

open Aeneas Aeneas.Std Result
open nonos_x_drivers_pci_types_msi

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.DriversPciTypesMsi

/-! ### The forwarding functions add nothing -/

theorem the_msiinfo_max_vectors_wrapper_is_its_method (a : drivers.pci.types.msi.MsiInfo) :
    msiinfo_max_vectors a = drivers.pci.types.msi.MsiInfo.max_vectors a := rfl

theorem the_msiinfo_allocated_vectors_wrapper_is_its_method (a : drivers.pci.types.msi.MsiInfo) :
    msiinfo_allocated_vectors a = drivers.pci.types.msi.MsiInfo.allocated_vectors a := rfl

theorem the_msixinfo_vector_count_wrapper_is_its_method (a : drivers.pci.types.msi.MsixInfo) :
    msixinfo_vector_count a = drivers.pci.types.msi.MsixInfo.vector_count a := rfl

theorem the_msimessage_new_wrapper_is_its_method (a : Std.U8) (b : Std.U8) (c : Bool) (d : Bool) :
    msimessage_new a b c d = drivers.pci.types.msi.MsiMessage.new a b c d := rfl

theorem the_msimessage_for_local_apic_wrapper_is_its_method (a : Std.U8) (b : Std.U8) :
    msimessage_for_local_apic a b = drivers.pci.types.msi.MsiMessage.for_local_apic a b := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.DriversPciTypesMsi.the_msiinfo_max_vectors_wrapper_is_its_method
#print axioms NonosExtraction.DriversPciTypesMsi.the_msiinfo_allocated_vectors_wrapper_is_its_method
#print axioms NonosExtraction.DriversPciTypesMsi.the_msixinfo_vector_count_wrapper_is_its_method
#print axioms NonosExtraction.DriversPciTypesMsi.the_msimessage_new_wrapper_is_its_method
#print axioms NonosExtraction.DriversPciTypesMsi.the_msimessage_for_local_apic_wrapper_is_its_method

end NonosExtraction.DriversPciTypesMsi
