-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [nonos_x_drivers_pci_stats_pci_stats]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace nonos_x_drivers_pci_stats_pci_stats

/-- [core::sync::atomic::private::Align8]
    Source: '/rustc/library/core/src/sync/atomic.rs', lines 273:4-273:24
    Name pattern: [core::sync::atomic::private::Align8]
    Visibility: public -/
@[rust_type "core::sync::atomic::private::Align8"]
axiom core.sync.atomic.private.Align8 (T : Type) : Type

/-- [core::sync::atomic::Atomic]
    Source: '/rustc/library/core/src/sync/atomic.rs', lines 366:0-366:37
    Name pattern: [core::sync::atomic::Atomic]
    Visibility: public -/
@[rust_type "core::sync::atomic::Atomic"]
axiom core.sync.atomic.Atomic (T : Type) (Clause0_Storage : Type) : Type

/-- [core::sync::atomic::Ordering]
    Source: '/rustc/library/core/src/sync/atomic.rs', lines 447:0-447:17
    Name pattern: [core::sync::atomic::Ordering]
    Visibility: public -/
@[discriminant isize, rust_type "core::sync::atomic::Ordering"]
inductive core.sync.atomic.Ordering where
| Relaxed : core.sync.atomic.Ordering
| Release : core.sync.atomic.Ordering
| Acquire : core.sync.atomic.Ordering
| AcqRel : core.sync.atomic.Ordering
| SeqCst : core.sync.atomic.Ordering

/-- [core::sync::atomic::{core::sync::atomic::Atomic<u64, core::sync::atomic::private::Align8<u64>>}::new]:
    Source: '/rustc/library/core/src/sync/atomic.rs', lines 2628:12-2628:50
    Name pattern: [core::sync::atomic::{core::sync::atomic::Atomic<u64, core::sync::atomic::private::Align8<u64>>}::new]
    Visibility: public -/
@[rust_fun
  "core::sync::atomic::{core::sync::atomic::Atomic<u64, core::sync::atomic::private::Align8<u64>>}::new"]
axiom core.sync.atomic.AtomicU64Align8U64.new
  :
  Std.U64 → Result (core.sync.atomic.Atomic Std.U64
    (core.sync.atomic.private.Align8 Std.U64))

/-- [core::sync::atomic::{core::sync::atomic::Atomic<u64, core::sync::atomic::private::Align8<u64>>}::load]:
    Source: '/rustc/library/core/src/sync/atomic.rs', lines 2868:12-2868:60
    Name pattern: [core::sync::atomic::{core::sync::atomic::Atomic<u64, core::sync::atomic::private::Align8<u64>>}::load]
    Visibility: public -/
@[rust_fun
  "core::sync::atomic::{core::sync::atomic::Atomic<u64, core::sync::atomic::private::Align8<u64>>}::load"]
axiom core.sync.atomic.AtomicU64Align8U64.load
  :
  core.sync.atomic.Atomic Std.U64 (core.sync.atomic.private.Align8 Std.U64) →
    core.sync.atomic.Ordering → Result Std.U64

/-- [alloc::collections::btree::map::BTreeMap]
    Source: '/rustc/library/alloc/src/collections/btree/map.rs', lines 189:0-193:1
    Name pattern: [alloc::collections::btree::map::BTreeMap]
    Visibility: public -/
@[rust_type "alloc::collections::btree::map::BTreeMap"]
axiom alloc.collections.btree.map.BTreeMap (K : Type) (V : Type) (A : Type) :
  Type

/-- [alloc::collections::btree::map::{alloc::collections::btree::map::BTreeMap<K, V, alloc::alloc::Global>}::new]:
    Source: '/rustc/library/alloc/src/collections/btree/map.rs', lines 651:4-651:40
    Name pattern: [alloc::collections::btree::map::{alloc::collections::btree::map::BTreeMap<@K, @V, alloc::alloc::Global>}::new]
    Visibility: public -/
@[rust_fun
  "alloc::collections::btree::map::{alloc::collections::btree::map::BTreeMap<@K, @V, alloc::alloc::Global>}::new"]
axiom alloc.collections.btree.map.BTreeMapKVGlobal.new
  (K : Type) (V : Type) :
  Result (alloc.collections.btree.map.BTreeMap K V Global)

/-- [alloc::collections::btree::map::{impl core::default::Default for alloc::collections::btree::map::BTreeMap<K, V, alloc::alloc::Global>}::default]:
    Source: '/rustc/library/alloc/src/collections/btree/map.rs', lines 2599:4-2599:34
    Name pattern: [alloc::collections::btree::map::{core::default::Default<alloc::collections::btree::map::BTreeMap<@K, @V, alloc::alloc::Global>>}::default]
    Visibility: public -/
@[rust_fun
  "alloc::collections::btree::map::{core::default::Default<alloc::collections::btree::map::BTreeMap<@K, @V, alloc::alloc::Global>>}::default"]
axiom
  alloc.collections.btree.map.BTreeMapKVGlobal.Insts.CoreDefaultDefault.default
  (K : Type) (V : Type) :
  Result (alloc.collections.btree.map.BTreeMap K V Global)

/-- [nonos_x_drivers_pci_stats_pci_stats::drivers::pci::stats::atomics::TOTAL_DEVICES]
    Source: 'src/drivers/pci/stats/../../../../../../../../src/drivers/pci/stats/atomics.rs', lines 19:0-19:63 -/
@[global_simps, irreducible]
def drivers.pci.stats.atomics.TOTAL_DEVICES
  :
  Result (core.sync.atomic.Atomic Std.U64 (core.sync.atomic.private.Align8
    Std.U64))
  :=
  core.sync.atomic.AtomicU64Align8U64.new 0#u64

/-- [nonos_x_drivers_pci_stats_pci_stats::drivers::pci::stats::atomics::BRIDGE_DEVICES]
    Source: 'src/drivers/pci/stats/../../../../../../../../src/drivers/pci/stats/atomics.rs', lines 20:0-20:64 -/
@[global_simps, irreducible]
def drivers.pci.stats.atomics.BRIDGE_DEVICES
  :
  Result (core.sync.atomic.Atomic Std.U64 (core.sync.atomic.private.Align8
    Std.U64))
  :=
  core.sync.atomic.AtomicU64Align8U64.new 0#u64

/-- [nonos_x_drivers_pci_stats_pci_stats::drivers::pci::stats::atomics::MSI_CAPABLE_DEVICES]
    Source: 'src/drivers/pci/stats/../../../../../../../../src/drivers/pci/stats/atomics.rs', lines 21:0-21:69 -/
@[global_simps, irreducible]
def drivers.pci.stats.atomics.MSI_CAPABLE_DEVICES
  :
  Result (core.sync.atomic.Atomic Std.U64 (core.sync.atomic.private.Align8
    Std.U64))
  :=
  core.sync.atomic.AtomicU64Align8U64.new 0#u64

/-- [nonos_x_drivers_pci_stats_pci_stats::drivers::pci::stats::atomics::MSIX_CAPABLE_DEVICES]
    Source: 'src/drivers/pci/stats/../../../../../../../../src/drivers/pci/stats/atomics.rs', lines 22:0-22:70 -/
@[global_simps, irreducible]
def drivers.pci.stats.atomics.MSIX_CAPABLE_DEVICES
  :
  Result (core.sync.atomic.Atomic Std.U64 (core.sync.atomic.private.Align8
    Std.U64))
  :=
  core.sync.atomic.AtomicU64Align8U64.new 0#u64

/-- [nonos_x_drivers_pci_stats_pci_stats::drivers::pci::stats::atomics::PCIE_DEVICES]
    Source: 'src/drivers/pci/stats/../../../../../../../../src/drivers/pci/stats/atomics.rs', lines 23:0-23:62 -/
@[global_simps, irreducible]
def drivers.pci.stats.atomics.PCIE_DEVICES
  :
  Result (core.sync.atomic.Atomic Std.U64 (core.sync.atomic.private.Align8
    Std.U64))
  :=
  core.sync.atomic.AtomicU64Align8U64.new 0#u64

/-- [nonos_x_drivers_pci_stats_pci_stats::drivers::pci::stats::atomics::DMA_CAPABLE_DEVICES]
    Source: 'src/drivers/pci/stats/../../../../../../../../src/drivers/pci/stats/atomics.rs', lines 24:0-24:69 -/
@[global_simps, irreducible]
def drivers.pci.stats.atomics.DMA_CAPABLE_DEVICES
  :
  Result (core.sync.atomic.Atomic Std.U64 (core.sync.atomic.private.Align8
    Std.U64))
  :=
  core.sync.atomic.AtomicU64Align8U64.new 0#u64

/-- [nonos_x_drivers_pci_stats_pci_stats::drivers::pci::stats::atomics::ENUMERATION_COUNT]
    Source: 'src/drivers/pci/stats/../../../../../../../../src/drivers/pci/stats/atomics.rs', lines 25:0-25:67 -/
@[global_simps, irreducible]
def drivers.pci.stats.atomics.ENUMERATION_COUNT
  :
  Result (core.sync.atomic.Atomic Std.U64 (core.sync.atomic.private.Align8
    Std.U64))
  :=
  core.sync.atomic.AtomicU64Align8U64.new 0#u64

/-- [nonos_x_drivers_pci_stats_pci_stats::drivers::pci::stats::atomics::ENUMERATION_TIME_US]
    Source: 'src/drivers/pci/stats/../../../../../../../../src/drivers/pci/stats/atomics.rs', lines 26:0-26:69 -/
@[global_simps, irreducible]
def drivers.pci.stats.atomics.ENUMERATION_TIME_US
  :
  Result (core.sync.atomic.Atomic Std.U64 (core.sync.atomic.private.Align8
    Std.U64))
  :=
  core.sync.atomic.AtomicU64Align8U64.new 0#u64

/-- [nonos_x_drivers_pci_stats_pci_stats::drivers::pci::stats::atomics::CONFIG_READS]
    Source: 'src/drivers/pci/stats/../../../../../../../../src/drivers/pci/stats/atomics.rs', lines 27:0-27:62 -/
@[global_simps, irreducible]
def drivers.pci.stats.atomics.CONFIG_READS
  :
  Result (core.sync.atomic.Atomic Std.U64 (core.sync.atomic.private.Align8
    Std.U64))
  :=
  core.sync.atomic.AtomicU64Align8U64.new 0#u64

/-- [nonos_x_drivers_pci_stats_pci_stats::drivers::pci::stats::atomics::CONFIG_WRITES]
    Source: 'src/drivers/pci/stats/../../../../../../../../src/drivers/pci/stats/atomics.rs', lines 28:0-28:63 -/
@[global_simps, irreducible]
def drivers.pci.stats.atomics.CONFIG_WRITES
  :
  Result (core.sync.atomic.Atomic Std.U64 (core.sync.atomic.private.Align8
    Std.U64))
  :=
  core.sync.atomic.AtomicU64Align8U64.new 0#u64

/-- [nonos_x_drivers_pci_stats_pci_stats::drivers::pci::stats::atomics::CONFIG_ERRORS]
    Source: 'src/drivers/pci/stats/../../../../../../../../src/drivers/pci/stats/atomics.rs', lines 29:0-29:63 -/
@[global_simps, irreducible]
def drivers.pci.stats.atomics.CONFIG_ERRORS
  :
  Result (core.sync.atomic.Atomic Std.U64 (core.sync.atomic.private.Align8
    Std.U64))
  :=
  core.sync.atomic.AtomicU64Align8U64.new 0#u64

/-- [nonos_x_drivers_pci_stats_pci_stats::drivers::pci::stats::atomics::INTERRUPTS_TOTAL]
    Source: 'src/drivers/pci/stats/../../../../../../../../src/drivers/pci/stats/atomics.rs', lines 30:0-30:66 -/
@[global_simps, irreducible]
def drivers.pci.stats.atomics.INTERRUPTS_TOTAL
  :
  Result (core.sync.atomic.Atomic Std.U64 (core.sync.atomic.private.Align8
    Std.U64))
  :=
  core.sync.atomic.AtomicU64Align8U64.new 0#u64

/-- [nonos_x_drivers_pci_stats_pci_stats::drivers::pci::stats::atomics::MSI_INTERRUPTS]
    Source: 'src/drivers/pci/stats/../../../../../../../../src/drivers/pci/stats/atomics.rs', lines 31:0-31:64 -/
@[global_simps, irreducible]
def drivers.pci.stats.atomics.MSI_INTERRUPTS
  :
  Result (core.sync.atomic.Atomic Std.U64 (core.sync.atomic.private.Align8
    Std.U64))
  :=
  core.sync.atomic.AtomicU64Align8U64.new 0#u64

/-- [nonos_x_drivers_pci_stats_pci_stats::drivers::pci::stats::atomics::LEGACY_INTERRUPTS]
    Source: 'src/drivers/pci/stats/../../../../../../../../src/drivers/pci/stats/atomics.rs', lines 32:0-32:67 -/
@[global_simps, irreducible]
def drivers.pci.stats.atomics.LEGACY_INTERRUPTS
  :
  Result (core.sync.atomic.Atomic Std.U64 (core.sync.atomic.private.Align8
    Std.U64))
  :=
  core.sync.atomic.AtomicU64Align8U64.new 0#u64

/-- [nonos_x_drivers_pci_stats_pci_stats::drivers::pci::stats::atomics::HOTPLUG_EVENTS]
    Source: 'src/drivers/pci/stats/../../../../../../../../src/drivers/pci/stats/atomics.rs', lines 33:0-33:64 -/
@[global_simps, irreducible]
def drivers.pci.stats.atomics.HOTPLUG_EVENTS
  :
  Result (core.sync.atomic.Atomic Std.U64 (core.sync.atomic.private.Align8
    Std.U64))
  :=
  core.sync.atomic.AtomicU64Align8U64.new 0#u64

/-- [nonos_x_drivers_pci_stats_pci_stats::drivers::pci::stats::atomics::POWER_STATE_CHANGES]
    Source: 'src/drivers/pci/stats/../../../../../../../../src/drivers/pci/stats/atomics.rs', lines 34:0-34:69 -/
@[global_simps, irreducible]
def drivers.pci.stats.atomics.POWER_STATE_CHANGES
  :
  Result (core.sync.atomic.Atomic Std.U64 (core.sync.atomic.private.Align8
    Std.U64))
  :=
  core.sync.atomic.AtomicU64Align8U64.new 0#u64

/-- [nonos_x_drivers_pci_stats_pci_stats::drivers::pci::stats::atomics::LINK_STATE_CHANGES]
    Source: 'src/drivers/pci/stats/../../../../../../../../src/drivers/pci/stats/atomics.rs', lines 35:0-35:68 -/
@[global_simps, irreducible]
def drivers.pci.stats.atomics.LINK_STATE_CHANGES
  :
  Result (core.sync.atomic.Atomic Std.U64 (core.sync.atomic.private.Align8
    Std.U64))
  :=
  core.sync.atomic.AtomicU64Align8U64.new 0#u64

/-- [nonos_x_drivers_pci_stats_pci_stats::drivers::pci::stats::atomics::ERROR_EVENTS]
    Source: 'src/drivers/pci/stats/../../../../../../../../src/drivers/pci/stats/atomics.rs', lines 36:0-36:62 -/
@[global_simps, irreducible]
def drivers.pci.stats.atomics.ERROR_EVENTS
  :
  Result (core.sync.atomic.Atomic Std.U64 (core.sync.atomic.private.Align8
    Std.U64))
  :=
  core.sync.atomic.AtomicU64Align8U64.new 0#u64

/-- [nonos_x_drivers_pci_stats_pci_stats::drivers::pci::stats::pci_stats::PciStats]
    Source: 'src/drivers/pci/stats/../../../../../../../../src/drivers/pci/stats/pci_stats.rs', lines 23:0-44:1
    Visibility: public -/
structure drivers.pci.stats.pci_stats.PciStats where
  total_devices : Std.U64
  bridge_devices : Std.U64
  msi_capable_devices : Std.U64
  msix_capable_devices : Std.U64
  pcie_devices : Std.U64
  dma_capable_devices : Std.U64
  enumeration_count : Std.U64
  enumeration_time_us : Std.U64
  config_reads : Std.U64
  config_writes : Std.U64
  config_errors : Std.U64
  interrupts_total : Std.U64
  msi_interrupts : Std.U64
  legacy_interrupts : Std.U64
  hotplug_events : Std.U64
  power_state_changes : Std.U64
  link_state_changes : Std.U64
  error_events : Std.U64
  devices_by_class : alloc.collections.btree.map.BTreeMap Std.U8 Std.U64 Global
  devices_by_vendor : alloc.collections.btree.map.BTreeMap Std.U16 Std.U64
    Global

/-- [nonos_x_drivers_pci_stats_pci_stats::drivers::pci::stats::pci_stats::{impl core::default::Default for nonos_x_drivers_pci_stats_pci_stats::drivers::pci::stats::pci_stats::PciStats}::default]:
    Source: 'src/drivers/pci/stats/../../../../../../../../src/drivers/pci/stats/pci_stats.rs', lines 22:23-22:30
    Visibility: public -/
def drivers.pci.stats.pci_stats.PciStats.Insts.CoreDefaultDefault.default
  : Result drivers.pci.stats.pci_stats.PciStats := do
  let bm ←
    alloc.collections.btree.map.BTreeMapKVGlobal.Insts.CoreDefaultDefault.default
      Std.U8 Std.U64
  let bm1 ←
    alloc.collections.btree.map.BTreeMapKVGlobal.Insts.CoreDefaultDefault.default
      Std.U16 Std.U64
  ok
    {
      total_devices := (core.default.DefaultU64.default),
      bridge_devices := (core.default.DefaultU64.default),
      msi_capable_devices := (core.default.DefaultU64.default),
      msix_capable_devices := (core.default.DefaultU64.default),
      pcie_devices := (core.default.DefaultU64.default),
      dma_capable_devices := (core.default.DefaultU64.default),
      enumeration_count := (core.default.DefaultU64.default),
      enumeration_time_us := (core.default.DefaultU64.default),
      config_reads := (core.default.DefaultU64.default),
      config_writes := (core.default.DefaultU64.default),
      config_errors := (core.default.DefaultU64.default),
      interrupts_total := (core.default.DefaultU64.default),
      msi_interrupts := (core.default.DefaultU64.default),
      legacy_interrupts := (core.default.DefaultU64.default),
      hotplug_events := (core.default.DefaultU64.default),
      power_state_changes := (core.default.DefaultU64.default),
      link_state_changes := (core.default.DefaultU64.default),
      error_events := (core.default.DefaultU64.default),
      devices_by_class := bm,
      devices_by_vendor := bm1
    }

/-- [nonos_x_drivers_pci_stats_pci_stats::drivers::pci::stats::pci_stats::{nonos_x_drivers_pci_stats_pci_stats::drivers::pci::stats::pci_stats::PciStats}::new]:
    Source: 'src/drivers/pci/stats/../../../../../../../../src/drivers/pci/stats/pci_stats.rs', lines 47:4-49:5
    Visibility: public -/
def drivers.pci.stats.pci_stats.PciStats.new
  : Result drivers.pci.stats.pci_stats.PciStats := do
  drivers.pci.stats.pci_stats.PciStats.Insts.CoreDefaultDefault.default

/-- [nonos_x_drivers_pci_stats_pci_stats::drivers::pci::stats::pci_stats::{nonos_x_drivers_pci_stats_pci_stats::drivers::pci::stats::pci_stats::PciStats}::snapshot]:
    Source: 'src/drivers/pci/stats/../../../../../../../../src/drivers/pci/stats/pci_stats.rs', lines 51:4-74:5
    Visibility: public -/
def drivers.pci.stats.pci_stats.PciStats.snapshot
  : Result drivers.pci.stats.pci_stats.PciStats := do
  let a ← drivers.pci.stats.atomics.TOTAL_DEVICES
  let i ←
    core.sync.atomic.AtomicU64Align8U64.load a
      core.sync.atomic.Ordering.Relaxed
  let a1 ← drivers.pci.stats.atomics.BRIDGE_DEVICES
  let i1 ←
    core.sync.atomic.AtomicU64Align8U64.load a1
      core.sync.atomic.Ordering.Relaxed
  let a2 ← drivers.pci.stats.atomics.MSI_CAPABLE_DEVICES
  let i2 ←
    core.sync.atomic.AtomicU64Align8U64.load a2
      core.sync.atomic.Ordering.Relaxed
  let a3 ← drivers.pci.stats.atomics.MSIX_CAPABLE_DEVICES
  let i3 ←
    core.sync.atomic.AtomicU64Align8U64.load a3
      core.sync.atomic.Ordering.Relaxed
  let a4 ← drivers.pci.stats.atomics.PCIE_DEVICES
  let i4 ←
    core.sync.atomic.AtomicU64Align8U64.load a4
      core.sync.atomic.Ordering.Relaxed
  let a5 ← drivers.pci.stats.atomics.DMA_CAPABLE_DEVICES
  let i5 ←
    core.sync.atomic.AtomicU64Align8U64.load a5
      core.sync.atomic.Ordering.Relaxed
  let a6 ← drivers.pci.stats.atomics.ENUMERATION_COUNT
  let i6 ←
    core.sync.atomic.AtomicU64Align8U64.load a6
      core.sync.atomic.Ordering.Relaxed
  let a7 ← drivers.pci.stats.atomics.ENUMERATION_TIME_US
  let i7 ←
    core.sync.atomic.AtomicU64Align8U64.load a7
      core.sync.atomic.Ordering.Relaxed
  let a8 ← drivers.pci.stats.atomics.CONFIG_READS
  let i8 ←
    core.sync.atomic.AtomicU64Align8U64.load a8
      core.sync.atomic.Ordering.Relaxed
  let a9 ← drivers.pci.stats.atomics.CONFIG_WRITES
  let i9 ←
    core.sync.atomic.AtomicU64Align8U64.load a9
      core.sync.atomic.Ordering.Relaxed
  let a10 ← drivers.pci.stats.atomics.CONFIG_ERRORS
  let i10 ←
    core.sync.atomic.AtomicU64Align8U64.load a10
      core.sync.atomic.Ordering.Relaxed
  let a11 ← drivers.pci.stats.atomics.INTERRUPTS_TOTAL
  let i11 ←
    core.sync.atomic.AtomicU64Align8U64.load a11
      core.sync.atomic.Ordering.Relaxed
  let a12 ← drivers.pci.stats.atomics.MSI_INTERRUPTS
  let i12 ←
    core.sync.atomic.AtomicU64Align8U64.load a12
      core.sync.atomic.Ordering.Relaxed
  let a13 ← drivers.pci.stats.atomics.LEGACY_INTERRUPTS
  let i13 ←
    core.sync.atomic.AtomicU64Align8U64.load a13
      core.sync.atomic.Ordering.Relaxed
  let a14 ← drivers.pci.stats.atomics.HOTPLUG_EVENTS
  let i14 ←
    core.sync.atomic.AtomicU64Align8U64.load a14
      core.sync.atomic.Ordering.Relaxed
  let a15 ← drivers.pci.stats.atomics.POWER_STATE_CHANGES
  let i15 ←
    core.sync.atomic.AtomicU64Align8U64.load a15
      core.sync.atomic.Ordering.Relaxed
  let a16 ← drivers.pci.stats.atomics.LINK_STATE_CHANGES
  let i16 ←
    core.sync.atomic.AtomicU64Align8U64.load a16
      core.sync.atomic.Ordering.Relaxed
  let a17 ← drivers.pci.stats.atomics.ERROR_EVENTS
  let i17 ←
    core.sync.atomic.AtomicU64Align8U64.load a17
      core.sync.atomic.Ordering.Relaxed
  let bm ← alloc.collections.btree.map.BTreeMapKVGlobal.new Std.U8 Std.U64
  let bm1 ← alloc.collections.btree.map.BTreeMapKVGlobal.new Std.U16 Std.U64
  ok
    {
      total_devices := i,
      bridge_devices := i1,
      msi_capable_devices := i2,
      msix_capable_devices := i3,
      pcie_devices := i4,
      dma_capable_devices := i5,
      enumeration_count := i6,
      enumeration_time_us := i7,
      config_reads := i8,
      config_writes := i9,
      config_errors := i10,
      interrupts_total := i11,
      msi_interrupts := i12,
      legacy_interrupts := i13,
      hotplug_events := i14,
      power_state_changes := i15,
      link_state_changes := i16,
      error_events := i17,
      devices_by_class := bm,
      devices_by_vendor := bm1
    }

/-- [nonos_x_drivers_pci_stats_pci_stats::drivers::pci::stats::pci_stats::{nonos_x_drivers_pci_stats_pci_stats::drivers::pci::stats::pci_stats::PciStats}::average_enumeration_time_us]:
    Source: 'src/drivers/pci/stats/../../../../../../../../src/drivers/pci/stats/pci_stats.rs', lines 76:4-82:5
    Visibility: public -/
def drivers.pci.stats.pci_stats.PciStats.average_enumeration_time_us
  (self : drivers.pci.stats.pci_stats.PciStats) : Result Std.U64 := do
  if self.enumeration_count = 0#u64
  then ok 0#u64
  else self.enumeration_time_us / self.enumeration_count

/-- [nonos_x_drivers_pci_stats_pci_stats::pcistats_new]:
    Source: 'src/lib.rs', lines 11:0-13:1
    Visibility: public -/
def pcistats_new : Result drivers.pci.stats.pci_stats.PciStats := do
  drivers.pci.stats.pci_stats.PciStats.new

/-- [nonos_x_drivers_pci_stats_pci_stats::pcistats_snapshot]:
    Source: 'src/lib.rs', lines 15:0-17:1
    Visibility: public -/
def pcistats_snapshot : Result drivers.pci.stats.pci_stats.PciStats := do
  drivers.pci.stats.pci_stats.PciStats.snapshot

/-- [nonos_x_drivers_pci_stats_pci_stats::pcistats_average_enumeration_time_us]:
    Source: 'src/lib.rs', lines 19:0-21:1
    Visibility: public -/
def pcistats_average_enumeration_time_us
  (this : drivers.pci.stats.pci_stats.PciStats) : Result Std.U64 := do
  drivers.pci.stats.pci_stats.PciStats.average_enumeration_time_us this

end nonos_x_drivers_pci_stats_pci_stats
