/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

record, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.DriversPciStatsRecord

open Aeneas Aeneas.Std Result
open nonos_x_drivers_pci_stats_record

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.DriversPciStatsRecord

/-! ### The forwarding functions add nothing -/

theorem the_record_enumeration_wrapper_is_its_method (a : Std.U64) :
    record_enumeration a = drivers.pci.stats.record.record_enumeration a := rfl

theorem the_record_config_read_wrapper_is_its_method :
    record_config_read = drivers.pci.stats.record.record_config_read := rfl

theorem the_record_config_write_wrapper_is_its_method :
    record_config_write = drivers.pci.stats.record.record_config_write := rfl

theorem the_record_config_error_wrapper_is_its_method :
    record_config_error = drivers.pci.stats.record.record_config_error := rfl

theorem the_record_interrupt_wrapper_is_its_method (a : Bool) :
    record_interrupt a = drivers.pci.stats.record.record_interrupt a := rfl

theorem the_record_hotplug_event_wrapper_is_its_method :
    record_hotplug_event = drivers.pci.stats.record.record_hotplug_event := rfl

theorem the_record_power_state_change_wrapper_is_its_method :
    record_power_state_change = drivers.pci.stats.record.record_power_state_change := rfl

theorem the_record_link_state_change_wrapper_is_its_method :
    record_link_state_change = drivers.pci.stats.record.record_link_state_change := rfl

theorem the_record_error_event_wrapper_is_its_method :
    record_error_event = drivers.pci.stats.record.record_error_event := rfl

theorem the_reset_stats_wrapper_is_its_method :
    reset_stats = drivers.pci.stats.record.reset_stats := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.DriversPciStatsRecord.the_record_enumeration_wrapper_is_its_method
#print axioms NonosExtraction.DriversPciStatsRecord.the_record_config_read_wrapper_is_its_method
#print axioms NonosExtraction.DriversPciStatsRecord.the_record_config_write_wrapper_is_its_method
#print axioms NonosExtraction.DriversPciStatsRecord.the_record_config_error_wrapper_is_its_method
#print axioms NonosExtraction.DriversPciStatsRecord.the_record_interrupt_wrapper_is_its_method
#print axioms NonosExtraction.DriversPciStatsRecord.the_record_hotplug_event_wrapper_is_its_method
#print axioms NonosExtraction.DriversPciStatsRecord.the_record_power_state_change_wrapper_is_its_method
#print axioms NonosExtraction.DriversPciStatsRecord.the_record_link_state_change_wrapper_is_its_method
#print axioms NonosExtraction.DriversPciStatsRecord.the_record_error_event_wrapper_is_its_method
#print axioms NonosExtraction.DriversPciStatsRecord.the_reset_stats_wrapper_is_its_method

end NonosExtraction.DriversPciStatsRecord
