/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

bar, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.DriversPciTypesBar

open Aeneas Aeneas.Std Result
open nonos_x_drivers_pci_types_bar

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.DriversPciTypesBar

/-! ### The forwarding functions add nothing -/

theorem the_pcibar_size_wrapper_is_its_method (a : drivers.pci.types.bar.PciBar) :
    pcibar_size a = drivers.pci.types.bar.PciBar.size a := rfl

theorem the_pcibar_is_memory_wrapper_is_its_method (a : drivers.pci.types.bar.PciBar) :
    pcibar_is_memory a = drivers.pci.types.bar.PciBar.is_memory a := rfl

theorem the_pcibar_is_io_wrapper_is_its_method (a : drivers.pci.types.bar.PciBar) :
    pcibar_is_io a = drivers.pci.types.bar.PciBar.is_io a := rfl

theorem the_pcibar_is_64bit_wrapper_is_its_method (a : drivers.pci.types.bar.PciBar) :
    pcibar_is_64bit a = drivers.pci.types.bar.PciBar.is_64bit a := rfl

theorem the_pcibar_is_prefetchable_wrapper_is_its_method (a : drivers.pci.types.bar.PciBar) :
    pcibar_is_prefetchable a = drivers.pci.types.bar.PciBar.is_prefetchable a := rfl

theorem the_pcibar_is_present_wrapper_is_its_method (a : drivers.pci.types.bar.PciBar) :
    pcibar_is_present a = drivers.pci.types.bar.PciBar.is_present a := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.DriversPciTypesBar.the_pcibar_size_wrapper_is_its_method
#print axioms NonosExtraction.DriversPciTypesBar.the_pcibar_is_memory_wrapper_is_its_method
#print axioms NonosExtraction.DriversPciTypesBar.the_pcibar_is_io_wrapper_is_its_method
#print axioms NonosExtraction.DriversPciTypesBar.the_pcibar_is_64bit_wrapper_is_its_method
#print axioms NonosExtraction.DriversPciTypesBar.the_pcibar_is_prefetchable_wrapper_is_its_method
#print axioms NonosExtraction.DriversPciTypesBar.the_pcibar_is_present_wrapper_is_its_method

end NonosExtraction.DriversPciTypesBar
