/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

getters, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.DriversPciStatsGetters

open Aeneas Aeneas.Std Result
open nonos_x_drivers_pci_stats_getters

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.DriversPciStatsGetters

/-! ### The forwarding functions add nothing -/

theorem the_get_total_devices_wrapper_is_its_method :
    get_total_devices = drivers.pci.stats.getters.get_total_devices := rfl

theorem the_get_pcie_devices_wrapper_is_its_method :
    get_pcie_devices = drivers.pci.stats.getters.get_pcie_devices := rfl

theorem the_get_msi_capable_devices_wrapper_is_its_method :
    get_msi_capable_devices = drivers.pci.stats.getters.get_msi_capable_devices := rfl

theorem the_get_msix_capable_devices_wrapper_is_its_method :
    get_msix_capable_devices = drivers.pci.stats.getters.get_msix_capable_devices := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.DriversPciStatsGetters.the_get_total_devices_wrapper_is_its_method
#print axioms NonosExtraction.DriversPciStatsGetters.the_get_pcie_devices_wrapper_is_its_method
#print axioms NonosExtraction.DriversPciStatsGetters.the_get_msi_capable_devices_wrapper_is_its_method
#print axioms NonosExtraction.DriversPciStatsGetters.the_get_msix_capable_devices_wrapper_is_its_method

end NonosExtraction.DriversPciStatsGetters
