-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [nonos_x_elf_dynlink_info_state]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace nonos_x_elf_dynlink_info_state

/-- [nonos_x_elf_dynlink_info_state::memory::addr::virt::VirtAddr]
    Source: 'src/memory/addr/../../../../../../../src/memory/addr/virt.rs', lines 19:0-19:25
    Visibility: public -/
@[reducible]
def memory.addr.virt.VirtAddr := Std.U64

/-- [nonos_x_elf_dynlink_info_state::elf::dynlink::info::state::DynLinkInfo]
    Source: 'src/elf/dynlink/info/../../../../../../../../src/elf/dynlink/info/state.rs', lines 22:0-36:1
    Visibility: public -/
structure elf.dynlink.info.state.DynLinkInfo where
  needed_libraries : alloc.vec.Vec String
  symtab : Option memory.addr.virt.VirtAddr
  strtab : Option memory.addr.virt.VirtAddr
  strtab_size : Std.Usize
  sym_count : Std.Usize
  rela_table : Option memory.addr.virt.VirtAddr
  rela_size : Std.Usize
  plt_relocations : Option memory.addr.virt.VirtAddr
  plt_rela_size : Std.Usize
  init : Option memory.addr.virt.VirtAddr
  fini : Option memory.addr.virt.VirtAddr
  init_array : Option (memory.addr.virt.VirtAddr × Std.Usize)
  fini_array : Option (memory.addr.virt.VirtAddr × Std.Usize)

/-- [nonos_x_elf_dynlink_info_state::elf::dynlink::info::state::{nonos_x_elf_dynlink_info_state::elf::dynlink::info::state::DynLinkInfo}::new]:
    Source: 'src/elf/dynlink/info/../../../../../../../../src/elf/dynlink/info/state.rs', lines 39:4-55:5
    Visibility: public -/
def elf.dynlink.info.state.DynLinkInfo.new
  : Result elf.dynlink.info.state.DynLinkInfo := do
  ok
    {
      needed_libraries := (alloc.vec.Vec.new String),
      symtab := none,
      strtab := none,
      strtab_size := 0#usize,
      sym_count := 0#usize,
      rela_table := none,
      rela_size := 0#usize,
      plt_relocations := none,
      plt_rela_size := 0#usize,
      init := none,
      fini := none,
      init_array := none,
      fini_array := none
    }

/-- [nonos_x_elf_dynlink_info_state::dynlinkinfo_new]:
    Source: 'src/lib.rs', lines 13:0-15:1
    Visibility: public -/
def dynlinkinfo_new : Result elf.dynlink.info.state.DynLinkInfo := do
  elf.dynlink.info.state.DynLinkInfo.new

end nonos_x_elf_dynlink_info_state
