-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [nonos_x_fs_vfs_types]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace nonos_x_fs_vfs_types

/-- [nonos_x_fs_vfs_types::fs::vfs::types::OpenFlags]
    Source: 'src/fs/vfs/../../../../../../../src/fs/vfs/types.rs', lines 121:0-121:26
    Visibility: public -/
@[reducible]
def fs.vfs.types.OpenFlags := Std.U32

/-- [nonos_x_fs_vfs_types::fs::vfs::types::{nonos_x_fs_vfs_types::fs::vfs::types::OpenFlags}::READ]
    Source: 'src/fs/vfs/../../../../../../../src/fs/vfs/types.rs', lines 124:4-124:48
    Visibility: public -/
@[global_simps, irreducible]
def fs.vfs.types.OpenFlags.READ : fs.vfs.types.OpenFlags := 1#u32

/-- [nonos_x_fs_vfs_types::fs::vfs::types::{nonos_x_fs_vfs_types::fs::vfs::types::OpenFlags}::WRITE]
    Source: 'src/fs/vfs/../../../../../../../src/fs/vfs/types.rs', lines 125:4-125:49
    Visibility: public -/
@[global_simps, irreducible]
def fs.vfs.types.OpenFlags.WRITE : fs.vfs.types.OpenFlags := 2#u32

/-- [nonos_x_fs_vfs_types::fs::vfs::types::{nonos_x_fs_vfs_types::fs::vfs::types::OpenFlags}::empty]:
    Source: 'src/fs/vfs/../../../../../../../src/fs/vfs/types.rs', lines 133:4-135:5
    Visibility: public -/
def fs.vfs.types.OpenFlags.empty : Result fs.vfs.types.OpenFlags := do
  ok 0#u32

/-- [nonos_x_fs_vfs_types::fs::vfs::types::{nonos_x_fs_vfs_types::fs::vfs::types::OpenFlags}::from_bits]:
    Source: 'src/fs/vfs/../../../../../../../src/fs/vfs/types.rs', lines 137:4-139:5
    Visibility: public -/
def fs.vfs.types.OpenFlags.from_bits
  (bits : Std.U32) : Result fs.vfs.types.OpenFlags := do
  ok bits

/-- [nonos_x_fs_vfs_types::fs::vfs::types::{nonos_x_fs_vfs_types::fs::vfs::types::OpenFlags}::bits]:
    Source: 'src/fs/vfs/../../../../../../../src/fs/vfs/types.rs', lines 141:4-143:5
    Visibility: public -/
def fs.vfs.types.OpenFlags.bits
  (self : fs.vfs.types.OpenFlags) : Result Std.U32 := do
  ok self

/-- [nonos_x_fs_vfs_types::fs::vfs::types::{nonos_x_fs_vfs_types::fs::vfs::types::OpenFlags}::contains]:
    Source: 'src/fs/vfs/../../../../../../../src/fs/vfs/types.rs', lines 145:4-147:5
    Visibility: public -/
def fs.vfs.types.OpenFlags.contains
  (self : fs.vfs.types.OpenFlags) (other : fs.vfs.types.OpenFlags) :
  Result Bool
  := do
  let i ← lift (self &&& other)
  ok (i = other)

/-- [nonos_x_fs_vfs_types::fs::vfs::types::{nonos_x_fs_vfs_types::fs::vfs::types::OpenFlags}::is_readable]:
    Source: 'src/fs/vfs/../../../../../../../src/fs/vfs/types.rs', lines 149:4-151:5
    Visibility: public -/
def fs.vfs.types.OpenFlags.is_readable
  (self : fs.vfs.types.OpenFlags) : Result Bool := do
  fs.vfs.types.OpenFlags.contains self fs.vfs.types.OpenFlags.READ

/-- [nonos_x_fs_vfs_types::fs::vfs::types::{nonos_x_fs_vfs_types::fs::vfs::types::OpenFlags}::is_writable]:
    Source: 'src/fs/vfs/../../../../../../../src/fs/vfs/types.rs', lines 153:4-155:5
    Visibility: public -/
def fs.vfs.types.OpenFlags.is_writable
  (self : fs.vfs.types.OpenFlags) : Result Bool := do
  fs.vfs.types.OpenFlags.contains self fs.vfs.types.OpenFlags.WRITE

/-- [nonos_x_fs_vfs_types::openflags_empty]:
    Source: 'src/lib.rs', lines 11:0-13:1
    Visibility: public -/
def openflags_empty : Result fs.vfs.types.OpenFlags := do
  fs.vfs.types.OpenFlags.empty

/-- [nonos_x_fs_vfs_types::openflags_from_bits]:
    Source: 'src/lib.rs', lines 15:0-17:1
    Visibility: public -/
def openflags_from_bits (bits : Std.U32) : Result fs.vfs.types.OpenFlags := do
  fs.vfs.types.OpenFlags.from_bits bits

/-- [nonos_x_fs_vfs_types::openflags_bits]:
    Source: 'src/lib.rs', lines 19:0-21:1
    Visibility: public -/
def openflags_bits (this : fs.vfs.types.OpenFlags) : Result Std.U32 := do
  fs.vfs.types.OpenFlags.bits this

/-- [nonos_x_fs_vfs_types::openflags_contains]:
    Source: 'src/lib.rs', lines 23:0-25:1
    Visibility: public -/
def openflags_contains
  (this : fs.vfs.types.OpenFlags) (other : fs.vfs.types.OpenFlags) :
  Result Bool
  := do
  fs.vfs.types.OpenFlags.contains this other

/-- [nonos_x_fs_vfs_types::openflags_is_readable]:
    Source: 'src/lib.rs', lines 27:0-29:1
    Visibility: public -/
def openflags_is_readable (this : fs.vfs.types.OpenFlags) : Result Bool := do
  fs.vfs.types.OpenFlags.is_readable this

/-- [nonos_x_fs_vfs_types::openflags_is_writable]:
    Source: 'src/lib.rs', lines 31:0-33:1
    Visibility: public -/
def openflags_is_writable (this : fs.vfs.types.OpenFlags) : Result Bool := do
  fs.vfs.types.OpenFlags.is_writable this

end nonos_x_fs_vfs_types
