/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

entry_frame, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.IdtEntryFrame

open Aeneas Aeneas.Std Result
open nonos_x_idt_entry_frame

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.IdtEntryFrame

/-! ### The forwarding functions add nothing -/

theorem the_interruptframe_from_user_wrapper_is_its_method (a : entry_frame.InterruptFrame) :
    interruptframe_from_user a = entry_frame.InterruptFrame.from_user a := rfl

theorem the_interruptframe_from_kernel_wrapper_is_its_method (a : entry_frame.InterruptFrame) :
    interruptframe_from_kernel a = entry_frame.InterruptFrame.from_kernel a := rfl

theorem the_pagefaulterror_protection_violation_wrapper_is_its_method (a : entry_frame.PageFaultError) :
    pagefaulterror_protection_violation a = entry_frame.PageFaultError.protection_violation a := rfl

theorem the_pagefaulterror_write_wrapper_is_its_method (a : entry_frame.PageFaultError) :
    pagefaulterror_write a = entry_frame.PageFaultError.write a := rfl

theorem the_pagefaulterror_user_wrapper_is_its_method (a : entry_frame.PageFaultError) :
    pagefaulterror_user a = entry_frame.PageFaultError.user a := rfl

theorem the_pagefaulterror_reserved_write_wrapper_is_its_method (a : entry_frame.PageFaultError) :
    pagefaulterror_reserved_write a = entry_frame.PageFaultError.reserved_write a := rfl

theorem the_pagefaulterror_instruction_fetch_wrapper_is_its_method (a : entry_frame.PageFaultError) :
    pagefaulterror_instruction_fetch a = entry_frame.PageFaultError.instruction_fetch a := rfl

theorem the_pagefaulterror_protection_key_wrapper_is_its_method (a : entry_frame.PageFaultError) :
    pagefaulterror_protection_key a = entry_frame.PageFaultError.protection_key a := rfl

theorem the_pagefaulterror_shadow_stack_wrapper_is_its_method (a : entry_frame.PageFaultError) :
    pagefaulterror_shadow_stack a = entry_frame.PageFaultError.shadow_stack a := rfl

theorem the_pagefaulterror_sgx_wrapper_is_its_method (a : entry_frame.PageFaultError) :
    pagefaulterror_sgx a = entry_frame.PageFaultError.sgx a := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.IdtEntryFrame.the_interruptframe_from_user_wrapper_is_its_method
#print axioms NonosExtraction.IdtEntryFrame.the_interruptframe_from_kernel_wrapper_is_its_method
#print axioms NonosExtraction.IdtEntryFrame.the_pagefaulterror_protection_violation_wrapper_is_its_method
#print axioms NonosExtraction.IdtEntryFrame.the_pagefaulterror_write_wrapper_is_its_method
#print axioms NonosExtraction.IdtEntryFrame.the_pagefaulterror_user_wrapper_is_its_method
#print axioms NonosExtraction.IdtEntryFrame.the_pagefaulterror_reserved_write_wrapper_is_its_method
#print axioms NonosExtraction.IdtEntryFrame.the_pagefaulterror_instruction_fetch_wrapper_is_its_method
#print axioms NonosExtraction.IdtEntryFrame.the_pagefaulterror_protection_key_wrapper_is_its_method
#print axioms NonosExtraction.IdtEntryFrame.the_pagefaulterror_shadow_stack_wrapper_is_its_method
#print axioms NonosExtraction.IdtEntryFrame.the_pagefaulterror_sgx_wrapper_is_its_method

end NonosExtraction.IdtEntryFrame
