/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

halt_safe, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.InterruptApicIdleTimerHaltSafe

open Aeneas Aeneas.Std Result
open nonos_x_interrupt_apic_idle_timer_halt_safe

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.InterruptApicIdleTimerHaltSafe

/-! ### The forwarding functions add nothing -/

theorem the_halt_safe_wrapper_is_its_method :
    halt_safe = arch.x86_64.interrupt.apic.idle_timer.halt_safe.halt_safe := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.InterruptApicIdleTimerHaltSafe.the_halt_safe_wrapper_is_its_method

end NonosExtraction.InterruptApicIdleTimerHaltSafe
