-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [nonos_iommu]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace nonos_iommu

/-- [nonos_iommu::arch::x86_64::iommu::regs::cap::agaw::AgawLevels]
    Source: 'src/arch/x86_64/iommu/regs/cap/../../../../../../../../../src/arch/x86_64/iommu/regs/cap/agaw.rs', lines 19:0-23:1
    Visibility: public -/
@[discriminant isize]
inductive arch.x86_64.iommu.regs.cap.agaw.AgawLevels where
| Three : arch.x86_64.iommu.regs.cap.agaw.AgawLevels
| Four : arch.x86_64.iommu.regs.cap.agaw.AgawLevels
| Five : arch.x86_64.iommu.regs.cap.agaw.AgawLevels

/-- [nonos_iommu::arch::x86_64::iommu::regs::cap::agaw::{nonos_iommu::arch::x86_64::iommu::regs::cap::agaw::AgawLevels}::page_table_levels]:
    Source: 'src/arch/x86_64/iommu/regs/cap/../../../../../../../../../src/arch/x86_64/iommu/regs/cap/agaw.rs', lines 26:4-32:5
    Visibility: public -/
def arch.x86_64.iommu.regs.cap.agaw.AgawLevels.page_table_levels
  (self : arch.x86_64.iommu.regs.cap.agaw.AgawLevels) : Result Std.U8 := do
  match self with
  | arch.x86_64.iommu.regs.cap.agaw.AgawLevels.Three => ok 3#u8
  | arch.x86_64.iommu.regs.cap.agaw.AgawLevels.Four => ok 4#u8
  | arch.x86_64.iommu.regs.cap.agaw.AgawLevels.Five => ok 5#u8

/-- [nonos_iommu::arch::x86_64::iommu::regs::cap::agaw::{nonos_iommu::arch::x86_64::iommu::regs::cap::agaw::AgawLevels}::context_aw]:
    Source: 'src/arch/x86_64/iommu/regs/cap/../../../../../../../../../src/arch/x86_64/iommu/regs/cap/agaw.rs', lines 35:4-41:5
    Visibility: public -/
def arch.x86_64.iommu.regs.cap.agaw.AgawLevels.context_aw
  (self : arch.x86_64.iommu.regs.cap.agaw.AgawLevels) : Result Std.U8 := do
  match self with
  | arch.x86_64.iommu.regs.cap.agaw.AgawLevels.Three => ok 1#u8
  | arch.x86_64.iommu.regs.cap.agaw.AgawLevels.Four => ok 2#u8
  | arch.x86_64.iommu.regs.cap.agaw.AgawLevels.Five => ok 3#u8

/-- [nonos_iommu::arch::x86_64::iommu::regs::cap::agaw::preferred_levels]:
    Source: 'src/arch/x86_64/iommu/regs/cap/../../../../../../../../../src/arch/x86_64/iommu/regs/cap/agaw.rs', lines 46:0-57:1
    Visibility: public -/
def arch.x86_64.iommu.regs.cap.agaw.preferred_levels
  (cap : Std.U64) :
  Result (Option arch.x86_64.iommu.regs.cap.agaw.AgawLevels)
  := do
  let i ← cap >>> 8#i32
  let sagaw ← lift (i &&& 31#u64)
  let i1 ← 1#u64 <<< 2#i32
  let i2 ← lift (sagaw &&& i1)
  if i2 != 0#u64
  then ok (some arch.x86_64.iommu.regs.cap.agaw.AgawLevels.Four)
  else
    let i3 ← 1#u64 <<< 1#i32
    let i4 ← lift (sagaw &&& i3)
    if i4 != 0#u64
    then ok (some arch.x86_64.iommu.regs.cap.agaw.AgawLevels.Three)
    else
      let i5 ← 1#u64 <<< 3#i32
      let i6 ← lift (sagaw &&& i5)
      if i6 != 0#u64
      then ok (some arch.x86_64.iommu.regs.cap.agaw.AgawLevels.Five)
      else ok none

/-- [nonos_iommu::arch::x86_64::iommu::tables::context::PRESENT]
    Source: 'src/arch/x86_64/iommu/tables/../../../../../../../../src/arch/x86_64/iommu/tables/context.rs', lines 26:0-26:32
    Visibility: public -/
@[global_simps, irreducible]
def arch.x86_64.iommu.tables.context.PRESENT : Result Std.U64 :=
  1#u64 <<< 0#i32

/-- [nonos_iommu::arch::x86_64::iommu::tables::context::ADDR_MASK]
    Source: 'src/arch/x86_64/iommu/tables/../../../../../../../../src/arch/x86_64/iommu/tables/context.rs', lines 29:0-29:49
    Visibility: public -/
@[global_simps, irreducible]
def arch.x86_64.iommu.tables.context.ADDR_MASK : Std.U64 :=
  4503599627366400#u64

/-- [nonos_iommu::arch::x86_64::iommu::tables::context::TT_MULTI_LEVEL]
    Source: 'src/arch/x86_64/iommu/tables/../../../../../../../../src/arch/x86_64/iommu/tables/context.rs', lines 37:0-37:37
    Visibility: public -/
@[global_simps, irreducible]
def arch.x86_64.iommu.tables.context.TT_MULTI_LEVEL : Std.U64 := 0#u64

/-- [nonos_iommu::arch::x86_64::iommu::tables::context::root_low]:
    Source: 'src/arch/x86_64/iommu/tables/../../../../../../../../src/arch/x86_64/iommu/tables/context.rs', lines 40:0-42:1
    Visibility: public -/
def arch.x86_64.iommu.tables.context.root_low
  (context_table_phys : Std.U64) : Result Std.U64 := do
  let i ←
    lift (context_table_phys &&& arch.x86_64.iommu.tables.context.ADDR_MASK)
  let i1 ← arch.x86_64.iommu.tables.context.PRESENT
  ok (i ||| i1)

/-- [nonos_iommu::arch::x86_64::iommu::tables::context::context_low]:
    Source: 'src/arch/x86_64/iommu/tables/../../../../../../../../src/arch/x86_64/iommu/tables/context.rs', lines 46:0-48:1
    Visibility: public -/
def arch.x86_64.iommu.tables.context.context_low
  (sl_root_phys : Std.U64) : Result Std.U64 := do
  let i ← lift (sl_root_phys &&& arch.x86_64.iommu.tables.context.ADDR_MASK)
  let i1 ← arch.x86_64.iommu.tables.context.TT_MULTI_LEVEL <<< 2#i32
  let i2 ← lift (i ||| i1)
  let i3 ← arch.x86_64.iommu.tables.context.PRESENT
  ok (i2 ||| i3)

/-- [nonos_iommu::arch::x86_64::iommu::tables::context::context_high]:
    Source: 'src/arch/x86_64/iommu/tables/../../../../../../../../src/arch/x86_64/iommu/tables/context.rs', lines 51:0-53:1
    Visibility: public -/
def arch.x86_64.iommu.tables.context.context_high
  (domain_id : Std.U16) (address_width : Std.U8) : Result Std.U64 := do
  let i ← lift (UScalar.cast .U64 address_width)
  let i1 ← lift (i &&& 7#u64)
  let i2 ← lift (UScalar.cast .U64 domain_id)
  let i3 ← i2 <<< 8#i32
  ok (i1 ||| i3)

/-- [nonos_iommu::arch::x86_64::iommu::tables::context::context_index]:
    Source: 'src/arch/x86_64/iommu/tables/../../../../../../../../src/arch/x86_64/iommu/tables/context.rs', lines 56:0-58:1
    Visibility: public -/
def arch.x86_64.iommu.tables.context.context_index
  (device : Std.U8) (function : Std.U8) : Result Std.Usize := do
  let i ← lift (device &&& 31#u8)
  let i1 ← lift (UScalar.cast .Usize i)
  let i2 ← i1 <<< 3#i32
  let i3 ← lift (function &&& 7#u8)
  let i4 ← lift (UScalar.cast .Usize i3)
  ok (i2 ||| i4)

/-- [nonos_iommu::arch::x86_64::iommu::tables::context::is_present]:
    Source: 'src/arch/x86_64/iommu/tables/../../../../../../../../src/arch/x86_64/iommu/tables/context.rs', lines 61:0-63:1
    Visibility: public -/
def arch.x86_64.iommu.tables.context.is_present
  (low : Std.U64) : Result Bool := do
  let i ← arch.x86_64.iommu.tables.context.PRESENT
  let i1 ← lift (low &&& i)
  ok (i1 != 0#u64)

/-- [nonos_iommu::arch::x86_64::iommu::tables::context::entry_address]:
    Source: 'src/arch/x86_64/iommu/tables/../../../../../../../../src/arch/x86_64/iommu/tables/context.rs', lines 66:0-68:1
    Visibility: public -/
def arch.x86_64.iommu.tables.context.entry_address
  (low : Std.U64) : Result Std.U64 := do
  ok (low &&& arch.x86_64.iommu.tables.context.ADDR_MASK)

/-- [nonos_iommu::arch::x86_64::iommu::tables::context::context_domain]:
    Source: 'src/arch/x86_64/iommu/tables/../../../../../../../../src/arch/x86_64/iommu/tables/context.rs', lines 71:0-73:1
    Visibility: public -/
def arch.x86_64.iommu.tables.context.context_domain
  (high : Std.U64) : Result Std.U16 := do
  let i ← high >>> 8#i32
  let i1 ← lift (i &&& 65535#u64)
  ok (UScalar.cast .U16 i1)

/-- [nonos_iommu::arch::x86_64::iommu::tables::sl_pte::SL_READ]
    Source: 'src/arch/x86_64/iommu/tables/../../../../../../../../src/arch/x86_64/iommu/tables/sl_pte.rs', lines 25:0-25:32
    Visibility: public -/
@[global_simps, irreducible]
def arch.x86_64.iommu.tables.sl_pte.SL_READ : Result Std.U64 := 1#u64 <<< 0#i32

/-- [nonos_iommu::arch::x86_64::iommu::tables::sl_pte::SL_WRITE]
    Source: 'src/arch/x86_64/iommu/tables/../../../../../../../../src/arch/x86_64/iommu/tables/sl_pte.rs', lines 27:0-27:33
    Visibility: public -/
@[global_simps, irreducible]
def arch.x86_64.iommu.tables.sl_pte.SL_WRITE : Result Std.U64 :=
  1#u64 <<< 1#i32

/-- [nonos_iommu::arch::x86_64::iommu::tables::sl_pte::SL_SNOOP]
    Source: 'src/arch/x86_64/iommu/tables/../../../../../../../../src/arch/x86_64/iommu/tables/sl_pte.rs', lines 29:0-29:34
    Visibility: public -/
@[global_simps, irreducible]
def arch.x86_64.iommu.tables.sl_pte.SL_SNOOP : Result Std.U64 :=
  1#u64 <<< 11#i32

/-- [nonos_iommu::arch::x86_64::iommu::tables::sl_pte::SL_ADDR_MASK]
    Source: 'src/arch/x86_64/iommu/tables/../../../../../../../../src/arch/x86_64/iommu/tables/sl_pte.rs', lines 35:0-35:52
    Visibility: public -/
@[global_simps, irreducible]
def arch.x86_64.iommu.tables.sl_pte.SL_ADDR_MASK : Std.U64 :=
  4503599627366400#u64

/-- [nonos_iommu::arch::x86_64::iommu::tables::sl_pte::ENTRIES]
    Source: 'src/arch/x86_64/iommu/tables/../../../../../../../../src/arch/x86_64/iommu/tables/sl_pte.rs', lines 38:0-38:31
    Visibility: public -/
@[global_simps, irreducible]
def arch.x86_64.iommu.tables.sl_pte.ENTRIES : Std.Usize := 512#usize

/-- [nonos_iommu::arch::x86_64::iommu::tables::sl_pte::LEVEL_SHIFT]
    Source: 'src/arch/x86_64/iommu/tables/../../../../../../../../src/arch/x86_64/iommu/tables/sl_pte.rs', lines 39:0-39:31
    Visibility: public -/
@[global_simps, irreducible]
def arch.x86_64.iommu.tables.sl_pte.LEVEL_SHIFT : Std.U32 := 9#u32

/-- [nonos_iommu::arch::x86_64::iommu::tables::sl_pte::PAGE_SHIFT]
    Source: 'src/arch/x86_64/iommu/tables/../../../../../../../../src/arch/x86_64/iommu/tables/sl_pte.rs', lines 40:0-40:31
    Visibility: public -/
@[global_simps, irreducible]
def arch.x86_64.iommu.tables.sl_pte.PAGE_SHIFT : Std.U32 := 12#u32

/-- [nonos_iommu::arch::x86_64::iommu::tables::sl_pte::is_present]:
    Source: 'src/arch/x86_64/iommu/tables/../../../../../../../../src/arch/x86_64/iommu/tables/sl_pte.rs', lines 43:0-45:1
    Visibility: public -/
def arch.x86_64.iommu.tables.sl_pte.is_present
  (entry : Std.U64) : Result Bool := do
  let i ← arch.x86_64.iommu.tables.sl_pte.SL_READ
  let i1 ← arch.x86_64.iommu.tables.sl_pte.SL_WRITE
  let i2 ← lift (i ||| i1)
  let i3 ← lift (entry &&& i2)
  ok (i3 != 0#u64)

/-- [nonos_iommu::arch::x86_64::iommu::tables::sl_pte::entry_address]:
    Source: 'src/arch/x86_64/iommu/tables/../../../../../../../../src/arch/x86_64/iommu/tables/sl_pte.rs', lines 48:0-50:1
    Visibility: public -/
def arch.x86_64.iommu.tables.sl_pte.entry_address
  (entry : Std.U64) : Result Std.U64 := do
  ok (entry &&& arch.x86_64.iommu.tables.sl_pte.SL_ADDR_MASK)

/-- [nonos_iommu::arch::x86_64::iommu::tables::sl_pte::leaf]:
    Source: 'src/arch/x86_64/iommu/tables/../../../../../../../../src/arch/x86_64/iommu/tables/sl_pte.rs', lines 54:0-66:1
    Visibility: public -/
def arch.x86_64.iommu.tables.sl_pte.leaf
  (phys : Std.U64) (read : Bool) (write : Bool) (snoop : Bool) :
  Result Std.U64
  := do
  let e ← lift (phys &&& arch.x86_64.iommu.tables.sl_pte.SL_ADDR_MASK)
  let e1 ←
    if read
    then do
         let i ← arch.x86_64.iommu.tables.sl_pte.SL_READ
         ok (e ||| i)
    else ok e
  let e2 ←
    if write
    then do
         let i ← arch.x86_64.iommu.tables.sl_pte.SL_WRITE
         ok (e1 ||| i)
    else ok e1
  if snoop
  then let i ← arch.x86_64.iommu.tables.sl_pte.SL_SNOOP
       ok (e2 ||| i)
  else ok e2

/-- [nonos_iommu::arch::x86_64::iommu::tables::sl_pte::table]:
    Source: 'src/arch/x86_64/iommu/tables/../../../../../../../../src/arch/x86_64/iommu/tables/sl_pte.rs', lines 70:0-72:1
    Visibility: public -/
def arch.x86_64.iommu.tables.sl_pte.table
  (phys : Std.U64) : Result Std.U64 := do
  let i ← lift (phys &&& arch.x86_64.iommu.tables.sl_pte.SL_ADDR_MASK)
  let i1 ← arch.x86_64.iommu.tables.sl_pte.SL_READ
  let i2 ← lift (i ||| i1)
  let i3 ← arch.x86_64.iommu.tables.sl_pte.SL_WRITE
  ok (i2 ||| i3)

/-- [nonos_iommu::arch::x86_64::iommu::tables::sl_pte::index_for]:
    Source: 'src/arch/x86_64/iommu/tables/../../../../../../../../src/arch/x86_64/iommu/tables/sl_pte.rs', lines 75:0-78:1
    Visibility: public -/
def arch.x86_64.iommu.tables.sl_pte.index_for
  (addr : Std.U64) (level : Std.U8) : Result Std.Usize := do
  let i ← lift (UScalar.cast .U32 level)
  let i1 ← i - 1#u32
  let i2 ← arch.x86_64.iommu.tables.sl_pte.LEVEL_SHIFT * i1
  let shift ← arch.x86_64.iommu.tables.sl_pte.PAGE_SHIFT + i2
  let i3 ← addr >>> shift
  let i4 ← lift (UScalar.cast .Usize i3)
  let i5 ← arch.x86_64.iommu.tables.sl_pte.ENTRIES - 1#usize
  ok (i4 &&& i5)

/-- [nonos_iommu::arch::x86_64::iommu::tables::sl_pte::level_span]:
    Source: 'src/arch/x86_64/iommu/tables/../../../../../../../../src/arch/x86_64/iommu/tables/sl_pte.rs', lines 81:0-83:1
    Visibility: public -/
def arch.x86_64.iommu.tables.sl_pte.level_span
  (level : Std.U8) : Result Std.U64 := do
  let i ← lift (UScalar.cast .U32 level)
  let i1 ← i - 1#u32
  let i2 ← arch.x86_64.iommu.tables.sl_pte.LEVEL_SHIFT * i1
  let i3 ← arch.x86_64.iommu.tables.sl_pte.PAGE_SHIFT + i2
  1#u64 <<< i3

/-- [nonos_iommu::arch::x86_64::iommu::tables::sl_pte::fits_address_width]:
    Source: 'src/arch/x86_64/iommu/tables/../../../../../../../../src/arch/x86_64/iommu/tables/sl_pte.rs', lines 86:0-92:1
    Visibility: public -/
def arch.x86_64.iommu.tables.sl_pte.fits_address_width
  (addr : Std.U64) (width_bits : Std.U8) : Result Bool := do
  if width_bits >= 64#u8
  then ok true
  else let i ← 1#u64 <<< width_bits
       ok (addr < i)

/-- [nonos_iommu::agaw_page_table_levels]:
    Source: 'src/lib.rs', lines 13:0-15:1
    Visibility: public -/
def agaw_page_table_levels
  (levels : arch.x86_64.iommu.regs.cap.agaw.AgawLevels) : Result Std.U8 := do
  arch.x86_64.iommu.regs.cap.agaw.AgawLevels.page_table_levels levels

/-- [nonos_iommu::agaw_context_aw]:
    Source: 'src/lib.rs', lines 17:0-19:1
    Visibility: public -/
def agaw_context_aw
  (levels : arch.x86_64.iommu.regs.cap.agaw.AgawLevels) : Result Std.U8 := do
  arch.x86_64.iommu.regs.cap.agaw.AgawLevels.context_aw levels

end nonos_iommu
