/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

iommu_device, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.IommuDevice

open Aeneas Aeneas.Std Result
open nonos_x_iommu_device

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.IommuDevice

/-! ### The forwarding functions add nothing -/

theorem the_deviceaddress_new_wrapper_is_its_method (a : Std.U32) :
    deviceaddress_new a = iommu_device.DeviceAddress.new a := rfl

theorem the_deviceaddress_pci_wrapper_is_its_method (a : Std.U8) (b : Std.U8) (c : Std.U8) :
    deviceaddress_pci a b c = iommu_device.DeviceAddress.pci a b c := rfl

theorem the_deviceaddress_as_u32_wrapper_is_its_method (a : iommu_device.DeviceAddress) :
    deviceaddress_as_u32 a = iommu_device.DeviceAddress.as_u32 a := rfl

theorem the_deviceaddress_pci_bus_wrapper_is_its_method (a : iommu_device.DeviceAddress) :
    deviceaddress_pci_bus a = iommu_device.DeviceAddress.pci_bus a := rfl

theorem the_deviceaddress_pci_device_wrapper_is_its_method (a : iommu_device.DeviceAddress) :
    deviceaddress_pci_device a = iommu_device.DeviceAddress.pci_device a := rfl

theorem the_deviceaddress_pci_function_wrapper_is_its_method (a : iommu_device.DeviceAddress) :
    deviceaddress_pci_function a = iommu_device.DeviceAddress.pci_function a := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.IommuDevice.the_deviceaddress_new_wrapper_is_its_method
#print axioms NonosExtraction.IommuDevice.the_deviceaddress_pci_wrapper_is_its_method
#print axioms NonosExtraction.IommuDevice.the_deviceaddress_as_u32_wrapper_is_its_method
#print axioms NonosExtraction.IommuDevice.the_deviceaddress_pci_bus_wrapper_is_its_method
#print axioms NonosExtraction.IommuDevice.the_deviceaddress_pci_device_wrapper_is_its_method
#print axioms NonosExtraction.IommuDevice.the_deviceaddress_pci_function_wrapper_is_its_method

end NonosExtraction.IommuDevice
