/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

types, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.KeyManagementTypes

open Aeneas Aeneas.Std Result
open nonos_x_key_management_types

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.KeyManagementTypes

/-! ### The forwarding functions add nothing -/

theorem the_keytype_key_length_wrapper_is_its_method (a : types.KeyType) :
    keytype_key_length a = types.KeyType.key_length a := rfl

theorem the_keyusage_signing_wrapper_is_its_method :
    keyusage_signing = types.KeyUsage.signing := rfl

theorem the_keyusage_verification_wrapper_is_its_method :
    keyusage_verification = types.KeyUsage.verification := rfl

theorem the_keyusage_encryption_wrapper_is_its_method :
    keyusage_encryption = types.KeyUsage.encryption := rfl

theorem the_keyusage_key_exchange_wrapper_is_its_method :
    keyusage_key_exchange = types.KeyUsage.key_exchange := rfl

theorem the_keyusage_master_wrapper_is_its_method :
    keyusage_master = types.KeyUsage.master := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.KeyManagementTypes.the_keytype_key_length_wrapper_is_its_method
#print axioms NonosExtraction.KeyManagementTypes.the_keyusage_signing_wrapper_is_its_method
#print axioms NonosExtraction.KeyManagementTypes.the_keyusage_verification_wrapper_is_its_method
#print axioms NonosExtraction.KeyManagementTypes.the_keyusage_encryption_wrapper_is_its_method
#print axioms NonosExtraction.KeyManagementTypes.the_keyusage_key_exchange_wrapper_is_its_method
#print axioms NonosExtraction.KeyManagementTypes.the_keyusage_master_wrapper_is_its_method

end NonosExtraction.KeyManagementTypes
