-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [nonos_x_keyring_capsule_types]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace nonos_x_keyring_capsule_types

/-- [nonos_x_keyring_capsule_types::types::KeyType]
    Source: 'src/../../../../../src/security/keyring_capsule/types.rs', lines 19:0-28:1
    Visibility: public -/
@[discriminant u8]
inductive types.KeyType where
| Symmetric : types.KeyType
| PrivateKey : types.KeyType
| PublicKey : types.KeyType
| HmacSecret : types.KeyType
| DerivedKey : types.KeyType
| SessionKey : types.KeyType
| MasterKey : types.KeyType
| SigningKey : types.KeyType

/-- [nonos_x_keyring_capsule_types::types::{nonos_x_keyring_capsule_types::types::KeyType}::to_u8]:
    Source: 'src/../../../../../src/security/keyring_capsule/types.rs', lines 45:4-47:5
    Visibility: public -/
def types.KeyType.to_u8 (self : types.KeyType) : Result Std.U8 := do
  let self1 := read_discriminant self
  ok (UScalar.cast .U8 self1)

/-- [nonos_x_keyring_capsule_types::keytype_to_u8]:
    Source: 'src/lib.rs', lines 10:0-12:1
    Visibility: public -/
def keytype_to_u8 (this : types.KeyType) : Result Std.U8 := do
  types.KeyType.to_u8 this

end nonos_x_keyring_capsule_types
