/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

section, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.MemoryLayoutTypesSection

open Aeneas Aeneas.Std Result
open nonos_x_memory_layout_types_section

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.MemoryLayoutTypesSection

/-! ### The forwarding functions add nothing -/

theorem the_section_new_wrapper_is_its_method (a : Std.U64) (b : Std.U64) (c : Bool) (d : Bool) (e : Bool) (f : Bool) :
    section_new a b c d e f = memory.layout.types.section.Section.new a b c d e f := rfl

theorem the_section_size_wrapper_is_its_method (a : memory.layout.types.section.Section) :
    section_size a = memory.layout.types.section.Section.size a := rfl

theorem the_section_page_count_wrapper_is_its_method (a : memory.layout.types.section.Section) :
    section_page_count a = memory.layout.types.section.Section.page_count a := rfl

theorem the_section_is_empty_wrapper_is_its_method (a : memory.layout.types.section.Section) :
    section_is_empty a = memory.layout.types.section.Section.is_empty a := rfl

theorem the_section_contains_wrapper_is_its_method (a : memory.layout.types.section.Section) (b : Std.U64) :
    section_contains a b = memory.layout.types.section.Section.contains a b := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.MemoryLayoutTypesSection.the_section_new_wrapper_is_its_method
#print axioms NonosExtraction.MemoryLayoutTypesSection.the_section_size_wrapper_is_its_method
#print axioms NonosExtraction.MemoryLayoutTypesSection.the_section_page_count_wrapper_is_its_method
#print axioms NonosExtraction.MemoryLayoutTypesSection.the_section_is_empty_wrapper_is_its_method
#print axioms NonosExtraction.MemoryLayoutTypesSection.the_section_contains_wrapper_is_its_method

end NonosExtraction.MemoryLayoutTypesSection
