-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [nonos_x_memory_mmio_types_flags]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace nonos_x_memory_mmio_types_flags

/-- [nonos_x_memory_mmio_types_flags::memory::mmio::types::flags::MmioFlags]
    Source: 'src/memory/mmio/types/../../../../../../../../src/memory/mmio/types/flags.rs', lines 20:0-25:1
    Visibility: public -/
structure memory.mmio.types.flags.MmioFlags where
  cacheable : Bool
  write_combining : Bool
  user_accessible : Bool
  executable : Bool

/-- [nonos_x_memory_mmio_types_flags::memory::mmio::types::flags::{nonos_x_memory_mmio_types_flags::memory::mmio::types::flags::MmioFlags}::device]:
    Source: 'src/memory/mmio/types/../../../../../../../../src/memory/mmio/types/flags.rs', lines 28:4-30:5
    Visibility: public -/
def memory.mmio.types.flags.MmioFlags.device
  : Result memory.mmio.types.flags.MmioFlags := do
  ok
    {
      cacheable := false,
      write_combining := false,
      user_accessible := false,
      executable := false
    }

/-- [nonos_x_memory_mmio_types_flags::mmioflags_device]:
    Source: 'src/lib.rs', lines 11:0-13:1
    Visibility: public -/
def mmioflags_device : Result memory.mmio.types.flags.MmioFlags := do
  memory.mmio.types.flags.MmioFlags.device

/-- [nonos_x_memory_mmio_types_flags::memory::mmio::types::flags::{nonos_x_memory_mmio_types_flags::memory::mmio::types::flags::MmioFlags}::framebuffer]:
    Source: 'src/memory/mmio/types/../../../../../../../../src/memory/mmio/types/flags.rs', lines 32:4-34:5
    Visibility: public -/
def memory.mmio.types.flags.MmioFlags.framebuffer
  : Result memory.mmio.types.flags.MmioFlags := do
  ok
    {
      cacheable := false,
      write_combining := true,
      user_accessible := false,
      executable := false
    }

/-- [nonos_x_memory_mmio_types_flags::mmioflags_framebuffer]:
    Source: 'src/lib.rs', lines 15:0-17:1
    Visibility: public -/
def mmioflags_framebuffer : Result memory.mmio.types.flags.MmioFlags := do
  memory.mmio.types.flags.MmioFlags.framebuffer

/-- [nonos_x_memory_mmio_types_flags::memory::mmio::types::flags::{nonos_x_memory_mmio_types_flags::memory::mmio::types::flags::MmioFlags}::user_device]:
    Source: 'src/memory/mmio/types/../../../../../../../../src/memory/mmio/types/flags.rs', lines 36:4-38:5
    Visibility: public -/
def memory.mmio.types.flags.MmioFlags.user_device
  : Result memory.mmio.types.flags.MmioFlags := do
  ok
    {
      cacheable := false,
      write_combining := false,
      user_accessible := true,
      executable := false
    }

/-- [nonos_x_memory_mmio_types_flags::mmioflags_user_device]:
    Source: 'src/lib.rs', lines 19:0-21:1
    Visibility: public -/
def mmioflags_user_device : Result memory.mmio.types.flags.MmioFlags := do
  memory.mmio.types.flags.MmioFlags.user_device

/-- [nonos_x_memory_mmio_types_flags::memory::mmio::constants::VM_FLAG_WRITE_COMBINE]
    Source: 'src/memory/mmio/../../../../../../../src/memory/mmio/constants.rs', lines 55:0-55:44
    Visibility: public -/
@[global_simps, irreducible]
def memory.mmio.constants.VM_FLAG_WRITE_COMBINE : Std.U32 := 32#u32

/-- [nonos_x_memory_mmio_types_flags::memory::mmio::constants::VM_FLAG_CACHE_DISABLE]
    Source: 'src/memory/mmio/../../../../../../../src/memory/mmio/constants.rs', lines 52:0-52:44
    Visibility: public -/
@[global_simps, irreducible]
def memory.mmio.constants.VM_FLAG_CACHE_DISABLE : Std.U32 := 16#u32

/-- [nonos_x_memory_mmio_types_flags::memory::mmio::constants::VM_FLAG_USER]
    Source: 'src/memory/mmio/../../../../../../../src/memory/mmio/constants.rs', lines 49:0-49:35
    Visibility: public -/
@[global_simps, irreducible]
def memory.mmio.constants.VM_FLAG_USER : Std.U32 := 8#u32

/-- [nonos_x_memory_mmio_types_flags::memory::mmio::constants::VM_FLAG_NX]
    Source: 'src/memory/mmio/../../../../../../../src/memory/mmio/constants.rs', lines 46:0-46:33
    Visibility: public -/
@[global_simps, irreducible]
def memory.mmio.constants.VM_FLAG_NX : Std.U32 := 4#u32

/-- [nonos_x_memory_mmio_types_flags::memory::mmio::constants::VM_FLAG_WRITABLE]
    Source: 'src/memory/mmio/../../../../../../../src/memory/mmio/constants.rs', lines 43:0-43:39
    Visibility: public -/
@[global_simps, irreducible]
def memory.mmio.constants.VM_FLAG_WRITABLE : Std.U32 := 2#u32

/-- [nonos_x_memory_mmio_types_flags::memory::mmio::constants::VM_FLAG_PRESENT]
    Source: 'src/memory/mmio/../../../../../../../src/memory/mmio/constants.rs', lines 40:0-40:38
    Visibility: public -/
@[global_simps, irreducible]
def memory.mmio.constants.VM_FLAG_PRESENT : Std.U32 := 1#u32

/-- [nonos_x_memory_mmio_types_flags::memory::mmio::types::flags::{nonos_x_memory_mmio_types_flags::memory::mmio::types::flags::MmioFlags}::to_vm_flags]:
    Source: 'src/memory/mmio/types/../../../../../../../../src/memory/mmio/types/flags.rs', lines 40:4-55:5
    Visibility: public -/
def memory.mmio.types.flags.MmioFlags.to_vm_flags
  (self : memory.mmio.types.flags.MmioFlags) : Result Std.U32 := do
  let flags ←
    lift (memory.mmio.constants.VM_FLAG_PRESENT |||
      memory.mmio.constants.VM_FLAG_WRITABLE)
  let flags1 ←
    if self.executable
    then ok flags
    else ok (flags ||| memory.mmio.constants.VM_FLAG_NX)
  let flags2 ←
    if self.user_accessible
    then ok (flags1 ||| memory.mmio.constants.VM_FLAG_USER)
    else ok flags1
  let flags3 ←
    if self.cacheable
    then ok flags2
    else ok (flags2 ||| memory.mmio.constants.VM_FLAG_CACHE_DISABLE)
  if self.write_combining
  then ok (flags3 ||| memory.mmio.constants.VM_FLAG_WRITE_COMBINE)
  else ok flags3

/-- [nonos_x_memory_mmio_types_flags::mmioflags_to_vm_flags]:
    Source: 'src/lib.rs', lines 23:0-25:1
    Visibility: public -/
def mmioflags_to_vm_flags
  (this : memory.mmio.types.flags.MmioFlags) : Result Std.U32 := do
  memory.mmio.types.flags.MmioFlags.to_vm_flags this

end nonos_x_memory_mmio_types_flags
