/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

address, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.MemoryLayoutManagerAddress

open Aeneas Aeneas.Std Result
open nonos_x_memory_layout_manager_address

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.MemoryLayoutManagerAddress

/-! ### The forwarding functions add nothing -/

theorem the_in_kernel_space_wrapper_is_its_method (a : Std.U64) :
    in_kernel_space a = memory.layout.manager.address.in_kernel_space a := rfl

theorem the_in_user_space_wrapper_is_its_method (a : Std.U64) :
    in_user_space a = memory.layout.manager.address.in_user_space a := rfl

theorem the_is_canonical_wrapper_is_its_method (a : Std.U64) :
    is_canonical a = memory.layout.manager.address.is_canonical a := rfl

theorem the_selfref_l4_va_wrapper_is_its_method :
    selfref_l4_va = memory.layout.manager.address.selfref_l4_va := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.MemoryLayoutManagerAddress.the_in_kernel_space_wrapper_is_its_method
#print axioms NonosExtraction.MemoryLayoutManagerAddress.the_in_user_space_wrapper_is_its_method
#print axioms NonosExtraction.MemoryLayoutManagerAddress.the_is_canonical_wrapper_is_its_method
#print axioms NonosExtraction.MemoryLayoutManagerAddress.the_selfref_l4_va_wrapper_is_its_method

end NonosExtraction.MemoryLayoutManagerAddress
