-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [nonos_x_memory_mmio_stats_record]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace nonos_x_memory_mmio_stats_record

/-- [core::sync::atomic::private::Align8]
    Source: '/rustc/library/core/src/sync/atomic.rs', lines 273:4-273:24
    Name pattern: [core::sync::atomic::private::Align8]
    Visibility: public -/
@[rust_type "core::sync::atomic::private::Align8"]
axiom core.sync.atomic.private.Align8 (T : Type) : Type

/-- [core::sync::atomic::Atomic]
    Source: '/rustc/library/core/src/sync/atomic.rs', lines 366:0-366:37
    Name pattern: [core::sync::atomic::Atomic]
    Visibility: public -/
@[rust_type "core::sync::atomic::Atomic"]
axiom core.sync.atomic.Atomic (T : Type) (Clause0_Storage : Type) : Type

/-- [core::sync::atomic::Ordering]
    Source: '/rustc/library/core/src/sync/atomic.rs', lines 447:0-447:17
    Name pattern: [core::sync::atomic::Ordering]
    Visibility: public -/
@[discriminant isize, rust_type "core::sync::atomic::Ordering"]
inductive core.sync.atomic.Ordering where
| Relaxed : core.sync.atomic.Ordering
| Release : core.sync.atomic.Ordering
| Acquire : core.sync.atomic.Ordering
| AcqRel : core.sync.atomic.Ordering
| SeqCst : core.sync.atomic.Ordering

/-- [core::sync::atomic::{core::sync::atomic::Atomic<u64, core::sync::atomic::private::Align8<u64>>}::fetch_add]:
    Source: '/rustc/library/core/src/sync/atomic.rs', lines 3160:12-3160:81
    Name pattern: [core::sync::atomic::{core::sync::atomic::Atomic<u64, core::sync::atomic::private::Align8<u64>>}::fetch_add]
    Visibility: public -/
@[rust_fun
  "core::sync::atomic::{core::sync::atomic::Atomic<u64, core::sync::atomic::private::Align8<u64>>}::fetch_add"]
axiom core.sync.atomic.AtomicU64Align8U64.fetch_add
  :
  core.sync.atomic.Atomic Std.U64 (core.sync.atomic.private.Align8 Std.U64) →
    Std.U64 → core.sync.atomic.Ordering → Result Std.U64

/-- [core::sync::atomic::{core::sync::atomic::Atomic<usize, core::sync::atomic::private::Align8<usize>>}::fetch_add]:
    Source: '/rustc/library/core/src/sync/atomic.rs', lines 3160:12-3160:81
    Name pattern: [core::sync::atomic::{core::sync::atomic::Atomic<usize, core::sync::atomic::private::Align8<usize>>}::fetch_add]
    Visibility: public -/
@[rust_fun
  "core::sync::atomic::{core::sync::atomic::Atomic<usize, core::sync::atomic::private::Align8<usize>>}::fetch_add"]
axiom core.sync.atomic.AtomicUsizeAlign8Usize.fetch_add
  :
  core.sync.atomic.Atomic Std.Usize (core.sync.atomic.private.Align8 Std.Usize)
    → Std.Usize → core.sync.atomic.Ordering → Result Std.Usize

/-- [core::sync::atomic::{core::sync::atomic::Atomic<usize, core::sync::atomic::private::Align8<usize>>}::fetch_sub]:
    Source: '/rustc/library/core/src/sync/atomic.rs', lines 3191:12-3191:81
    Name pattern: [core::sync::atomic::{core::sync::atomic::Atomic<usize, core::sync::atomic::private::Align8<usize>>}::fetch_sub]
    Visibility: public -/
@[rust_fun
  "core::sync::atomic::{core::sync::atomic::Atomic<usize, core::sync::atomic::private::Align8<usize>>}::fetch_sub"]
axiom core.sync.atomic.AtomicUsizeAlign8Usize.fetch_sub
  :
  core.sync.atomic.Atomic Std.Usize (core.sync.atomic.private.Align8 Std.Usize)
    → Std.Usize → core.sync.atomic.Ordering → Result Std.Usize

/-- [core::sync::atomic::{core::sync::atomic::Atomic<u64, core::sync::atomic::private::Align8<u64>>}::fetch_sub]:
    Source: '/rustc/library/core/src/sync/atomic.rs', lines 3191:12-3191:81
    Name pattern: [core::sync::atomic::{core::sync::atomic::Atomic<u64, core::sync::atomic::private::Align8<u64>>}::fetch_sub]
    Visibility: public -/
@[rust_fun
  "core::sync::atomic::{core::sync::atomic::Atomic<u64, core::sync::atomic::private::Align8<u64>>}::fetch_sub"]
axiom core.sync.atomic.AtomicU64Align8U64.fetch_sub
  :
  core.sync.atomic.Atomic Std.U64 (core.sync.atomic.private.Align8 Std.U64) →
    Std.U64 → core.sync.atomic.Ordering → Result Std.U64

/-- [nonos_x_memory_mmio_stats_record::memory::mmio::stats::types::MmioStats]
    Source: 'src/memory/mmio/stats/../../../../../../../../src/memory/mmio/stats/types.rs', lines 19:0-25:1
    Visibility: public -/
structure memory.mmio.stats.types.MmioStats where
  total_regions : core.sync.atomic.Atomic Std.Usize
    (core.sync.atomic.private.Align8 Std.Usize)
  total_mapped_size : core.sync.atomic.Atomic Std.U64
    (core.sync.atomic.private.Align8 Std.U64)
  read_operations : core.sync.atomic.Atomic Std.U64
    (core.sync.atomic.private.Align8 Std.U64)
  write_operations : core.sync.atomic.Atomic Std.U64
    (core.sync.atomic.private.Align8 Std.U64)
  next_region_id : core.sync.atomic.Atomic Std.U64
    (core.sync.atomic.private.Align8 Std.U64)

/-- [nonos_x_memory_mmio_stats_record::memory::mmio::stats::record::{nonos_x_memory_mmio_stats_record::memory::mmio::stats::types::MmioStats}::next_id]:
    Source: 'src/memory/mmio/stats/../../../../../../../../src/memory/mmio/stats/record.rs', lines 21:4-23:5
    Visibility: public -/
def memory.mmio.stats.record.MmioStats.next_id
  (self : memory.mmio.stats.types.MmioStats) : Result Std.U64 := do
  core.sync.atomic.AtomicU64Align8U64.fetch_add self.next_region_id 1#u64
    core.sync.atomic.Ordering.Relaxed

/-- [nonos_x_memory_mmio_stats_record::mmiostats_next_id]:
    Source: 'src/lib.rs', lines 11:0-13:1
    Visibility: public -/
def mmiostats_next_id
  (this : memory.mmio.stats.types.MmioStats) : Result Std.U64 := do
  memory.mmio.stats.record.MmioStats.next_id this

/-- [nonos_x_memory_mmio_stats_record::memory::mmio::stats::record::{nonos_x_memory_mmio_stats_record::memory::mmio::stats::types::MmioStats}::record_mapping]:
    Source: 'src/memory/mmio/stats/../../../../../../../../src/memory/mmio/stats/record.rs', lines 25:4-28:5
    Visibility: public -/
def memory.mmio.stats.record.MmioStats.record_mapping
  (self : memory.mmio.stats.types.MmioStats) (size : Std.Usize) :
  Result Unit
  := do
  let _ ←
    core.sync.atomic.AtomicUsizeAlign8Usize.fetch_add self.total_regions
      1#usize core.sync.atomic.Ordering.Relaxed
  let i ← lift (UScalar.cast .U64 size)
  let _ ←
    core.sync.atomic.AtomicU64Align8U64.fetch_add self.total_mapped_size i
      core.sync.atomic.Ordering.Relaxed
  ok ()

/-- [nonos_x_memory_mmio_stats_record::mmiostats_record_mapping]:
    Source: 'src/lib.rs', lines 15:0-17:1
    Visibility: public -/
def mmiostats_record_mapping
  (this : memory.mmio.stats.types.MmioStats) (size : Std.Usize) :
  Result Unit
  := do
  memory.mmio.stats.record.MmioStats.record_mapping this size

/-- [nonos_x_memory_mmio_stats_record::memory::mmio::stats::record::{nonos_x_memory_mmio_stats_record::memory::mmio::stats::types::MmioStats}::record_unmapping]:
    Source: 'src/memory/mmio/stats/../../../../../../../../src/memory/mmio/stats/record.rs', lines 30:4-33:5
    Visibility: public -/
def memory.mmio.stats.record.MmioStats.record_unmapping
  (self : memory.mmio.stats.types.MmioStats) (size : Std.Usize) :
  Result Unit
  := do
  let _ ←
    core.sync.atomic.AtomicUsizeAlign8Usize.fetch_sub self.total_regions
      1#usize core.sync.atomic.Ordering.Relaxed
  let i ← lift (UScalar.cast .U64 size)
  let _ ←
    core.sync.atomic.AtomicU64Align8U64.fetch_sub self.total_mapped_size i
      core.sync.atomic.Ordering.Relaxed
  ok ()

/-- [nonos_x_memory_mmio_stats_record::mmiostats_record_unmapping]:
    Source: 'src/lib.rs', lines 19:0-21:1
    Visibility: public -/
def mmiostats_record_unmapping
  (this : memory.mmio.stats.types.MmioStats) (size : Std.Usize) :
  Result Unit
  := do
  memory.mmio.stats.record.MmioStats.record_unmapping this size

/-- [nonos_x_memory_mmio_stats_record::memory::mmio::stats::record::{nonos_x_memory_mmio_stats_record::memory::mmio::stats::types::MmioStats}::record_read]:
    Source: 'src/memory/mmio/stats/../../../../../../../../src/memory/mmio/stats/record.rs', lines 36:4-38:5
    Visibility: public -/
def memory.mmio.stats.record.MmioStats.record_read
  (self : memory.mmio.stats.types.MmioStats) : Result Unit := do
  let _ ←
    core.sync.atomic.AtomicU64Align8U64.fetch_add self.read_operations 1#u64
      core.sync.atomic.Ordering.Relaxed
  ok ()

/-- [nonos_x_memory_mmio_stats_record::mmiostats_record_read]:
    Source: 'src/lib.rs', lines 23:0-25:1
    Visibility: public -/
def mmiostats_record_read
  (this : memory.mmio.stats.types.MmioStats) : Result Unit := do
  memory.mmio.stats.record.MmioStats.record_read this

/-- [nonos_x_memory_mmio_stats_record::memory::mmio::stats::record::{nonos_x_memory_mmio_stats_record::memory::mmio::stats::types::MmioStats}::record_write]:
    Source: 'src/memory/mmio/stats/../../../../../../../../src/memory/mmio/stats/record.rs', lines 41:4-43:5
    Visibility: public -/
def memory.mmio.stats.record.MmioStats.record_write
  (self : memory.mmio.stats.types.MmioStats) : Result Unit := do
  let _ ←
    core.sync.atomic.AtomicU64Align8U64.fetch_add self.write_operations 1#u64
      core.sync.atomic.Ordering.Relaxed
  ok ()

/-- [nonos_x_memory_mmio_stats_record::mmiostats_record_write]:
    Source: 'src/lib.rs', lines 27:0-29:1
    Visibility: public -/
def mmiostats_record_write
  (this : memory.mmio.stats.types.MmioStats) : Result Unit := do
  memory.mmio.stats.record.MmioStats.record_write this

end nonos_x_memory_mmio_stats_record
