/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

query, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.MemoryDmaStatsQuery

open Aeneas Aeneas.Std Result
open nonos_x_memory_dma_stats_query

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.MemoryDmaStatsQuery

/-! ### The forwarding functions add nothing -/

theorem the_dmastats_total_memory_wrapper_is_its_method (a : memory.dma.stats.types.DmaStats) :
    dmastats_total_memory a = memory.dma.stats.query.DmaStats.total_memory a := rfl

theorem the_dmastats_coherent_count_wrapper_is_its_method (a : memory.dma.stats.types.DmaStats) :
    dmastats_coherent_count a = memory.dma.stats.query.DmaStats.coherent_count a := rfl

theorem the_dmastats_streaming_count_wrapper_is_its_method (a : memory.dma.stats.types.DmaStats) :
    dmastats_streaming_count a = memory.dma.stats.query.DmaStats.streaming_count a := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.MemoryDmaStatsQuery.the_dmastats_total_memory_wrapper_is_its_method
#print axioms NonosExtraction.MemoryDmaStatsQuery.the_dmastats_coherent_count_wrapper_is_its_method
#print axioms NonosExtraction.MemoryDmaStatsQuery.the_dmastats_streaming_count_wrapper_is_its_method

end NonosExtraction.MemoryDmaStatsQuery
