/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

frame, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.MemoryPhysTypesFrame

open Aeneas Aeneas.Std Result
open nonos_x_memory_phys_types_frame

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.MemoryPhysTypesFrame

/-! ### The forwarding functions add nothing -/

theorem the_frame_new_wrapper_is_its_method (a : Std.U64) :
    frame_new a = memory.phys.types.frame.Frame.new a := rfl

theorem the_frame_addr_wrapper_is_its_method (a : memory.phys.types.frame.Frame) :
    frame_addr a = memory.phys.types.frame.Frame.addr a := rfl

theorem the_frame_number_wrapper_is_its_method (a : memory.phys.types.frame.Frame) (b : Std.U64) (c : Std.U64) :
    frame_number a b c = memory.phys.types.frame.Frame.number a b c := rfl

theorem the_frame_is_null_wrapper_is_its_method (a : memory.phys.types.frame.Frame) :
    frame_is_null a = memory.phys.types.frame.Frame.is_null a := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.MemoryPhysTypesFrame.the_frame_new_wrapper_is_its_method
#print axioms NonosExtraction.MemoryPhysTypesFrame.the_frame_addr_wrapper_is_its_method
#print axioms NonosExtraction.MemoryPhysTypesFrame.the_frame_number_wrapper_is_its_method
#print axioms NonosExtraction.MemoryPhysTypesFrame.the_frame_is_null_wrapper_is_its_method

end NonosExtraction.MemoryPhysTypesFrame
