/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

helpers, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.MemoryMmuConstantsHelpers

open Aeneas Aeneas.Std Result
open nonos_x_memory_mmu_constants_helpers

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.MemoryMmuConstantsHelpers

/-! ### The forwarding functions add nothing -/

theorem the_pml4_index_wrapper_is_its_method (a : Std.U64) :
    pml4_index a = memory.mmu.constants.helpers.pml4_index a := rfl

theorem the_pdpt_index_wrapper_is_its_method (a : Std.U64) :
    pdpt_index a = memory.mmu.constants.helpers.pdpt_index a := rfl

theorem the_pd_index_wrapper_is_its_method (a : Std.U64) :
    pd_index a = memory.mmu.constants.helpers.pd_index a := rfl

theorem the_pt_index_wrapper_is_its_method (a : Std.U64) :
    pt_index a = memory.mmu.constants.helpers.pt_index a := rfl

theorem the_pte_is_present_wrapper_is_its_method (a : Std.U64) :
    pte_is_present a = memory.mmu.constants.helpers.pte_is_present a := rfl

theorem the_pte_address_wrapper_is_its_method (a : Std.U64) :
    pte_address a = memory.mmu.constants.helpers.pte_address a := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.MemoryMmuConstantsHelpers.the_pml4_index_wrapper_is_its_method
#print axioms NonosExtraction.MemoryMmuConstantsHelpers.the_pdpt_index_wrapper_is_its_method
#print axioms NonosExtraction.MemoryMmuConstantsHelpers.the_pd_index_wrapper_is_its_method
#print axioms NonosExtraction.MemoryMmuConstantsHelpers.the_pt_index_wrapper_is_its_method
#print axioms NonosExtraction.MemoryMmuConstantsHelpers.the_pte_is_present_wrapper_is_its_method
#print axioms NonosExtraction.MemoryMmuConstantsHelpers.the_pte_address_wrapper_is_its_method

end NonosExtraction.MemoryMmuConstantsHelpers
