/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

record, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.MemoryBuddyAllocStatsRecord

open Aeneas Aeneas.Std Result
open nonos_x_memory_buddy_alloc_stats_record

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.MemoryBuddyAllocStatsRecord

/-! ### The forwarding functions add nothing -/

theorem the_allocationstatistics_record_allocation_wrapper_is_its_method (a : memory.buddy_alloc.stats.types.AllocationStatistics) (b : Std.U64) :
    allocationstatistics_record_allocation a b = memory.buddy_alloc.stats.record.AllocationStatistics.record_allocation a b := rfl

theorem the_allocationstatistics_record_deallocation_wrapper_is_its_method (a : memory.buddy_alloc.stats.types.AllocationStatistics) (b : Std.U64) :
    allocationstatistics_record_deallocation a b = memory.buddy_alloc.stats.record.AllocationStatistics.record_deallocation a b := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.MemoryBuddyAllocStatsRecord.the_allocationstatistics_record_allocation_wrapper_is_its_method
#print axioms NonosExtraction.MemoryBuddyAllocStatsRecord.the_allocationstatistics_record_deallocation_wrapper_is_its_method

end NonosExtraction.MemoryBuddyAllocStatsRecord
