/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

flags, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.MemoryMmioTypesFlags

open Aeneas Aeneas.Std Result
open nonos_x_memory_mmio_types_flags

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.MemoryMmioTypesFlags

/-! ### The forwarding functions add nothing -/

theorem the_mmioflags_device_wrapper_is_its_method :
    mmioflags_device = memory.mmio.types.flags.MmioFlags.device := rfl

theorem the_mmioflags_framebuffer_wrapper_is_its_method :
    mmioflags_framebuffer = memory.mmio.types.flags.MmioFlags.framebuffer := rfl

theorem the_mmioflags_user_device_wrapper_is_its_method :
    mmioflags_user_device = memory.mmio.types.flags.MmioFlags.user_device := rfl

theorem the_mmioflags_to_vm_flags_wrapper_is_its_method (a : memory.mmio.types.flags.MmioFlags) :
    mmioflags_to_vm_flags a = memory.mmio.types.flags.MmioFlags.to_vm_flags a := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.MemoryMmioTypesFlags.the_mmioflags_device_wrapper_is_its_method
#print axioms NonosExtraction.MemoryMmioTypesFlags.the_mmioflags_framebuffer_wrapper_is_its_method
#print axioms NonosExtraction.MemoryMmioTypesFlags.the_mmioflags_user_device_wrapper_is_its_method
#print axioms NonosExtraction.MemoryMmioTypesFlags.the_mmioflags_to_vm_flags_wrapper_is_its_method

end NonosExtraction.MemoryMmioTypesFlags
