/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

query, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.MemoryRegionStatsQuery

open Aeneas Aeneas.Std Result
open nonos_x_memory_region_stats_query

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.MemoryRegionStatsQuery

/-! ### The forwarding functions add nothing -/

theorem the_regionstatistics_total_regions_wrapper_is_its_method (a : memory.region.stats.state.RegionStatistics) :
    regionstatistics_total_regions a = memory.region.stats.query.RegionStatistics.total_regions a := rfl

theorem the_regionstatistics_allocated_bytes_wrapper_is_its_method (a : memory.region.stats.state.RegionStatistics) :
    regionstatistics_allocated_bytes a = memory.region.stats.query.RegionStatistics.allocated_bytes a := rfl

theorem the_regionstatistics_free_bytes_wrapper_is_its_method (a : memory.region.stats.state.RegionStatistics) :
    regionstatistics_free_bytes a = memory.region.stats.query.RegionStatistics.free_bytes a := rfl

theorem the_regionstatistics_allocation_count_wrapper_is_its_method (a : memory.region.stats.state.RegionStatistics) :
    regionstatistics_allocation_count a = memory.region.stats.query.RegionStatistics.allocation_count a := rfl

theorem the_regionstatistics_deallocation_count_wrapper_is_its_method (a : memory.region.stats.state.RegionStatistics) :
    regionstatistics_deallocation_count a = memory.region.stats.query.RegionStatistics.deallocation_count a := rfl

theorem the_regionstatistics_merge_count_wrapper_is_its_method (a : memory.region.stats.state.RegionStatistics) :
    regionstatistics_merge_count a = memory.region.stats.query.RegionStatistics.merge_count a := rfl

theorem the_regionstatistics_split_count_wrapper_is_its_method (a : memory.region.stats.state.RegionStatistics) :
    regionstatistics_split_count a = memory.region.stats.query.RegionStatistics.split_count a := rfl

theorem the_regionstatistics_fragmentation_count_wrapper_is_its_method (a : memory.region.stats.state.RegionStatistics) :
    regionstatistics_fragmentation_count a = memory.region.stats.query.RegionStatistics.fragmentation_count a := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.MemoryRegionStatsQuery.the_regionstatistics_total_regions_wrapper_is_its_method
#print axioms NonosExtraction.MemoryRegionStatsQuery.the_regionstatistics_allocated_bytes_wrapper_is_its_method
#print axioms NonosExtraction.MemoryRegionStatsQuery.the_regionstatistics_free_bytes_wrapper_is_its_method
#print axioms NonosExtraction.MemoryRegionStatsQuery.the_regionstatistics_allocation_count_wrapper_is_its_method
#print axioms NonosExtraction.MemoryRegionStatsQuery.the_regionstatistics_deallocation_count_wrapper_is_its_method
#print axioms NonosExtraction.MemoryRegionStatsQuery.the_regionstatistics_merge_count_wrapper_is_its_method
#print axioms NonosExtraction.MemoryRegionStatsQuery.the_regionstatistics_split_count_wrapper_is_its_method
#print axioms NonosExtraction.MemoryRegionStatsQuery.the_regionstatistics_fragmentation_count_wrapper_is_its_method

end NonosExtraction.MemoryRegionStatsQuery
