/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

impls_recover, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.MemoryPagingErrorImplsRecover

open Aeneas Aeneas.Std Result
open nonos_x_memory_paging_error_impls_recover

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.MemoryPagingErrorImplsRecover

/-! ### The forwarding functions add nothing -/

theorem the_pagingerror_is_recoverable_wrapper_is_its_method (a : memory.paging.error.types.PagingError) :
    pagingerror_is_recoverable a = memory.paging.error.impls_recover.PagingError.is_recoverable a := rfl

theorem the_pagingerror_is_demand_pageable_wrapper_is_its_method (a : memory.paging.error.types.PagingError) :
    pagingerror_is_demand_pageable a = memory.paging.error.impls_recover.PagingError.is_demand_pageable a := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.MemoryPagingErrorImplsRecover.the_pagingerror_is_recoverable_wrapper_is_its_method
#print axioms NonosExtraction.MemoryPagingErrorImplsRecover.the_pagingerror_is_demand_pageable_wrapper_is_its_method

end NonosExtraction.MemoryPagingErrorImplsRecover
