/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

page_size, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.MemoryPagingTypesPageSize

open Aeneas Aeneas.Std Result
open nonos_x_memory_paging_types_page_size

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.MemoryPagingTypesPageSize

/-! ### The forwarding functions add nothing -/

theorem the_pagesize_bytes_wrapper_is_its_method (a : memory.paging.types.page_size.PageSize) :
    pagesize_bytes a = memory.paging.types.page_size.PageSize.bytes a := rfl

theorem the_pagesize_align_mask_wrapper_is_its_method (a : memory.paging.types.page_size.PageSize) :
    pagesize_align_mask a = memory.paging.types.page_size.PageSize.align_mask a := rfl

theorem the_pagesize_is_aligned_wrapper_is_its_method (a : memory.paging.types.page_size.PageSize) (b : Std.U64) :
    pagesize_is_aligned a b = memory.paging.types.page_size.PageSize.is_aligned a b := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.MemoryPagingTypesPageSize.the_pagesize_bytes_wrapper_is_its_method
#print axioms NonosExtraction.MemoryPagingTypesPageSize.the_pagesize_align_mask_wrapper_is_its_method
#print axioms NonosExtraction.MemoryPagingTypesPageSize.the_pagesize_is_aligned_wrapper_is_its_method

end NonosExtraction.MemoryPagingTypesPageSize
