/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

query, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.MemoryHardeningStatsQuery

open Aeneas Aeneas.Std Result
open nonos_x_memory_hardening_stats_query

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.MemoryHardeningStatsQuery

/-! ### The forwarding functions add nothing -/

theorem the_hardeningstats_guard_violations_wrapper_is_its_method (a : memory.hardening.stats.types.HardeningStats) :
    hardeningstats_guard_violations a = memory.hardening.stats.query.HardeningStats.guard_violations a := rfl

theorem the_hardeningstats_wx_violations_wrapper_is_its_method (a : memory.hardening.stats.types.HardeningStats) :
    hardeningstats_wx_violations a = memory.hardening.stats.query.HardeningStats.wx_violations a := rfl

theorem the_hardeningstats_stack_overflows_wrapper_is_its_method (a : memory.hardening.stats.types.HardeningStats) :
    hardeningstats_stack_overflows a = memory.hardening.stats.query.HardeningStats.stack_overflows a := rfl

theorem the_hardeningstats_heap_corruptions_wrapper_is_its_method (a : memory.hardening.stats.types.HardeningStats) :
    hardeningstats_heap_corruptions a = memory.hardening.stats.query.HardeningStats.heap_corruptions a := rfl

theorem the_hardeningstats_double_frees_wrapper_is_its_method (a : memory.hardening.stats.types.HardeningStats) :
    hardeningstats_double_frees a = memory.hardening.stats.query.HardeningStats.double_frees a := rfl

theorem the_hardeningstats_use_after_free_wrapper_is_its_method (a : memory.hardening.stats.types.HardeningStats) :
    hardeningstats_use_after_free a = memory.hardening.stats.query.HardeningStats.use_after_free a := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.MemoryHardeningStatsQuery.the_hardeningstats_guard_violations_wrapper_is_its_method
#print axioms NonosExtraction.MemoryHardeningStatsQuery.the_hardeningstats_wx_violations_wrapper_is_its_method
#print axioms NonosExtraction.MemoryHardeningStatsQuery.the_hardeningstats_stack_overflows_wrapper_is_its_method
#print axioms NonosExtraction.MemoryHardeningStatsQuery.the_hardeningstats_heap_corruptions_wrapper_is_its_method
#print axioms NonosExtraction.MemoryHardeningStatsQuery.the_hardeningstats_double_frees_wrapper_is_its_method
#print axioms NonosExtraction.MemoryHardeningStatsQuery.the_hardeningstats_use_after_free_wrapper_is_its_method

end NonosExtraction.MemoryHardeningStatsQuery
