/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

pte_funcs, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.MemoryPagingConstantsPteFuncs

open Aeneas Aeneas.Std Result
open nonos_x_memory_paging_constants_pte_funcs

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.MemoryPagingConstantsPteFuncs

/-! ### The forwarding functions add nothing -/

theorem the_pte_is_present_wrapper_is_its_method (a : Std.U64) :
    pte_is_present a = memory.paging.constants.pte_funcs.pte_is_present a := rfl

theorem the_pte_is_huge_wrapper_is_its_method (a : Std.U64) :
    pte_is_huge a = memory.paging.constants.pte_funcs.pte_is_huge a := rfl

theorem the_pte_address_wrapper_is_its_method (a : Std.U64) :
    pte_address a = memory.paging.constants.pte_funcs.pte_address a := rfl

theorem the_pte_is_writable_wrapper_is_its_method (a : Std.U64) :
    pte_is_writable a = memory.paging.constants.pte_funcs.pte_is_writable a := rfl

theorem the_pte_is_executable_wrapper_is_its_method (a : Std.U64) :
    pte_is_executable a = memory.paging.constants.pte_funcs.pte_is_executable a := rfl

theorem the_pte_is_user_wrapper_is_its_method (a : Std.U64) :
    pte_is_user a = memory.paging.constants.pte_funcs.pte_is_user a := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.MemoryPagingConstantsPteFuncs.the_pte_is_present_wrapper_is_its_method
#print axioms NonosExtraction.MemoryPagingConstantsPteFuncs.the_pte_is_huge_wrapper_is_its_method
#print axioms NonosExtraction.MemoryPagingConstantsPteFuncs.the_pte_address_wrapper_is_its_method
#print axioms NonosExtraction.MemoryPagingConstantsPteFuncs.the_pte_is_writable_wrapper_is_its_method
#print axioms NonosExtraction.MemoryPagingConstantsPteFuncs.the_pte_is_executable_wrapper_is_its_method
#print axioms NonosExtraction.MemoryPagingConstantsPteFuncs.the_pte_is_user_wrapper_is_its_method

end NonosExtraction.MemoryPagingConstantsPteFuncs
