/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

flags, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.MemoryPageInfoTypesFlags

open Aeneas Aeneas.Std Result
open nonos_x_memory_page_info_types_flags

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.MemoryPageInfoTypesFlags

/-! ### The forwarding functions add nothing -/

theorem the_pageflags_from_bits_wrapper_is_its_method (a : Std.U32) :
    pageflags_from_bits a = memory.page_info.types.flags.PageFlags.from_bits a := rfl

theorem the_pageflags_bits_wrapper_is_its_method (a : memory.page_info.types.flags.PageFlags) :
    pageflags_bits a = memory.page_info.types.flags.PageFlags.impl.bits a := rfl

theorem the_pageflags_contains_wrapper_is_its_method (a : memory.page_info.types.flags.PageFlags) (b : memory.page_info.types.flags.PageFlags) :
    pageflags_contains a b = memory.page_info.types.flags.PageFlags.contains a b := rfl

theorem the_pageflags_union_wrapper_is_its_method (a : memory.page_info.types.flags.PageFlags) (b : memory.page_info.types.flags.PageFlags) :
    pageflags_union a b = memory.page_info.types.flags.PageFlags.union a b := rfl

theorem the_pageflags_intersection_wrapper_is_its_method (a : memory.page_info.types.flags.PageFlags) (b : memory.page_info.types.flags.PageFlags) :
    pageflags_intersection a b = memory.page_info.types.flags.PageFlags.intersection a b := rfl

theorem the_pageflags_difference_wrapper_is_its_method (a : memory.page_info.types.flags.PageFlags) (b : memory.page_info.types.flags.PageFlags) :
    pageflags_difference a b = memory.page_info.types.flags.PageFlags.difference a b := rfl

theorem the_pageflags_is_empty_wrapper_is_its_method (a : memory.page_info.types.flags.PageFlags) :
    pageflags_is_empty a = memory.page_info.types.flags.PageFlags.is_empty a := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.MemoryPageInfoTypesFlags.the_pageflags_from_bits_wrapper_is_its_method
#print axioms NonosExtraction.MemoryPageInfoTypesFlags.the_pageflags_bits_wrapper_is_its_method
#print axioms NonosExtraction.MemoryPageInfoTypesFlags.the_pageflags_contains_wrapper_is_its_method
#print axioms NonosExtraction.MemoryPageInfoTypesFlags.the_pageflags_union_wrapper_is_its_method
#print axioms NonosExtraction.MemoryPageInfoTypesFlags.the_pageflags_intersection_wrapper_is_its_method
#print axioms NonosExtraction.MemoryPageInfoTypesFlags.the_pageflags_difference_wrapper_is_its_method
#print axioms NonosExtraction.MemoryPageInfoTypesFlags.the_pageflags_is_empty_wrapper_is_its_method

end NonosExtraction.MemoryPageInfoTypesFlags
