/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

stats, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.MemoryStats

open Aeneas Aeneas.Std Result
open nonos_x_memory_stats

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.MemoryStats

/-! ### The forwarding functions add nothing -/

theorem the_init_wrapper_is_its_method (a : Std.U64) :
    init a = stats.init a := rfl

theorem the_add_used_wrapper_is_its_method (a : Std.U64) :
    add_used a = stats.add_used a := rfl

theorem the_sub_used_wrapper_is_its_method (a : Std.U64) :
    sub_used a = stats.sub_used a := rfl

theorem the_used_bytes_wrapper_is_its_method :
    used_bytes = stats.used_bytes := rfl

theorem the_total_bytes_wrapper_is_its_method :
    total_bytes = stats.total_bytes := rfl

theorem the_used_mb_wrapper_is_its_method :
    used_mb = stats.used_mb := rfl

theorem the_total_mb_wrapper_is_its_method :
    total_mb = stats.total_mb := rfl

theorem the_free_mb_wrapper_is_its_method :
    free_mb = stats.free_mb := rfl

theorem the_usage_percent_wrapper_is_its_method :
    usage_percent = stats.usage_percent := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.MemoryStats.the_init_wrapper_is_its_method
#print axioms NonosExtraction.MemoryStats.the_add_used_wrapper_is_its_method
#print axioms NonosExtraction.MemoryStats.the_sub_used_wrapper_is_its_method
#print axioms NonosExtraction.MemoryStats.the_used_bytes_wrapper_is_its_method
#print axioms NonosExtraction.MemoryStats.the_total_bytes_wrapper_is_its_method
#print axioms NonosExtraction.MemoryStats.the_used_mb_wrapper_is_its_method
#print axioms NonosExtraction.MemoryStats.the_total_mb_wrapper_is_its_method
#print axioms NonosExtraction.MemoryStats.the_free_mb_wrapper_is_its_method
#print axioms NonosExtraction.MemoryStats.the_usage_percent_wrapper_is_its_method

end NonosExtraction.MemoryStats
