/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

memory_region, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.MemoryBootMemoryTypesMemoryRegion

open Aeneas Aeneas.Std Result
open nonos_x_memory_boot_memory_types_memory_region

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.MemoryBootMemoryTypesMemoryRegion

/-! ### The forwarding functions add nothing -/

theorem the_memoryregion_size_wrapper_is_its_method (a : memory.boot_memory.types.memory_region.MemoryRegion) :
    memoryregion_size a = memory.boot_memory.types.memory_region.MemoryRegion.size a := rfl

theorem the_memoryregion_page_count_wrapper_is_its_method (a : memory.boot_memory.types.memory_region.MemoryRegion) :
    memoryregion_page_count a = memory.boot_memory.types.memory_region.MemoryRegion.page_count a := rfl

theorem the_memoryregion_is_available_wrapper_is_its_method (a : memory.boot_memory.types.memory_region.MemoryRegion) :
    memoryregion_is_available a = memory.boot_memory.types.memory_region.MemoryRegion.is_available a := rfl

theorem the_memoryregion_is_empty_wrapper_is_its_method (a : memory.boot_memory.types.memory_region.MemoryRegion) :
    memoryregion_is_empty a = memory.boot_memory.types.memory_region.MemoryRegion.is_empty a := rfl

theorem the_memoryregion_has_flag_wrapper_is_its_method (a : memory.boot_memory.types.memory_region.MemoryRegion) (b : Std.U32) :
    memoryregion_has_flag a b = memory.boot_memory.types.memory_region.MemoryRegion.has_flag a b := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.MemoryBootMemoryTypesMemoryRegion.the_memoryregion_size_wrapper_is_its_method
#print axioms NonosExtraction.MemoryBootMemoryTypesMemoryRegion.the_memoryregion_page_count_wrapper_is_its_method
#print axioms NonosExtraction.MemoryBootMemoryTypesMemoryRegion.the_memoryregion_is_available_wrapper_is_its_method
#print axioms NonosExtraction.MemoryBootMemoryTypesMemoryRegion.the_memoryregion_is_empty_wrapper_is_its_method
#print axioms NonosExtraction.MemoryBootMemoryTypesMemoryRegion.the_memoryregion_has_flag_wrapper_is_its_method

end NonosExtraction.MemoryBootMemoryTypesMemoryRegion
