-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [nonos_x_memory_page_info_types_flags]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace nonos_x_memory_page_info_types_flags

/-- [nonos_x_memory_page_info_types_flags::memory::page_info::types::flags::PageFlags]
    Source: 'src/memory/page_info/types/../../../../../../../../src/memory/page_info/types/flags.rs', lines 20:0-22:1
    Visibility: public -/
structure memory.page_info.types.flags.PageFlags where
  bits : Std.U32

/-- [nonos_x_memory_page_info_types_flags::memory::page_info::types::flags::{nonos_x_memory_page_info_types_flags::memory::page_info::types::flags::PageFlags}::from_bits]:
    Source: 'src/memory/page_info/types/../../../../../../../../src/memory/page_info/types/flags.rs', lines 34:4-36:5
    Visibility: public -/
def memory.page_info.types.flags.PageFlags.from_bits
  (bits : Std.U32) : Result memory.page_info.types.flags.PageFlags := do
  ok { bits }

/-- [nonos_x_memory_page_info_types_flags::pageflags_from_bits]:
    Source: 'src/lib.rs', lines 11:0-13:1
    Visibility: public -/
def pageflags_from_bits
  (bits : Std.U32) : Result memory.page_info.types.flags.PageFlags := do
  memory.page_info.types.flags.PageFlags.from_bits bits

/-- [nonos_x_memory_page_info_types_flags::memory::page_info::types::flags::{nonos_x_memory_page_info_types_flags::memory::page_info::types::flags::PageFlags}::bits]:
    Source: 'src/memory/page_info/types/../../../../../../../../src/memory/page_info/types/flags.rs', lines 37:4-39:5
    Visibility: public -/
def memory.page_info.types.flags.PageFlags.impl.bits
  (self : memory.page_info.types.flags.PageFlags) : Result Std.U32 := do
  ok self.bits

/-- [nonos_x_memory_page_info_types_flags::pageflags_bits]:
    Source: 'src/lib.rs', lines 15:0-17:1
    Visibility: public -/
def pageflags_bits
  (this : memory.page_info.types.flags.PageFlags) : Result Std.U32 := do
  memory.page_info.types.flags.PageFlags.impl.bits this

/-- [nonos_x_memory_page_info_types_flags::memory::page_info::types::flags::{nonos_x_memory_page_info_types_flags::memory::page_info::types::flags::PageFlags}::contains]:
    Source: 'src/memory/page_info/types/../../../../../../../../src/memory/page_info/types/flags.rs', lines 40:4-42:5
    Visibility: public -/
def memory.page_info.types.flags.PageFlags.contains
  (self : memory.page_info.types.flags.PageFlags)
  (other : memory.page_info.types.flags.PageFlags) :
  Result Bool
  := do
  let i ← lift (self.bits &&& other.bits)
  ok (i = other.bits)

/-- [nonos_x_memory_page_info_types_flags::pageflags_contains]:
    Source: 'src/lib.rs', lines 19:0-21:1
    Visibility: public -/
def pageflags_contains
  (this : memory.page_info.types.flags.PageFlags)
  (other : memory.page_info.types.flags.PageFlags) :
  Result Bool
  := do
  memory.page_info.types.flags.PageFlags.contains this other

/-- [nonos_x_memory_page_info_types_flags::memory::page_info::types::flags::{nonos_x_memory_page_info_types_flags::memory::page_info::types::flags::PageFlags}::union]:
    Source: 'src/memory/page_info/types/../../../../../../../../src/memory/page_info/types/flags.rs', lines 43:4-45:5
    Visibility: public -/
def memory.page_info.types.flags.PageFlags.union
  (self : memory.page_info.types.flags.PageFlags)
  (other : memory.page_info.types.flags.PageFlags) :
  Result memory.page_info.types.flags.PageFlags
  := do
  let i ← lift (self.bits ||| other.bits)
  ok { bits := i }

/-- [nonos_x_memory_page_info_types_flags::pageflags_union]:
    Source: 'src/lib.rs', lines 23:0-25:1
    Visibility: public -/
def pageflags_union
  (this : memory.page_info.types.flags.PageFlags)
  (other : memory.page_info.types.flags.PageFlags) :
  Result memory.page_info.types.flags.PageFlags
  := do
  memory.page_info.types.flags.PageFlags.union this other

/-- [nonos_x_memory_page_info_types_flags::memory::page_info::types::flags::{nonos_x_memory_page_info_types_flags::memory::page_info::types::flags::PageFlags}::intersection]:
    Source: 'src/memory/page_info/types/../../../../../../../../src/memory/page_info/types/flags.rs', lines 46:4-48:5
    Visibility: public -/
def memory.page_info.types.flags.PageFlags.intersection
  (self : memory.page_info.types.flags.PageFlags)
  (other : memory.page_info.types.flags.PageFlags) :
  Result memory.page_info.types.flags.PageFlags
  := do
  let i ← lift (self.bits &&& other.bits)
  ok { bits := i }

/-- [nonos_x_memory_page_info_types_flags::pageflags_intersection]:
    Source: 'src/lib.rs', lines 27:0-29:1
    Visibility: public -/
def pageflags_intersection
  (this : memory.page_info.types.flags.PageFlags)
  (other : memory.page_info.types.flags.PageFlags) :
  Result memory.page_info.types.flags.PageFlags
  := do
  memory.page_info.types.flags.PageFlags.intersection this other

/-- [nonos_x_memory_page_info_types_flags::memory::page_info::types::flags::{nonos_x_memory_page_info_types_flags::memory::page_info::types::flags::PageFlags}::difference]:
    Source: 'src/memory/page_info/types/../../../../../../../../src/memory/page_info/types/flags.rs', lines 49:4-51:5
    Visibility: public -/
def memory.page_info.types.flags.PageFlags.difference
  (self : memory.page_info.types.flags.PageFlags)
  (other : memory.page_info.types.flags.PageFlags) :
  Result memory.page_info.types.flags.PageFlags
  := do
  let i ← lift (~~~ other.bits)
  let i1 ← lift (self.bits &&& i)
  ok { bits := i1 }

/-- [nonos_x_memory_page_info_types_flags::pageflags_difference]:
    Source: 'src/lib.rs', lines 31:0-33:1
    Visibility: public -/
def pageflags_difference
  (this : memory.page_info.types.flags.PageFlags)
  (other : memory.page_info.types.flags.PageFlags) :
  Result memory.page_info.types.flags.PageFlags
  := do
  memory.page_info.types.flags.PageFlags.difference this other

/-- [nonos_x_memory_page_info_types_flags::memory::page_info::types::flags::{nonos_x_memory_page_info_types_flags::memory::page_info::types::flags::PageFlags}::is_empty]:
    Source: 'src/memory/page_info/types/../../../../../../../../src/memory/page_info/types/flags.rs', lines 52:4-54:5
    Visibility: public -/
def memory.page_info.types.flags.PageFlags.is_empty
  (self : memory.page_info.types.flags.PageFlags) : Result Bool := do
  ok (self.bits = 0#u32)

/-- [nonos_x_memory_page_info_types_flags::pageflags_is_empty]:
    Source: 'src/lib.rs', lines 35:0-37:1
    Visibility: public -/
def pageflags_is_empty
  (this : memory.page_info.types.flags.PageFlags) : Result Bool := do
  memory.page_info.types.flags.PageFlags.is_empty this

end nonos_x_memory_page_info_types_flags
