/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

helpers, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.MemoryBuddyAllocConstantsHelpers

open Aeneas Aeneas.Std Result
open nonos_x_memory_buddy_alloc_constants_helpers

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.MemoryBuddyAllocConstantsHelpers

/-! ### The forwarding functions add nothing -/

theorem the_order_to_size_wrapper_is_its_method (a : Std.Usize) :
    order_to_size a = memory.buddy_alloc.constants.helpers.order_to_size a := rfl

theorem the_size_to_order_wrapper_is_its_method (a : Std.Usize) :
    size_to_order a = memory.buddy_alloc.constants.helpers.size_to_order a := rfl

theorem the_buddy_address_wrapper_is_its_method (a : Std.U64) (b : Std.Usize) :
    buddy_address a b = memory.buddy_alloc.constants.helpers.buddy_address a b := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.MemoryBuddyAllocConstantsHelpers.the_order_to_size_wrapper_is_its_method
#print axioms NonosExtraction.MemoryBuddyAllocConstantsHelpers.the_size_to_order_wrapper_is_its_method
#print axioms NonosExtraction.MemoryBuddyAllocConstantsHelpers.the_buddy_address_wrapper_is_its_method

end NonosExtraction.MemoryBuddyAllocConstantsHelpers
