-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [nonos_x_memory_layout_types_region]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace nonos_x_memory_layout_types_region

/-- [nonos_x_memory_layout_types_region::memory::layout::types::region_kind::RegionKind]
    Source: 'src/memory/layout/types/../../../../../../../../src/memory/layout/types/region_kind.rs', lines 18:0-27:1
    Visibility: public -/
@[discriminant isize]
inductive memory.layout.types.region_kind.RegionKind where
| Available : memory.layout.types.region_kind.RegionKind
| Usable : memory.layout.types.region_kind.RegionKind
| Reserved : memory.layout.types.region_kind.RegionKind
| Acpi : memory.layout.types.region_kind.RegionKind
| Mmio : memory.layout.types.region_kind.RegionKind
| Kernel : memory.layout.types.region_kind.RegionKind
| Boot : memory.layout.types.region_kind.RegionKind
| Unknown : memory.layout.types.region_kind.RegionKind

/-- [nonos_x_memory_layout_types_region::memory::layout::types::region::Region]
    Source: 'src/memory/layout/types/../../../../../../../../src/memory/layout/types/region.rs', lines 21:0-25:1
    Visibility: public -/
structure memory.layout.types.region.Region where
  start : Std.U64
  «end» : Std.U64
  kind : memory.layout.types.region_kind.RegionKind

/-- [nonos_x_memory_layout_types_region::memory::layout::types::region::{nonos_x_memory_layout_types_region::memory::layout::types::region::Region}::len]:
    Source: 'src/memory/layout/types/../../../../../../../../src/memory/layout/types/region.rs', lines 33:4-39:5
    Visibility: public -/
def memory.layout.types.region.Region.len
  (self : memory.layout.types.region.Region) : Result Std.U64 := do
  if self.«end» > self.start
  then self.«end» - self.start
  else ok 0#u64

/-- [nonos_x_memory_layout_types_region::region_len]:
    Source: 'src/lib.rs', lines 11:0-13:1
    Visibility: public -/
def region_len
  (this : memory.layout.types.region.Region) : Result Std.U64 := do
  memory.layout.types.region.Region.len this

/-- [nonos_x_memory_layout_types_region::memory::layout::types::region::{nonos_x_memory_layout_types_region::memory::layout::types::region::Region}::is_empty]:
    Source: 'src/memory/layout/types/../../../../../../../../src/memory/layout/types/region.rs', lines 42:4-44:5
    Visibility: public -/
def memory.layout.types.region.Region.is_empty
  (self : memory.layout.types.region.Region) : Result Bool := do
  ok (self.«end» <= self.start)

/-- [nonos_x_memory_layout_types_region::region_is_empty]:
    Source: 'src/lib.rs', lines 15:0-17:1
    Visibility: public -/
def region_is_empty
  (this : memory.layout.types.region.Region) : Result Bool := do
  memory.layout.types.region.Region.is_empty this

/-- [nonos_x_memory_layout_types_region::memory::layout::types::region_kind::{nonos_x_memory_layout_types_region::memory::layout::types::region_kind::RegionKind}::is_usable]:
    Source: 'src/memory/layout/types/../../../../../../../../src/memory/layout/types/region_kind.rs', lines 31:4-33:5
    Visibility: public -/
def memory.layout.types.region_kind.RegionKind.is_usable
  (self : memory.layout.types.region_kind.RegionKind) : Result Bool := do
  match self with
  | memory.layout.types.region_kind.RegionKind.Available => ok true
  | memory.layout.types.region_kind.RegionKind.Usable => ok true
  | memory.layout.types.region_kind.RegionKind.Reserved => ok false
  | memory.layout.types.region_kind.RegionKind.Acpi => ok false
  | memory.layout.types.region_kind.RegionKind.Mmio => ok false
  | memory.layout.types.region_kind.RegionKind.Kernel => ok false
  | memory.layout.types.region_kind.RegionKind.Boot => ok false
  | memory.layout.types.region_kind.RegionKind.Unknown => ok false

/-- [nonos_x_memory_layout_types_region::memory::layout::types::region::{nonos_x_memory_layout_types_region::memory::layout::types::region::Region}::is_usable]:
    Source: 'src/memory/layout/types/../../../../../../../../src/memory/layout/types/region.rs', lines 47:4-49:5
    Visibility: public -/
def memory.layout.types.region.Region.is_usable
  (self : memory.layout.types.region.Region) : Result Bool := do
  memory.layout.types.region_kind.RegionKind.is_usable self.kind

/-- [nonos_x_memory_layout_types_region::region_is_usable]:
    Source: 'src/lib.rs', lines 19:0-21:1
    Visibility: public -/
def region_is_usable
  (this : memory.layout.types.region.Region) : Result Bool := do
  memory.layout.types.region.Region.is_usable this

/-- [nonos_x_memory_layout_types_region::memory::layout::types::region::{nonos_x_memory_layout_types_region::memory::layout::types::region::Region}::start_addr]:
    Source: 'src/memory/layout/types/../../../../../../../../src/memory/layout/types/region.rs', lines 52:4-54:5
    Visibility: public -/
def memory.layout.types.region.Region.start_addr
  (self : memory.layout.types.region.Region) : Result Std.U64 := do
  ok self.start

/-- [nonos_x_memory_layout_types_region::region_start_addr]:
    Source: 'src/lib.rs', lines 23:0-25:1
    Visibility: public -/
def region_start_addr
  (this : memory.layout.types.region.Region) : Result Std.U64 := do
  memory.layout.types.region.Region.start_addr this

/-- [nonos_x_memory_layout_types_region::memory::layout::types::region::{nonos_x_memory_layout_types_region::memory::layout::types::region::Region}::end_addr]:
    Source: 'src/memory/layout/types/../../../../../../../../src/memory/layout/types/region.rs', lines 57:4-59:5
    Visibility: public -/
def memory.layout.types.region.Region.end_addr
  (self : memory.layout.types.region.Region) : Result Std.U64 := do
  ok self.«end»

/-- [nonos_x_memory_layout_types_region::region_end_addr]:
    Source: 'src/lib.rs', lines 27:0-29:1
    Visibility: public -/
def region_end_addr
  (this : memory.layout.types.region.Region) : Result Std.U64 := do
  memory.layout.types.region.Region.end_addr this

/-- [nonos_x_memory_layout_types_region::memory::layout::constants::page::PAGE_SIZE]
    Source: 'src/memory/layout/constants/../../../../../../../../src/memory/layout/constants/page.rs', lines 17:0-17:34
    Visibility: public -/
@[global_simps, irreducible]
def memory.layout.constants.page.PAGE_SIZE : Std.Usize := 4096#usize

/-- [nonos_x_memory_layout_types_region::memory::layout::constants::page::PAGE_SIZE_U64]
    Source: 'src/memory/layout/constants/../../../../../../../../src/memory/layout/constants/page.rs', lines 18:0-18:48
    Visibility: public -/
@[global_simps, irreducible]
def memory.layout.constants.page.PAGE_SIZE_U64 : Result Std.U64 :=
  ok (UScalar.cast .U64 memory.layout.constants.page.PAGE_SIZE)

/-- [nonos_x_memory_layout_types_region::memory::layout::types::region::{nonos_x_memory_layout_types_region::memory::layout::types::region::Region}::page_count]:
    Source: 'src/memory/layout/types/../../../../../../../../src/memory/layout/types/region.rs', lines 62:4-64:5
    Visibility: public -/
def memory.layout.types.region.Region.page_count
  (self : memory.layout.types.region.Region) : Result Std.U64 := do
  let i ← memory.layout.types.region.Region.len self
  let i1 ← memory.layout.constants.page.PAGE_SIZE_U64
  i / i1

/-- [nonos_x_memory_layout_types_region::region_page_count]:
    Source: 'src/lib.rs', lines 31:0-33:1
    Visibility: public -/
def region_page_count
  (this : memory.layout.types.region.Region) : Result Std.U64 := do
  memory.layout.types.region.Region.page_count this

/-- [nonos_x_memory_layout_types_region::memory::layout::types::region::{nonos_x_memory_layout_types_region::memory::layout::types::region::Region}::contains]:
    Source: 'src/memory/layout/types/../../../../../../../../src/memory/layout/types/region.rs', lines 67:4-69:5
    Visibility: public -/
def memory.layout.types.region.Region.contains
  (self : memory.layout.types.region.Region) (addr : Std.U64) :
  Result Bool
  := do
  if addr >= self.start
  then ok (addr < self.«end»)
  else ok false

/-- [nonos_x_memory_layout_types_region::region_contains]:
    Source: 'src/lib.rs', lines 35:0-37:1
    Visibility: public -/
def region_contains
  (this : memory.layout.types.region.Region) (addr : Std.U64) :
  Result Bool
  := do
  memory.layout.types.region.Region.contains this addr

end nonos_x_memory_layout_types_region
