/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

record, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.MemoryRegionStatsRecord

open Aeneas Aeneas.Std Result
open nonos_x_memory_region_stats_record

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.MemoryRegionStatsRecord

/-! ### The forwarding functions add nothing -/

theorem the_regionstatistics_record_allocation_wrapper_is_its_method (a : memory.region.stats.state.RegionStatistics) (b : Std.U64) :
    regionstatistics_record_allocation a b = memory.region.stats.record.RegionStatistics.record_allocation a b := rfl

theorem the_regionstatistics_record_deallocation_wrapper_is_its_method (a : memory.region.stats.state.RegionStatistics) (b : Std.U64) :
    regionstatistics_record_deallocation a b = memory.region.stats.record.RegionStatistics.record_deallocation a b := rfl

theorem the_regionstatistics_record_merge_wrapper_is_its_method (a : memory.region.stats.state.RegionStatistics) :
    regionstatistics_record_merge a = memory.region.stats.record.RegionStatistics.record_merge a := rfl

theorem the_regionstatistics_record_split_wrapper_is_its_method (a : memory.region.stats.state.RegionStatistics) :
    regionstatistics_record_split a = memory.region.stats.record.RegionStatistics.record_split a := rfl

theorem the_regionstatistics_add_region_wrapper_is_its_method (a : memory.region.stats.state.RegionStatistics) (b : Std.U64) (c : Bool) :
    regionstatistics_add_region a b c = memory.region.stats.record.RegionStatistics.add_region a b c := rfl

theorem the_regionstatistics_remove_region_wrapper_is_its_method (a : memory.region.stats.state.RegionStatistics) (b : Std.U64) (c : Bool) :
    regionstatistics_remove_region a b c = memory.region.stats.record.RegionStatistics.remove_region a b c := rfl

theorem the_regionstatistics_record_fragmentation_wrapper_is_its_method (a : memory.region.stats.state.RegionStatistics) :
    regionstatistics_record_fragmentation a = memory.region.stats.record.RegionStatistics.record_fragmentation a := rfl

theorem the_regionstatistics_reduce_fragmentation_wrapper_is_its_method (a : memory.region.stats.state.RegionStatistics) :
    regionstatistics_reduce_fragmentation a = memory.region.stats.record.RegionStatistics.reduce_fragmentation a := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.MemoryRegionStatsRecord.the_regionstatistics_record_allocation_wrapper_is_its_method
#print axioms NonosExtraction.MemoryRegionStatsRecord.the_regionstatistics_record_deallocation_wrapper_is_its_method
#print axioms NonosExtraction.MemoryRegionStatsRecord.the_regionstatistics_record_merge_wrapper_is_its_method
#print axioms NonosExtraction.MemoryRegionStatsRecord.the_regionstatistics_record_split_wrapper_is_its_method
#print axioms NonosExtraction.MemoryRegionStatsRecord.the_regionstatistics_add_region_wrapper_is_its_method
#print axioms NonosExtraction.MemoryRegionStatsRecord.the_regionstatistics_remove_region_wrapper_is_its_method
#print axioms NonosExtraction.MemoryRegionStatsRecord.the_regionstatistics_record_fragmentation_wrapper_is_its_method
#print axioms NonosExtraction.MemoryRegionStatsRecord.the_regionstatistics_reduce_fragmentation_wrapper_is_its_method

end NonosExtraction.MemoryRegionStatsRecord
