/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

index_funcs, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.MemoryPagingConstantsIndexFuncs

open Aeneas Aeneas.Std Result
open nonos_x_memory_paging_constants_index_funcs

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.MemoryPagingConstantsIndexFuncs

/-! ### The forwarding functions add nothing -/

theorem the_pml4_index_wrapper_is_its_method (a : Std.U64) :
    pml4_index a = memory.paging.constants.index_funcs.pml4_index a := rfl

theorem the_pdpt_index_wrapper_is_its_method (a : Std.U64) :
    pdpt_index a = memory.paging.constants.index_funcs.pdpt_index a := rfl

theorem the_pd_index_wrapper_is_its_method (a : Std.U64) :
    pd_index a = memory.paging.constants.index_funcs.pd_index a := rfl

theorem the_pt_index_wrapper_is_its_method (a : Std.U64) :
    pt_index a = memory.paging.constants.index_funcs.pt_index a := rfl

theorem the_page_offset_wrapper_is_its_method (a : Std.U64) :
    page_offset a = memory.paging.constants.index_funcs.page_offset a := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.MemoryPagingConstantsIndexFuncs.the_pml4_index_wrapper_is_its_method
#print axioms NonosExtraction.MemoryPagingConstantsIndexFuncs.the_pdpt_index_wrapper_is_its_method
#print axioms NonosExtraction.MemoryPagingConstantsIndexFuncs.the_pd_index_wrapper_is_its_method
#print axioms NonosExtraction.MemoryPagingConstantsIndexFuncs.the_pt_index_wrapper_is_its_method
#print axioms NonosExtraction.MemoryPagingConstantsIndexFuncs.the_page_offset_wrapper_is_its_method

end NonosExtraction.MemoryPagingConstantsIndexFuncs
