/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

header, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.MemoryHeapTypesHeader

open Aeneas Aeneas.Std Result
open nonos_x_memory_heap_types_header

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.MemoryHeapTypesHeader

/-! ### The forwarding functions add nothing -/

theorem the_allocationheader_new_wrapper_is_its_method (a : Std.Usize) (b : Std.U64) :
    allocationheader_new a b = memory.heap.types.header.AllocationHeader.new a b := rfl

theorem the_allocationheader_is_valid_wrapper_is_its_method (a : memory.heap.types.header.AllocationHeader) :
    allocationheader_is_valid a = memory.heap.types.header.AllocationHeader.is_valid a := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.MemoryHeapTypesHeader.the_allocationheader_new_wrapper_is_its_method
#print axioms NonosExtraction.MemoryHeapTypesHeader.the_allocationheader_is_valid_wrapper_is_its_method

end NonosExtraction.MemoryHeapTypesHeader
