-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [nonos_x_memory_paging_types_page_size]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace nonos_x_memory_paging_types_page_size

/-- [nonos_x_memory_paging_types_page_size::memory::paging::types::page_size::PageSize]
    Source: 'src/memory/paging/types/../../../../../../../../src/memory/paging/types/page_size.rs', lines 20:0-24:1
    Visibility: public -/
@[discriminant isize]
inductive memory.paging.types.page_size.PageSize where
| Size4KiB : memory.paging.types.page_size.PageSize
| Size2MiB : memory.paging.types.page_size.PageSize
| Size1GiB : memory.paging.types.page_size.PageSize

/-- [nonos_x_memory_paging_types_page_size::memory::paging::constants::page_sizes::PAGE_SIZE_1G]
    Source: 'src/memory/paging/../../../../../../../src/memory/paging/constants/page_sizes.rs', lines 19:0-19:51
    Visibility: public -/
@[global_simps, irreducible]
def memory.paging.constants.page_sizes.PAGE_SIZE_1G : Result Std.Usize := do
  let i ← 1024#usize * 1024#usize
  i * 1024#usize

/-- [nonos_x_memory_paging_types_page_size::memory::paging::constants::page_sizes::PAGE_SIZE_2M]
    Source: 'src/memory/paging/../../../../../../../src/memory/paging/constants/page_sizes.rs', lines 18:0-18:48
    Visibility: public -/
@[global_simps, irreducible]
def memory.paging.constants.page_sizes.PAGE_SIZE_2M : Result Std.Usize := do
  let i ← 2#usize * 1024#usize
  i * 1024#usize

/-- [nonos_x_memory_paging_types_page_size::memory::paging::constants::page_sizes::PAGE_SIZE_4K]
    Source: 'src/memory/paging/../../../../../../../src/memory/paging/constants/page_sizes.rs', lines 17:0-17:37
    Visibility: public -/
@[global_simps, irreducible]
def memory.paging.constants.page_sizes.PAGE_SIZE_4K : Std.Usize := 4096#usize

/-- [nonos_x_memory_paging_types_page_size::memory::paging::types::page_size::{nonos_x_memory_paging_types_page_size::memory::paging::types::page_size::PageSize}::bytes]:
    Source: 'src/memory/paging/types/../../../../../../../../src/memory/paging/types/page_size.rs', lines 27:4-33:5
    Visibility: public -/
def memory.paging.types.page_size.PageSize.bytes
  (self : memory.paging.types.page_size.PageSize) : Result Std.Usize := do
  match self with
  | memory.paging.types.page_size.PageSize.Size4KiB =>
    ok memory.paging.constants.page_sizes.PAGE_SIZE_4K
  | memory.paging.types.page_size.PageSize.Size2MiB =>
    memory.paging.constants.page_sizes.PAGE_SIZE_2M
  | memory.paging.types.page_size.PageSize.Size1GiB =>
    memory.paging.constants.page_sizes.PAGE_SIZE_1G

/-- [nonos_x_memory_paging_types_page_size::pagesize_bytes]:
    Source: 'src/lib.rs', lines 13:0-15:1
    Visibility: public -/
def pagesize_bytes
  (this : memory.paging.types.page_size.PageSize) : Result Std.Usize := do
  memory.paging.types.page_size.PageSize.bytes this

/-- [nonos_x_memory_paging_types_page_size::memory::paging::types::page_size::{nonos_x_memory_paging_types_page_size::memory::paging::types::page_size::PageSize}::align_mask]:
    Source: 'src/memory/paging/types/../../../../../../../../src/memory/paging/types/page_size.rs', lines 35:4-41:5
    Visibility: public -/
def memory.paging.types.page_size.PageSize.align_mask
  (self : memory.paging.types.page_size.PageSize) : Result Std.U64 := do
  match self with
  | memory.paging.types.page_size.PageSize.Size4KiB => ok 4095#u64
  | memory.paging.types.page_size.PageSize.Size2MiB => ok 2097151#u64
  | memory.paging.types.page_size.PageSize.Size1GiB => ok 1073741823#u64

/-- [nonos_x_memory_paging_types_page_size::pagesize_align_mask]:
    Source: 'src/lib.rs', lines 17:0-19:1
    Visibility: public -/
def pagesize_align_mask
  (this : memory.paging.types.page_size.PageSize) : Result Std.U64 := do
  memory.paging.types.page_size.PageSize.align_mask this

/-- [nonos_x_memory_paging_types_page_size::memory::paging::types::page_size::{nonos_x_memory_paging_types_page_size::memory::paging::types::page_size::PageSize}::is_aligned]:
    Source: 'src/memory/paging/types/../../../../../../../../src/memory/paging/types/page_size.rs', lines 43:4-45:5
    Visibility: public -/
def memory.paging.types.page_size.PageSize.is_aligned
  (self : memory.paging.types.page_size.PageSize) (addr : Std.U64) :
  Result Bool
  := do
  let i ← memory.paging.types.page_size.PageSize.align_mask self
  let i1 ← lift (addr &&& i)
  ok (i1 = 0#u64)

/-- [nonos_x_memory_paging_types_page_size::pagesize_is_aligned]:
    Source: 'src/lib.rs', lines 21:0-23:1
    Visibility: public -/
def pagesize_is_aligned
  (this : memory.paging.types.page_size.PageSize) (addr : Std.U64) :
  Result Bool
  := do
  memory.paging.types.page_size.PageSize.is_aligned this addr

end nonos_x_memory_paging_types_page_size
