/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

record, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.MemoryDmaStatsRecord

open Aeneas Aeneas.Std Result
open nonos_x_memory_dma_stats_record

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.MemoryDmaStatsRecord

/-! ### The forwarding functions add nothing -/

theorem the_dmastats_record_coherent_alloc_wrapper_is_its_method (a : memory.dma.stats.types.DmaStats) (b : Std.Usize) :
    dmastats_record_coherent_alloc a b = memory.dma.stats.record.DmaStats.record_coherent_alloc a b := rfl

theorem the_dmastats_record_coherent_free_wrapper_is_its_method (a : memory.dma.stats.types.DmaStats) (b : Std.Usize) :
    dmastats_record_coherent_free a b = memory.dma.stats.record.DmaStats.record_coherent_free a b := rfl

theorem the_dmastats_record_streaming_map_wrapper_is_its_method (a : memory.dma.stats.types.DmaStats) :
    dmastats_record_streaming_map a = memory.dma.stats.record.DmaStats.record_streaming_map a := rfl

theorem the_dmastats_record_streaming_unmap_wrapper_is_its_method (a : memory.dma.stats.types.DmaStats) :
    dmastats_record_streaming_unmap a = memory.dma.stats.record.DmaStats.record_streaming_unmap a := rfl

theorem the_dmastats_record_bounce_usage_wrapper_is_its_method (a : memory.dma.stats.types.DmaStats) (b : Bool) :
    dmastats_record_bounce_usage a b = memory.dma.stats.record.DmaStats.record_bounce_usage a b := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.MemoryDmaStatsRecord.the_dmastats_record_coherent_alloc_wrapper_is_its_method
#print axioms NonosExtraction.MemoryDmaStatsRecord.the_dmastats_record_coherent_free_wrapper_is_its_method
#print axioms NonosExtraction.MemoryDmaStatsRecord.the_dmastats_record_streaming_map_wrapper_is_its_method
#print axioms NonosExtraction.MemoryDmaStatsRecord.the_dmastats_record_streaming_unmap_wrapper_is_its_method
#print axioms NonosExtraction.MemoryDmaStatsRecord.the_dmastats_record_bounce_usage_wrapper_is_its_method

end NonosExtraction.MemoryDmaStatsRecord
