-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [nonos_x_memory_boot_memory_types_memory_region]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace nonos_x_memory_boot_memory_types_memory_region

/-- [nonos_x_memory_boot_memory_types_memory_region::memory::boot_memory::types::region_type::RegionType]
    Source: 'src/memory/boot_memory/types/../../../../../../../../src/memory/boot_memory/types/region_type.rs', lines 20:0-27:1
    Visibility: public -/
@[discriminant isize]
inductive memory.boot_memory.types.region_type.RegionType where
| Available : memory.boot_memory.types.region_type.RegionType
| Reserved : memory.boot_memory.types.region_type.RegionType
| Kernel : memory.boot_memory.types.region_type.RegionType
| Capsule : memory.boot_memory.types.region_type.RegionType
| Hardware : memory.boot_memory.types.region_type.RegionType
| Defective : memory.boot_memory.types.region_type.RegionType

/-- [nonos_x_memory_boot_memory_types_memory_region::memory::addr::phys::PhysAddr]
    Source: 'src/memory/addr/../../../../../../../src/memory/addr/phys.rs', lines 19:0-19:25
    Visibility: public -/
@[reducible]
def memory.addr.phys.PhysAddr := Std.U64

/-- [nonos_x_memory_boot_memory_types_memory_region::memory::boot_memory::types::memory_region::MemoryRegion]
    Source: 'src/memory/boot_memory/types/../../../../../../../../src/memory/boot_memory/types/memory_region.rs', lines 22:0-27:1
    Visibility: public -/
structure memory.boot_memory.types.memory_region.MemoryRegion where
  start : memory.addr.phys.PhysAddr
  «end» : memory.addr.phys.PhysAddr
  region_type : memory.boot_memory.types.region_type.RegionType
  flags : Std.U32

/-- [nonos_x_memory_boot_memory_types_memory_region::memory::addr::phys::{nonos_x_memory_boot_memory_types_memory_region::memory::addr::phys::PhysAddr}::as_u64]:
    Source: 'src/memory/addr/../../../../../../../src/memory/addr/phys.rs', lines 30:4-32:5
    Visibility: public -/
def memory.addr.phys.PhysAddr.as_u64
  (self : memory.addr.phys.PhysAddr) : Result Std.U64 := do
  ok self

/-- [nonos_x_memory_boot_memory_types_memory_region::memory::boot_memory::types::memory_region::{nonos_x_memory_boot_memory_types_memory_region::memory::boot_memory::types::memory_region::MemoryRegion}::size]:
    Source: 'src/memory/boot_memory/types/../../../../../../../../src/memory/boot_memory/types/memory_region.rs', lines 35:4-41:5
    Visibility: public -/
def memory.boot_memory.types.memory_region.MemoryRegion.size
  (self : memory.boot_memory.types.memory_region.MemoryRegion) :
  Result Std.U64
  := do
  let i ← memory.addr.phys.PhysAddr.as_u64 self.«end»
  let i1 ← memory.addr.phys.PhysAddr.as_u64 self.start
  if i > i1
  then i - i1
  else ok 0#u64

/-- [nonos_x_memory_boot_memory_types_memory_region::memoryregion_size]:
    Source: 'src/lib.rs', lines 11:0-13:1
    Visibility: public -/
def memoryregion_size
  (this : memory.boot_memory.types.memory_region.MemoryRegion) :
  Result Std.U64
  := do
  memory.boot_memory.types.memory_region.MemoryRegion.size this

/-- [nonos_x_memory_boot_memory_types_memory_region::memory::boot_memory::constants::page_sizes::PAGE_SIZE]
    Source: 'src/memory/boot_memory/../../../../../../../src/memory/boot_memory/constants/page_sizes.rs', lines 17:0-17:34
    Visibility: public -/
@[global_simps, irreducible]
def memory.boot_memory.constants.page_sizes.PAGE_SIZE : Std.Usize := 4096#usize

/-- [nonos_x_memory_boot_memory_types_memory_region::memory::boot_memory::constants::page_sizes::PAGE_SIZE_U64]
    Source: 'src/memory/boot_memory/../../../../../../../src/memory/boot_memory/constants/page_sizes.rs', lines 18:0-18:48
    Visibility: public -/
@[global_simps, irreducible]
def memory.boot_memory.constants.page_sizes.PAGE_SIZE_U64 : Result Std.U64 :=
  ok (UScalar.cast .U64 memory.boot_memory.constants.page_sizes.PAGE_SIZE)

/-- [nonos_x_memory_boot_memory_types_memory_region::memory::boot_memory::types::memory_region::{nonos_x_memory_boot_memory_types_memory_region::memory::boot_memory::types::memory_region::MemoryRegion}::page_count]:
    Source: 'src/memory/boot_memory/types/../../../../../../../../src/memory/boot_memory/types/memory_region.rs', lines 44:4-46:5
    Visibility: public -/
def memory.boot_memory.types.memory_region.MemoryRegion.page_count
  (self : memory.boot_memory.types.memory_region.MemoryRegion) :
  Result Std.U64
  := do
  let i ← memory.boot_memory.types.memory_region.MemoryRegion.size self
  let i1 ← memory.boot_memory.constants.page_sizes.PAGE_SIZE_U64
  i / i1

/-- [nonos_x_memory_boot_memory_types_memory_region::memoryregion_page_count]:
    Source: 'src/lib.rs', lines 15:0-17:1
    Visibility: public -/
def memoryregion_page_count
  (this : memory.boot_memory.types.memory_region.MemoryRegion) :
  Result Std.U64
  := do
  memory.boot_memory.types.memory_region.MemoryRegion.page_count this

/-- [nonos_x_memory_boot_memory_types_memory_region::memory::boot_memory::types::region_type::{nonos_x_memory_boot_memory_types_memory_region::memory::boot_memory::types::region_type::RegionType}::is_allocatable]:
    Source: 'src/memory/boot_memory/types/../../../../../../../../src/memory/boot_memory/types/region_type.rs', lines 52:4-54:5
    Visibility: public -/
def memory.boot_memory.types.region_type.RegionType.is_allocatable
  (self : memory.boot_memory.types.region_type.RegionType) : Result Bool := do
  match self with
  | memory.boot_memory.types.region_type.RegionType.Available => ok true
  | memory.boot_memory.types.region_type.RegionType.Reserved => ok false
  | memory.boot_memory.types.region_type.RegionType.Kernel => ok false
  | memory.boot_memory.types.region_type.RegionType.Capsule => ok false
  | memory.boot_memory.types.region_type.RegionType.Hardware => ok false
  | memory.boot_memory.types.region_type.RegionType.Defective => ok false

/-- [nonos_x_memory_boot_memory_types_memory_region::memory::boot_memory::types::memory_region::{nonos_x_memory_boot_memory_types_memory_region::memory::boot_memory::types::memory_region::MemoryRegion}::is_available]:
    Source: 'src/memory/boot_memory/types/../../../../../../../../src/memory/boot_memory/types/memory_region.rs', lines 52:4-54:5
    Visibility: public -/
def memory.boot_memory.types.memory_region.MemoryRegion.is_available
  (self : memory.boot_memory.types.memory_region.MemoryRegion) :
  Result Bool
  := do
  memory.boot_memory.types.region_type.RegionType.is_allocatable
    self.region_type

/-- [nonos_x_memory_boot_memory_types_memory_region::memoryregion_is_available]:
    Source: 'src/lib.rs', lines 19:0-21:1
    Visibility: public -/
def memoryregion_is_available
  (this : memory.boot_memory.types.memory_region.MemoryRegion) :
  Result Bool
  := do
  memory.boot_memory.types.memory_region.MemoryRegion.is_available this

/-- [nonos_x_memory_boot_memory_types_memory_region::memory::boot_memory::types::memory_region::{nonos_x_memory_boot_memory_types_memory_region::memory::boot_memory::types::memory_region::MemoryRegion}::is_empty]:
    Source: 'src/memory/boot_memory/types/../../../../../../../../src/memory/boot_memory/types/memory_region.rs', lines 56:4-58:5
    Visibility: public -/
def memory.boot_memory.types.memory_region.MemoryRegion.is_empty
  (self : memory.boot_memory.types.memory_region.MemoryRegion) :
  Result Bool
  := do
  let i ← memory.addr.phys.PhysAddr.as_u64 self.«end»
  let i1 ← memory.addr.phys.PhysAddr.as_u64 self.start
  ok (i <= i1)

/-- [nonos_x_memory_boot_memory_types_memory_region::memoryregion_is_empty]:
    Source: 'src/lib.rs', lines 23:0-25:1
    Visibility: public -/
def memoryregion_is_empty
  (this : memory.boot_memory.types.memory_region.MemoryRegion) :
  Result Bool
  := do
  memory.boot_memory.types.memory_region.MemoryRegion.is_empty this

/-- [nonos_x_memory_boot_memory_types_memory_region::memory::boot_memory::types::memory_region::{nonos_x_memory_boot_memory_types_memory_region::memory::boot_memory::types::memory_region::MemoryRegion}::has_flag]:
    Source: 'src/memory/boot_memory/types/../../../../../../../../src/memory/boot_memory/types/memory_region.rs', lines 60:4-62:5
    Visibility: public -/
def memory.boot_memory.types.memory_region.MemoryRegion.has_flag
  (self : memory.boot_memory.types.memory_region.MemoryRegion) (flag : Std.U32)
  :
  Result Bool
  := do
  let i ← lift (self.flags &&& flag)
  ok (i != 0#u32)

/-- [nonos_x_memory_boot_memory_types_memory_region::memoryregion_has_flag]:
    Source: 'src/lib.rs', lines 27:0-29:1
    Visibility: public -/
def memoryregion_has_flag
  (this : memory.boot_memory.types.memory_region.MemoryRegion) (flag : Std.U32)
  :
  Result Bool
  := do
  memory.boot_memory.types.memory_region.MemoryRegion.has_flag this flag

end nonos_x_memory_boot_memory_types_memory_region
