/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

query, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.MemoryMmioStatsQuery

open Aeneas Aeneas.Std Result
open nonos_x_memory_mmio_stats_query

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.MemoryMmioStatsQuery

/-! ### The forwarding functions add nothing -/

theorem the_mmiostats_total_regions_wrapper_is_its_method (a : memory.mmio.stats.types.MmioStats) :
    mmiostats_total_regions a = memory.mmio.stats.query.MmioStats.total_regions a := rfl

theorem the_mmiostats_total_mapped_size_wrapper_is_its_method (a : memory.mmio.stats.types.MmioStats) :
    mmiostats_total_mapped_size a = memory.mmio.stats.query.MmioStats.total_mapped_size a := rfl

theorem the_mmiostats_read_operations_wrapper_is_its_method (a : memory.mmio.stats.types.MmioStats) :
    mmiostats_read_operations a = memory.mmio.stats.query.MmioStats.read_operations a := rfl

theorem the_mmiostats_write_operations_wrapper_is_its_method (a : memory.mmio.stats.types.MmioStats) :
    mmiostats_write_operations a = memory.mmio.stats.query.MmioStats.write_operations a := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.MemoryMmioStatsQuery.the_mmiostats_total_regions_wrapper_is_its_method
#print axioms NonosExtraction.MemoryMmioStatsQuery.the_mmiostats_total_mapped_size_wrapper_is_its_method
#print axioms NonosExtraction.MemoryMmioStatsQuery.the_mmiostats_read_operations_wrapper_is_its_method
#print axioms NonosExtraction.MemoryMmioStatsQuery.the_mmiostats_write_operations_wrapper_is_its_method

end NonosExtraction.MemoryMmioStatsQuery
