/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

mode, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.MteMode

open Aeneas Aeneas.Std Result
open nonos_x_mte_mode

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.MteMode

/-! ### The forwarding functions add nothing -/

theorem the_mtemode_tcf_wrapper_is_its_method (a : mode.MteMode) :
    mtemode_tcf a = mode.MteMode.tcf a := rfl

/-! ### What the tag check fault field can hold

    `set_mte_mode` in `security/mte/control.rs` clears the two-bit fields at
    SCTLR_EL1 bits 40..41 (TCF) and 38..39 (TCF0) and ors `tcf() << 40` and
    `tcf() << 38` into them. That is only sound if `tcf` never exceeds two bits: a
    value of four or more would spill out of TCF0 into TCF, or out of TCF into
    bit 42 and above. The theorems below establish that bound, that zero (no tag
    checking) is produced by `Disabled` and by nothing else, and that the four
    modes select four distinct fields. They cannot establish anything about the
    register write itself, which is inline assembly behind a CPU feature test
    and is not extracted.
-/

/-- Every mode fits in the two-bit TCF field, so shifting it to bit 40 or bit 38
    touches only the bits `set_mte_mode` cleared. -/
theorem mtemode_tcf_fits_the_two_bit_field (m : mode.MteMode) :
    ∃ t, mtemode_tcf m = ok t ∧ t.val < 4 := by
  cases m <;> exact ⟨_, rfl, by decide⟩

/-- Tag checking is off exactly for `Disabled`: no enabled mode is silently
    encoded as "tag check faults ignored". -/
theorem mtemode_tcf_is_zero_only_when_disabled (m : mode.MteMode) :
    mtemode_tcf m = ok 0#u64 ↔ m = mode.MteMode.Disabled := by
  cases m <;> simp [mtemode_tcf, mode.MteMode.tcf]

/-- The four modes program four different fields, so asking for one mode never
    yields another's behaviour. -/
theorem mtemode_tcf_tells_every_mode_apart (a b : mode.MteMode)
    (h : mtemode_tcf a = mtemode_tcf b) : a = b := by
  cases a <;> cases b <;> simp_all [mtemode_tcf, mode.MteMode.tcf]

/-! ### Axiom profile -/

#print axioms NonosExtraction.MteMode.the_mtemode_tcf_wrapper_is_its_method

#print axioms NonosExtraction.MteMode.mtemode_tcf_fits_the_two_bit_field
#print axioms NonosExtraction.MteMode.mtemode_tcf_is_zero_only_when_disabled
#print axioms NonosExtraction.MteMode.mtemode_tcf_tells_every_mode_apart

end NonosExtraction.MteMode
