/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

platform_types, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.MultibootPlatformTypes

open Aeneas Aeneas.Std Result
open nonos_x_multiboot_platform_types

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.MultibootPlatformTypes

/-! ### The forwarding functions add nothing -/

theorem the_platform_is_virtual_wrapper_is_its_method (a : platform_types.Platform) :
    platform_is_virtual a = platform_types.Platform.is_virtual a := rfl

theorem the_platform_is_qemu_wrapper_is_its_method (a : platform_types.Platform) :
    platform_is_qemu a = platform_types.Platform.is_qemu a := rfl

theorem the_platform_has_hw_virtualization_wrapper_is_its_method (a : platform_types.Platform) :
    platform_has_hw_virtualization a = platform_types.Platform.has_hw_virtualization a := rfl

theorem the_platform_supports_virtio_wrapper_is_its_method (a : platform_types.Platform) :
    platform_supports_virtio a = platform_types.Platform.supports_virtio a := rfl

theorem the_platform_timer_frequency_wrapper_is_its_method (a : platform_types.Platform) :
    platform_timer_frequency a = platform_types.Platform.timer_frequency a := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.MultibootPlatformTypes.the_platform_is_virtual_wrapper_is_its_method
#print axioms NonosExtraction.MultibootPlatformTypes.the_platform_is_qemu_wrapper_is_its_method
#print axioms NonosExtraction.MultibootPlatformTypes.the_platform_has_hw_virtualization_wrapper_is_its_method
#print axioms NonosExtraction.MultibootPlatformTypes.the_platform_supports_virtio_wrapper_is_its_method
#print axioms NonosExtraction.MultibootPlatformTypes.the_platform_timer_frequency_wrapper_is_its_method

end NonosExtraction.MultibootPlatformTypes
