/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

stats, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.NonosInboxStats

open Aeneas Aeneas.Std Result
open nonos_x_nonos_inbox_stats

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.NonosInboxStats

/-! ### The forwarding functions add nothing -/

theorem the_inboxstats_new_wrapper_is_its_method :
    inboxstats_new = stats.InboxStats.new := rfl

theorem the_inboxstats_record_enqueue_wrapper_is_its_method (a : stats.InboxStats) (b : Std.Usize) :
    inboxstats_record_enqueue a b = stats.InboxStats.record_enqueue a b := rfl

theorem the_inboxstats_record_dequeue_wrapper_is_its_method (a : stats.InboxStats) :
    inboxstats_record_dequeue a = stats.InboxStats.record_dequeue a := rfl

theorem the_inboxstats_record_dropped_wrapper_is_its_method (a : stats.InboxStats) :
    inboxstats_record_dropped a = stats.InboxStats.record_dropped a := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.NonosInboxStats.the_inboxstats_new_wrapper_is_its_method
#print axioms NonosExtraction.NonosInboxStats.the_inboxstats_record_enqueue_wrapper_is_its_method
#print axioms NonosExtraction.NonosInboxStats.the_inboxstats_record_dequeue_wrapper_is_its_method
#print axioms NonosExtraction.NonosInboxStats.the_inboxstats_record_dropped_wrapper_is_its_method

end NonosExtraction.NonosInboxStats
