/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

policy, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.ObservabilityPolicy

open Aeneas Aeneas.Std Result
open nonos_x_observability_policy

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.ObservabilityPolicy

/-! ### The forwarding functions add nothing -/

theorem the_is_production_mode_wrapper_is_its_method :
    is_production_mode = policy.is_production_mode := rfl

theorem the_set_production_mode_wrapper_is_its_method (a : Bool) :
    set_production_mode a = policy.set_production_mode a := rfl

theorem the_should_log_debug_wrapper_is_its_method :
    should_log_debug = policy.should_log_debug := rfl

theorem the_should_emit_serial_wrapper_is_its_method :
    should_emit_serial = policy.should_emit_serial := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.ObservabilityPolicy.the_is_production_mode_wrapper_is_its_method
#print axioms NonosExtraction.ObservabilityPolicy.the_set_production_mode_wrapper_is_its_method
#print axioms NonosExtraction.ObservabilityPolicy.the_should_log_debug_wrapper_is_its_method
#print axioms NonosExtraction.ObservabilityPolicy.the_should_emit_serial_wrapper_is_its_method

end NonosExtraction.ObservabilityPolicy
