/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

flags, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.PagingTypesPermissionsFlags

open Aeneas Aeneas.Std Result
open nonos_x_paging_types_permissions_flags

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.PagingTypesPermissionsFlags

/-! ### The forwarding functions add nothing -/

theorem the_pagepermissions_empty_wrapper_is_its_method :
    pagepermissions_empty = memory.paging.types.permissions.flags.PagePermissions.empty := rfl

theorem the_pagepermissions_from_bits_wrapper_is_its_method (a : Std.U32) :
    pagepermissions_from_bits a = memory.paging.types.permissions.flags.PagePermissions.from_bits a := rfl

theorem the_pagepermissions_bits_wrapper_is_its_method (a : memory.paging.types.permissions.flags.PagePermissions) :
    pagepermissions_bits a = memory.paging.types.permissions.flags.PagePermissions.impl.bits a := rfl

theorem the_pagepermissions_contains_wrapper_is_its_method (a : memory.paging.types.permissions.flags.PagePermissions) (b : memory.paging.types.permissions.flags.PagePermissions) :
    pagepermissions_contains a b = memory.paging.types.permissions.flags.PagePermissions.contains a b := rfl

theorem the_pagepermissions_union_wrapper_is_its_method (a : memory.paging.types.permissions.flags.PagePermissions) (b : memory.paging.types.permissions.flags.PagePermissions) :
    pagepermissions_union a b = memory.paging.types.permissions.flags.PagePermissions.union a b := rfl

theorem the_pagepermissions_remove_wrapper_is_its_method (a : memory.paging.types.permissions.flags.PagePermissions) (b : memory.paging.types.permissions.flags.PagePermissions) :
    pagepermissions_remove a b = memory.paging.types.permissions.flags.PagePermissions.remove a b := rfl

theorem the_pagepermissions_insert_wrapper_is_its_method (a : memory.paging.types.permissions.flags.PagePermissions) (b : memory.paging.types.permissions.flags.PagePermissions) :
    pagepermissions_insert a b = memory.paging.types.permissions.flags.PagePermissions.insert a b := rfl

theorem the_pagepermissions_is_wx_violation_wrapper_is_its_method (a : memory.paging.types.permissions.flags.PagePermissions) :
    pagepermissions_is_wx_violation a = memory.paging.types.permissions.flags.PagePermissions.is_wx_violation a := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.PagingTypesPermissionsFlags.the_pagepermissions_empty_wrapper_is_its_method
#print axioms NonosExtraction.PagingTypesPermissionsFlags.the_pagepermissions_from_bits_wrapper_is_its_method
#print axioms NonosExtraction.PagingTypesPermissionsFlags.the_pagepermissions_bits_wrapper_is_its_method
#print axioms NonosExtraction.PagingTypesPermissionsFlags.the_pagepermissions_contains_wrapper_is_its_method
#print axioms NonosExtraction.PagingTypesPermissionsFlags.the_pagepermissions_union_wrapper_is_its_method
#print axioms NonosExtraction.PagingTypesPermissionsFlags.the_pagepermissions_remove_wrapper_is_its_method
#print axioms NonosExtraction.PagingTypesPermissionsFlags.the_pagepermissions_insert_wrapper_is_its_method
#print axioms NonosExtraction.PagingTypesPermissionsFlags.the_pagepermissions_is_wx_violation_wrapper_is_its_method

end NonosExtraction.PagingTypesPermissionsFlags
