-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [nonos_x_paging_types_permissions_flags]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace nonos_x_paging_types_permissions_flags

/-- [nonos_x_paging_types_permissions_flags::memory::paging::types::permissions::flags::PagePermissions]
    Source: 'src/memory/paging/types/permissions/../../../../../../../../../src/memory/paging/types/permissions/flags.rs', lines 20:0-22:1
    Visibility: public -/
structure memory.paging.types.permissions.flags.PagePermissions where
  bits : Std.U32

/-- [nonos_x_paging_types_permissions_flags::memory::paging::types::permissions::flags::{nonos_x_paging_types_permissions_flags::memory::paging::types::permissions::flags::PagePermissions}::empty]:
    Source: 'src/memory/paging/types/permissions/../../../../../../../../../src/memory/paging/types/permissions/flags.rs', lines 39:4-41:5
    Visibility: public -/
def memory.paging.types.permissions.flags.PagePermissions.empty
  : Result memory.paging.types.permissions.flags.PagePermissions := do
  ok { bits := 0#u32 }

/-- [nonos_x_paging_types_permissions_flags::pagepermissions_empty]:
    Source: 'src/lib.rs', lines 13:0-15:1
    Visibility: public -/
def pagepermissions_empty
  : Result memory.paging.types.permissions.flags.PagePermissions := do
  memory.paging.types.permissions.flags.PagePermissions.empty

/-- [nonos_x_paging_types_permissions_flags::memory::paging::types::permissions::flags::{nonos_x_paging_types_permissions_flags::memory::paging::types::permissions::flags::PagePermissions}::from_bits]:
    Source: 'src/memory/paging/types/permissions/../../../../../../../../../src/memory/paging/types/permissions/flags.rs', lines 42:4-44:5
    Visibility: public -/
def memory.paging.types.permissions.flags.PagePermissions.from_bits
  (bits : Std.U32) :
  Result memory.paging.types.permissions.flags.PagePermissions
  := do
  ok { bits }

/-- [nonos_x_paging_types_permissions_flags::pagepermissions_from_bits]:
    Source: 'src/lib.rs', lines 17:0-19:1
    Visibility: public -/
def pagepermissions_from_bits
  (bits : Std.U32) :
  Result memory.paging.types.permissions.flags.PagePermissions
  := do
  memory.paging.types.permissions.flags.PagePermissions.from_bits bits

/-- [nonos_x_paging_types_permissions_flags::memory::paging::types::permissions::flags::{nonos_x_paging_types_permissions_flags::memory::paging::types::permissions::flags::PagePermissions}::bits]:
    Source: 'src/memory/paging/types/permissions/../../../../../../../../../src/memory/paging/types/permissions/flags.rs', lines 45:4-47:5
    Visibility: public -/
def memory.paging.types.permissions.flags.PagePermissions.impl.bits
  (self : memory.paging.types.permissions.flags.PagePermissions) :
  Result Std.U32
  := do
  ok self.bits

/-- [nonos_x_paging_types_permissions_flags::pagepermissions_bits]:
    Source: 'src/lib.rs', lines 21:0-23:1
    Visibility: public -/
def pagepermissions_bits
  (this : memory.paging.types.permissions.flags.PagePermissions) :
  Result Std.U32
  := do
  memory.paging.types.permissions.flags.PagePermissions.impl.bits this

/-- [nonos_x_paging_types_permissions_flags::memory::paging::types::permissions::flags::{nonos_x_paging_types_permissions_flags::memory::paging::types::permissions::flags::PagePermissions}::contains]:
    Source: 'src/memory/paging/types/permissions/../../../../../../../../../src/memory/paging/types/permissions/flags.rs', lines 48:4-50:5
    Visibility: public -/
def memory.paging.types.permissions.flags.PagePermissions.contains
  (self : memory.paging.types.permissions.flags.PagePermissions)
  (other : memory.paging.types.permissions.flags.PagePermissions) :
  Result Bool
  := do
  let i ← lift (self.bits &&& other.bits)
  ok (i = other.bits)

/-- [nonos_x_paging_types_permissions_flags::pagepermissions_contains]:
    Source: 'src/lib.rs', lines 25:0-27:1
    Visibility: public -/
def pagepermissions_contains
  (this : memory.paging.types.permissions.flags.PagePermissions)
  (other : memory.paging.types.permissions.flags.PagePermissions) :
  Result Bool
  := do
  memory.paging.types.permissions.flags.PagePermissions.contains this other

/-- [nonos_x_paging_types_permissions_flags::memory::paging::types::permissions::flags::{nonos_x_paging_types_permissions_flags::memory::paging::types::permissions::flags::PagePermissions}::union]:
    Source: 'src/memory/paging/types/permissions/../../../../../../../../../src/memory/paging/types/permissions/flags.rs', lines 51:4-53:5
    Visibility: public -/
def memory.paging.types.permissions.flags.PagePermissions.union
  (self : memory.paging.types.permissions.flags.PagePermissions)
  (other : memory.paging.types.permissions.flags.PagePermissions) :
  Result memory.paging.types.permissions.flags.PagePermissions
  := do
  let i ← lift (self.bits ||| other.bits)
  ok { bits := i }

/-- [nonos_x_paging_types_permissions_flags::pagepermissions_union]:
    Source: 'src/lib.rs', lines 29:0-31:1
    Visibility: public -/
def pagepermissions_union
  (this : memory.paging.types.permissions.flags.PagePermissions)
  (other : memory.paging.types.permissions.flags.PagePermissions) :
  Result memory.paging.types.permissions.flags.PagePermissions
  := do
  memory.paging.types.permissions.flags.PagePermissions.union this other

/-- [nonos_x_paging_types_permissions_flags::memory::paging::types::permissions::flags::{nonos_x_paging_types_permissions_flags::memory::paging::types::permissions::flags::PagePermissions}::remove]:
    Source: 'src/memory/paging/types/permissions/../../../../../../../../../src/memory/paging/types/permissions/flags.rs', lines 54:4-56:5
    Visibility: public -/
def memory.paging.types.permissions.flags.PagePermissions.remove
  (self : memory.paging.types.permissions.flags.PagePermissions)
  (other : memory.paging.types.permissions.flags.PagePermissions) :
  Result memory.paging.types.permissions.flags.PagePermissions
  := do
  let i ← lift (~~~ other.bits)
  let i1 ← lift (self.bits &&& i)
  ok { bits := i1 }

/-- [nonos_x_paging_types_permissions_flags::pagepermissions_remove]:
    Source: 'src/lib.rs', lines 33:0-35:1
    Visibility: public -/
def pagepermissions_remove
  (this : memory.paging.types.permissions.flags.PagePermissions)
  (other : memory.paging.types.permissions.flags.PagePermissions) :
  Result memory.paging.types.permissions.flags.PagePermissions
  := do
  memory.paging.types.permissions.flags.PagePermissions.remove this other

/-- [nonos_x_paging_types_permissions_flags::memory::paging::types::permissions::flags::{nonos_x_paging_types_permissions_flags::memory::paging::types::permissions::flags::PagePermissions}::insert]:
    Source: 'src/memory/paging/types/permissions/../../../../../../../../../src/memory/paging/types/permissions/flags.rs', lines 57:4-59:5
    Visibility: public -/
def memory.paging.types.permissions.flags.PagePermissions.insert
  (self : memory.paging.types.permissions.flags.PagePermissions)
  (other : memory.paging.types.permissions.flags.PagePermissions) :
  Result memory.paging.types.permissions.flags.PagePermissions
  := do
  memory.paging.types.permissions.flags.PagePermissions.union self other

/-- [nonos_x_paging_types_permissions_flags::pagepermissions_insert]:
    Source: 'src/lib.rs', lines 37:0-39:1
    Visibility: public -/
def pagepermissions_insert
  (this : memory.paging.types.permissions.flags.PagePermissions)
  (other : memory.paging.types.permissions.flags.PagePermissions) :
  Result memory.paging.types.permissions.flags.PagePermissions
  := do
  memory.paging.types.permissions.flags.PagePermissions.insert this other

/-- [nonos_x_paging_types_permissions_flags::memory::paging::constants::permissions::PERM_EXECUTE]
    Source: 'src/memory/paging/../../../../../../../src/memory/paging/constants/permissions.rs', lines 19:0-19:37
    Visibility: public -/
@[global_simps, irreducible]
def memory.paging.constants.permissions.PERM_EXECUTE : Result Std.U32 :=
  1#u32 <<< 2#i32

/-- [nonos_x_paging_types_permissions_flags::memory::paging::types::permissions::flags::{nonos_x_paging_types_permissions_flags::memory::paging::types::permissions::flags::PagePermissions}::EXECUTE]
    Source: 'src/memory/paging/types/permissions/../../../../../../../../../src/memory/paging/types/permissions/flags.rs', lines 27:4-27:58
    Visibility: public -/
@[global_simps, irreducible]
def memory.paging.types.permissions.flags.PagePermissions.EXECUTE
  : Result memory.paging.types.permissions.flags.PagePermissions := do
  let i ← memory.paging.constants.permissions.PERM_EXECUTE
  ok { bits := i }

/-- [nonos_x_paging_types_permissions_flags::memory::paging::constants::permissions::PERM_WRITE]
    Source: 'src/memory/paging/../../../../../../../src/memory/paging/constants/permissions.rs', lines 18:0-18:35
    Visibility: public -/
@[global_simps, irreducible]
def memory.paging.constants.permissions.PERM_WRITE : Result Std.U32 :=
  1#u32 <<< 1#i32

/-- [nonos_x_paging_types_permissions_flags::memory::paging::types::permissions::flags::{nonos_x_paging_types_permissions_flags::memory::paging::types::permissions::flags::PagePermissions}::WRITE]
    Source: 'src/memory/paging/types/permissions/../../../../../../../../../src/memory/paging/types/permissions/flags.rs', lines 26:4-26:54
    Visibility: public -/
@[global_simps, irreducible]
def memory.paging.types.permissions.flags.PagePermissions.WRITE
  : Result memory.paging.types.permissions.flags.PagePermissions := do
  let i ← memory.paging.constants.permissions.PERM_WRITE
  ok { bits := i }

/-- [nonos_x_paging_types_permissions_flags::memory::paging::types::permissions::flags::{nonos_x_paging_types_permissions_flags::memory::paging::types::permissions::flags::PagePermissions}::is_wx_violation]:
    Source: 'src/memory/paging/types/permissions/../../../../../../../../../src/memory/paging/types/permissions/flags.rs', lines 60:4-62:5
    Visibility: public -/
def memory.paging.types.permissions.flags.PagePermissions.is_wx_violation
  (self : memory.paging.types.permissions.flags.PagePermissions) :
  Result Bool
  := do
  let pp ← memory.paging.types.permissions.flags.PagePermissions.WRITE
  let b ←
    memory.paging.types.permissions.flags.PagePermissions.contains self pp
  if b
  then
    let pp1 ← memory.paging.types.permissions.flags.PagePermissions.EXECUTE
    memory.paging.types.permissions.flags.PagePermissions.contains self pp1
  else ok false

/-- [nonos_x_paging_types_permissions_flags::pagepermissions_is_wx_violation]:
    Source: 'src/lib.rs', lines 41:0-43:1
    Visibility: public -/
def pagepermissions_is_wx_violation
  (this : memory.paging.types.permissions.flags.PagePermissions) :
  Result Bool
  := do
  memory.paging.types.permissions.flags.PagePermissions.is_wx_violation this

end nonos_x_paging_types_permissions_flags
