/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

types, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.PciTypes

open Aeneas Aeneas.Std Result
open nonos_x_pci_types

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.PciTypes

/-! ### The forwarding functions add nothing -/

theorem the_pcidevice_bdf_wrapper_is_its_method (a : types.PciDevice) :
    pcidevice_bdf a = types.PciDevice.bdf a := rfl

theorem the_pcidevice_is_bridge_wrapper_is_its_method (a : types.PciDevice) :
    pcidevice_is_bridge a = types.PciDevice.is_bridge a := rfl

theorem the_pcidevice_is_storage_wrapper_is_its_method (a : types.PciDevice) :
    pcidevice_is_storage a = types.PciDevice.is_storage a := rfl

theorem the_pcidevice_is_network_wrapper_is_its_method (a : types.PciDevice) :
    pcidevice_is_network a = types.PciDevice.is_network a := rfl

theorem the_pcidevice_is_display_wrapper_is_its_method (a : types.PciDevice) :
    pcidevice_is_display a = types.PciDevice.is_display a := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.PciTypes.the_pcidevice_bdf_wrapper_is_its_method
#print axioms NonosExtraction.PciTypes.the_pcidevice_is_bridge_wrapper_is_its_method
#print axioms NonosExtraction.PciTypes.the_pcidevice_is_storage_wrapper_is_its_method
#print axioms NonosExtraction.PciTypes.the_pcidevice_is_network_wrapper_is_its_method
#print axioms NonosExtraction.PciTypes.the_pcidevice_is_display_wrapper_is_its_method

end NonosExtraction.PciTypes
