-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [nonos_x_pio_types]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace nonos_x_pio_types

/-- [nonos_x_pio_types::types::PioWidth]
    Source: 'src/../../../../../src/hardware/broker/pio/types.rs', lines 39:0-43:1
    Visibility: public -/
@[discriminant u8 [1,2,4]]
inductive types.PioWidth where
| U8 : types.PioWidth
| U16 : types.PioWidth
| U32 : types.PioWidth

/-- [nonos_x_pio_types::types::{nonos_x_pio_types::types::PioWidth}::bytes]:
    Source: 'src/../../../../../src/hardware/broker/pio/types.rs', lines 55:4-57:5
    Visibility: public -/
def types.PioWidth.bytes (self : types.PioWidth) : Result Std.U16 := do
  let self1 := read_discriminant self
  ok (UScalar.cast .U16 self1)

/-- [nonos_x_pio_types::piowidth_bytes]:
    Source: 'src/lib.rs', lines 10:0-12:1
    Visibility: public -/
def piowidth_bytes (this : types.PioWidth) : Result Std.U16 := do
  types.PioWidth.bytes this

end nonos_x_pio_types
