/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

types, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.PipeTypes

open Aeneas Aeneas.Std Result
open nonos_x_pipe_types

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.PipeTypes

/-! ### The forwarding functions add nothing -/

theorem the_pipe_new_wrapper_is_its_method (a : Std.U32) (b : Std.Usize) :
    pipe_new a b = types.Pipe.new a b := rfl

theorem the_pipe_pipe_id_wrapper_is_its_method (a : types.Pipe) :
    pipe_pipe_id a = types.Pipe.pipe_id a := rfl

theorem the_pipe_is_broken_wrapper_is_its_method (a : types.Pipe) :
    pipe_is_broken a = types.Pipe.is_broken a := rfl

theorem the_pipe_space_available_wrapper_is_its_method (a : types.Pipe) :
    pipe_space_available a = types.Pipe.space_available a := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.PipeTypes.the_pipe_new_wrapper_is_its_method
#print axioms NonosExtraction.PipeTypes.the_pipe_pipe_id_wrapper_is_its_method
#print axioms NonosExtraction.PipeTypes.the_pipe_is_broken_wrapper_is_its_method
#print axioms NonosExtraction.PipeTypes.the_pipe_space_available_wrapper_is_its_method

end NonosExtraction.PipeTypes
