/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

buffer, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.PipeBuffer

open Aeneas Aeneas.Std Result
open nonos_x_pipe_buffer

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.PipeBuffer

/-! ### The forwarding functions add nothing -/

theorem the_pipebuffer_new_wrapper_is_its_method :
    pipebuffer_new = buffer.PipeBuffer.new := rfl

theorem the_pipebuffer_len_wrapper_is_its_method (a : buffer.PipeBuffer) :
    pipebuffer_len a = buffer.PipeBuffer.len a := rfl

theorem the_pipebuffer_is_empty_wrapper_is_its_method (a : buffer.PipeBuffer) :
    pipebuffer_is_empty a = buffer.PipeBuffer.is_empty a := rfl

theorem the_pipebuffer_available_write_wrapper_is_its_method (a : buffer.PipeBuffer) :
    pipebuffer_available_write a = buffer.PipeBuffer.available_write a := rfl

theorem the_pipebuffer_add_reader_wrapper_is_its_method (a : buffer.PipeBuffer) :
    pipebuffer_add_reader a = buffer.PipeBuffer.add_reader a := rfl

theorem the_pipebuffer_remove_reader_wrapper_is_its_method (a : buffer.PipeBuffer) :
    pipebuffer_remove_reader a = buffer.PipeBuffer.remove_reader a := rfl

theorem the_pipebuffer_add_writer_wrapper_is_its_method (a : buffer.PipeBuffer) :
    pipebuffer_add_writer a = buffer.PipeBuffer.add_writer a := rfl

theorem the_pipebuffer_remove_writer_wrapper_is_its_method (a : buffer.PipeBuffer) :
    pipebuffer_remove_writer a = buffer.PipeBuffer.remove_writer a := rfl

theorem the_pipebuffer_has_readers_wrapper_is_its_method (a : buffer.PipeBuffer) :
    pipebuffer_has_readers a = buffer.PipeBuffer.has_readers a := rfl

theorem the_pipebuffer_has_writers_wrapper_is_its_method (a : buffer.PipeBuffer) :
    pipebuffer_has_writers a = buffer.PipeBuffer.has_writers a := rfl


/-! ### The ring arithmetic

    A pipe keeps one slot empty so that a full buffer and an empty one are
    distinguishable, and every question about occupancy is derived from `head`,
    `tail` and `capacity`.

    `len` and `available_write` are extracted. `read` and `write` are not, since
    they take slices and mutate them, but `write` computes the space it has
    inline rather than calling `available_write`. That is two copies of one rule
    living in one file, and the first theorem below is the obligation they owe
    each other.

    The atomics are opaque to the translation, so the loads below are not
    reduced. That costs nothing here: every property in this section is about the
    arithmetic applied to whatever the loads returned.
-/

/-- `available_write` is `capacity - len - 1` by construction. Written out so the
    second copy has something to be compared against. -/
theorem available_is_capacity_less_length_less_one (b : buffer.PipeBuffer) :
    pipebuffer_available_write b =
      (do let l ← buffer.PipeBuffer.len b
          let i ← b.capacity - l
          i - 1#usize) := rfl

/-- The obligation the two copies owe each other, as plain arithmetic on the
    quantities both of them read.

    `write` computes `capacity - head + tail - 1` when head is at or above tail
    and `tail - head - 1` otherwise. `available_write` computes
    `capacity - len - 1`, where `len` is `head - tail` in the first case and
    `capacity - tail + head` in the second. They agree, in both directions, and
    this is why. -/
theorem the_inline_copy_agrees_with_the_function
    (cap head tail : Nat) (ht : tail ≤ cap) (hh : head ≤ cap) :
    (tail ≤ head → cap - head + tail - 1 = cap - (head - tail) - 1) ∧
    (head < tail → tail - head - 1 = cap - (cap - tail + head) - 1) := by
  refine ⟨?_, ?_⟩ <;> intro h <;> omega

/-- A buffer that reports itself completely full does not get told it has no
    room, it halts. `available_write` is `capacity - len - 1`, so at
    `len = capacity` the first subtraction gives zero and the second underflows,
    and this kernel builds with overflow checks and panic equal to abort.

    Shown at the shipped capacity, which is the value `new` installs. The
    reserved slot is what normally keeps `len` below `capacity`, so reaching this
    needs `head`, `tail` or `capacity` to have been set outside the ring
    discipline. All three are `pub` on the struct. -/
theorem a_full_buffer_halts_rather_than_reporting_no_room :
    (do let i ← (65536#usize) - (65536#usize); i - 1#usize)
      = fail Error.integerOverflow := by rfl

/-- Emptiness is exactly a length of zero, so the two questions a caller can ask
    about an idle pipe cannot disagree. -/
theorem emptiness_is_a_length_of_zero (b : buffer.PipeBuffer) :
    pipebuffer_is_empty b =
      (do let l ← buffer.PipeBuffer.len b; ok (decide (l = 0#usize))) := rfl

/-- The capacity a fresh pipe is built with. Sixty four kilobytes, which is the
    figure `PIPE_BUF_SIZE` names and the one every occupancy answer is relative
    to. -/
theorem the_pipe_is_sixty_four_kilobytes :
    buffer.PIPE_BUF_SIZE = 65536#usize := by
  unfold buffer.PIPE_BUF_SIZE; rfl

/-! ### Occupancy, a fresh pipe, and the endpoint counters

    `len` is proven to be the ring distance from `tail` to `head` whenever both
    lie inside the ring: it cannot overflow, it stays strictly below
    `capacity`, advancing `tail` by it lands on `head` (the step `read` takes
    when it drains everything), and it agrees with `available_write` in the
    sense that the two, plus the reserved slot, add up to `capacity`.

    `new` is proven to back the ring with exactly `capacity` zero bytes, so
    every index `(head + i) % capacity` that `read` and `write` compute is in
    bounds, and to start `head` and `tail` from one value, so a fresh pipe is
    empty whatever that value reads as.

    The reader and writer counters are atomics, and Aeneas leaves every atomic
    operation opaque. What can be established is which cell each operation
    touches, by how much, with which ordering, and how a load is turned into a
    yes or no. What cannot be established here is the value a counter holds
    after a sequence of operations: that a fresh pipe starts with one reader and
    one writer, that `fetch_sub` wraps at zero, and anything about concurrent
    interleavings all live inside the opaque atomics. The callers in
    `src/fs/pipe` (`PipeReader`, `PipeWriter`, `pipe_read`, `pipe_write`,
    `sys_pipe2`) are not extracted either.
-/

/-- Inside the ring discipline, `len` is the distance from `tail` forward to
    `head`. It returns without overflow, it is strictly below `capacity`, adding
    it to `tail` gives `head` either directly or after one wrap, and it and
    `available_write` together with the one reserved slot account for the whole
    capacity. The last clause is the agreement between the two extracted
    occupancy functions. -/
theorem pipebuffer_len_is_the_ring_distance_and_complements_available_write
    (b : buffer.PipeBuffer) (h t : Std.Usize)
    (hh : core.sync.atomic.AtomicUsizeAlign8Usize.load b.head .SeqCst = ok h)
    (ht : core.sync.atomic.AtomicUsizeAlign8Usize.load b.tail .SeqCst = ok t)
    (hhc : h.val < b.capacity.val) (htc : t.val < b.capacity.val) :
    ∃ l a, pipebuffer_len b = ok l ∧ pipebuffer_available_write b = ok a ∧
      l.val < b.capacity.val ∧
      (t.val + l.val = h.val ∨ t.val + l.val = h.val + b.capacity.val) ∧
      l.val + a.val + 1 = b.capacity.val := by
  unfold pipebuffer_len pipebuffer_available_write buffer.PipeBuffer.available_write
    buffer.PipeBuffer.len
  simp only [hh, ht, bind_tc_ok]
  split
  · have ⟨l, hl, hlv⟩ := WP.spec_imp_exists
      (Usize.sub_spec (x := h) (y := t) (by scalar_tac))
    simp only [hl, bind_tc_ok]
    have ⟨i, hi, hiv⟩ := WP.spec_imp_exists
      (Usize.sub_spec (x := b.capacity) (y := l) (by scalar_tac))
    simp only [hi, bind_tc_ok]
    have ⟨a, ha, hav⟩ := WP.spec_imp_exists
      (Usize.sub_spec (x := i) (y := 1#usize) (by scalar_tac))
    refine ⟨l, a, rfl, ha, ?_, ?_, ?_⟩ <;> scalar_tac
  · have ⟨j, hj, hjv⟩ := WP.spec_imp_exists
      (Usize.sub_spec (x := b.capacity) (y := t) (by scalar_tac))
    simp only [hj, bind_tc_ok]
    have ⟨l, hl, hlv⟩ := WP.spec_imp_exists
      (Usize.add_spec (x := j) (y := h) (by scalar_tac))
    simp only [hl, bind_tc_ok]
    have ⟨i, hi, hiv⟩ := WP.spec_imp_exists
      (Usize.sub_spec (x := b.capacity) (y := l) (by scalar_tac))
    simp only [hi, bind_tc_ok]
    have ⟨a, ha, hav⟩ := WP.spec_imp_exists
      (Usize.sub_spec (x := i) (y := 1#usize) (by scalar_tac))
    refine ⟨l, a, rfl, ha, ?_, ?_, ?_⟩ <;> scalar_tac

/-- A pipe that `new` returns has a capacity of sixty four kilobytes, a backing
    vector of exactly that many bytes, all of them zero, so no index reduced
    modulo `capacity` falls outside it and no stale data is readable. Its `head`
    and `tail` are the same cell, and its reader and writer counters are built
    from the same initial value. -/
theorem pipebuffer_new_builds_a_zeroed_ring_of_its_own_capacity
    (b : buffer.PipeBuffer) (hb : pipebuffer_new = ok b) :
    b.capacity.val = 65536 ∧ b.data.length = b.capacity.val ∧
    b.data.val = List.replicate 65536 0#u8 ∧ b.head = b.tail ∧
    b.readers = b.writers := by
  unfold pipebuffer_new buffer.PipeBuffer.new at hb
  have ⟨v, hv, hvl, hvlen⟩ := WP.spec_imp_exists
    (alloc.vec.from_elem_spec core.clone.CloneU8 0#u8 buffer.PIPE_BUF_SIZE (by rfl))
  have hc : buffer.PIPE_BUF_SIZE = 65536#usize := by unfold buffer.PIPE_BUF_SIZE; rfl
  rw [hv] at hb
  simp only [bind_tc_ok] at hb
  cases h0 : core.sync.atomic.AtomicUsizeAlign8Usize.new 0#usize <;> rw [h0] at hb <;>
    simp only [bind_tc_ok, bind_tc_fail, bind_tc_div, reduceCtorEq] at hb
  cases h1 : core.sync.atomic.AtomicUsizeAlign8Usize.new 1#usize <;> rw [h1] at hb <;>
    simp only [bind_tc_ok, bind_tc_fail, bind_tc_div, reduceCtorEq] at hb
  cases hb
  rw [hc] at hvl hvlen
  exact ⟨by rw [hc]; rfl, by rw [hc]; exact hvlen, hvl, rfl, rfl⟩

/-- A fresh pipe is empty: whatever its shared `head` and `tail` cell loads as,
    `len` answers zero. -/
theorem pipebuffer_new_is_empty_by_pipebuffer_len
    (b : buffer.PipeBuffer) (hb : pipebuffer_new = ok b) (x : Std.Usize)
    (hx : core.sync.atomic.AtomicUsizeAlign8Usize.load b.head .SeqCst = ok x) :
    pipebuffer_len b = ok 0#usize := by
  have ⟨_, _, _, hht, _⟩ := pipebuffer_new_builds_a_zeroed_ring_of_its_own_capacity b hb
  have ht : core.sync.atomic.AtomicUsizeAlign8Usize.load b.tail .SeqCst = ok x := by
    rw [← hht]; exact hx
  unfold pipebuffer_len buffer.PipeBuffer.len
  simp only [hx, ht, bind_tc_ok, ge_iff_le, le_refl, ↓reduceIte]
  have ⟨l, hl, hlv⟩ := WP.spec_imp_exists (Usize.sub_spec (x := x) (y := x) (by scalar_tac))
  rw [hl]
  congr 1
  apply UScalar.eq_of_val_eq
  scalar_tac

/-- `has_readers` is exactly "the reader count is not zero". A single remaining
    reader counts: `pipe_write` keeps a blocked writer waiting while this holds,
    and `PipeWriter::poll` raises its error bit when it does not. -/
theorem pipebuffer_has_readers_is_the_reader_count_being_nonzero
    (b : buffer.PipeBuffer) (n : Std.Usize)
    (h : core.sync.atomic.AtomicUsizeAlign8Usize.load b.readers .SeqCst = ok n) :
    pipebuffer_has_readers b = ok (decide (n.val ≠ 0)) := by
  unfold pipebuffer_has_readers buffer.PipeBuffer.has_readers
  simp only [h, bind_tc_ok]
  congr 1
  apply decide_eq_decide.mpr
  constructor <;> intro _ <;> scalar_tac

/-- `has_writers` is exactly "the writer count is not zero". `pipe_read` treats a
    false answer on an empty pipe as end of file and a true one as a reason to
    wait. -/
theorem pipebuffer_has_writers_is_the_writer_count_being_nonzero
    (b : buffer.PipeBuffer) (n : Std.Usize)
    (h : core.sync.atomic.AtomicUsizeAlign8Usize.load b.writers .SeqCst = ok n) :
    pipebuffer_has_writers b = ok (decide (n.val ≠ 0)) := by
  unfold pipebuffer_has_writers buffer.PipeBuffer.has_writers
  simp only [h, bind_tc_ok]
  congr 1
  apply decide_eq_decide.mpr
  constructor <;> intro _ <;> scalar_tac

/-- Every reader operation depends on the reader counter alone: two buffers that
    share it give the same answer to `add_reader`, `remove_reader` and
    `has_readers`, whatever their writers, ring positions or data. So no reader
    operation touches the writer counter. -/
theorem reader_operations_read_only_the_reader_count
    (b b' : buffer.PipeBuffer) (h : b.readers = b'.readers) :
    pipebuffer_add_reader b = pipebuffer_add_reader b' ∧
    pipebuffer_remove_reader b = pipebuffer_remove_reader b' ∧
    pipebuffer_has_readers b = pipebuffer_has_readers b' := by
  simp only [pipebuffer_add_reader, buffer.PipeBuffer.add_reader,
    pipebuffer_remove_reader, buffer.PipeBuffer.remove_reader,
    pipebuffer_has_readers, buffer.PipeBuffer.has_readers, h, and_self]

/-- Every writer operation depends on the writer counter alone, the dual of the
    reader statement. Together they say the two counters are never confused. -/
theorem writer_operations_read_only_the_writer_count
    (b b' : buffer.PipeBuffer) (h : b.writers = b'.writers) :
    pipebuffer_add_writer b = pipebuffer_add_writer b' ∧
    pipebuffer_remove_writer b = pipebuffer_remove_writer b' ∧
    pipebuffer_has_writers b = pipebuffer_has_writers b' := by
  simp only [pipebuffer_add_writer, buffer.PipeBuffer.add_writer,
    pipebuffer_remove_writer, buffer.PipeBuffer.remove_writer,
    pipebuffer_has_writers, buffer.PipeBuffer.has_writers, h, and_self]

/-- `add_reader` and `remove_reader` are one atomic step each on the same cell,
    the reader counter, with the same delta of one and the same ordering, and
    they discard the old value. So an add followed by a remove is meant to
    cancel.

    This also records a defect. `remove_reader` does not load the counter or
    guard against zero before subtracting, and an atomic `fetch_sub` wraps
    rather than trapping. `PipeReader::close` and `PipeReader::drop` both call
    it, so closing and then dropping the last reader takes the count from one
    through zero to `usize::MAX`, after which `has_readers` holds forever. -/
theorem pipebuffer_remove_reader_undoes_pipebuffer_add_reader_without_a_zero_guard
    (b : buffer.PipeBuffer) :
    ∃ (cell : core.sync.atomic.Atomic Std.Usize
        (core.sync.atomic.private.Align8 Std.Usize))
      (δ : Std.Usize) (o : core.sync.atomic.Ordering),
      δ = 1#usize ∧ cell = b.readers ∧
      pipebuffer_add_reader b =
        (do let _ ← core.sync.atomic.AtomicUsizeAlign8Usize.fetch_add cell δ o; ok ()) ∧
      pipebuffer_remove_reader b =
        (do let _ ← core.sync.atomic.AtomicUsizeAlign8Usize.fetch_sub cell δ o; ok ()) :=
  ⟨b.readers, 1#usize, .SeqCst, rfl, rfl, rfl, rfl⟩

/-- `add_writer` and `remove_writer` are one atomic step each on the writer
    counter, with the same delta of one and the same ordering.

    As for readers, this records a defect: `remove_writer` has no zero guard,
    and `PipeWriter::close` followed by `PipeWriter::drop` wraps the count to
    `usize::MAX`, after which a blocked `pipe_read` on an empty pipe waits
    forever instead of seeing end of file. -/
theorem pipebuffer_remove_writer_undoes_pipebuffer_add_writer_without_a_zero_guard
    (b : buffer.PipeBuffer) :
    ∃ (cell : core.sync.atomic.Atomic Std.Usize
        (core.sync.atomic.private.Align8 Std.Usize))
      (δ : Std.Usize) (o : core.sync.atomic.Ordering),
      δ = 1#usize ∧ cell = b.writers ∧
      pipebuffer_add_writer b =
        (do let _ ← core.sync.atomic.AtomicUsizeAlign8Usize.fetch_add cell δ o; ok ()) ∧
      pipebuffer_remove_writer b =
        (do let _ ← core.sync.atomic.AtomicUsizeAlign8Usize.fetch_sub cell δ o; ok ()) :=
  ⟨b.writers, 1#usize, .SeqCst, rfl, rfl, rfl, rfl⟩

/-! ### Axiom profile -/

#print axioms NonosExtraction.PipeBuffer.available_is_capacity_less_length_less_one
#print axioms NonosExtraction.PipeBuffer.the_inline_copy_agrees_with_the_function
#print axioms NonosExtraction.PipeBuffer.a_full_buffer_halts_rather_than_reporting_no_room
#print axioms NonosExtraction.PipeBuffer.emptiness_is_a_length_of_zero
#print axioms NonosExtraction.PipeBuffer.the_pipe_is_sixty_four_kilobytes
#print axioms NonosExtraction.PipeBuffer.the_pipebuffer_new_wrapper_is_its_method
#print axioms NonosExtraction.PipeBuffer.the_pipebuffer_len_wrapper_is_its_method
#print axioms NonosExtraction.PipeBuffer.the_pipebuffer_is_empty_wrapper_is_its_method
#print axioms NonosExtraction.PipeBuffer.the_pipebuffer_available_write_wrapper_is_its_method
#print axioms NonosExtraction.PipeBuffer.the_pipebuffer_add_reader_wrapper_is_its_method
#print axioms NonosExtraction.PipeBuffer.the_pipebuffer_remove_reader_wrapper_is_its_method
#print axioms NonosExtraction.PipeBuffer.the_pipebuffer_add_writer_wrapper_is_its_method
#print axioms NonosExtraction.PipeBuffer.the_pipebuffer_remove_writer_wrapper_is_its_method
#print axioms NonosExtraction.PipeBuffer.the_pipebuffer_has_readers_wrapper_is_its_method
#print axioms NonosExtraction.PipeBuffer.the_pipebuffer_has_writers_wrapper_is_its_method
#print axioms NonosExtraction.PipeBuffer.pipebuffer_len_is_the_ring_distance_and_complements_available_write
#print axioms NonosExtraction.PipeBuffer.pipebuffer_new_builds_a_zeroed_ring_of_its_own_capacity
#print axioms NonosExtraction.PipeBuffer.pipebuffer_new_is_empty_by_pipebuffer_len
#print axioms NonosExtraction.PipeBuffer.pipebuffer_has_readers_is_the_reader_count_being_nonzero
#print axioms NonosExtraction.PipeBuffer.pipebuffer_has_writers_is_the_writer_count_being_nonzero
#print axioms NonosExtraction.PipeBuffer.reader_operations_read_only_the_reader_count
#print axioms NonosExtraction.PipeBuffer.writer_operations_read_only_the_writer_count
#print axioms NonosExtraction.PipeBuffer.pipebuffer_remove_reader_undoes_pipebuffer_add_reader_without_a_zero_guard
#print axioms NonosExtraction.PipeBuffer.pipebuffer_remove_writer_undoes_pipebuffer_add_writer_without_a_zero_guard

end NonosExtraction.PipeBuffer
