/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

buffer, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.PipeBuffer

open Aeneas Aeneas.Std Result
open nonos_x_pipe_buffer

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.PipeBuffer

/-! ### The forwarding functions add nothing -/

theorem the_pipebuffer_new_wrapper_is_its_method :
    pipebuffer_new = buffer.PipeBuffer.new := rfl

theorem the_pipebuffer_len_wrapper_is_its_method (a : buffer.PipeBuffer) :
    pipebuffer_len a = buffer.PipeBuffer.len a := rfl

theorem the_pipebuffer_is_empty_wrapper_is_its_method (a : buffer.PipeBuffer) :
    pipebuffer_is_empty a = buffer.PipeBuffer.is_empty a := rfl

theorem the_pipebuffer_available_write_wrapper_is_its_method (a : buffer.PipeBuffer) :
    pipebuffer_available_write a = buffer.PipeBuffer.available_write a := rfl

theorem the_pipebuffer_add_reader_wrapper_is_its_method (a : buffer.PipeBuffer) :
    pipebuffer_add_reader a = buffer.PipeBuffer.add_reader a := rfl

theorem the_pipebuffer_remove_reader_wrapper_is_its_method (a : buffer.PipeBuffer) :
    pipebuffer_remove_reader a = buffer.PipeBuffer.remove_reader a := rfl

theorem the_pipebuffer_add_writer_wrapper_is_its_method (a : buffer.PipeBuffer) :
    pipebuffer_add_writer a = buffer.PipeBuffer.add_writer a := rfl

theorem the_pipebuffer_remove_writer_wrapper_is_its_method (a : buffer.PipeBuffer) :
    pipebuffer_remove_writer a = buffer.PipeBuffer.remove_writer a := rfl

theorem the_pipebuffer_has_readers_wrapper_is_its_method (a : buffer.PipeBuffer) :
    pipebuffer_has_readers a = buffer.PipeBuffer.has_readers a := rfl

theorem the_pipebuffer_has_writers_wrapper_is_its_method (a : buffer.PipeBuffer) :
    pipebuffer_has_writers a = buffer.PipeBuffer.has_writers a := rfl


/-! ### The ring arithmetic

    A pipe keeps one slot empty so that a full buffer and an empty one are
    distinguishable, and every question about occupancy is derived from `head`,
    `tail` and `capacity`.

    `len` and `available_write` are extracted. `read` and `write` are not, since
    they take slices and mutate them, but `write` computes the space it has
    inline rather than calling `available_write`. That is two copies of one rule
    living in one file, and the first theorem below is the obligation they owe
    each other.

    The atomics are opaque to the translation, so the loads below are not
    reduced. That costs nothing here: every property in this section is about the
    arithmetic applied to whatever the loads returned.
-/

/-- `available_write` is `capacity - len - 1` by construction. Written out so the
    second copy has something to be compared against. -/
theorem available_is_capacity_less_length_less_one (b : buffer.PipeBuffer) :
    pipebuffer_available_write b =
      (do let l ← buffer.PipeBuffer.len b
          let i ← b.capacity - l
          i - 1#usize) := rfl

/-- The obligation the two copies owe each other, as plain arithmetic on the
    quantities both of them read.

    `write` computes `capacity - head + tail - 1` when head is at or above tail
    and `tail - head - 1` otherwise. `available_write` computes
    `capacity - len - 1`, where `len` is `head - tail` in the first case and
    `capacity - tail + head` in the second. They agree, in both directions, and
    this is why. -/
theorem the_inline_copy_agrees_with_the_function
    (cap head tail : Nat) (ht : tail ≤ cap) (hh : head ≤ cap) :
    (tail ≤ head → cap - head + tail - 1 = cap - (head - tail) - 1) ∧
    (head < tail → tail - head - 1 = cap - (cap - tail + head) - 1) := by
  refine ⟨?_, ?_⟩ <;> intro h <;> omega

/-- A buffer that reports itself completely full does not get told it has no
    room, it halts. `available_write` is `capacity - len - 1`, so at
    `len = capacity` the first subtraction gives zero and the second underflows,
    and this kernel builds with overflow checks and panic equal to abort.

    Shown at the shipped capacity, which is the value `new` installs. The
    reserved slot is what normally keeps `len` below `capacity`, so reaching this
    needs `head`, `tail` or `capacity` to have been set outside the ring
    discipline. All three are `pub` on the struct. -/
theorem a_full_buffer_halts_rather_than_reporting_no_room :
    (do let i ← (65536#usize) - (65536#usize); i - 1#usize)
      = fail Error.integerOverflow := by rfl

/-- Emptiness is exactly a length of zero, so the two questions a caller can ask
    about an idle pipe cannot disagree. -/
theorem emptiness_is_a_length_of_zero (b : buffer.PipeBuffer) :
    pipebuffer_is_empty b =
      (do let l ← buffer.PipeBuffer.len b; ok (decide (l = 0#usize))) := rfl

/-- The capacity a fresh pipe is built with. Sixty four kilobytes, which is the
    figure `PIPE_BUF_SIZE` names and the one every occupancy answer is relative
    to. -/
theorem the_pipe_is_sixty_four_kilobytes :
    buffer.PIPE_BUF_SIZE = 65536#usize := by
  unfold buffer.PIPE_BUF_SIZE; rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.PipeBuffer.available_is_capacity_less_length_less_one
#print axioms NonosExtraction.PipeBuffer.the_inline_copy_agrees_with_the_function
#print axioms NonosExtraction.PipeBuffer.a_full_buffer_halts_rather_than_reporting_no_room
#print axioms NonosExtraction.PipeBuffer.emptiness_is_a_length_of_zero
#print axioms NonosExtraction.PipeBuffer.the_pipe_is_sixty_four_kilobytes
#print axioms NonosExtraction.PipeBuffer.the_pipebuffer_new_wrapper_is_its_method
#print axioms NonosExtraction.PipeBuffer.the_pipebuffer_len_wrapper_is_its_method
#print axioms NonosExtraction.PipeBuffer.the_pipebuffer_is_empty_wrapper_is_its_method
#print axioms NonosExtraction.PipeBuffer.the_pipebuffer_available_write_wrapper_is_its_method
#print axioms NonosExtraction.PipeBuffer.the_pipebuffer_add_reader_wrapper_is_its_method
#print axioms NonosExtraction.PipeBuffer.the_pipebuffer_remove_reader_wrapper_is_its_method
#print axioms NonosExtraction.PipeBuffer.the_pipebuffer_add_writer_wrapper_is_its_method
#print axioms NonosExtraction.PipeBuffer.the_pipebuffer_remove_writer_wrapper_is_its_method
#print axioms NonosExtraction.PipeBuffer.the_pipebuffer_has_readers_wrapper_is_its_method
#print axioms NonosExtraction.PipeBuffer.the_pipebuffer_has_writers_wrapper_is_its_method

end NonosExtraction.PipeBuffer
