/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

buffer, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.PipeBuffer

open Aeneas Aeneas.Std Result
open nonos_x_pipe_buffer

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.PipeBuffer

/-! ### The forwarding functions add nothing -/

theorem the_pipebuffer_new_wrapper_is_its_method :
    pipebuffer_new = buffer.PipeBuffer.new := rfl

theorem the_pipebuffer_len_wrapper_is_its_method (a : buffer.PipeBuffer) :
    pipebuffer_len a = buffer.PipeBuffer.len a := rfl

theorem the_pipebuffer_is_empty_wrapper_is_its_method (a : buffer.PipeBuffer) :
    pipebuffer_is_empty a = buffer.PipeBuffer.is_empty a := rfl

theorem the_pipebuffer_available_write_wrapper_is_its_method (a : buffer.PipeBuffer) :
    pipebuffer_available_write a = buffer.PipeBuffer.available_write a := rfl

theorem the_pipebuffer_add_reader_wrapper_is_its_method (a : buffer.PipeBuffer) :
    pipebuffer_add_reader a = buffer.PipeBuffer.add_reader a := rfl

theorem the_pipebuffer_remove_reader_wrapper_is_its_method (a : buffer.PipeBuffer) :
    pipebuffer_remove_reader a = buffer.PipeBuffer.remove_reader a := rfl

theorem the_pipebuffer_add_writer_wrapper_is_its_method (a : buffer.PipeBuffer) :
    pipebuffer_add_writer a = buffer.PipeBuffer.add_writer a := rfl

theorem the_pipebuffer_remove_writer_wrapper_is_its_method (a : buffer.PipeBuffer) :
    pipebuffer_remove_writer a = buffer.PipeBuffer.remove_writer a := rfl

theorem the_pipebuffer_has_readers_wrapper_is_its_method (a : buffer.PipeBuffer) :
    pipebuffer_has_readers a = buffer.PipeBuffer.has_readers a := rfl

theorem the_pipebuffer_has_writers_wrapper_is_its_method (a : buffer.PipeBuffer) :
    pipebuffer_has_writers a = buffer.PipeBuffer.has_writers a := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.PipeBuffer.the_pipebuffer_new_wrapper_is_its_method
#print axioms NonosExtraction.PipeBuffer.the_pipebuffer_len_wrapper_is_its_method
#print axioms NonosExtraction.PipeBuffer.the_pipebuffer_is_empty_wrapper_is_its_method
#print axioms NonosExtraction.PipeBuffer.the_pipebuffer_available_write_wrapper_is_its_method
#print axioms NonosExtraction.PipeBuffer.the_pipebuffer_add_reader_wrapper_is_its_method
#print axioms NonosExtraction.PipeBuffer.the_pipebuffer_remove_reader_wrapper_is_its_method
#print axioms NonosExtraction.PipeBuffer.the_pipebuffer_add_writer_wrapper_is_its_method
#print axioms NonosExtraction.PipeBuffer.the_pipebuffer_remove_writer_wrapper_is_its_method
#print axioms NonosExtraction.PipeBuffer.the_pipebuffer_has_readers_wrapper_is_its_method
#print axioms NonosExtraction.PipeBuffer.the_pipebuffer_has_writers_wrapper_is_its_method

end NonosExtraction.PipeBuffer
