/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

bits, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.ProcessSignalSetBits

open Aeneas Aeneas.Std Result
open nonos_x_process_signal_set_bits

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.ProcessSignalSetBits

/-! ### The forwarding functions add nothing -/

theorem the_signalset_empty_wrapper_is_its_method :
    signalset_empty = process.signal.set.bits.SignalSet.empty := rfl

theorem the_signalset_full_wrapper_is_its_method :
    signalset_full = process.signal.set.bits.SignalSet.full := rfl

theorem the_signalset_contains_wrapper_is_its_method (a : process.signal.set.bits.SignalSet) (b : Std.U8) :
    signalset_contains a b = process.signal.set.bits.SignalSet.contains a b := rfl

theorem the_signalset_is_empty_wrapper_is_its_method (a : process.signal.set.bits.SignalSet) :
    signalset_is_empty a = process.signal.set.bits.SignalSet.is_empty a := rfl

theorem the_signalset_as_bits_wrapper_is_its_method (a : process.signal.set.bits.SignalSet) :
    signalset_as_bits a = process.signal.set.bits.SignalSet.as_bits a := rfl

theorem the_signalset_from_bits_wrapper_is_its_method (a : Std.U64) :
    signalset_from_bits a = process.signal.set.bits.SignalSet.from_bits a := rfl

theorem the_signalset_complement_wrapper_is_its_method (a : process.signal.set.bits.SignalSet) :
    signalset_complement a = process.signal.set.bits.SignalSet.complement a := rfl

theorem the_signalset_count_wrapper_is_its_method (a : process.signal.set.bits.SignalSet) :
    signalset_count a = process.signal.set.bits.SignalSet.count a := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.ProcessSignalSetBits.the_signalset_empty_wrapper_is_its_method
#print axioms NonosExtraction.ProcessSignalSetBits.the_signalset_full_wrapper_is_its_method
#print axioms NonosExtraction.ProcessSignalSetBits.the_signalset_contains_wrapper_is_its_method
#print axioms NonosExtraction.ProcessSignalSetBits.the_signalset_is_empty_wrapper_is_its_method
#print axioms NonosExtraction.ProcessSignalSetBits.the_signalset_as_bits_wrapper_is_its_method
#print axioms NonosExtraction.ProcessSignalSetBits.the_signalset_from_bits_wrapper_is_its_method
#print axioms NonosExtraction.ProcessSignalSetBits.the_signalset_complement_wrapper_is_its_method
#print axioms NonosExtraction.ProcessSignalSetBits.the_signalset_count_wrapper_is_its_method

end NonosExtraction.ProcessSignalSetBits
