/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

device, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.RedistributorDevice

open Aeneas Aeneas.Std Result
open nonos_x_redistributor_device

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.RedistributorDevice

/-! ### The forwarding functions add nothing -/

theorem the_gicredistributor_new_wrapper_is_its_method (a : Std.U64) :
    gicredistributor_new a = device.GicRedistributor.new a := rfl

/-! ### The redistributor frame is where the firmware put it

    `new` records the base address it is given without masking, rounding or
    offsetting it, so every register access the driver makes is relative to the
    address the device tree or ACPI table reported, including each frame `find.rs` walks. The theorems cannot say that
    the address is a valid, mapped redistributor frame; that comes from the firmware
    tables and the MMIO mapping, neither of which is extracted.
-/

/-- The constructed redistributor keeps the base exactly as given. -/
theorem gicredistributor_new_keeps_the_firmware_base (b : Std.U64) :
    ∃ d, gicredistributor_new b = ok d ∧ d.base = b := ⟨_, rfl, rfl⟩

/-- Different bases give different devices, so two frames are never collapsed
    onto one. -/
theorem gicredistributor_new_tells_bases_apart (a b : Std.U64) (h : gicredistributor_new a = gicredistributor_new b) : a = b := by
  simpa [gicredistributor_new, device.GicRedistributor.new] using h

/-! ### Axiom profile -/

#print axioms NonosExtraction.RedistributorDevice.the_gicredistributor_new_wrapper_is_its_method

#print axioms NonosExtraction.RedistributorDevice.gicredistributor_new_keeps_the_firmware_base
#print axioms NonosExtraction.RedistributorDevice.gicredistributor_new_tells_bases_apart

end NonosExtraction.RedistributorDevice
