/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

overlap, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.RegionOverlap

open Aeneas Aeneas.Std Result
open nonos_x_region_overlap

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.RegionOverlap

/-! ### The forwarding functions add nothing -/

theorem the_overlaps_wrapper_is_its_method (a : Std.U64) (b : Std.U64) (c : Std.U64) (d : Std.U64) :
    overlaps a b c d = overlap.overlaps a b c d := rfl

theorem the_contains_wrapper_is_its_method (a : Std.U64) (b : Std.U64) (c : Std.U64) :
    contains a b c = overlap.contains a b c := rfl

theorem the_contains_range_wrapper_is_its_method (a : Std.U64) (b : Std.U64) (c : Std.U64) (d : Std.U64) :
    contains_range a b c d = overlap.contains_range a b c d := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.RegionOverlap.the_overlaps_wrapper_is_its_method
#print axioms NonosExtraction.RegionOverlap.the_contains_wrapper_is_its_method
#print axioms NonosExtraction.RegionOverlap.the_contains_range_wrapper_is_its_method

end NonosExtraction.RegionOverlap
