/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

query, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.Riscv64CpuExtensionsQuery

open Aeneas Aeneas.Std Result
open nonos_x_riscv64_cpu_extensions_query

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.Riscv64CpuExtensionsQuery

/-! ### The forwarding functions add nothing -/

theorem the_has_vector_wrapper_is_its_method :
    has_vector = arch.riscv64.cpu.extensions.query.has_vector := rfl

theorem the_has_compressed_wrapper_is_its_method :
    has_compressed = arch.riscv64.cpu.extensions.query.has_compressed := rfl

theorem the_has_atomics_wrapper_is_its_method :
    has_atomics = arch.riscv64.cpu.extensions.query.has_atomics := rfl

theorem the_has_float_wrapper_is_its_method :
    has_float = arch.riscv64.cpu.extensions.query.has_float := rfl

theorem the_has_double_wrapper_is_its_method :
    has_double = arch.riscv64.cpu.extensions.query.has_double := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.Riscv64CpuExtensionsQuery.the_has_vector_wrapper_is_its_method
#print axioms NonosExtraction.Riscv64CpuExtensionsQuery.the_has_compressed_wrapper_is_its_method
#print axioms NonosExtraction.Riscv64CpuExtensionsQuery.the_has_atomics_wrapper_is_its_method
#print axioms NonosExtraction.Riscv64CpuExtensionsQuery.the_has_float_wrapper_is_its_method
#print axioms NonosExtraction.Riscv64CpuExtensionsQuery.the_has_double_wrapper_is_its_method

end NonosExtraction.Riscv64CpuExtensionsQuery
