/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

query, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.Riscv64CpuCapsQuery

open Aeneas Aeneas.Std Result
open nonos_x_riscv64_cpu_caps_query

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.Riscv64CpuCapsQuery

/-! ### The forwarding functions add nothing -/

theorem the_is_configured_wrapper_is_its_method :
    is_configured = arch.riscv64.cpu.caps.query.is_configured := rfl

theorem the_has_f_wrapper_is_its_method :
    has_f = arch.riscv64.cpu.caps.query.has_f := rfl

theorem the_has_d_wrapper_is_its_method :
    has_d = arch.riscv64.cpu.caps.query.has_d := rfl

theorem the_has_v_wrapper_is_its_method :
    has_v = arch.riscv64.cpu.caps.query.has_v := rfl

theorem the_has_a_wrapper_is_its_method :
    has_a = arch.riscv64.cpu.caps.query.has_a := rfl

theorem the_has_c_wrapper_is_its_method :
    has_c = arch.riscv64.cpu.caps.query.has_c := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.Riscv64CpuCapsQuery.the_is_configured_wrapper_is_its_method
#print axioms NonosExtraction.Riscv64CpuCapsQuery.the_has_f_wrapper_is_its_method
#print axioms NonosExtraction.Riscv64CpuCapsQuery.the_has_d_wrapper_is_its_method
#print axioms NonosExtraction.Riscv64CpuCapsQuery.the_has_v_wrapper_is_its_method
#print axioms NonosExtraction.Riscv64CpuCapsQuery.the_has_a_wrapper_is_its_method
#print axioms NonosExtraction.Riscv64CpuCapsQuery.the_has_c_wrapper_is_its_method

end NonosExtraction.Riscv64CpuCapsQuery
