-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [nonos_rv_flags]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace nonos_rv_flags

/-- [nonos_rv_flags::flags::PteFlags]
    Source: 'src/../../../../src/arch/riscv64/mmu/attributes/flags.rs', lines 18:0-18:25
    Visibility: public -/
@[reducible]
def flags.PteFlags := Std.U64

/-- [nonos_rv_flags::flags::{nonos_rv_flags::flags::PteFlags}::V]
    Source: 'src/../../../../src/arch/riscv64/mmu/attributes/flags.rs', lines 21:4-21:30
    Visibility: public -/
@[global_simps, irreducible]
def flags.PteFlags.V : Result Std.U64 := 1#u64 <<< 0#i32

/-- [nonos_rv_flags::flags::{nonos_rv_flags::flags::PteFlags}::R]
    Source: 'src/../../../../src/arch/riscv64/mmu/attributes/flags.rs', lines 22:4-22:30
    Visibility: public -/
@[global_simps, irreducible]
def flags.PteFlags.R : Result Std.U64 := 1#u64 <<< 1#i32

/-- [nonos_rv_flags::flags::{nonos_rv_flags::flags::PteFlags}::W]
    Source: 'src/../../../../src/arch/riscv64/mmu/attributes/flags.rs', lines 23:4-23:30
    Visibility: public -/
@[global_simps, irreducible]
def flags.PteFlags.W : Result Std.U64 := 1#u64 <<< 2#i32

/-- [nonos_rv_flags::flags::{nonos_rv_flags::flags::PteFlags}::X]
    Source: 'src/../../../../src/arch/riscv64/mmu/attributes/flags.rs', lines 24:4-24:30
    Visibility: public -/
@[global_simps, irreducible]
def flags.PteFlags.X : Result Std.U64 := 1#u64 <<< 3#i32

/-- [nonos_rv_flags::flags::{nonos_rv_flags::flags::PteFlags}::U]
    Source: 'src/../../../../src/arch/riscv64/mmu/attributes/flags.rs', lines 25:4-25:30
    Visibility: public -/
@[global_simps, irreducible]
def flags.PteFlags.U : Result Std.U64 := 1#u64 <<< 4#i32

/-- [nonos_rv_flags::flags::{nonos_rv_flags::flags::PteFlags}::G]
    Source: 'src/../../../../src/arch/riscv64/mmu/attributes/flags.rs', lines 26:4-26:30
    Visibility: public -/
@[global_simps, irreducible]
def flags.PteFlags.G : Result Std.U64 := 1#u64 <<< 5#i32

/-- [nonos_rv_flags::flags::{nonos_rv_flags::flags::PteFlags}::A]
    Source: 'src/../../../../src/arch/riscv64/mmu/attributes/flags.rs', lines 27:4-27:30
    Visibility: public -/
@[global_simps, irreducible]
def flags.PteFlags.A : Result Std.U64 := 1#u64 <<< 6#i32

/-- [nonos_rv_flags::flags::{nonos_rv_flags::flags::PteFlags}::D]
    Source: 'src/../../../../src/arch/riscv64/mmu/attributes/flags.rs', lines 28:4-28:30
    Visibility: public -/
@[global_simps, irreducible]
def flags.PteFlags.D : Result Std.U64 := 1#u64 <<< 7#i32

/-- [nonos_rv_flags::flags::{nonos_rv_flags::flags::PteFlags}::new]:
    Source: 'src/../../../../src/arch/riscv64/mmu/attributes/flags.rs', lines 29:4-31:5
    Visibility: public -/
def flags.PteFlags.new : Result flags.PteFlags := do
  ok 0#u64

/-- [nonos_rv_flags::flags::{nonos_rv_flags::flags::PteFlags}::from_bits]:
    Source: 'src/../../../../src/arch/riscv64/mmu/attributes/flags.rs', lines 32:4-34:5
    Visibility: public -/
def flags.PteFlags.from_bits (bits : Std.U64) : Result flags.PteFlags := do
  ok bits

/-- [nonos_rv_flags::flags::{nonos_rv_flags::flags::PteFlags}::valid]:
    Source: 'src/../../../../src/arch/riscv64/mmu/attributes/flags.rs', lines 35:4-38:5
    Visibility: public -/
def flags.PteFlags.valid (self : flags.PteFlags) : Result flags.PteFlags := do
  let i ← flags.PteFlags.V
  let i1 ← lift (self ||| i)
  ok i1

/-- [nonos_rv_flags::flags::{nonos_rv_flags::flags::PteFlags}::readable]:
    Source: 'src/../../../../src/arch/riscv64/mmu/attributes/flags.rs', lines 39:4-42:5
    Visibility: public -/
def flags.PteFlags.readable
  (self : flags.PteFlags) : Result flags.PteFlags := do
  let i ← flags.PteFlags.R
  let i1 ← lift (self ||| i)
  ok i1

/-- [nonos_rv_flags::flags::{nonos_rv_flags::flags::PteFlags}::writable]:
    Source: 'src/../../../../src/arch/riscv64/mmu/attributes/flags.rs', lines 43:4-46:5
    Visibility: public -/
def flags.PteFlags.writable
  (self : flags.PteFlags) : Result flags.PteFlags := do
  let i ← flags.PteFlags.W
  let i1 ← lift (self ||| i)
  ok i1

/-- [nonos_rv_flags::flags::{nonos_rv_flags::flags::PteFlags}::executable]:
    Source: 'src/../../../../src/arch/riscv64/mmu/attributes/flags.rs', lines 47:4-50:5
    Visibility: public -/
def flags.PteFlags.executable
  (self : flags.PteFlags) : Result flags.PteFlags := do
  let i ← flags.PteFlags.X
  let i1 ← lift (self ||| i)
  ok i1

/-- [nonos_rv_flags::flags::{nonos_rv_flags::flags::PteFlags}::user]:
    Source: 'src/../../../../src/arch/riscv64/mmu/attributes/flags.rs', lines 51:4-54:5
    Visibility: public -/
def flags.PteFlags.user (self : flags.PteFlags) : Result flags.PteFlags := do
  let i ← flags.PteFlags.U
  let i1 ← lift (self ||| i)
  ok i1

/-- [nonos_rv_flags::flags::{nonos_rv_flags::flags::PteFlags}::global]:
    Source: 'src/../../../../src/arch/riscv64/mmu/attributes/flags.rs', lines 55:4-58:5
    Visibility: public -/
def flags.PteFlags.global (self : flags.PteFlags) : Result flags.PteFlags := do
  let i ← flags.PteFlags.G
  let i1 ← lift (self ||| i)
  ok i1

/-- [nonos_rv_flags::flags::{nonos_rv_flags::flags::PteFlags}::accessed]:
    Source: 'src/../../../../src/arch/riscv64/mmu/attributes/flags.rs', lines 59:4-62:5
    Visibility: public -/
def flags.PteFlags.accessed
  (self : flags.PteFlags) : Result flags.PteFlags := do
  let i ← flags.PteFlags.A
  let i1 ← lift (self ||| i)
  ok i1

/-- [nonos_rv_flags::flags::{nonos_rv_flags::flags::PteFlags}::dirty]:
    Source: 'src/../../../../src/arch/riscv64/mmu/attributes/flags.rs', lines 63:4-66:5
    Visibility: public -/
def flags.PteFlags.dirty (self : flags.PteFlags) : Result flags.PteFlags := do
  let i ← flags.PteFlags.D
  let i1 ← lift (self ||| i)
  ok i1

/-- [nonos_rv_flags::flags::{nonos_rv_flags::flags::PteFlags}::bits]:
    Source: 'src/../../../../src/arch/riscv64/mmu/attributes/flags.rs', lines 67:4-69:5
    Visibility: public -/
def flags.PteFlags.bits (self : flags.PteFlags) : Result Std.U64 := do
  ok self

/-- [nonos_rv_flags::flags::{nonos_rv_flags::flags::PteFlags}::is_valid]:
    Source: 'src/../../../../src/arch/riscv64/mmu/attributes/flags.rs', lines 70:4-72:5
    Visibility: public -/
def flags.PteFlags.is_valid (self : flags.PteFlags) : Result Bool := do
  let i ← flags.PteFlags.V
  let i1 ← lift (self &&& i)
  ok (i1 != 0#u64)

/-- [nonos_rv_flags::flags::{nonos_rv_flags::flags::PteFlags}::is_leaf]:
    Source: 'src/../../../../src/arch/riscv64/mmu/attributes/flags.rs', lines 73:4-75:5
    Visibility: public -/
def flags.PteFlags.is_leaf (self : flags.PteFlags) : Result Bool := do
  let i ← flags.PteFlags.R
  let i1 ← flags.PteFlags.W
  let i2 ← lift (i ||| i1)
  let i3 ← flags.PteFlags.X
  let i4 ← lift (i2 ||| i3)
  let i5 ← lift (self &&& i4)
  ok (i5 != 0#u64)

/-- [nonos_rv_flags::flags::{nonos_rv_flags::flags::PteFlags}::is_readable]:
    Source: 'src/../../../../src/arch/riscv64/mmu/attributes/flags.rs', lines 76:4-78:5
    Visibility: public -/
def flags.PteFlags.is_readable (self : flags.PteFlags) : Result Bool := do
  let i ← flags.PteFlags.R
  let i1 ← lift (self &&& i)
  ok (i1 != 0#u64)

/-- [nonos_rv_flags::flags::{nonos_rv_flags::flags::PteFlags}::is_writable]:
    Source: 'src/../../../../src/arch/riscv64/mmu/attributes/flags.rs', lines 79:4-81:5
    Visibility: public -/
def flags.PteFlags.is_writable (self : flags.PteFlags) : Result Bool := do
  let i ← flags.PteFlags.W
  let i1 ← lift (self &&& i)
  ok (i1 != 0#u64)

/-- [nonos_rv_flags::flags::{nonos_rv_flags::flags::PteFlags}::is_executable]:
    Source: 'src/../../../../src/arch/riscv64/mmu/attributes/flags.rs', lines 82:4-84:5
    Visibility: public -/
def flags.PteFlags.is_executable (self : flags.PteFlags) : Result Bool := do
  let i ← flags.PteFlags.X
  let i1 ← lift (self &&& i)
  ok (i1 != 0#u64)

/-- [nonos_rv_flags::flags::{nonos_rv_flags::flags::PteFlags}::is_user]:
    Source: 'src/../../../../src/arch/riscv64/mmu/attributes/flags.rs', lines 85:4-87:5
    Visibility: public -/
def flags.PteFlags.is_user (self : flags.PteFlags) : Result Bool := do
  let i ← flags.PteFlags.U
  let i1 ← lift (self &&& i)
  ok (i1 != 0#u64)

/-- [nonos_rv_flags::pteflags_new]:
    Source: 'src/lib.rs', lines 10:0-12:1
    Visibility: public -/
def pteflags_new : Result flags.PteFlags := do
  flags.PteFlags.new

/-- [nonos_rv_flags::pteflags_from_bits]:
    Source: 'src/lib.rs', lines 14:0-16:1
    Visibility: public -/
def pteflags_from_bits (bits : Std.U64) : Result flags.PteFlags := do
  flags.PteFlags.from_bits bits

/-- [nonos_rv_flags::pteflags_valid]:
    Source: 'src/lib.rs', lines 18:0-20:1
    Visibility: public -/
def pteflags_valid (this : flags.PteFlags) : Result flags.PteFlags := do
  flags.PteFlags.valid this

/-- [nonos_rv_flags::pteflags_readable]:
    Source: 'src/lib.rs', lines 22:0-24:1
    Visibility: public -/
def pteflags_readable (this : flags.PteFlags) : Result flags.PteFlags := do
  flags.PteFlags.readable this

/-- [nonos_rv_flags::pteflags_writable]:
    Source: 'src/lib.rs', lines 26:0-28:1
    Visibility: public -/
def pteflags_writable (this : flags.PteFlags) : Result flags.PteFlags := do
  flags.PteFlags.writable this

/-- [nonos_rv_flags::pteflags_executable]:
    Source: 'src/lib.rs', lines 30:0-32:1
    Visibility: public -/
def pteflags_executable (this : flags.PteFlags) : Result flags.PteFlags := do
  flags.PteFlags.executable this

/-- [nonos_rv_flags::pteflags_user]:
    Source: 'src/lib.rs', lines 34:0-36:1
    Visibility: public -/
def pteflags_user (this : flags.PteFlags) : Result flags.PteFlags := do
  flags.PteFlags.user this

/-- [nonos_rv_flags::pteflags_global]:
    Source: 'src/lib.rs', lines 38:0-40:1
    Visibility: public -/
def pteflags_global (this : flags.PteFlags) : Result flags.PteFlags := do
  flags.PteFlags.global this

/-- [nonos_rv_flags::pteflags_accessed]:
    Source: 'src/lib.rs', lines 42:0-44:1
    Visibility: public -/
def pteflags_accessed (this : flags.PteFlags) : Result flags.PteFlags := do
  flags.PteFlags.accessed this

/-- [nonos_rv_flags::pteflags_dirty]:
    Source: 'src/lib.rs', lines 46:0-48:1
    Visibility: public -/
def pteflags_dirty (this : flags.PteFlags) : Result flags.PteFlags := do
  flags.PteFlags.dirty this

/-- [nonos_rv_flags::pteflags_bits]:
    Source: 'src/lib.rs', lines 50:0-52:1
    Visibility: public -/
def pteflags_bits (this : flags.PteFlags) : Result Std.U64 := do
  flags.PteFlags.bits this

/-- [nonos_rv_flags::pteflags_is_valid]:
    Source: 'src/lib.rs', lines 54:0-56:1
    Visibility: public -/
def pteflags_is_valid (this : flags.PteFlags) : Result Bool := do
  flags.PteFlags.is_valid this

/-- [nonos_rv_flags::pteflags_is_leaf]:
    Source: 'src/lib.rs', lines 58:0-60:1
    Visibility: public -/
def pteflags_is_leaf (this : flags.PteFlags) : Result Bool := do
  flags.PteFlags.is_leaf this

/-- [nonos_rv_flags::pteflags_is_readable]:
    Source: 'src/lib.rs', lines 62:0-64:1
    Visibility: public -/
def pteflags_is_readable (this : flags.PteFlags) : Result Bool := do
  flags.PteFlags.is_readable this

/-- [nonos_rv_flags::pteflags_is_writable]:
    Source: 'src/lib.rs', lines 66:0-68:1
    Visibility: public -/
def pteflags_is_writable (this : flags.PteFlags) : Result Bool := do
  flags.PteFlags.is_writable this

/-- [nonos_rv_flags::pteflags_is_executable]:
    Source: 'src/lib.rs', lines 70:0-72:1
    Visibility: public -/
def pteflags_is_executable (this : flags.PteFlags) : Result Bool := do
  flags.PteFlags.is_executable this

/-- [nonos_rv_flags::pteflags_is_user]:
    Source: 'src/lib.rs', lines 74:0-76:1
    Visibility: public -/
def pteflags_is_user (this : flags.PteFlags) : Result Bool := do
  flags.PteFlags.is_user this

end nonos_rv_flags
