/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

flags, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.RvFlags
import NonosExtraction.Bits

open Aeneas Aeneas.Std Result
open nonos_rv_flags

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.RvFlags

/-! ### The forwarding functions add nothing -/

theorem the_pteflags_new_wrapper_is_its_method :
    pteflags_new = flags.PteFlags.new := rfl

theorem the_pteflags_from_bits_wrapper_is_its_method (a : Std.U64) :
    pteflags_from_bits a = flags.PteFlags.from_bits a := rfl

theorem the_pteflags_valid_wrapper_is_its_method (a : flags.PteFlags) :
    pteflags_valid a = flags.PteFlags.valid a := rfl

theorem the_pteflags_readable_wrapper_is_its_method (a : flags.PteFlags) :
    pteflags_readable a = flags.PteFlags.readable a := rfl

theorem the_pteflags_writable_wrapper_is_its_method (a : flags.PteFlags) :
    pteflags_writable a = flags.PteFlags.writable a := rfl

theorem the_pteflags_executable_wrapper_is_its_method (a : flags.PteFlags) :
    pteflags_executable a = flags.PteFlags.executable a := rfl

theorem the_pteflags_user_wrapper_is_its_method (a : flags.PteFlags) :
    pteflags_user a = flags.PteFlags.user a := rfl

theorem the_pteflags_global_wrapper_is_its_method (a : flags.PteFlags) :
    pteflags_global a = flags.PteFlags.global a := rfl

theorem the_pteflags_accessed_wrapper_is_its_method (a : flags.PteFlags) :
    pteflags_accessed a = flags.PteFlags.accessed a := rfl

theorem the_pteflags_dirty_wrapper_is_its_method (a : flags.PteFlags) :
    pteflags_dirty a = flags.PteFlags.dirty a := rfl

theorem the_pteflags_bits_wrapper_is_its_method (a : flags.PteFlags) :
    pteflags_bits a = flags.PteFlags.bits a := rfl

theorem the_pteflags_is_valid_wrapper_is_its_method (a : flags.PteFlags) :
    pteflags_is_valid a = flags.PteFlags.is_valid a := rfl

theorem the_pteflags_is_leaf_wrapper_is_its_method (a : flags.PteFlags) :
    pteflags_is_leaf a = flags.PteFlags.is_leaf a := rfl

theorem the_pteflags_is_readable_wrapper_is_its_method (a : flags.PteFlags) :
    pteflags_is_readable a = flags.PteFlags.is_readable a := rfl

theorem the_pteflags_is_writable_wrapper_is_its_method (a : flags.PteFlags) :
    pteflags_is_writable a = flags.PteFlags.is_writable a := rfl

theorem the_pteflags_is_executable_wrapper_is_its_method (a : flags.PteFlags) :
    pteflags_is_executable a = flags.PteFlags.is_executable a := rfl

theorem the_pteflags_is_user_wrapper_is_its_method (a : flags.PteFlags) :
    pteflags_is_user a = flags.PteFlags.is_user a := rfl


/-! ### What the flags mean

    These are RISC-V page table entry bits, so `W` and `X` together on one entry
    is a page that is both writable and executable. The builders below are the
    only way this module constructs an entry, and nothing in it refuses that
    combination.

    The flag constants are extracted as `irreducible`, so each proof unfolds the
    wrapper, its method and the constants it reads. That is mechanical and it is
    why the statements are small.
-/

/-- Each builder sets exactly its own bit. -/
theorem the_valid_builder_sets_bit_zero : pteflags_valid 0#u64 = ok 1#u64 := by
  unfold pteflags_valid flags.PteFlags.valid flags.PteFlags.V; rfl

theorem the_writable_builder_sets_bit_two : pteflags_writable 0#u64 = ok 4#u64 := by
  unfold pteflags_writable flags.PteFlags.writable flags.PteFlags.W; rfl

theorem the_executable_builder_sets_bit_three :
    pteflags_executable 0#u64 = ok 8#u64 := by
  unfold pteflags_executable flags.PteFlags.executable flags.PteFlags.X; rfl

theorem the_user_builder_sets_bit_four : pteflags_user 0#u64 = ok 16#u64 := by
  unfold pteflags_user flags.PteFlags.user flags.PteFlags.U; rfl

/-- The finding, stated as a construction rather than an opinion. Nothing in this
    module refuses a page that is writable and executable at once. The two
    builders compose and the result reports both.

    The x86_64 side has a W^X check over its own encoder, proven in
    `PolicyRefinement`. This backend has no equivalent, so whatever refuses the
    combination has to sit above it, and nothing in this file does. -/
theorem nothing_here_refuses_write_and_execute :
    (do let a ← pteflags_writable 0#u64; pteflags_executable a) = ok 12#u64 := by
  unfold pteflags_writable pteflags_executable flags.PteFlags.writable
    flags.PteFlags.executable flags.PteFlags.W flags.PteFlags.X
  rfl

theorem and_that_entry_reports_both :
    pteflags_is_writable 12#u64 = ok true := by
  unfold pteflags_is_writable flags.PteFlags.is_writable flags.PteFlags.W; rfl

theorem and_reports_executable_too :
    pteflags_is_executable 12#u64 = ok true := by
  unfold pteflags_is_executable flags.PteFlags.is_executable flags.PteFlags.X; rfl

/-- Validity is the low bit and is independent of the permission bits, so an
    entry built with permissions and never marked valid still reports as
    writable while the hardware will not walk it. Worth knowing when reading a
    dump. -/
theorem permissions_are_reported_on_an_invalid_entry :
    pteflags_is_valid 12#u64 = ok false := by
  unfold pteflags_is_valid flags.PteFlags.is_valid flags.PteFlags.V; rfl

/-! ### Each builder sets its own bit, each reader reads its own

    For every word, `readable`, `global`, `accessed` and `dirty` set exactly bits
    1, 5, 6 and 7 and keep every other bit, and `is_readable` and `is_user` read
    bits 1 and 4, the Sv39 encoding. `from_bits` and `bits` pass the word through
    unchanged and `new` is the empty entry.

    `is_leaf` reads R, W or X and ignores V, while `page_table.rs::is_leaf_entry`
    requires V. So for the entry `0x2`, R with V clear, this predicate answers
    leaf where the other copy and the hardware see an invalid entry, and it also
    calls the reserved W-without-R encoding a leaf. `is_leaf` has no caller
    today; the two theorems at the end pin both so a caller cannot be added
    without seeing them.
-/

private theorem sets_bit (f : Std.U64) (k : Nat) (hk : k < 64) (c : Std.U64) (hc : c.val = 2 ^ k) (i : Nat) :
    (f ||| c).val.testBit i = (f.val.testBit i || decide (i = k)) := by
  rw [UScalar.val_or, Nat.testBit_or, hc, Nat.testBit_two_pow]
  by_cases h : i = k
  · subst h
    simp
  · have h' : ¬ k = i := fun e => h e.symm
    simp only [h, h', decide_false]

theorem readable_sets_bit_one_and_keeps_the_rest (f : Std.U64) :
    ∃ g, pteflags_readable f = ok g ∧ ∀ i, g.val.testBit i = (f.val.testBit i || decide (i = 1)) := by
  refine ⟨f ||| 2#u64, ?_, sets_bit f 1 (by decide) 2#u64 rfl⟩
  unfold pteflags_readable flags.PteFlags.readable flags.PteFlags.R
  rfl

theorem global_sets_bit_five_and_keeps_the_rest (f : Std.U64) :
    ∃ g, pteflags_global f = ok g ∧ ∀ i, g.val.testBit i = (f.val.testBit i || decide (i = 5)) := by
  refine ⟨f ||| 32#u64, ?_, sets_bit f 5 (by decide) 32#u64 rfl⟩
  unfold pteflags_global flags.PteFlags.global flags.PteFlags.G
  rfl

theorem accessed_sets_bit_six_and_keeps_the_rest (f : Std.U64) :
    ∃ g, pteflags_accessed f = ok g ∧ ∀ i, g.val.testBit i = (f.val.testBit i || decide (i = 6)) := by
  refine ⟨f ||| 64#u64, ?_, sets_bit f 6 (by decide) 64#u64 rfl⟩
  unfold pteflags_accessed flags.PteFlags.accessed flags.PteFlags.A
  rfl

theorem dirty_sets_bit_seven_and_keeps_the_rest (f : Std.U64) :
    ∃ g, pteflags_dirty f = ok g ∧ ∀ i, g.val.testBit i = (f.val.testBit i || decide (i = 7)) := by
  refine ⟨f ||| 128#u64, ?_, sets_bit f 7 (by decide) 128#u64 rfl⟩
  unfold pteflags_dirty flags.PteFlags.dirty flags.PteFlags.D
  rfl

theorem is_readable_reads_bit_one (f : Std.U64) :
    pteflags_is_readable f = ok (f.val.testBit 1) := by
  unfold pteflags_is_readable flags.PteFlags.is_readable flags.PteFlags.R
  have hs : (1#u64 <<< 1#i32 : Result Std.U64) = ok 2#u64 := by rfl
  simp only [hs, lift, bind_tc_ok]
  rw [Bits.reads_bit f 2#u64 0#u64 1 rfl rfl]

theorem is_user_reads_bit_four (f : Std.U64) :
    pteflags_is_user f = ok (f.val.testBit 4) := by
  unfold pteflags_is_user flags.PteFlags.is_user flags.PteFlags.U
  have hs : (1#u64 <<< 4#i32 : Result Std.U64) = ok 16#u64 := by rfl
  simp only [hs, lift, bind_tc_ok]
  rw [Bits.reads_bit f 16#u64 0#u64 4 rfl rfl]

theorem the_word_passes_through (w : Std.U64) :
    (do let f ← pteflags_from_bits w; pteflags_bits f) = ok w := rfl

theorem the_new_entry_is_empty_and_not_readable :
    pteflags_new = ok 0#u64 ∧ pteflags_is_readable 0#u64 = ok false ∧
      pteflags_is_user 0#u64 = ok false := by
  refine ⟨rfl, ?_, ?_⟩
  · rw [is_readable_reads_bit_one]; rfl
  · rw [is_user_reads_bit_four]; rfl

/-- The leaf test reads R, W and X, and nothing else. -/
theorem is_leaf_reads_r_w_or_x (f : Std.U64) :
    pteflags_is_leaf f = ok (f.val.testBit 1 || f.val.testBit 2 || f.val.testBit 3) := by
  unfold pteflags_is_leaf flags.PteFlags.is_leaf flags.PteFlags.R flags.PteFlags.W flags.PteFlags.X
  have h1 : (1#u64 <<< 1#i32 : Result Std.U64) = ok 2#u64 := by rfl
  have h2 : (1#u64 <<< 2#i32 : Result Std.U64) = ok 4#u64 := by rfl
  have h3 : (1#u64 <<< 3#i32 : Result Std.U64) = ok 8#u64 := by rfl
  simp only [h1, h2, h3, lift, bind_tc_ok, ok.injEq]
  have hm : ((2#u64 : Std.U64) ||| 4#u64 ||| 8#u64) = 14#u64 := by rfl
  rw [hm]
  have hv : (f &&& 14#u64).val = f.val &&& 14 := UScalar.val_and _ _
  cases h : (f.val.testBit 1 || f.val.testBit 2 || f.val.testBit 3)
  · simp only [Bool.or_eq_false_iff] at h
    have hz : (f &&& 14#u64) = 0#u64 := by
      apply UScalar.eq_of_val_eq
      rw [hv, show (0#u64 : Std.U64).val = 0 from rfl]
      apply Nat.eq_of_testBit_eq
      intro i
      rw [Nat.testBit_and, Nat.zero_testBit]
      match i with
      | 0 => simp
      | 1 => simp [h.1.1]
      | 2 => simp [h.1.2]
      | 3 => simp [h.2]
      | n + 4 =>
        have h14 : (14 : Nat).testBit (n + 4) = false :=
          Nat.testBit_eq_false_of_lt (Nat.lt_of_lt_of_le (by decide) (Nat.pow_le_pow_right (by decide) (Nat.le_add_left 4 n)))
        simp [h14]
    simp [hz]
  · have hne : (f &&& 14#u64) ≠ 0#u64 := by
      intro h0
      have h0v := congrArg (fun v : Std.U64 => v.val) h0
      simp only [hv, show (0#u64 : Std.U64).val = 0 from rfl] at h0v
      simp only [Bool.or_eq_true] at h
      rcases h with (h | h) | h
      · have := congrArg (fun n => Nat.testBit n 1) h0v
        simp only [Nat.testBit_and, h, Nat.zero_testBit, Bool.true_and] at this
        exact absurd this (by decide)
      · have := congrArg (fun n => Nat.testBit n 2) h0v
        simp only [Nat.testBit_and, h, Nat.zero_testBit, Bool.true_and] at this
        exact absurd this (by decide)
      · have := congrArg (fun n => Nat.testBit n 3) h0v
        simp only [Nat.testBit_and, h, Nat.zero_testBit, Bool.true_and] at this
        exact absurd this (by decide)
    simp [bne_iff_ne, hne]

/-- Records the disagreement: `0x2`, R set and V clear, is invalid to the hardware
    and to `is_leaf_entry`, and a leaf here. -/
theorem an_invalid_entry_is_called_a_leaf :
    pteflags_is_leaf 2#u64 = ok true ∧ pteflags_is_valid 2#u64 = ok false := by
  refine ⟨by rw [is_leaf_reads_r_w_or_x]; rfl, ?_⟩
  unfold pteflags_is_valid flags.PteFlags.is_valid flags.PteFlags.V
  rfl

/-- Records the reserved encoding: V and W without R is reserved by the RISC-V
    privileged specification and must fault, and it is a leaf here. -/
theorem the_reserved_write_only_encoding_is_called_a_leaf :
    pteflags_is_leaf 5#u64 = ok true := by
  rw [is_leaf_reads_r_w_or_x]; rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.RvFlags.the_valid_builder_sets_bit_zero
#print axioms NonosExtraction.RvFlags.the_writable_builder_sets_bit_two
#print axioms NonosExtraction.RvFlags.the_executable_builder_sets_bit_three
#print axioms NonosExtraction.RvFlags.the_user_builder_sets_bit_four
#print axioms NonosExtraction.RvFlags.nothing_here_refuses_write_and_execute
#print axioms NonosExtraction.RvFlags.and_that_entry_reports_both
#print axioms NonosExtraction.RvFlags.and_reports_executable_too
#print axioms NonosExtraction.RvFlags.permissions_are_reported_on_an_invalid_entry
#print axioms NonosExtraction.RvFlags.nothing_here_refuses_write_and_execute
#print axioms NonosExtraction.RvFlags.the_pteflags_new_wrapper_is_its_method
#print axioms NonosExtraction.RvFlags.the_pteflags_from_bits_wrapper_is_its_method
#print axioms NonosExtraction.RvFlags.the_pteflags_valid_wrapper_is_its_method
#print axioms NonosExtraction.RvFlags.the_pteflags_readable_wrapper_is_its_method
#print axioms NonosExtraction.RvFlags.the_pteflags_writable_wrapper_is_its_method
#print axioms NonosExtraction.RvFlags.the_pteflags_executable_wrapper_is_its_method
#print axioms NonosExtraction.RvFlags.the_pteflags_user_wrapper_is_its_method
#print axioms NonosExtraction.RvFlags.the_pteflags_global_wrapper_is_its_method
#print axioms NonosExtraction.RvFlags.the_pteflags_accessed_wrapper_is_its_method
#print axioms NonosExtraction.RvFlags.the_pteflags_dirty_wrapper_is_its_method
#print axioms NonosExtraction.RvFlags.the_pteflags_bits_wrapper_is_its_method
#print axioms NonosExtraction.RvFlags.the_pteflags_is_valid_wrapper_is_its_method
#print axioms NonosExtraction.RvFlags.the_pteflags_is_leaf_wrapper_is_its_method
#print axioms NonosExtraction.RvFlags.the_pteflags_is_readable_wrapper_is_its_method
#print axioms NonosExtraction.RvFlags.the_pteflags_is_writable_wrapper_is_its_method
#print axioms NonosExtraction.RvFlags.the_pteflags_is_executable_wrapper_is_its_method
#print axioms NonosExtraction.RvFlags.the_pteflags_is_user_wrapper_is_its_method
#print axioms NonosExtraction.RvFlags.readable_sets_bit_one_and_keeps_the_rest
#print axioms NonosExtraction.RvFlags.global_sets_bit_five_and_keeps_the_rest
#print axioms NonosExtraction.RvFlags.accessed_sets_bit_six_and_keeps_the_rest
#print axioms NonosExtraction.RvFlags.dirty_sets_bit_seven_and_keeps_the_rest
#print axioms NonosExtraction.RvFlags.is_readable_reads_bit_one
#print axioms NonosExtraction.RvFlags.is_user_reads_bit_four
#print axioms NonosExtraction.RvFlags.the_word_passes_through
#print axioms NonosExtraction.RvFlags.the_new_entry_is_empty_and_not_readable
#print axioms NonosExtraction.RvFlags.is_leaf_reads_r_w_or_x
#print axioms NonosExtraction.RvFlags.an_invalid_entry_is_called_a_leaf
#print axioms NonosExtraction.RvFlags.the_reserved_write_only_encoding_is_called_a_leaf

end NonosExtraction.RvFlags
