-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [nonos_x_sdt_entry_count]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace nonos_x_sdt_entry_count

/-- [nonos_x_sdt_entry_count::entry_count::sdt_entry_count]:
    Source: 'src/../../../../../src/arch/x86_64/acpi/tables/sdt/entry_count.rs', lines 29:0-34:1
    Visibility: public -/
def entry_count.sdt_entry_count
  (table_length : Std.Usize) (header_size : Std.Usize) (entry_size : Std.Usize)
  :
  Result Std.Usize
  := do
  if entry_size = 0#usize
  then ok 0#usize
  else
    let i ← lift (core.num.Usize.saturating_sub table_length header_size)
    i / entry_size

/-- [nonos_x_sdt_entry_count::sdt_entry_count]:
    Source: 'src/lib.rs', lines 10:0-12:1
    Visibility: public -/
def sdt_entry_count
  (table_length : Std.Usize) (header_size : Std.Usize) (entry_size : Std.Usize)
  :
  Result Std.Usize
  := do
  entry_count.sdt_entry_count table_length header_size entry_size

end nonos_x_sdt_entry_count
