-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [nonos_x_security_attest_registry_entry]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace nonos_x_security_attest_registry_entry

/-- [nonos_x_security_attest_registry_entry::security::dev_roots::authority::Authority]
    Source: 'src/security/dev_roots/../../../../../../../src/security/dev_roots/authority.rs', lines 25:0-37:1
    Visibility: public -/
@[discriminant isize]
inductive security.dev_roots.authority.Authority where
| Vendor : security.dev_roots.authority.Authority
| Developer : Std.U8 → security.dev_roots.authority.Authority
| Publisher : security.dev_roots.authority.Authority

/-- [nonos_x_security_attest_registry_entry::security::attest_registry::entry::AttestedCapsule]
    Source: 'src/security/attest_registry/../../../../../../../src/security/attest_registry/entry.rs', lines 27:0-34:1
    Visibility: public -/
structure security.attest_registry.entry.AttestedCapsule where
  pid : Std.U32
  measurement : Array Std.U8 32#usize
  caps : Std.U64
  authority : security.dev_roots.authority.Authority

/-- [nonos_x_security_attest_registry_entry::security::attest_registry::entry::{nonos_x_security_attest_registry_entry::security::attest_registry::entry::AttestedCapsule}::empty]:
    Source: 'src/security/attest_registry/../../../../../../../src/security/attest_registry/entry.rs', lines 37:4-39:5
    Visibility: public -/
def security.attest_registry.entry.AttestedCapsule.empty
  : Result security.attest_registry.entry.AttestedCapsule := do
  let a := Array.repeat 32#usize 0#u8
  ok
    {
      pid := 0#u32,
      measurement := a,
      caps := 0#u64,
      authority := security.dev_roots.authority.Authority.Vendor
    }

/-- [nonos_x_security_attest_registry_entry::attestedcapsule_empty]:
    Source: 'src/lib.rs', lines 11:0-13:1
    Visibility: public -/
def attestedcapsule_empty
  : Result security.attest_registry.entry.AttestedCapsule := do
  security.attest_registry.entry.AttestedCapsule.empty

end nonos_x_security_attest_registry_entry
