/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

types, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.SecurityBootSecureBootTypes

open Aeneas Aeneas.Std Result
open nonos_x_security_boot_secure_boot_types

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.SecurityBootSecureBootTypes

/-! ### The forwarding functions add nothing -/

theorem the_bootmeasurements_new_wrapper_is_its_method :
    bootmeasurements_new = security.boot.secure_boot.types.BootMeasurements.new := rfl

theorem the_bootmeasurements_has_initrd_wrapper_is_its_method (a : security.boot.secure_boot.types.BootMeasurements) :
    bootmeasurements_has_initrd a = security.boot.secure_boot.types.BootMeasurements.has_initrd a := rfl

theorem the_bootmeasurements_has_acpi_wrapper_is_its_method (a : security.boot.secure_boot.types.BootMeasurements) :
    bootmeasurements_has_acpi a = security.boot.secure_boot.types.BootMeasurements.has_acpi a := rfl

theorem the_bootmeasurements_is_signature_valid_wrapper_is_its_method (a : security.boot.secure_boot.types.BootMeasurements) :
    bootmeasurements_is_signature_valid a = security.boot.secure_boot.types.BootMeasurements.is_signature_valid a := rfl

theorem the_bootmeasurements_is_uefi_secure_boot_wrapper_is_its_method (a : security.boot.secure_boot.types.BootMeasurements) :
    bootmeasurements_is_uefi_secure_boot a = security.boot.secure_boot.types.BootMeasurements.is_uefi_secure_boot a := rfl

theorem the_bootmeasurements_get_boot_timestamp_wrapper_is_its_method (a : security.boot.secure_boot.types.BootMeasurements) :
    bootmeasurements_get_boot_timestamp a = security.boot.secure_boot.types.BootMeasurements.get_boot_timestamp a := rfl

theorem the_bootmeasurements_is_chain_verified_wrapper_is_its_method (a : security.boot.secure_boot.types.BootMeasurements) :
    bootmeasurements_is_chain_verified a = security.boot.secure_boot.types.BootMeasurements.is_chain_verified a := rfl

theorem the_trustedbootkeys_new_wrapper_is_its_method :
    trustedbootkeys_new = security.boot.secure_boot.types.TrustedBootKeys.new := rfl

theorem the_trustedbootkeys_get_rotation_count_wrapper_is_its_method (a : security.boot.secure_boot.types.TrustedBootKeys) :
    trustedbootkeys_get_rotation_count a = security.boot.secure_boot.types.TrustedBootKeys.get_rotation_count a := rfl

theorem the_trustedbootkeys_total_keys_wrapper_is_its_method (a : security.boot.secure_boot.types.TrustedBootKeys) :
    trustedbootkeys_total_keys a = security.boot.secure_boot.types.TrustedBootKeys.total_keys a := rfl

theorem the_trustedkey_created_at_wrapper_is_its_method (a : security.boot.secure_boot.types.TrustedKey) :
    trustedkey_created_at a = security.boot.secure_boot.types.TrustedKey.impl.created_at a := rfl

theorem the_trustedkey_expires_at_wrapper_is_its_method (a : security.boot.secure_boot.types.TrustedKey) :
    trustedkey_expires_at a = security.boot.secure_boot.types.TrustedKey.impl.expires_at a := rfl

theorem the_trustedkey_is_production_wrapper_is_its_method (a : security.boot.secure_boot.types.TrustedKey) :
    trustedkey_is_production a = security.boot.secure_boot.types.TrustedKey.impl.is_production a := rfl

theorem the_trustedkey_is_expired_wrapper_is_its_method (a : security.boot.secure_boot.types.TrustedKey) (b : Std.U64) :
    trustedkey_is_expired a b = security.boot.secure_boot.types.TrustedKey.is_expired a b := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.SecurityBootSecureBootTypes.the_bootmeasurements_new_wrapper_is_its_method
#print axioms NonosExtraction.SecurityBootSecureBootTypes.the_bootmeasurements_has_initrd_wrapper_is_its_method
#print axioms NonosExtraction.SecurityBootSecureBootTypes.the_bootmeasurements_has_acpi_wrapper_is_its_method
#print axioms NonosExtraction.SecurityBootSecureBootTypes.the_bootmeasurements_is_signature_valid_wrapper_is_its_method
#print axioms NonosExtraction.SecurityBootSecureBootTypes.the_bootmeasurements_is_uefi_secure_boot_wrapper_is_its_method
#print axioms NonosExtraction.SecurityBootSecureBootTypes.the_bootmeasurements_get_boot_timestamp_wrapper_is_its_method
#print axioms NonosExtraction.SecurityBootSecureBootTypes.the_bootmeasurements_is_chain_verified_wrapper_is_its_method
#print axioms NonosExtraction.SecurityBootSecureBootTypes.the_trustedbootkeys_new_wrapper_is_its_method
#print axioms NonosExtraction.SecurityBootSecureBootTypes.the_trustedbootkeys_get_rotation_count_wrapper_is_its_method
#print axioms NonosExtraction.SecurityBootSecureBootTypes.the_trustedbootkeys_total_keys_wrapper_is_its_method
#print axioms NonosExtraction.SecurityBootSecureBootTypes.the_trustedkey_created_at_wrapper_is_its_method
#print axioms NonosExtraction.SecurityBootSecureBootTypes.the_trustedkey_expires_at_wrapper_is_its_method
#print axioms NonosExtraction.SecurityBootSecureBootTypes.the_trustedkey_is_production_wrapper_is_its_method
#print axioms NonosExtraction.SecurityBootSecureBootTypes.the_trustedkey_is_expired_wrapper_is_its_method

end NonosExtraction.SecurityBootSecureBootTypes
