-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [nonos_x_security_mmio_range]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace nonos_x_security_mmio_range

/-- [nonos_x_security_mmio_range::mmio_range::range_ok]:
    Source: 'src/../../../../../src/drivers/security/mmio_range.rs', lines 25:0-33:1 -/
def mmio_range.range_ok
  (base : Std.Usize) (size : Std.Usize) : Result Bool := do
  if size = 0#usize
  then ok false
  else
    let o ← lift (Usize.checked_add base size)
    match o with
    | none => ok false
    | some end1 => ok (end1 > base)

/-- [nonos_x_security_mmio_range::range_ok]:
    Source: 'src/lib.rs', lines 10:0-12:1
    Visibility: public -/
def range_ok (base : Std.Usize) (size : Std.Usize) : Result Bool := do
  mmio_range.range_ok base size

end nonos_x_security_mmio_range
