/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

respawn, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.ServicesLifecycleStateRespawn

open Aeneas Aeneas.Std Result
open nonos_x_services_lifecycle_state_respawn

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.ServicesLifecycleStateRespawn

/-! ### The forwarding functions add nothing -/

theorem the_capsulestate_restart_count_wrapper_is_its_method (a : services.lifecycle.state.types.CapsuleState) :
    capsulestate_restart_count a = services.lifecycle.state.respawn.CapsuleState.restart_count a := rfl

theorem the_capsulestate_last_exit_ms_wrapper_is_its_method (a : services.lifecycle.state.types.CapsuleState) :
    capsulestate_last_exit_ms a = services.lifecycle.state.respawn.CapsuleState.last_exit_ms a := rfl

theorem the_capsulestate_record_exit_wrapper_is_its_method (a : services.lifecycle.state.types.CapsuleState) (b : Std.U64) :
    capsulestate_record_exit a b = services.lifecycle.state.respawn.CapsuleState.record_exit a b := rfl

theorem the_capsulestate_should_respawn_wrapper_is_its_method (a : services.lifecycle.state.types.CapsuleState) (b : Std.U64) :
    capsulestate_should_respawn a b = services.lifecycle.state.respawn.CapsuleState.should_respawn a b := rfl

theorem the_capsulestate_set_max_restarts_wrapper_is_its_method (a : services.lifecycle.state.types.CapsuleState) (b : Std.U32) :
    capsulestate_set_max_restarts a b = services.lifecycle.state.respawn.CapsuleState.set_max_restarts a b := rfl

theorem the_capsulestate_set_debounce_ms_wrapper_is_its_method (a : services.lifecycle.state.types.CapsuleState) (b : Std.U64) :
    capsulestate_set_debounce_ms a b = services.lifecycle.state.respawn.CapsuleState.set_debounce_ms a b := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.ServicesLifecycleStateRespawn.the_capsulestate_restart_count_wrapper_is_its_method
#print axioms NonosExtraction.ServicesLifecycleStateRespawn.the_capsulestate_last_exit_ms_wrapper_is_its_method
#print axioms NonosExtraction.ServicesLifecycleStateRespawn.the_capsulestate_record_exit_wrapper_is_its_method
#print axioms NonosExtraction.ServicesLifecycleStateRespawn.the_capsulestate_should_respawn_wrapper_is_its_method
#print axioms NonosExtraction.ServicesLifecycleStateRespawn.the_capsulestate_set_max_restarts_wrapper_is_its_method
#print axioms NonosExtraction.ServicesLifecycleStateRespawn.the_capsulestate_set_debounce_ms_wrapper_is_its_method

end NonosExtraction.ServicesLifecycleStateRespawn
