-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [nonos_x_services_caps_types]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace nonos_x_services_caps_types

/-- [nonos_x_services_caps_types::services::caps::types::ServiceCap]
    Source: 'src/services/caps/../../../../../../../src/services/caps/types.rs', lines 73:0-77:1
    Visibility: public -/
structure services.caps.types.ServiceCap where
  bits : Std.U64
  owner_pid : Std.U32
  expires_ms : Std.U64

/-- [nonos_x_services_caps_types::services::caps::types::{nonos_x_services_caps_types::services::caps::types::ServiceCap}::new]:
    Source: 'src/services/caps/../../../../../../../src/services/caps/types.rs', lines 80:4-82:5
    Visibility: public -/
def services.caps.types.ServiceCap.new
  (bits : Std.U64) (owner : Std.U32) :
  Result services.caps.types.ServiceCap
  := do
  ok { bits, owner_pid := owner, expires_ms := 0#u64 }

/-- [nonos_x_services_caps_types::servicecap_new]:
    Source: 'src/lib.rs', lines 13:0-15:1
    Visibility: public -/
def servicecap_new
  (bits : Std.U64) (owner : Std.U32) :
  Result services.caps.types.ServiceCap
  := do
  services.caps.types.ServiceCap.new bits owner

/-- [nonos_x_services_caps_types::services::caps::types::{nonos_x_services_caps_types::services::caps::types::ServiceCap}::with_expiry]:
    Source: 'src/services/caps/../../../../../../../src/services/caps/types.rs', lines 84:4-86:5
    Visibility: public -/
def services.caps.types.ServiceCap.with_expiry
  (bits : Std.U64) (owner : Std.U32) (expires_ms : Std.U64) :
  Result services.caps.types.ServiceCap
  := do
  ok { bits, owner_pid := owner, expires_ms }

/-- [nonos_x_services_caps_types::servicecap_with_expiry]:
    Source: 'src/lib.rs', lines 17:0-19:1
    Visibility: public -/
def servicecap_with_expiry
  (bits : Std.U64) (owner : Std.U32) (expires_ms : Std.U64) :
  Result services.caps.types.ServiceCap
  := do
  services.caps.types.ServiceCap.with_expiry bits owner expires_ms

/-- [nonos_x_services_caps_types::services::caps::types::{nonos_x_services_caps_types::services::caps::types::ServiceCap}::has]:
    Source: 'src/services/caps/../../../../../../../src/services/caps/types.rs', lines 88:4-90:5
    Visibility: public -/
def services.caps.types.ServiceCap.has
  (self : services.caps.types.ServiceCap) (cap : Std.U64) : Result Bool := do
  let i ← lift (self.bits &&& cap)
  ok (i = cap)

/-- [nonos_x_services_caps_types::servicecap_has]:
    Source: 'src/lib.rs', lines 21:0-23:1
    Visibility: public -/
def servicecap_has
  (this : services.caps.types.ServiceCap) (cap : Std.U64) : Result Bool := do
  services.caps.types.ServiceCap.has this cap

/-- [nonos_x_services_caps_types::services::caps::types::{nonos_x_services_caps_types::services::caps::types::ServiceCap}::is_expired]:
    Source: 'src/services/caps/../../../../../../../src/services/caps/types.rs', lines 92:4-94:5
    Visibility: public -/
def services.caps.types.ServiceCap.is_expired
  (self : services.caps.types.ServiceCap) (now_ms : Std.U64) :
  Result Bool
  := do
  if self.expires_ms != 0#u64
  then ok (now_ms > self.expires_ms)
  else ok false

/-- [nonos_x_services_caps_types::servicecap_is_expired]:
    Source: 'src/lib.rs', lines 25:0-27:1
    Visibility: public -/
def servicecap_is_expired
  (this : services.caps.types.ServiceCap) (now_ms : Std.U64) :
  Result Bool
  := do
  services.caps.types.ServiceCap.is_expired this now_ms

end nonos_x_services_caps_types
