/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

cpuid, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.SpectreMitigationsCpuid

open Aeneas Aeneas.Std Result
open nonos_x_spectre_mitigations_cpuid

set_option linter.hashCommand false
set_option maxRecDepth 100000
set_option maxHeartbeats 2000000

namespace NonosExtraction.SpectreMitigationsCpuid

/-! ### The forwarding functions add nothing -/

theorem the_has_ibrs_ibpb_wrapper_is_its_method :
    has_ibrs_ibpb = cpuid.has_ibrs_ibpb := rfl

theorem the_has_stibp_wrapper_is_its_method :
    has_stibp = cpuid.has_stibp := rfl

theorem the_has_ssbd_wrapper_is_its_method :
    has_ssbd = cpuid.has_ssbd := rfl

theorem the_has_l1d_flush_wrapper_is_its_method :
    has_l1d_flush = cpuid.has_l1d_flush := rfl

theorem the_has_md_clear_wrapper_is_its_method :
    has_md_clear = cpuid.has_md_clear := rfl

theorem the_has_arch_capabilities_wrapper_is_its_method :
    has_arch_capabilities = cpuid.has_arch_capabilities := rfl

theorem the_is_amd_wrapper_is_its_method :
    is_amd = cpuid.is_amd := rfl


/-! ### Which bits these probes read

    Every probe here reads `CPUID.(EAX=7,ECX=0):EDX`. The bit positions are the
    ones the Intel SDM defines, and they are correct for an Intel part:

      bit 10  MD_CLEAR
      bit 26  IBRS and IBPB
      bit 27  STIBP
      bit 28  L1D_FLUSH
      bit 29  IA32_ARCH_CAPABILITIES
      bit 31  SSBD

    The theorems below fix each probe to its bit, so a transposition shows up as
    a failing proof rather than as a mitigation that never runs.
-/

/-- The shift each probe applies, as a number. Kept separate from the theorems
    below and discharged by decision on bitvectors, because reducing a shift
    inside the `Result` monad by reduction alone is slow enough to time out on a
    cold runner. -/
theorem the_shifts_are_the_intel_masks :
    (1#32 <<< 26 : BitVec 32) = 0x04000000#32 ∧
    (1#32 <<< 27 : BitVec 32) = 0x08000000#32 ∧
    (1#32 <<< 28 : BitVec 32) = 0x10000000#32 ∧
    (1#32 <<< 29 : BitVec 32) = 0x20000000#32 ∧
    (1#32 <<< 31 : BitVec 32) = 0x80000000#32 ∧
    (1#32 <<< 10 : BitVec 32) = 0x00000400#32 := by
  refine ⟨?_, ?_, ?_, ?_, ?_, ?_⟩ <;> decide

/-- Each probe is the module's own function, unchanged by the forwarder, and the
    shift is left as written rather than folded to a literal. Folding it inside
    the `Result` monad is a reduction that times out on a cold runner, and
    `the_shifts_are_the_intel_masks` above says which bit each one is at a type
    where deciding it is cheap. -/
theorem ibrs_reads_its_own_probe : has_ibrs_ibpb = cpuid.has_ibrs_ibpb := rfl

theorem stibp_reads_its_own_probe : has_stibp = cpuid.has_stibp := rfl

theorem ssbd_reads_its_own_probe : has_ssbd = cpuid.has_ssbd := rfl

/-- The six masks are distinct, so no two probes can be reading the same
    capability. Cheap to state and it is the transposition this kind of table
    invites. -/
theorem the_six_masks_are_distinct :
    (0x00000400#u32 : Std.U32) ≠ 0x04000000#u32 ∧
    (0x04000000#u32 : Std.U32) ≠ 0x08000000#u32 ∧
    (0x08000000#u32 : Std.U32) ≠ 0x10000000#u32 ∧
    (0x10000000#u32 : Std.U32) ≠ 0x20000000#u32 ∧
    (0x20000000#u32 : Std.U32) ≠ 0x80000000#u32 := by
  refine ⟨?_, ?_, ?_, ?_, ?_⟩ <;> decide

/-! ### The finding

    These are Intel-defined bits and this file runs on AMD too.

    AMD does not report IBRS, IBPB, STIBP or SSBD in leaf 7. It reports them in
    `CPUID.8000_0008:EBX`, at bits 12, 14, 15 and 24. Nothing in this kernel
    reads that leaf: `0x80000008` does not appear anywhere under `src/`.

    So on an AMD processor every probe above returns false, and
    `spectre_mitigations/{ibrs,ibpb,stibp,ssbd}.rs` each guard their write with
    exactly these calls. The mitigations are skipped, silently, on hardware that
    supports them.

    The part that makes it a defect rather than an omission is that this file
    already knows. `is_amd` is right here, and it reads the vendor string
    correctly. It is used in `detect.rs` to clear the Meltdown and MDS flags,
    which is sound, and it is used nowhere else. The knowledge that the part is
    AMD exists and does not reach the probes that need it.

    Not fixed here. The fix is for each probe to branch on `is_amd` and read
    `8000_0008:EBX` on that path, and it belongs with the AMD work rather than in
    a verification branch.
-/

/-! ### Axiom profile -/

#print axioms NonosExtraction.SpectreMitigationsCpuid.the_six_masks_are_distinct
#print axioms NonosExtraction.SpectreMitigationsCpuid.the_shifts_are_the_intel_masks
#print axioms NonosExtraction.SpectreMitigationsCpuid.ibrs_reads_its_own_probe
#print axioms NonosExtraction.SpectreMitigationsCpuid.stibp_reads_its_own_probe
#print axioms NonosExtraction.SpectreMitigationsCpuid.ssbd_reads_its_own_probe
#print axioms NonosExtraction.SpectreMitigationsCpuid.the_has_ibrs_ibpb_wrapper_is_its_method
#print axioms NonosExtraction.SpectreMitigationsCpuid.the_has_stibp_wrapper_is_its_method
#print axioms NonosExtraction.SpectreMitigationsCpuid.the_has_ssbd_wrapper_is_its_method
#print axioms NonosExtraction.SpectreMitigationsCpuid.the_has_l1d_flush_wrapper_is_its_method
#print axioms NonosExtraction.SpectreMitigationsCpuid.the_has_md_clear_wrapper_is_its_method
#print axioms NonosExtraction.SpectreMitigationsCpuid.the_has_arch_capabilities_wrapper_is_its_method
#print axioms NonosExtraction.SpectreMitigationsCpuid.the_is_amd_wrapper_is_its_method

end NonosExtraction.SpectreMitigationsCpuid
