/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

unsupported, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.SyscallMicrokernelPioUnsupported

open Aeneas Aeneas.Std Result
open nonos_x_syscall_microkernel_pio_unsupported

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.SyscallMicrokernelPioUnsupported

/-! ### The forwarding functions add nothing -/

theorem the_sys_pio_grant_wrapper_is_its_method (a : Std.U64) (b : Std.U64) (c : Std.U8) (d : Std.U32) (e : Std.U64) :
    sys_pio_grant a b c d e = syscall.microkernel.pio.unsupported.sys_pio_grant a b c d e := rfl

theorem the_sys_pio_read_wrapper_is_its_method (a : Std.U64) (b : Std.U64) (c : Std.U64) (d : Std.U64) :
    sys_pio_read a b c d = syscall.microkernel.pio.unsupported.sys_pio_read a b c d := rfl

theorem the_sys_pio_write_wrapper_is_its_method (a : Std.U64) (b : Std.U64) (c : Std.U64) (d : Std.U64) :
    sys_pio_write a b c d = syscall.microkernel.pio.unsupported.sys_pio_write a b c d := rfl

theorem the_sys_pio_release_wrapper_is_its_method (a : Std.U64) :
    sys_pio_release a = syscall.microkernel.pio.unsupported.sys_pio_release a := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.SyscallMicrokernelPioUnsupported.the_sys_pio_grant_wrapper_is_its_method
#print axioms NonosExtraction.SyscallMicrokernelPioUnsupported.the_sys_pio_read_wrapper_is_its_method
#print axioms NonosExtraction.SyscallMicrokernelPioUnsupported.the_sys_pio_write_wrapper_is_its_method
#print axioms NonosExtraction.SyscallMicrokernelPioUnsupported.the_sys_pio_release_wrapper_is_its_method

end NonosExtraction.SyscallMicrokernelPioUnsupported
