/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

convert, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.SysTimerTscConvert

open Aeneas Aeneas.Std Result
open nonos_x_sys_timer_tsc_convert

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.SysTimerTscConvert

/-! ### The forwarding functions add nothing -/

theorem the_tsc_frequency_wrapper_is_its_method :
    tsc_frequency = sys.timer.tsc.convert.tsc_frequency := rfl

theorem the_ticks_to_ns_wrapper_is_its_method (a : Std.U64) :
    ticks_to_ns a = sys.timer.tsc.convert.ticks_to_ns a := rfl

theorem the_ticks_to_us_wrapper_is_its_method (a : Std.U64) :
    ticks_to_us a = sys.timer.tsc.convert.ticks_to_us a := rfl

theorem the_ticks_to_ms_wrapper_is_its_method (a : Std.U64) :
    ticks_to_ms a = sys.timer.tsc.convert.ticks_to_ms a := rfl

theorem the_us_to_ticks_wrapper_is_its_method (a : Std.U64) :
    us_to_ticks a = sys.timer.tsc.convert.us_to_ticks a := rfl

theorem the_ms_to_ticks_wrapper_is_its_method (a : Std.U64) :
    ms_to_ticks a = sys.timer.tsc.convert.ms_to_ticks a := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.SysTimerTscConvert.the_tsc_frequency_wrapper_is_its_method
#print axioms NonosExtraction.SysTimerTscConvert.the_ticks_to_ns_wrapper_is_its_method
#print axioms NonosExtraction.SysTimerTscConvert.the_ticks_to_us_wrapper_is_its_method
#print axioms NonosExtraction.SysTimerTscConvert.the_ticks_to_ms_wrapper_is_its_method
#print axioms NonosExtraction.SysTimerTscConvert.the_us_to_ticks_wrapper_is_its_method
#print axioms NonosExtraction.SysTimerTscConvert.the_ms_to_ticks_wrapper_is_its_method

end NonosExtraction.SysTimerTscConvert
