/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

memory_type, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.TablesMemoryType

open Aeneas Aeneas.Std Result
open nonos_x_tables_memory_type

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.TablesMemoryType

/-! ### The forwarding functions add nothing -/

theorem the_memorytype_is_usable_wrapper_is_its_method (a : memory_type.MemoryType) :
    memorytype_is_usable a = memory_type.MemoryType.is_usable a := rfl

theorem the_memorytype_is_reserved_wrapper_is_its_method (a : memory_type.MemoryType) :
    memorytype_is_reserved a = memory_type.MemoryType.is_reserved a := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.TablesMemoryType.the_memorytype_is_usable_wrapper_is_its_method
#print axioms NonosExtraction.TablesMemoryType.the_memorytype_is_reserved_wrapper_is_its_method

end NonosExtraction.TablesMemoryType
