/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

sl_pte, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.TablesSlPte

open Aeneas Aeneas.Std Result
open nonos_x_tables_sl_pte

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.TablesSlPte

/-! ### The forwarding functions add nothing -/

theorem the_is_present_wrapper_is_its_method (a : Std.U64) :
    is_present a = sl_pte.is_present a := rfl

theorem the_entry_address_wrapper_is_its_method (a : Std.U64) :
    entry_address a = sl_pte.entry_address a := rfl

theorem the_leaf_wrapper_is_its_method (a : Std.U64) (b : Bool) (c : Bool) (d : Bool) :
    leaf a b c d = sl_pte.leaf a b c d := rfl

theorem the_table_wrapper_is_its_method (a : Std.U64) :
    table a = sl_pte.table a := rfl

theorem the_index_for_wrapper_is_its_method (a : Std.U64) (b : Std.U8) :
    index_for a b = sl_pte.index_for a b := rfl

theorem the_level_span_wrapper_is_its_method (a : Std.U8) :
    level_span a = sl_pte.level_span a := rfl

theorem the_fits_address_width_wrapper_is_its_method (a : Std.U64) (b : Std.U8) :
    fits_address_width a b = sl_pte.fits_address_width a b := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.TablesSlPte.the_is_present_wrapper_is_its_method
#print axioms NonosExtraction.TablesSlPte.the_entry_address_wrapper_is_its_method
#print axioms NonosExtraction.TablesSlPte.the_leaf_wrapper_is_its_method
#print axioms NonosExtraction.TablesSlPte.the_table_wrapper_is_its_method
#print axioms NonosExtraction.TablesSlPte.the_index_for_wrapper_is_its_method
#print axioms NonosExtraction.TablesSlPte.the_level_span_wrapper_is_its_method
#print axioms NonosExtraction.TablesSlPte.the_fits_address_width_wrapper_is_its_method

end NonosExtraction.TablesSlPte
