/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

memory_desc, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.TablesMemoryDesc
import NonosExtraction.Bits

open Aeneas Aeneas.Std Result
open nonos_x_tables_memory_desc

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.TablesMemoryDesc

/-! ### The forwarding functions add nothing -/

theorem the_memorydescriptor_size_bytes_wrapper_is_its_method (a : memory_desc.MemoryDescriptor) :
    memorydescriptor_size_bytes a = memory_desc.MemoryDescriptor.size_bytes a := rfl

theorem the_memorydescriptor_end_address_wrapper_is_its_method (a : memory_desc.MemoryDescriptor) :
    memorydescriptor_end_address a = memory_desc.MemoryDescriptor.end_address a := rfl

theorem the_memorydescriptor_is_runtime_wrapper_is_its_method (a : memory_desc.MemoryDescriptor) :
    memorydescriptor_is_runtime a = memory_desc.MemoryDescriptor.is_runtime a := rfl

theorem the_memorydescriptor_is_usable_wrapper_is_its_method (a : memory_desc.MemoryDescriptor) :
    memorydescriptor_is_usable a = memory_desc.MemoryDescriptor.is_usable a := rfl

/-! ### Page arithmetic, the runtime bit and the usable types

A UEFI memory descriptor counts its extent in 4 KiB pages, whatever the page size
of the machine. The theorems below fix the arithmetic exactly: `size_bytes` is the
page count times 4096, saturated at `2^64 - 1` from 2^52 pages upward, and
`end_address` is the exclusive end `physical_start + size`, saturated the same
way. Neither can fail. Both used to overflow on such a descriptor, and with
overflow checks on in every profile a firmware map with a descriptor reaching
the top of the address space, or claiming 2^52 pages or more, halted the kernel. `is_runtime` reads bit
63 of the attribute word and nothing else, and `is_usable` accepts exactly the
types 1, 2, 3, 4 and 7, which are the discriminants `LoaderCode`, `LoaderData`,
`BootServicesCode`, `BootServicesData` and `ConventionalMemory` of the kernel's
`MemoryType` enum in memory_type.rs (so the runtime services types 5 and 6, and
the ACPI types 9 and 10, are refused).

What this cannot establish: the descriptors come from firmware, so nothing here
says a firmware map is well formed, and no kernel caller of these methods is
extracted (none exists in the tree at present).
-/

private theorem u64_mul_ok (x y : Std.U64) (h : x.val * y.val < 2 ^ 64) :
    ∃ z, x * y = ok z ∧ z.val = x.val * y.val := by
  have hm := UScalar.mul_equiv x y
  rw [show (x * y : Result Std.U64) = UScalar.mul x y from rfl]
  cases hr : UScalar.mul x y with
  | ok z => rw [hr] at hm; exact ⟨z, rfl, hm.2.1⟩
  | fail e =>
    rw [hr] at hm
    simp only [UScalar.max_UScalarTy_U64_eq, U64.max_eq] at hm
    omega
  | div => rw [hr] at hm; exact hm.elim

private theorem u64_saturating_add_val (a b : Std.U64) :
    (core.num.U64.saturating_add a b).val = min (2 ^ 64 - 1) (a.val + b.val) := by
  simp only [core.num.U64.saturating_add, UScalar.saturating_add, UScalar.val, UScalar.max]
  rw [BitVec.toNat_ofNat]
  show min (2 ^ 64 - 1) _ % 2 ^ 64 = _
  exact Nat.mod_eq_of_lt (by omega)

/-- `size_bytes` never fails. It is the page count times 4096 below 2^52 pages
    and `2^64 - 1` from there up. A page size other than 4096 would move both the
    value and the bound. -/
theorem memorydescriptor_size_bytes_is_pages_of_4096_saturated
    (d : memory_desc.MemoryDescriptor) :
    ∃ s, memorydescriptor_size_bytes d = ok s ∧
      s.val = if d.number_of_pages.val < 2 ^ 52 then d.number_of_pages.val * 4096
        else 2 ^ 64 - 1 := by
  unfold memorydescriptor_size_bytes memory_desc.MemoryDescriptor.size_bytes
  have hq : (core.num.U64.MAX / 4096#u64 : Result Std.U64) = ok 0xFFFFFFFFFFFFF#u64 := by
    unfold core.num.U64.MAX; rfl
  simp only [hq, bind_tc_ok]
  by_cases h : d.number_of_pages.val < 2 ^ 52
  · have : ¬ d.number_of_pages > 0xFFFFFFFFFFFFF#u64 := by scalar_tac
    simp only [this, ↓reduceIte, h]
    obtain ⟨z, hz, hv⟩ := u64_mul_ok d.number_of_pages 4096#u64 (by
      show d.number_of_pages.val * 4096 < 2 ^ 64; omega)
    exact ⟨z, hz, hv⟩
  · have : d.number_of_pages > 0xFFFFFFFFFFFFF#u64 := by scalar_tac
    simp only [this, ↓reduceIte, h]
    exact ⟨_, rfl, by unfold core.num.U64.MAX; rfl⟩

/-- The boundary on concrete descriptors: 2^52 - 1 pages is the largest count
    whose size is exact, and one page more saturates instead of halting. -/
theorem memorydescriptor_size_bytes_at_the_page_count_limit :
    memorydescriptor_size_bytes
        { memory_type := 7#u32, physical_start := 0#u64, virtual_start := 0#u64,
          number_of_pages := 0xFFFFFFFFFFFFF#u64, «attribute» := 0#u64 } =
      ok 0xFFFFFFFFFFFFF000#u64 ∧
    memorydescriptor_size_bytes
        { memory_type := 7#u32, physical_start := 0#u64, virtual_start := 0#u64,
          number_of_pages := 0x10000000000000#u64, «attribute» := 0#u64 } =
      ok 0xFFFFFFFFFFFFFFFF#u64 := by
  constructor
  · obtain ⟨s, hs, hv⟩ := memorydescriptor_size_bytes_is_pages_of_4096_saturated
      { memory_type := 7#u32, physical_start := 0#u64, virtual_start := 0#u64,
        number_of_pages := 0xFFFFFFFFFFFFF#u64, «attribute» := 0#u64 }
    rw [hs]; congr 1; apply UScalar.eq_of_val_eq; rw [hv]; rfl
  · obtain ⟨s, hs, hv⟩ := memorydescriptor_size_bytes_is_pages_of_4096_saturated
      { memory_type := 7#u32, physical_start := 0#u64, virtual_start := 0#u64,
        number_of_pages := 0x10000000000000#u64, «attribute» := 0#u64 }
    rw [hs]; congr 1; apply UScalar.eq_of_val_eq; rw [hv]; rfl

/-- `end_address` never fails. It is the start plus the size, both as above,
    saturated at `2^64 - 1`; the virtual start plays no part. Below 2^52 pages
    and below the top of the address space it is the exact exclusive end. -/
theorem memorydescriptor_end_address_is_physical_start_plus_size_saturated
    (d : memory_desc.MemoryDescriptor) :
    ∃ e, memorydescriptor_end_address d = ok e ∧
      e.val = min (2 ^ 64 - 1) (d.physical_start.val +
        if d.number_of_pages.val < 2 ^ 52 then d.number_of_pages.val * 4096
        else 2 ^ 64 - 1) := by
  unfold memorydescriptor_end_address memory_desc.MemoryDescriptor.end_address
  obtain ⟨s, hs, hv⟩ := memorydescriptor_size_bytes_is_pages_of_4096_saturated d
  unfold memorydescriptor_size_bytes at hs
  rw [hs, bind_tc_ok]
  exact ⟨_, rfl, by rw [u64_saturating_add_val, hv]⟩

/-- A descriptor that covers the last page of the physical address space, whose
    exclusive end is 2^64, gets the saturated end `2^64 - 1`. It used to halt
    the kernel. -/
theorem memorydescriptor_end_address_saturates_on_the_top_page :
    memorydescriptor_end_address
      { memory_type := 7#u32, physical_start := 0xFFFFFFFFFFFFF000#u64,
        virtual_start := 0#u64, number_of_pages := 1#u64, «attribute» := 0#u64 } =
      ok 0xFFFFFFFFFFFFFFFF#u64 := by
  obtain ⟨e, he, hv⟩ := memorydescriptor_end_address_is_physical_start_plus_size_saturated
    { memory_type := 7#u32, physical_start := 0xFFFFFFFFFFFFF000#u64,
      virtual_start := 0#u64, number_of_pages := 1#u64, «attribute» := 0#u64 }
  rw [he]; congr 1; apply UScalar.eq_of_val_eq; rw [hv]; rfl

/-- `is_runtime` is bit 63 of the attribute word, `EFI_MEMORY_RUNTIME` in the UEFI
    specification, and no other bit. -/
theorem memorydescriptor_is_runtime_reads_bit_63 (d : memory_desc.MemoryDescriptor) :
    memorydescriptor_is_runtime d = ok (d.«attribute».val.testBit 63) := by
  unfold memorydescriptor_is_runtime memory_desc.MemoryDescriptor.is_runtime
  simp only [lift, bind_tc_ok]
  rw [NonosExtraction.Bits.reads_bit _ _ _ 63
    (by unfold memory_desc.MemoryDescriptor.EFI_MEMORY_RUNTIME; rfl) rfl]

/-- Since bit 63 is the top bit of the word, the same test is an ordering: the
    attribute is runtime exactly when it is at least 2^63. -/
theorem memorydescriptor_is_runtime_is_the_upper_half_of_attributes
    (d : memory_desc.MemoryDescriptor) :
    memorydescriptor_is_runtime d = ok (decide (2 ^ 63 ≤ d.«attribute».val)) := by
  rw [memorydescriptor_is_runtime_reads_bit_63, Nat.testBit_eq_decide_div_mod_eq]
  have hb := d.«attribute».hBounds
  simp only [UScalarTy.numBits] at hb
  congr 1
  by_cases h : 2 ^ 63 ≤ d.«attribute».val
  · simp only [h, decide_true]; simp; omega
  · simp only [h, decide_false]; simp; omega

/-- `is_usable` accepts exactly the five types the kernel's `MemoryType::is_usable`
    names, by discriminant: 1, 2, 3, 4 and 7. -/
theorem memorydescriptor_is_usable_accepts_exactly_types_1_2_3_4_7
    (d : memory_desc.MemoryDescriptor) :
    memorydescriptor_is_usable d =
      ok (decide (d.memory_type.val = 1 ∨ d.memory_type.val = 2 ∨ d.memory_type.val = 3 ∨
          d.memory_type.val = 4 ∨ d.memory_type.val = 7)) := by
  unfold memorydescriptor_is_usable memory_desc.MemoryDescriptor.is_usable
  split
  · rename_i heq; rw [heq]; rfl
  · rename_i heq; rw [heq]; rfl
  · rename_i heq; rw [heq]; rfl
  · rename_i heq; rw [heq]; rfl
  · rename_i heq; rw [heq]; rfl
  · rename_i h7 h1 h2 h3 h4
    have h7' : ¬ d.memory_type.val = 7 := fun h => h7 (UScalar.eq_of_val_eq (by rw [h]; rfl))
    have h1' : ¬ d.memory_type.val = 1 := fun h => h1 (UScalar.eq_of_val_eq (by rw [h]; rfl))
    have h2' : ¬ d.memory_type.val = 2 := fun h => h2 (UScalar.eq_of_val_eq (by rw [h]; rfl))
    have h3' : ¬ d.memory_type.val = 3 := fun h => h3 (UScalar.eq_of_val_eq (by rw [h]; rfl))
    have h4' : ¬ d.memory_type.val = 4 := fun h => h4 (UScalar.eq_of_val_eq (by rw [h]; rfl))
    have : ¬ (d.memory_type.val = 1 ∨ d.memory_type.val = 2 ∨ d.memory_type.val = 3 ∨
        d.memory_type.val = 4 ∨ d.memory_type.val = 7) := by omega
    rw [decide_eq_false this]

/-! ### Axiom profile -/

#print axioms NonosExtraction.TablesMemoryDesc.the_memorydescriptor_size_bytes_wrapper_is_its_method
#print axioms NonosExtraction.TablesMemoryDesc.the_memorydescriptor_end_address_wrapper_is_its_method
#print axioms NonosExtraction.TablesMemoryDesc.the_memorydescriptor_is_runtime_wrapper_is_its_method
#print axioms NonosExtraction.TablesMemoryDesc.the_memorydescriptor_is_usable_wrapper_is_its_method
#print axioms NonosExtraction.TablesMemoryDesc.memorydescriptor_size_bytes_is_pages_of_4096_saturated
#print axioms NonosExtraction.TablesMemoryDesc.memorydescriptor_size_bytes_at_the_page_count_limit
#print axioms NonosExtraction.TablesMemoryDesc.memorydescriptor_end_address_is_physical_start_plus_size_saturated
#print axioms NonosExtraction.TablesMemoryDesc.memorydescriptor_end_address_saturates_on_the_top_page
#print axioms NonosExtraction.TablesMemoryDesc.memorydescriptor_is_runtime_reads_bit_63
#print axioms NonosExtraction.TablesMemoryDesc.memorydescriptor_is_runtime_is_the_upper_half_of_attributes
#print axioms NonosExtraction.TablesMemoryDesc.memorydescriptor_is_usable_accepts_exactly_types_1_2_3_4_7

end NonosExtraction.TablesMemoryDesc
