/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

srat_processor, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.TablesSratProcessor

open Aeneas Aeneas.Std Result
open nonos_x_tables_srat_processor

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.TablesSratProcessor

/-! ### The forwarding functions add nothing -/

theorem the_sratprocessoraffinity_proximity_domain_wrapper_is_its_method (a : srat_processor.SratProcessorAffinity) :
    sratprocessoraffinity_proximity_domain a = srat_processor.SratProcessorAffinity.proximity_domain a := rfl

theorem the_sratprocessoraffinity_is_enabled_wrapper_is_its_method (a : srat_processor.SratProcessorAffinity) :
    sratprocessoraffinity_is_enabled a = srat_processor.SratProcessorAffinity.is_enabled a := rfl

theorem the_sratx2apicaffinity_is_enabled_wrapper_is_its_method (a : srat_processor.SratX2ApicAffinity) :
    sratx2apicaffinity_is_enabled a = srat_processor.SratX2ApicAffinity.is_enabled a := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.TablesSratProcessor.the_sratprocessoraffinity_proximity_domain_wrapper_is_its_method
#print axioms NonosExtraction.TablesSratProcessor.the_sratprocessoraffinity_is_enabled_wrapper_is_its_method
#print axioms NonosExtraction.TablesSratProcessor.the_sratx2apicaffinity_is_enabled_wrapper_is_its_method

end NonosExtraction.TablesSratProcessor
