-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [nonos_x_time_rtc_types_time]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace nonos_x_time_rtc_types_time

/-- [nonos_x_time_rtc_types_time::arch::x86_64::time::rtc::calendar::is_leap_year]:
    Source: 'src/arch/x86_64/time/rtc/../../../../../../../../../src/arch/x86_64/time/rtc/calendar.rs', lines 18:0-20:1
    Visibility: public -/
def arch.x86_64.time.rtc.calendar.is_leap_year
  (year : Std.U16) : Result Bool := do
  let i ← year % 4#u16
  if i = 0#u16
  then
    let i1 ← year % 100#u16
    if i1 != 0#u16
    then ok true
    else let i2 ← year % 400#u16
         ok (i2 = 0#u16)
  else let i1 ← year % 400#u16
       ok (i1 = 0#u16)

/-- [nonos_x_time_rtc_types_time::arch::x86_64::time::rtc::calendar::days_in_month]:
    Source: 'src/arch/x86_64/time/rtc/../../../../../../../../../src/arch/x86_64/time/rtc/calendar.rs', lines 22:0-35:1
    Visibility: public -/
def arch.x86_64.time.rtc.calendar.days_in_month
  (year : Std.U16) (month : Std.U8) : Result Std.U8 := do
  match month with
  | 1#uscalar => ok 31#u8
  | 3#uscalar => ok 31#u8
  | 5#uscalar => ok 31#u8
  | 7#uscalar => ok 31#u8
  | 8#uscalar => ok 31#u8
  | 10#uscalar => ok 31#u8
  | 12#uscalar => ok 31#u8
  | 4#uscalar => ok 30#u8
  | 6#uscalar => ok 30#u8
  | 9#uscalar => ok 30#u8
  | 11#uscalar => ok 30#u8
  | 2#uscalar =>
    let b ← arch.x86_64.time.rtc.calendar.is_leap_year year
    if b
    then ok 29#u8
    else ok 28#u8
  | _ => ok 0#u8

/-- [nonos_x_time_rtc_types_time::arch::x86_64::time::rtc::calendar::day_of_week]:
    Source: 'src/arch/x86_64/time/rtc/../../../../../../../../../src/arch/x86_64/time/rtc/calendar.rs', lines 37:0-46:1
    Visibility: public -/
def arch.x86_64.time.rtc.calendar.day_of_week
  (year : Std.U16) (month : Std.U8) (day : Std.U8) : Result Std.U8 := do
  let y ← lift (UScalar.hcast .I32 year)
  let m ← lift (UScalar.hcast .I32 month)
  let (y1, m1) ←
    if m < 3#i32
    then do
         let m2 ← m + 12#i32
         let y2 ← y - 1#i32
         ok (y2, m2)
    else ok (y, m)
  let q ← lift (UScalar.hcast .I32 day)
  let k ← y1 % 100#i32
  let j ← y1 / 100#i32
  let i ← m1 + 1#i32
  let i1 ← 13#i32 * i
  let i2 ← i1 / 5#i32
  let i3 ← q + i2
  let i4 ← i3 + k
  let i5 ← k / 4#i32
  let i6 ← i4 + i5
  let i7 ← j / 4#i32
  let i8 ← i6 + i7
  let i9 ← 2#i32 * j
  let i10 ← i8 - i9
  let h ← i10 % 7#i32
  let i11 ← h + 6#i32
  let i12 ← i11 % 7#i32
  let i13 ← i12 + 1#i32
  ok (IScalar.hcast .U8 i13)

/-- [nonos_x_time_rtc_types_time::arch::x86_64::time::rtc::constants::UNIX_EPOCH_YEAR]
    Source: 'src/arch/x86_64/time/rtc/../../../../../../../../../src/arch/x86_64/time/rtc/constants.rs', lines 17:0-17:38
    Visibility: public -/
@[global_simps, irreducible]
def arch.x86_64.time.rtc.constants.UNIX_EPOCH_YEAR : Std.U16 := 1970#u16

/-- [nonos_x_time_rtc_types_time::arch::x86_64::time::rtc::constants::SECS_PER_MIN]
    Source: 'src/arch/x86_64/time/rtc/../../../../../../../../../src/arch/x86_64/time/rtc/constants.rs', lines 19:0-19:33
    Visibility: public -/
@[global_simps, irreducible]
def arch.x86_64.time.rtc.constants.SECS_PER_MIN : Std.U64 := 60#u64

/-- [nonos_x_time_rtc_types_time::arch::x86_64::time::rtc::constants::SECS_PER_HOUR]
    Source: 'src/arch/x86_64/time/rtc/../../../../../../../../../src/arch/x86_64/time/rtc/constants.rs', lines 21:0-21:36
    Visibility: public -/
@[global_simps, irreducible]
def arch.x86_64.time.rtc.constants.SECS_PER_HOUR : Std.U64 := 3600#u64

/-- [nonos_x_time_rtc_types_time::arch::x86_64::time::rtc::constants::SECS_PER_DAY]
    Source: 'src/arch/x86_64/time/rtc/../../../../../../../../../src/arch/x86_64/time/rtc/constants.rs', lines 23:0-23:36
    Visibility: public -/
@[global_simps, irreducible]
def arch.x86_64.time.rtc.constants.SECS_PER_DAY : Std.U64 := 86400#u64

/-- [nonos_x_time_rtc_types_time::arch::x86_64::time::rtc::unix::datetime_to_unix]: loop body 0:
    Source: 'src/arch/x86_64/time/rtc/../../../../../../../../../src/arch/x86_64/time/rtc/unix.rs', lines 23:4-25:5
    Visibility: public -/
@[rust_loop_body]
def arch.x86_64.time.rtc.unix.datetime_to_unix_loop0.body
  (iter : core.ops.range.Range Std.U16) (days : Std.U64) :
  Result (ControlFlow ((core.ops.range.Range Std.U16) × Std.U64) Std.U64)
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepU16 iter
  match o with
  | none => ok (done days)
  | some y =>
    let b ← arch.x86_64.time.rtc.calendar.is_leap_year y
    let i ← if b
              then ok 366#u64
              else ok 365#u64
    let days1 ← days + i
    ok (cont (iter1, days1))

/-- [nonos_x_time_rtc_types_time::arch::x86_64::time::rtc::unix::datetime_to_unix]: loop 0:
    Source: 'src/arch/x86_64/time/rtc/../../../../../../../../../src/arch/x86_64/time/rtc/unix.rs', lines 23:4-25:5
    Visibility: public -/
@[rust_loop]
def arch.x86_64.time.rtc.unix.datetime_to_unix_loop0
  (iter : core.ops.range.Range Std.U16) (days : Std.U64) : Result Std.U64 := do
  loop
    (fun (iter1, days1) =>
      arch.x86_64.time.rtc.unix.datetime_to_unix_loop0.body iter1 days1)
    (iter, days)

/-- [nonos_x_time_rtc_types_time::arch::x86_64::time::rtc::unix::datetime_to_unix]: loop body 1:
    Source: 'src/arch/x86_64/time/rtc/../../../../../../../../../src/arch/x86_64/time/rtc/unix.rs', lines 26:4-28:5
    Visibility: public -/
@[rust_loop_body]
def arch.x86_64.time.rtc.unix.datetime_to_unix_loop1.body
  (year : Std.U16) (iter : core.ops.range.Range Std.U8) (days : Std.U64) :
  Result (ControlFlow ((core.ops.range.Range Std.U8) × Std.U64) Std.U64)
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepU8 iter
  match o with
  | none => ok (done days)
  | some m =>
    let i ← arch.x86_64.time.rtc.calendar.days_in_month year m
    let i1 ← lift (UScalar.cast .U64 i)
    let days1 ← days + i1
    ok (cont (iter1, days1))

/-- [nonos_x_time_rtc_types_time::arch::x86_64::time::rtc::unix::datetime_to_unix]: loop 1:
    Source: 'src/arch/x86_64/time/rtc/../../../../../../../../../src/arch/x86_64/time/rtc/unix.rs', lines 26:4-28:5
    Visibility: public -/
@[rust_loop]
def arch.x86_64.time.rtc.unix.datetime_to_unix_loop1
  (iter : core.ops.range.Range Std.U8) (year : Std.U16) (days : Std.U64) :
  Result Std.U64
  := do
  loop
    (fun (iter1, days1) =>
      arch.x86_64.time.rtc.unix.datetime_to_unix_loop1.body year iter1 days1)
    (iter, days)

/-- [nonos_x_time_rtc_types_time::arch::x86_64::time::rtc::unix::datetime_to_unix]:
    Source: 'src/arch/x86_64/time/rtc/../../../../../../../../../src/arch/x86_64/time/rtc/unix.rs', lines 21:0-34:1
    Visibility: public -/
def arch.x86_64.time.rtc.unix.datetime_to_unix
  (year : Std.U16) (month : Std.U8) (day : Std.U8) (hour : Std.U8)
  (minute : Std.U8) (second : Std.U8) :
  Result Std.U64
  := do
  let days ←
    arch.x86_64.time.rtc.unix.datetime_to_unix_loop0
      {
        start := arch.x86_64.time.rtc.constants.UNIX_EPOCH_YEAR,
        «end» := year
      } 0#u64
  let days1 ←
    arch.x86_64.time.rtc.unix.datetime_to_unix_loop1
      { start := 1#u8, «end» := month } year days
  let i ← day - 1#u8
  let i1 ← lift (UScalar.cast .U64 i)
  let days2 ← days1 + i1
  let i2 ← days2 * arch.x86_64.time.rtc.constants.SECS_PER_DAY
  let i3 ← lift (UScalar.cast .U64 hour)
  let i4 ← i3 * arch.x86_64.time.rtc.constants.SECS_PER_HOUR
  let i5 ← i2 + i4
  let i6 ← lift (UScalar.cast .U64 minute)
  let i7 ← i6 * arch.x86_64.time.rtc.constants.SECS_PER_MIN
  let i8 ← i5 + i7
  let i9 ← lift (UScalar.cast .U64 second)
  i8 + i9

/-- [nonos_x_time_rtc_types_time::arch::x86_64::time::rtc::types::time::RtcTime]
    Source: 'src/arch/x86_64/time/rtc/types/../../../../../../../../../../src/arch/x86_64/time/rtc/types/time.rs', lines 23:0-31:1
    Visibility: public -/
structure arch.x86_64.time.rtc.types.time.RtcTime where
  year : Std.U16
  month : Std.U8
  day : Std.U8
  hour : Std.U8
  minute : Std.U8
  second : Std.U8
  day_of_week : Std.U8

/-- [nonos_x_time_rtc_types_time::arch::x86_64::time::rtc::unix::unix_to_datetime]: loop body 0:
    Source: 'src/arch/x86_64/time/rtc/../../../../../../../../../src/arch/x86_64/time/rtc/unix.rs', lines 45:4-52:5
    Visibility: public -/
@[rust_loop_body]
def arch.x86_64.time.rtc.unix.unix_to_datetime_loop0.body
  (remaining : Std.U64) (year : Std.U16) :
  Result (ControlFlow (Std.U64 × Std.U16) (Std.U64 × Std.U16))
  := do
  let b ← arch.x86_64.time.rtc.calendar.is_leap_year year
  let days_in_year ← if b
                       then ok 366#i32
                       else ok 365#i32
  let i ← lift (IScalar.hcast .U64 days_in_year)
  if remaining < i
  then ok (done (remaining, year))
  else
    let i1 ← lift (IScalar.hcast .U64 days_in_year)
    let remaining1 ← remaining - i1
    let year1 ← year + 1#u16
    ok (cont (remaining1, year1))

/-- [nonos_x_time_rtc_types_time::arch::x86_64::time::rtc::unix::unix_to_datetime]: loop 0:
    Source: 'src/arch/x86_64/time/rtc/../../../../../../../../../src/arch/x86_64/time/rtc/unix.rs', lines 45:4-52:5
    Visibility: public -/
@[rust_loop]
def arch.x86_64.time.rtc.unix.unix_to_datetime_loop0
  (remaining : Std.U64) (year : Std.U16) : Result (Std.U64 × Std.U16) := do
  loop
    (fun (remaining1, year1) =>
      arch.x86_64.time.rtc.unix.unix_to_datetime_loop0.body remaining1 year1)
    (remaining, year)

/-- [nonos_x_time_rtc_types_time::arch::x86_64::time::rtc::unix::unix_to_datetime]: loop body 1:
    Source: 'src/arch/x86_64/time/rtc/../../../../../../../../../src/arch/x86_64/time/rtc/unix.rs', lines 54:4-61:5
    Visibility: public -/
@[rust_loop_body]
def arch.x86_64.time.rtc.unix.unix_to_datetime_loop1.body
  (year : Std.U16) (remaining : Std.U64) (month : Std.U8) :
  Result (ControlFlow (Std.U64 × Std.U8) (Std.U64 × Std.U8))
  := do
  let i ← arch.x86_64.time.rtc.calendar.days_in_month year month
  let days ← lift (UScalar.cast .U64 i)
  if remaining < days
  then ok (done (remaining, month))
  else
    let remaining1 ← remaining - days
    let month1 ← month + 1#u8
    ok (cont (remaining1, month1))

/-- [nonos_x_time_rtc_types_time::arch::x86_64::time::rtc::unix::unix_to_datetime]: loop 1:
    Source: 'src/arch/x86_64/time/rtc/../../../../../../../../../src/arch/x86_64/time/rtc/unix.rs', lines 54:4-61:5
    Visibility: public -/
@[rust_loop]
def arch.x86_64.time.rtc.unix.unix_to_datetime_loop1
  (remaining : Std.U64) (year : Std.U16) (month : Std.U8) :
  Result (Std.U64 × Std.U8)
  := do
  loop
    (fun (remaining1, month1) =>
      arch.x86_64.time.rtc.unix.unix_to_datetime_loop1.body year remaining1
      month1)
    (remaining, month)

/-- [nonos_x_time_rtc_types_time::arch::x86_64::time::rtc::unix::unix_to_datetime]:
    Source: 'src/arch/x86_64/time/rtc/../../../../../../../../../src/arch/x86_64/time/rtc/unix.rs', lines 36:0-64:1
    Visibility: public -/
def arch.x86_64.time.rtc.unix.unix_to_datetime
  (timestamp : Std.U64) : Result arch.x86_64.time.rtc.types.time.RtcTime := do
  let i ← timestamp % 60#u64
  let second ← lift (UScalar.cast .U8 i)
  let remaining ← timestamp / 60#u64
  let i1 ← remaining % 60#u64
  let minute ← lift (UScalar.cast .U8 i1)
  let remaining1 ← remaining / 60#u64
  let i2 ← remaining1 % 24#u64
  let hour ← lift (UScalar.cast .U8 i2)
  let remaining2 ← remaining1 / 24#u64
  let (remaining3, year) ←
    arch.x86_64.time.rtc.unix.unix_to_datetime_loop0 remaining2
      arch.x86_64.time.rtc.constants.UNIX_EPOCH_YEAR
  let (remaining4, month) ←
    arch.x86_64.time.rtc.unix.unix_to_datetime_loop1 remaining3 year 1#u8
  let i3 ← lift (UScalar.cast .U8 remaining4)
  let day ← i3 + 1#u8
  let i4 ← arch.x86_64.time.rtc.calendar.day_of_week year month day
  ok { year, month, day, hour, minute, second, day_of_week := i4 }

/-- [nonos_x_time_rtc_types_time::arch::x86_64::time::rtc::types::time::{nonos_x_time_rtc_types_time::arch::x86_64::time::rtc::types::time::RtcTime}::new]:
    Source: 'src/arch/x86_64/time/rtc/types/../../../../../../../../../../src/arch/x86_64/time/rtc/types/time.rs', lines 34:4-36:5
    Visibility: public -/
def arch.x86_64.time.rtc.types.time.RtcTime.new
  (year : Std.U16) (month : Std.U8) (day : Std.U8) (hour : Std.U8)
  (minute : Std.U8) (second : Std.U8) :
  Result arch.x86_64.time.rtc.types.time.RtcTime
  := do
  ok { year, month, day, hour, minute, second, day_of_week := 0#u8 }

/-- [nonos_x_time_rtc_types_time::arch::x86_64::time::rtc::types::time::{nonos_x_time_rtc_types_time::arch::x86_64::time::rtc::types::time::RtcTime}::to_unix_timestamp]:
    Source: 'src/arch/x86_64/time/rtc/types/../../../../../../../../../../src/arch/x86_64/time/rtc/types/time.rs', lines 68:4-70:5
    Visibility: public -/
def arch.x86_64.time.rtc.types.time.RtcTime.to_unix_timestamp
  (self : arch.x86_64.time.rtc.types.time.RtcTime) : Result Std.U64 := do
  arch.x86_64.time.rtc.unix.datetime_to_unix self.year self.month self.day
    self.hour self.minute self.second

/-- [nonos_x_time_rtc_types_time::arch::x86_64::time::rtc::types::time::{nonos_x_time_rtc_types_time::arch::x86_64::time::rtc::types::time::RtcTime}::from_unix_timestamp]:
    Source: 'src/arch/x86_64/time/rtc/types/../../../../../../../../../../src/arch/x86_64/time/rtc/types/time.rs', lines 72:4-74:5
    Visibility: public -/
def arch.x86_64.time.rtc.types.time.RtcTime.from_unix_timestamp
  (timestamp : Std.U64) : Result arch.x86_64.time.rtc.types.time.RtcTime := do
  arch.x86_64.time.rtc.unix.unix_to_datetime timestamp

/-- [nonos_x_time_rtc_types_time::arch::x86_64::time::rtc::types::time::{nonos_x_time_rtc_types_time::arch::x86_64::time::rtc::types::time::RtcTime}::calculate_day_of_week]:
    Source: 'src/arch/x86_64/time/rtc/types/../../../../../../../../../../src/arch/x86_64/time/rtc/types/time.rs', lines 76:4-78:5
    Visibility: public -/
def arch.x86_64.time.rtc.types.time.RtcTime.calculate_day_of_week
  (self : arch.x86_64.time.rtc.types.time.RtcTime) : Result Std.U8 := do
  arch.x86_64.time.rtc.calendar.day_of_week self.year self.month self.day

/-- [nonos_x_time_rtc_types_time::arch::x86_64::time::rtc::types::time::{nonos_x_time_rtc_types_time::arch::x86_64::time::rtc::types::time::RtcTime}::with_day_of_week]:
    Source: 'src/arch/x86_64/time/rtc/types/../../../../../../../../../../src/arch/x86_64/time/rtc/types/time.rs', lines 80:4-83:5
    Visibility: public -/
def arch.x86_64.time.rtc.types.time.RtcTime.with_day_of_week
  (self : arch.x86_64.time.rtc.types.time.RtcTime) :
  Result arch.x86_64.time.rtc.types.time.RtcTime
  := do
  let i ← arch.x86_64.time.rtc.types.time.RtcTime.calculate_day_of_week self
  ok { self with day_of_week := i }

/-- [nonos_x_time_rtc_types_time::arch::x86_64::time::rtc::types::time::{nonos_x_time_rtc_types_time::arch::x86_64::time::rtc::types::time::RtcTime}::is_leap_year]:
    Source: 'src/arch/x86_64/time/rtc/types/../../../../../../../../../../src/arch/x86_64/time/rtc/types/time.rs', lines 85:4-87:5
    Visibility: public -/
def arch.x86_64.time.rtc.types.time.RtcTime.is_leap_year
  (self : arch.x86_64.time.rtc.types.time.RtcTime) : Result Bool := do
  arch.x86_64.time.rtc.calendar.is_leap_year self.year

/-- [nonos_x_time_rtc_types_time::arch::x86_64::time::rtc::types::time::{nonos_x_time_rtc_types_time::arch::x86_64::time::rtc::types::time::RtcTime}::day_of_year]: loop body 0:
    Source: 'src/arch/x86_64/time/rtc/types/../../../../../../../../../../src/arch/x86_64/time/rtc/types/time.rs', lines 91:8-93:9
    Visibility: public -/
@[rust_loop_body]
def arch.x86_64.time.rtc.types.time.RtcTime.day_of_year_loop.body
  (i : Std.U16) (iter : core.ops.range.Range Std.U8) (day : Std.U16) :
  Result (ControlFlow ((core.ops.range.Range Std.U8) × Std.U16) Std.U16)
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepU8 iter
  match o with
  | none => ok (done day)
  | some m =>
    let i1 ← arch.x86_64.time.rtc.calendar.days_in_month i m
    let i2 ← lift (UScalar.cast .U16 i1)
    let day1 ← day + i2
    ok (cont (iter1, day1))

/-- [nonos_x_time_rtc_types_time::arch::x86_64::time::rtc::types::time::{nonos_x_time_rtc_types_time::arch::x86_64::time::rtc::types::time::RtcTime}::day_of_year]: loop 0:
    Source: 'src/arch/x86_64/time/rtc/types/../../../../../../../../../../src/arch/x86_64/time/rtc/types/time.rs', lines 91:8-93:9
    Visibility: public -/
@[rust_loop]
def arch.x86_64.time.rtc.types.time.RtcTime.day_of_year_loop
  (iter : core.ops.range.Range Std.U8) (i : Std.U16) (day : Std.U16) :
  Result Std.U16
  := do
  loop
    (fun (iter1, day1) =>
      arch.x86_64.time.rtc.types.time.RtcTime.day_of_year_loop.body i iter1
      day1)
    (iter, day)

/-- [nonos_x_time_rtc_types_time::arch::x86_64::time::rtc::types::time::{nonos_x_time_rtc_types_time::arch::x86_64::time::rtc::types::time::RtcTime}::day_of_year]:
    Source: 'src/arch/x86_64/time/rtc/types/../../../../../../../../../../src/arch/x86_64/time/rtc/types/time.rs', lines 89:4-95:5
    Visibility: public -/
def arch.x86_64.time.rtc.types.time.RtcTime.day_of_year
  (self : arch.x86_64.time.rtc.types.time.RtcTime) : Result Std.U16 := do
  let day ← lift (UScalar.cast .U16 self.day)
  arch.x86_64.time.rtc.types.time.RtcTime.day_of_year_loop
    { start := 1#u8, «end» := self.month } self.year day

/-- [nonos_x_time_rtc_types_time::rtctime_new]:
    Source: 'src/lib.rs', lines 11:0-13:1
    Visibility: public -/
def rtctime_new
  (year : Std.U16) (month : Std.U8) (day : Std.U8) (hour : Std.U8)
  (minute : Std.U8) (second : Std.U8) :
  Result arch.x86_64.time.rtc.types.time.RtcTime
  := do
  arch.x86_64.time.rtc.types.time.RtcTime.new year month day hour minute second

/-- [nonos_x_time_rtc_types_time::rtctime_to_unix_timestamp]:
    Source: 'src/lib.rs', lines 15:0-17:1
    Visibility: public -/
def rtctime_to_unix_timestamp
  (this : arch.x86_64.time.rtc.types.time.RtcTime) : Result Std.U64 := do
  arch.x86_64.time.rtc.types.time.RtcTime.to_unix_timestamp this

/-- [nonos_x_time_rtc_types_time::rtctime_from_unix_timestamp]:
    Source: 'src/lib.rs', lines 19:0-21:1
    Visibility: public -/
def rtctime_from_unix_timestamp
  (timestamp : Std.U64) : Result arch.x86_64.time.rtc.types.time.RtcTime := do
  arch.x86_64.time.rtc.types.time.RtcTime.from_unix_timestamp timestamp

/-- [nonos_x_time_rtc_types_time::rtctime_calculate_day_of_week]:
    Source: 'src/lib.rs', lines 23:0-25:1
    Visibility: public -/
def rtctime_calculate_day_of_week
  (this : arch.x86_64.time.rtc.types.time.RtcTime) : Result Std.U8 := do
  arch.x86_64.time.rtc.types.time.RtcTime.calculate_day_of_week this

/-- [nonos_x_time_rtc_types_time::rtctime_with_day_of_week]:
    Source: 'src/lib.rs', lines 27:0-29:1
    Visibility: public -/
def rtctime_with_day_of_week
  (this : arch.x86_64.time.rtc.types.time.RtcTime) :
  Result arch.x86_64.time.rtc.types.time.RtcTime
  := do
  arch.x86_64.time.rtc.types.time.RtcTime.with_day_of_week this

/-- [nonos_x_time_rtc_types_time::rtctime_is_leap_year]:
    Source: 'src/lib.rs', lines 31:0-33:1
    Visibility: public -/
def rtctime_is_leap_year
  (this : arch.x86_64.time.rtc.types.time.RtcTime) : Result Bool := do
  arch.x86_64.time.rtc.types.time.RtcTime.is_leap_year this

/-- [nonos_x_time_rtc_types_time::rtctime_day_of_year]:
    Source: 'src/lib.rs', lines 35:0-37:1
    Visibility: public -/
def rtctime_day_of_year
  (this : arch.x86_64.time.rtc.types.time.RtcTime) : Result Std.U16 := do
  arch.x86_64.time.rtc.types.time.RtcTime.day_of_year this

end nonos_x_time_rtc_types_time
