-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [nonos_x_time_rtc_types_alarm]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace nonos_x_time_rtc_types_alarm

/-- [nonos_x_time_rtc_types_alarm::arch::x86_64::time::rtc::types::alarm::RtcAlarm]
    Source: 'src/arch/x86_64/time/rtc/types/../../../../../../../../../../src/arch/x86_64/time/rtc/types/alarm.rs', lines 20:0-24:1
    Visibility: public -/
structure arch.x86_64.time.rtc.types.alarm.RtcAlarm where
  hour : Std.U8
  minute : Std.U8
  second : Std.U8

/-- [nonos_x_time_rtc_types_alarm::arch::x86_64::time::rtc::types::alarm::{nonos_x_time_rtc_types_alarm::arch::x86_64::time::rtc::types::alarm::RtcAlarm}::new]:
    Source: 'src/arch/x86_64/time/rtc/types/../../../../../../../../../../src/arch/x86_64/time/rtc/types/alarm.rs', lines 27:4-29:5
    Visibility: public -/
def arch.x86_64.time.rtc.types.alarm.RtcAlarm.new
  (hour : Std.U8) (minute : Std.U8) (second : Std.U8) :
  Result arch.x86_64.time.rtc.types.alarm.RtcAlarm
  := do
  ok { hour, minute, second }

/-- [nonos_x_time_rtc_types_alarm::arch::x86_64::time::rtc::types::alarm::{nonos_x_time_rtc_types_alarm::arch::x86_64::time::rtc::types::alarm::RtcAlarm}::every_second]:
    Source: 'src/arch/x86_64/time/rtc/types/../../../../../../../../../../src/arch/x86_64/time/rtc/types/alarm.rs', lines 31:4-33:5
    Visibility: public -/
def arch.x86_64.time.rtc.types.alarm.RtcAlarm.every_second
  : Result arch.x86_64.time.rtc.types.alarm.RtcAlarm := do
  ok { hour := 255#u8, minute := 255#u8, second := 255#u8 }

/-- [nonos_x_time_rtc_types_alarm::arch::x86_64::time::rtc::types::alarm::{nonos_x_time_rtc_types_alarm::arch::x86_64::time::rtc::types::alarm::RtcAlarm}::every_minute]:
    Source: 'src/arch/x86_64/time/rtc/types/../../../../../../../../../../src/arch/x86_64/time/rtc/types/alarm.rs', lines 35:4-37:5
    Visibility: public -/
def arch.x86_64.time.rtc.types.alarm.RtcAlarm.every_minute
  : Result arch.x86_64.time.rtc.types.alarm.RtcAlarm := do
  ok { hour := 255#u8, minute := 255#u8, second := 0#u8 }

/-- [nonos_x_time_rtc_types_alarm::arch::x86_64::time::rtc::types::alarm::{nonos_x_time_rtc_types_alarm::arch::x86_64::time::rtc::types::alarm::RtcAlarm}::every_hour]:
    Source: 'src/arch/x86_64/time/rtc/types/../../../../../../../../../../src/arch/x86_64/time/rtc/types/alarm.rs', lines 39:4-41:5
    Visibility: public -/
def arch.x86_64.time.rtc.types.alarm.RtcAlarm.every_hour
  : Result arch.x86_64.time.rtc.types.alarm.RtcAlarm := do
  ok { hour := 255#u8, minute := 0#u8, second := 0#u8 }

/-- [nonos_x_time_rtc_types_alarm::rtcalarm_new]:
    Source: 'src/lib.rs', lines 11:0-13:1
    Visibility: public -/
def rtcalarm_new
  (hour : Std.U8) (minute : Std.U8) (second : Std.U8) :
  Result arch.x86_64.time.rtc.types.alarm.RtcAlarm
  := do
  arch.x86_64.time.rtc.types.alarm.RtcAlarm.new hour minute second

/-- [nonos_x_time_rtc_types_alarm::rtcalarm_every_second]:
    Source: 'src/lib.rs', lines 15:0-17:1
    Visibility: public -/
def rtcalarm_every_second
  : Result arch.x86_64.time.rtc.types.alarm.RtcAlarm := do
  arch.x86_64.time.rtc.types.alarm.RtcAlarm.every_second

/-- [nonos_x_time_rtc_types_alarm::rtcalarm_every_minute]:
    Source: 'src/lib.rs', lines 19:0-21:1
    Visibility: public -/
def rtcalarm_every_minute
  : Result arch.x86_64.time.rtc.types.alarm.RtcAlarm := do
  arch.x86_64.time.rtc.types.alarm.RtcAlarm.every_minute

/-- [nonos_x_time_rtc_types_alarm::rtcalarm_every_hour]:
    Source: 'src/lib.rs', lines 23:0-25:1
    Visibility: public -/
def rtcalarm_every_hour
  : Result arch.x86_64.time.rtc.types.alarm.RtcAlarm := do
  arch.x86_64.time.rtc.types.alarm.RtcAlarm.every_hour

end nonos_x_time_rtc_types_alarm
