/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

alarm, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.TimeRtcTypesAlarm

open Aeneas Aeneas.Std Result
open nonos_x_time_rtc_types_alarm

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.TimeRtcTypesAlarm

/-! ### The forwarding functions add nothing -/

theorem the_rtcalarm_new_wrapper_is_its_method (a : Std.U8) (b : Std.U8) (c : Std.U8) :
    rtcalarm_new a b c = arch.x86_64.time.rtc.types.alarm.RtcAlarm.new a b c := rfl

theorem the_rtcalarm_every_second_wrapper_is_its_method :
    rtcalarm_every_second = arch.x86_64.time.rtc.types.alarm.RtcAlarm.every_second := rfl

theorem the_rtcalarm_every_minute_wrapper_is_its_method :
    rtcalarm_every_minute = arch.x86_64.time.rtc.types.alarm.RtcAlarm.every_minute := rfl

theorem the_rtcalarm_every_hour_wrapper_is_its_method :
    rtcalarm_every_hour = arch.x86_64.time.rtc.types.alarm.RtcAlarm.every_hour := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.TimeRtcTypesAlarm.the_rtcalarm_new_wrapper_is_its_method
#print axioms NonosExtraction.TimeRtcTypesAlarm.the_rtcalarm_every_second_wrapper_is_its_method
#print axioms NonosExtraction.TimeRtcTypesAlarm.the_rtcalarm_every_minute_wrapper_is_its_method
#print axioms NonosExtraction.TimeRtcTypesAlarm.the_rtcalarm_every_hour_wrapper_is_its_method

end NonosExtraction.TimeRtcTypesAlarm
