-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [nonos_x_types_stats_snapshot]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace nonos_x_types_stats_snapshot

/-- [nonos_x_types_stats_snapshot::stats_snapshot::MmioStatsSnapshot]
    Source: 'src/../../../../../src/memory/mmio/types/stats_snapshot.rs', lines 18:0-23:1
    Visibility: public -/
structure stats_snapshot.MmioStatsSnapshot where
  total_regions : Std.Usize
  total_mapped_size : Std.U64
  read_operations : Std.U64
  write_operations : Std.U64

/-- [nonos_x_types_stats_snapshot::stats_snapshot::{nonos_x_types_stats_snapshot::stats_snapshot::MmioStatsSnapshot}::new]:
    Source: 'src/../../../../../src/memory/mmio/types/stats_snapshot.rs', lines 26:4-28:5
    Visibility: public -/
def stats_snapshot.MmioStatsSnapshot.new
  : Result stats_snapshot.MmioStatsSnapshot := do
  ok
    {
      total_regions := 0#usize,
      total_mapped_size := 0#u64,
      read_operations := 0#u64,
      write_operations := 0#u64
    }

/-- [nonos_x_types_stats_snapshot::stats_snapshot::{nonos_x_types_stats_snapshot::stats_snapshot::MmioStatsSnapshot}::total_operations]:
    Source: 'src/../../../../../src/memory/mmio/types/stats_snapshot.rs', lines 30:4-32:5
    Visibility: public -/
def stats_snapshot.MmioStatsSnapshot.total_operations
  (self : stats_snapshot.MmioStatsSnapshot) : Result Std.U64 := do
  self.read_operations + self.write_operations

/-- [nonos_x_types_stats_snapshot::mmiostatssnapshot_new]:
    Source: 'src/lib.rs', lines 10:0-12:1
    Visibility: public -/
def mmiostatssnapshot_new : Result stats_snapshot.MmioStatsSnapshot := do
  stats_snapshot.MmioStatsSnapshot.new

/-- [nonos_x_types_stats_snapshot::mmiostatssnapshot_total_operations]:
    Source: 'src/lib.rs', lines 14:0-16:1
    Visibility: public -/
def mmiostatssnapshot_total_operations
  (this : stats_snapshot.MmioStatsSnapshot) : Result Std.U64 := do
  stats_snapshot.MmioStatsSnapshot.total_operations this

end nonos_x_types_stats_snapshot
