-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [nonos_x_types_range]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace nonos_x_types_range

/-- [nonos_x_types_range::range::PortRange]
    Source: 'src/../../../../../src/arch/x86_64/port/types/range.rs', lines 18:0-21:1
    Visibility: public -/
structure range.PortRange where
  start : Std.U16
  count : Std.U16

/-- [nonos_x_types_range::range::{nonos_x_types_range::range::PortRange}::new]:
    Source: 'src/../../../../../src/arch/x86_64/port/types/range.rs', lines 24:4-26:5
    Visibility: public -/
def range.PortRange.new
  (start : Std.U16) (count : Std.U16) : Result range.PortRange := do
  ok { start, count }

/-- [nonos_x_types_range::range::{nonos_x_types_range::range::PortRange}::start]:
    Source: 'src/../../../../../src/arch/x86_64/port/types/range.rs', lines 28:4-30:5
    Visibility: public -/
def range.PortRange.impl.start (self : range.PortRange) : Result Std.U16 := do
  ok self.start

/-- [nonos_x_types_range::range::{nonos_x_types_range::range::PortRange}::count]:
    Source: 'src/../../../../../src/arch/x86_64/port/types/range.rs', lines 32:4-34:5
    Visibility: public -/
def range.PortRange.impl.count (self : range.PortRange) : Result Std.U16 := do
  ok self.count

/-- [nonos_x_types_range::range::{nonos_x_types_range::range::PortRange}::end]:
    Source: 'src/../../../../../src/arch/x86_64/port/types/range.rs', lines 36:4-38:5
    Visibility: public -/
def range.PortRange.end (self : range.PortRange) : Result Std.U16 := do
  ok (core.num.U16.saturating_add self.start self.count)

/-- [nonos_x_types_range::range::{nonos_x_types_range::range::PortRange}::contains]:
    Source: 'src/../../../../../src/arch/x86_64/port/types/range.rs', lines 40:4-42:5
    Visibility: public -/
def range.PortRange.contains
  (self : range.PortRange) (port : Std.U16) : Result Bool := do
  if port >= self.start
  then let i ← range.PortRange.end self
       ok (port < i)
  else ok false

/-- [nonos_x_types_range::portrange_new]:
    Source: 'src/lib.rs', lines 10:0-12:1
    Visibility: public -/
def portrange_new
  (start : Std.U16) (count : Std.U16) : Result range.PortRange := do
  range.PortRange.new start count

/-- [nonos_x_types_range::portrange_start]:
    Source: 'src/lib.rs', lines 14:0-16:1
    Visibility: public -/
def portrange_start (this : range.PortRange) : Result Std.U16 := do
  range.PortRange.impl.start this

/-- [nonos_x_types_range::portrange_count]:
    Source: 'src/lib.rs', lines 18:0-20:1
    Visibility: public -/
def portrange_count (this : range.PortRange) : Result Std.U16 := do
  range.PortRange.impl.count this

/-- [nonos_x_types_range::portrange_end]:
    Source: 'src/lib.rs', lines 22:0-24:1
    Visibility: public -/
def portrange_end (this : range.PortRange) : Result Std.U16 := do
  range.PortRange.end this

/-- [nonos_x_types_range::portrange_contains]:
    Source: 'src/lib.rs', lines 26:0-28:1
    Visibility: public -/
def portrange_contains
  (this : range.PortRange) (port : Std.U16) : Result Bool := do
  range.PortRange.contains this port

end nonos_x_types_range
