/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

ids, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.TypesIds

open Aeneas Aeneas.Std Result
open nonos_x_types_ids

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.TypesIds

/-! ### The forwarding functions add nothing -/

theorem the_domainid_new_wrapper_is_its_method (a : Std.U16) :
    domainid_new a = ids.DomainId.new a := rfl

theorem the_domainid_as_u16_wrapper_is_its_method (a : ids.DomainId) :
    domainid_as_u16 a = ids.DomainId.as_u16 a := rfl

theorem the_sourceid_new_wrapper_is_its_method (a : Std.U16) :
    sourceid_new a = ids.SourceId.new a := rfl

theorem the_sourceid_as_u16_wrapper_is_its_method (a : ids.SourceId) :
    sourceid_as_u16 a = ids.SourceId.as_u16 a := rfl

theorem the_sourceid_bus_wrapper_is_its_method (a : ids.SourceId) :
    sourceid_bus a = ids.SourceId.bus a := rfl

theorem the_sourceid_device_wrapper_is_its_method (a : ids.SourceId) :
    sourceid_device a = ids.SourceId.device a := rfl

theorem the_sourceid_function_wrapper_is_its_method (a : ids.SourceId) :
    sourceid_function a = ids.SourceId.function a := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.TypesIds.the_domainid_new_wrapper_is_its_method
#print axioms NonosExtraction.TypesIds.the_domainid_as_u16_wrapper_is_its_method
#print axioms NonosExtraction.TypesIds.the_sourceid_new_wrapper_is_its_method
#print axioms NonosExtraction.TypesIds.the_sourceid_as_u16_wrapper_is_its_method
#print axioms NonosExtraction.TypesIds.the_sourceid_bus_wrapper_is_its_method
#print axioms NonosExtraction.TypesIds.the_sourceid_device_wrapper_is_its_method
#print axioms NonosExtraction.TypesIds.the_sourceid_function_wrapper_is_its_method

end NonosExtraction.TypesIds
