/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

attributes, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.TypesAttributes

open Aeneas Aeneas.Std Result
open nonos_x_types_attributes

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.TypesAttributes

/-! ### The forwarding functions add nothing -/

theorem the_variableattributes_empty_wrapper_is_its_method :
    variableattributes_empty = attributes.VariableAttributes.empty := rfl

theorem the_variableattributes_bits_wrapper_is_its_method (a : attributes.VariableAttributes) :
    variableattributes_bits a = attributes.VariableAttributes.bits a := rfl

theorem the_variableattributes_from_bits_wrapper_is_its_method (a : Std.U32) :
    variableattributes_from_bits a = attributes.VariableAttributes.from_bits a := rfl

theorem the_variableattributes_from_bits_truncate_wrapper_is_its_method (a : Std.U32) :
    variableattributes_from_bits_truncate a = attributes.VariableAttributes.from_bits_truncate a := rfl

theorem the_variableattributes_contains_wrapper_is_its_method (a : attributes.VariableAttributes) (b : attributes.VariableAttributes) :
    variableattributes_contains a b = attributes.VariableAttributes.contains a b := rfl

theorem the_variableattributes_is_empty_wrapper_is_its_method (a : attributes.VariableAttributes) :
    variableattributes_is_empty a = attributes.VariableAttributes.is_empty a := rfl

theorem the_variableattributes_is_non_volatile_wrapper_is_its_method (a : attributes.VariableAttributes) :
    variableattributes_is_non_volatile a = attributes.VariableAttributes.is_non_volatile a := rfl

theorem the_variableattributes_is_runtime_access_wrapper_is_its_method (a : attributes.VariableAttributes) :
    variableattributes_is_runtime_access a = attributes.VariableAttributes.is_runtime_access a := rfl

theorem the_variableattributes_requires_authentication_wrapper_is_its_method (a : attributes.VariableAttributes) :
    variableattributes_requires_authentication a = attributes.VariableAttributes.requires_authentication a := rfl

theorem the_variableattributes_intersection_wrapper_is_its_method (a : attributes.VariableAttributes) (b : attributes.VariableAttributes) :
    variableattributes_intersection a b = attributes.VariableAttributes.intersection a b := rfl

theorem the_variableattributes_union_wrapper_is_its_method (a : attributes.VariableAttributes) (b : attributes.VariableAttributes) :
    variableattributes_union a b = attributes.VariableAttributes.union a b := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.TypesAttributes.the_variableattributes_empty_wrapper_is_its_method
#print axioms NonosExtraction.TypesAttributes.the_variableattributes_bits_wrapper_is_its_method
#print axioms NonosExtraction.TypesAttributes.the_variableattributes_from_bits_wrapper_is_its_method
#print axioms NonosExtraction.TypesAttributes.the_variableattributes_from_bits_truncate_wrapper_is_its_method
#print axioms NonosExtraction.TypesAttributes.the_variableattributes_contains_wrapper_is_its_method
#print axioms NonosExtraction.TypesAttributes.the_variableattributes_is_empty_wrapper_is_its_method
#print axioms NonosExtraction.TypesAttributes.the_variableattributes_is_non_volatile_wrapper_is_its_method
#print axioms NonosExtraction.TypesAttributes.the_variableattributes_is_runtime_access_wrapper_is_its_method
#print axioms NonosExtraction.TypesAttributes.the_variableattributes_requires_authentication_wrapper_is_its_method
#print axioms NonosExtraction.TypesAttributes.the_variableattributes_intersection_wrapper_is_its_method
#print axioms NonosExtraction.TypesAttributes.the_variableattributes_union_wrapper_is_its_method

end NonosExtraction.TypesAttributes
