/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

region_type, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.TypesRegionType

open Aeneas Aeneas.Std Result
open nonos_x_types_region_type

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.TypesRegionType

/-! ### The forwarding functions add nothing -/

theorem the_regiontype_is_allocatable_wrapper_is_its_method (a : region_type.RegionType) :
    regiontype_is_allocatable a = region_type.RegionType.is_allocatable a := rfl

theorem the_regiontype_is_kernel_wrapper_is_its_method (a : region_type.RegionType) :
    regiontype_is_kernel a = region_type.RegionType.is_kernel a := rfl

theorem the_regiontype_is_reserved_wrapper_is_its_method (a : region_type.RegionType) :
    regiontype_is_reserved a = region_type.RegionType.is_reserved a := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.TypesRegionType.the_regiontype_is_allocatable_wrapper_is_its_method
#print axioms NonosExtraction.TypesRegionType.the_regiontype_is_kernel_wrapper_is_its_method
#print axioms NonosExtraction.TypesRegionType.the_regiontype_is_reserved_wrapper_is_its_method

end NonosExtraction.TypesRegionType
