-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [nonos_x_types_region_stats]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace nonos_x_types_region_stats

/-- [nonos_x_types_region_stats::region_stats::RegionStats]
    Source: 'src/../../../../../src/memory/boot_memory/types/region_stats.rs', lines 18:0-28:1
    Visibility: public -/
structure region_stats.RegionStats where
  total_memory : Std.U64
  available_memory : Std.U64
  allocated_memory : Std.U64
  reserved_memory : Std.U64
  kernel_memory : Std.U64
  capsule_memory : Std.U64
  hardware_memory : Std.U64
  defective_memory : Std.U64
  region_count : Std.Usize

/-- [nonos_x_types_region_stats::region_stats::{nonos_x_types_region_stats::region_stats::RegionStats}::free_memory]:
    Source: 'src/../../../../../src/memory/boot_memory/types/region_stats.rs', lines 32:4-38:5
    Visibility: public -/
def region_stats.RegionStats.free_memory
  (self : region_stats.RegionStats) : Result Std.U64 := do
  if self.available_memory > self.allocated_memory
  then self.available_memory - self.allocated_memory
  else ok 0#u64

/-- [nonos_x_types_region_stats::regionstats_free_memory]:
    Source: 'src/lib.rs', lines 10:0-12:1
    Visibility: public -/
def regionstats_free_memory
  (this : region_stats.RegionStats) : Result Std.U64 := do
  region_stats.RegionStats.free_memory this

end nonos_x_types_region_stats
