-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [nonos_x_types_direction]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace nonos_x_types_direction

/-- [nonos_x_types_direction::direction::DmaDirection]
    Source: 'src/../../../../../src/memory/dma/types/direction.rs', lines 18:0-22:1
    Visibility: public -/
@[discriminant isize]
inductive direction.DmaDirection where
| ToDevice : direction.DmaDirection
| FromDevice : direction.DmaDirection
| Bidirectional : direction.DmaDirection

/-- [nonos_x_types_direction::direction::{nonos_x_types_direction::direction::DmaDirection}::writes_to_device]:
    Source: 'src/../../../../../src/memory/dma/types/direction.rs', lines 25:4-27:5
    Visibility: public -/
def direction.DmaDirection.writes_to_device
  (self : direction.DmaDirection) : Result Bool := do
  match self with
  | direction.DmaDirection.ToDevice => ok true
  | direction.DmaDirection.FromDevice => ok false
  | direction.DmaDirection.Bidirectional => ok true

/-- [nonos_x_types_direction::direction::{nonos_x_types_direction::direction::DmaDirection}::reads_from_device]:
    Source: 'src/../../../../../src/memory/dma/types/direction.rs', lines 29:4-31:5
    Visibility: public -/
def direction.DmaDirection.reads_from_device
  (self : direction.DmaDirection) : Result Bool := do
  match self with
  | direction.DmaDirection.ToDevice => ok false
  | direction.DmaDirection.FromDevice => ok true
  | direction.DmaDirection.Bidirectional => ok true

/-- [nonos_x_types_direction::dmadirection_writes_to_device]:
    Source: 'src/lib.rs', lines 10:0-12:1
    Visibility: public -/
def dmadirection_writes_to_device
  (this : direction.DmaDirection) : Result Bool := do
  direction.DmaDirection.writes_to_device this

/-- [nonos_x_types_direction::dmadirection_reads_from_device]:
    Source: 'src/lib.rs', lines 14:0-16:1
    Visibility: public -/
def dmadirection_reads_from_device
  (this : direction.DmaDirection) : Result Bool := do
  direction.DmaDirection.reads_from_device this

end nonos_x_types_direction
