/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

stack, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.TypesStack

open Aeneas Aeneas.Std Result
open nonos_x_types_stack

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.TypesStack

/-! ### The forwarding functions add nothing -/

theorem the_stackregion_new_wrapper_is_its_method (a : Std.U64) (b : Std.Usize) (c : Std.Usize) :
    stackregion_new a b c = stack.StackRegion.new a b c := rfl

theorem the_stackregion_per_cpu_wrapper_is_its_method (a : Std.U64) (b : Std.Usize) (c : Std.Usize) (d : Std.U32) :
    stackregion_per_cpu a b c d = stack.StackRegion.per_cpu a b c d := rfl

theorem the_stackregion_total_size_wrapper_is_its_method (a : stack.StackRegion) :
    stackregion_total_size a = stack.StackRegion.total_size a := rfl

theorem the_stackregion_stack_top_wrapper_is_its_method (a : stack.StackRegion) :
    stackregion_stack_top a = stack.StackRegion.stack_top a := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.TypesStack.the_stackregion_new_wrapper_is_its_method
#print axioms NonosExtraction.TypesStack.the_stackregion_per_cpu_wrapper_is_its_method
#print axioms NonosExtraction.TypesStack.the_stackregion_total_size_wrapper_is_its_method
#print axioms NonosExtraction.TypesStack.the_stackregion_stack_top_wrapper_is_its_method

end NonosExtraction.TypesStack
