/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

protection, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.TypesProtection

open Aeneas Aeneas.Std Result
open nonos_x_types_protection

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.TypesProtection

/-! ### The forwarding functions add nothing -/

theorem the_protectionflags_new_wrapper_is_its_method :
    protectionflags_new = protection.ProtectionFlags.new := rfl

theorem the_protectionflags_is_fully_protected_wrapper_is_its_method (a : protection.ProtectionFlags) :
    protectionflags_is_fully_protected a = protection.ProtectionFlags.is_fully_protected a := rfl

/-! ### Full protection is the four mandatory features, and bring-up starts with none

    The kernel file promises that a caller gating on these flags never gets a
    false yes. These theorems establish that `protectionflags_new` claims none of
    the five features, so an MMU read before bring-up is not fully protected;
    that `protectionflags_is_fully_protected` is true exactly when SMEP, SMAP, NX
    and WP are all set, so clearing any one of them makes it false; and that
    UMIP, which the source marks best-effort, does not affect the answer either
    way. They cannot establish that the fields reflect the control registers,
    since the register reads that set them and the mutex around them are not
    extracted.
-/

theorem protectionflags_new_claims_no_protection :
    protectionflags_new = ok (protection.ProtectionFlags.mk
      (smep_enabled := false) (smap_enabled := false) (nx_enabled := false)
      (wp_enabled := false) (umip_enabled := false)) := rfl

theorem protectionflags_new_is_not_fully_protected :
    (do let f ← protectionflags_new; protectionflags_is_fully_protected f) = ok false := rfl

theorem protectionflags_is_fully_protected_exactly_when_smep_smap_nx_and_wp_are_set
    (f : protection.ProtectionFlags) :
    protectionflags_is_fully_protected f =
      ok (f.smep_enabled && f.smap_enabled && f.nx_enabled && f.wp_enabled) := by
  unfold protectionflags_is_fully_protected protection.ProtectionFlags.is_fully_protected
  cases f.smep_enabled <;> cases f.smap_enabled <;> cases f.nx_enabled <;> rfl

/-- UMIP is tracked but not required: setting or clearing it never changes
    whether the flags count as fully protected. -/
theorem protectionflags_is_fully_protected_ignores_umip (f : protection.ProtectionFlags) (u : Bool) :
    protectionflags_is_fully_protected { f with umip_enabled := u } =
      protectionflags_is_fully_protected f := by
  simp only [protectionflags_is_fully_protected_exactly_when_smep_smap_nx_and_wp_are_set]

/-! ### Axiom profile -/

#print axioms NonosExtraction.TypesProtection.the_protectionflags_new_wrapper_is_its_method
#print axioms NonosExtraction.TypesProtection.the_protectionflags_is_fully_protected_wrapper_is_its_method
#print axioms NonosExtraction.TypesProtection.protectionflags_new_claims_no_protection
#print axioms NonosExtraction.TypesProtection.protectionflags_new_is_not_fully_protected
#print axioms NonosExtraction.TypesProtection.protectionflags_is_fully_protected_exactly_when_smep_smap_nx_and_wp_are_set
#print axioms NonosExtraction.TypesProtection.protectionflags_is_fully_protected_ignores_umip

end NonosExtraction.TypesProtection
