-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [nonos_x_types_percpu]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace nonos_x_types_percpu

/-- [nonos_x_types_percpu::percpu::PercpuRegion]
    Source: 'src/../../../../../src/memory/layout/types/percpu.rs', lines 18:0-22:1
    Visibility: public -/
structure percpu.PercpuRegion where
  base : Std.U64
  size : Std.Usize
  cpu_id : Std.U32

/-- [nonos_x_types_percpu::percpu::{nonos_x_types_percpu::percpu::PercpuRegion}::new]:
    Source: 'src/../../../../../src/memory/layout/types/percpu.rs', lines 25:4-27:5
    Visibility: public -/
def percpu.PercpuRegion.new
  (base : Std.U64) (size : Std.Usize) (cpu_id : Std.U32) :
  Result percpu.PercpuRegion
  := do
  ok { base, size, cpu_id }

/-- [nonos_x_types_percpu::percpu::{nonos_x_types_percpu::percpu::PercpuRegion}::end]:
    Source: 'src/../../../../../src/memory/layout/types/percpu.rs', lines 30:4-32:5
    Visibility: public -/
def percpu.PercpuRegion.end (self : percpu.PercpuRegion) : Result Std.U64 := do
  let i ← lift (UScalar.cast .U64 self.size)
  ok (core.num.U64.saturating_add self.base i)

/-- [nonos_x_types_percpu::percpu::{nonos_x_types_percpu::percpu::PercpuRegion}::contains]:
    Source: 'src/../../../../../src/memory/layout/types/percpu.rs', lines 37:4-39:5
    Visibility: public -/
def percpu.PercpuRegion.contains
  (self : percpu.PercpuRegion) (addr : Std.U64) : Result Bool := do
  if addr >= self.base
  then
    let i ← addr - self.base
    let i1 ← lift (UScalar.cast .U64 self.size)
    ok (i < i1)
  else ok false

/-- [nonos_x_types_percpu::percpuregion_new]:
    Source: 'src/lib.rs', lines 10:0-12:1
    Visibility: public -/
def percpuregion_new
  (base : Std.U64) (size : Std.Usize) (cpu_id : Std.U32) :
  Result percpu.PercpuRegion
  := do
  percpu.PercpuRegion.new base size cpu_id

/-- [nonos_x_types_percpu::percpuregion_end]:
    Source: 'src/lib.rs', lines 14:0-16:1
    Visibility: public -/
def percpuregion_end (this : percpu.PercpuRegion) : Result Std.U64 := do
  percpu.PercpuRegion.end this

/-- [nonos_x_types_percpu::percpuregion_contains]:
    Source: 'src/lib.rs', lines 18:0-20:1
    Visibility: public -/
def percpuregion_contains
  (this : percpu.PercpuRegion) (addr : Std.U64) : Result Bool := do
  percpu.PercpuRegion.contains this addr

end nonos_x_types_percpu
