/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

stack, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.TypesStack
import NonosExtraction.LayoutStackSlotsRefinement

open Aeneas Aeneas.Std Result
open nonos_x_types_stack

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.TypesStack

/-! ### The forwarding functions add nothing -/

theorem the_stackregion_new_wrapper_is_its_method (a : Std.U64) (b : Std.Usize) (c : Std.Usize) :
    stackregion_new a b c = stack.StackRegion.new a b c := rfl

theorem the_stackregion_per_cpu_wrapper_is_its_method (a : Std.U64) (b : Std.Usize) (c : Std.Usize) (d : Std.U32) :
    stackregion_per_cpu a b c d = stack.StackRegion.per_cpu a b c d := rfl

theorem the_stackregion_total_size_wrapper_is_its_method (a : stack.StackRegion) :
    stackregion_total_size a = stack.StackRegion.total_size a := rfl

theorem the_stackregion_stack_top_wrapper_is_its_method (a : stack.StackRegion) :
    stackregion_stack_top a = stack.StackRegion.stack_top a := rfl

/-! ### Where a stack region ends, and what it refuses

`new` and `per_cpu` build the same region apart from the CPU tag, and neither
moves or swaps the three numbers it is given. `stack_top` is `base + size` and
`total_size` is `size + guard_size`, both overflow checked: a region whose top or
whose footprint has no representable value is refused with an integer overflow,
never reported as a wrapped small number. The guard never enters `stack_top`.

These theorems are about the five functions as extracted. They cannot see the
callers that build regions, `get_all_stack_regions` in
`layout/manager/percpu.rs` and `get_guard_regions` in
`safety/manager/guards.rs`, which are not extracted; the last two theorems say
what `stack_top` implies for the layout those callers produce.
-/

/-- A fresh region keeps each argument in its own field and is owned by no CPU
and no thread. -/
theorem stackregion_new_keeps_its_arguments_and_is_unowned
    (b : Std.U64) (s g : Std.Usize) :
    ∃ r, stackregion_new b s g = ok r ∧ r.base = b ∧ r.size = s ∧
      r.guard_size = g ∧ r.cpu_id = none ∧ r.thread_id = none :=
  ⟨_, rfl, rfl, rfl, rfl, rfl, rfl⟩

/-- `per_cpu` is `new` with the CPU tag set, and agrees with it on every other
field, so a per CPU stack is not placed or sized differently from a plain one. -/
theorem stackregion_per_cpu_is_stackregion_new_tagged_with_its_cpu
    (b : Std.U64) (s g : Std.Usize) (c : Std.U32) :
    ∃ r, stackregion_new b s g = ok r ∧
      stackregion_per_cpu b s g c = ok { r with cpu_id := some c } :=
  ⟨_, rfl, rfl⟩

/-- `stack_top` returns exactly `base + size` when that sum fits in 64 bits,
and the guard size plays no part. -/
theorem stackregion_stack_top_is_base_plus_size_when_it_fits
    (r : stack.StackRegion) (v : Std.U64) :
    stackregion_stack_top r = ok v ↔
      (r.base.val + r.size.val ≤ U64.max ∧ v.val = r.base.val + r.size.val) := by
  unfold stackregion_stack_top stack.StackRegion.stack_top
  simp only [lift, bind_tc_ok]
  have hc : (UScalar.cast .U64 r.size : Std.U64).val = r.size.val := by simp
  have h := UScalar.add_equiv r.base (UScalar.cast .U64 r.size : Std.U64)
  rw [hc] at h
  constructor
  · intro hv
    rw [hv] at h
    simp only [U64.max_eq] at *
    obtain ⟨h1, h2, _⟩ := h
    simp [UScalarTy.numBits] at h1
    omega
  · rintro ⟨hle, hv⟩
    cases hr : (r.base + (UScalar.cast .U64 r.size : Std.U64) : Result Std.U64) with
    | ok z =>
      rw [hr] at h
      obtain ⟨_, h2, _⟩ := h
      have : z = v := UScalar.eq_of_val_eq (by omega)
      rw [this]
    | fail e =>
      rw [hr] at h
      simp [UScalar.inBounds, UScalarTy.numBits] at h
      simp only [U64.max_eq] at hle
      omega
    | div => rw [hr] at h; exact h.elim

/-- A region whose top fits in 64 bits always has one. -/
theorem stackregion_stack_top_succeeds_when_it_fits
    (r : stack.StackRegion) (h : r.base.val + r.size.val ≤ U64.max) :
    ∃ t, stackregion_stack_top r = ok t ∧ t.val = r.base.val + r.size.val := by
  unfold stackregion_stack_top stack.StackRegion.stack_top
  simp only [lift, bind_tc_ok]
  have hc : (UScalar.cast .U64 r.size : Std.U64).val = r.size.val := by simp
  have ha := UScalar.add_equiv r.base (UScalar.cast .U64 r.size : Std.U64)
  rw [hc] at ha
  cases hr : (r.base + (UScalar.cast .U64 r.size : Std.U64) : Result Std.U64) with
  | ok z => rw [hr] at ha; exact ⟨z, rfl, ha.2.1⟩
  | fail e =>
    rw [hr] at ha
    simp [UScalar.inBounds, UScalarTy.numBits] at ha
    simp only [U64.max_eq] at h
    omega
  | div => rw [hr] at ha; exact ha.elim

/-- A region whose top would pass `2^64` is refused rather than wrapped. -/
theorem stackregion_stack_top_refuses_a_top_past_the_address_space
    (r : stack.StackRegion) (h : U64.max < r.base.val + r.size.val) :
    stackregion_stack_top r = fail .integerOverflow := by
  unfold stackregion_stack_top stack.StackRegion.stack_top
  simp only [lift, bind_tc_ok]
  have hc : (UScalar.cast .U64 r.size : Std.U64).val = r.size.val := by simp
  have ha := UScalar.add_equiv r.base (UScalar.cast .U64 r.size : Std.U64)
  rw [hc] at ha
  cases hr : (r.base + (UScalar.cast .U64 r.size : Std.U64) : Result Std.U64) with
  | ok z =>
    rw [hr] at ha
    simp only [U64.max_eq] at h
    simp [UScalarTy.numBits] at ha
    omega
  | fail e =>
    have : e = .integerOverflow := by
      revert hr
      simp only [HAdd.hAdd, UScalar.add, UScalar.tryMk, UScalar.tryMkOpt]
      split <;> simp_all
    rw [this]
  | div => rw [hr] at ha; exact ha.elim

/-- A 64 KiB stack flush against the top of the address space has no
representable top and is refused, not reported as top 0. -/
theorem stackregion_stack_top_refuses_a_stack_ending_at_two_to_the_64 :
    stackregion_stack_top
      ⟨0xFFFFFFFFFFFF0000#u64, 0x10000#usize, 0x1000#usize, none, none⟩ =
      fail .integerOverflow :=
  stackregion_stack_top_refuses_a_top_past_the_address_space _ (by
    simp only [U64.max_eq]; simp)

/-- `total_size` returns exactly `size + guard_size` when the sum fits in a
`usize`, so a returned footprint is never smaller than the stack it covers. -/
theorem stackregion_total_size_is_size_plus_one_guard_when_it_fits
    (r : stack.StackRegion) (v : Std.Usize) :
    stackregion_total_size r = ok v ↔
      (r.size.val + r.guard_size.val ≤ Usize.max ∧
        v.val = r.size.val + r.guard_size.val) := by
  unfold stackregion_total_size stack.StackRegion.total_size
  have h := UScalar.add_equiv r.size r.guard_size
  have hm : Usize.max = 2 ^ UScalarTy.Usize.numBits - 1 := by
    simp [Usize.max, UScalarTy.numBits, Usize.numBits]
  have hp : 0 < 2 ^ UScalarTy.Usize.numBits := Nat.two_pow_pos _
  constructor
  · intro hv
    rw [hv] at h
    obtain ⟨h1, h2, _⟩ := h
    omega
  · rintro ⟨hle, hv⟩
    cases hr : (r.size + r.guard_size : Result Std.Usize) with
    | ok z =>
      rw [hr] at h
      obtain ⟨_, h2, _⟩ := h
      have : z = v := UScalar.eq_of_val_eq (by omega)
      rw [this]
    | fail e =>
      rw [hr] at h
      simp [UScalar.inBounds] at h
      have hn : UScalarTy.Usize.numBits = System.Platform.numBits := rfl
      rw [hn] at hm hp
      omega
    | div => rw [hr] at h; exact h.elim

/-- A footprint that would pass the top of `usize` is refused. -/
theorem stackregion_total_size_refuses_a_footprint_past_usize_max
    (r : stack.StackRegion) (h : Usize.max < r.size.val + r.guard_size.val) :
    ∃ e, stackregion_total_size r = fail e := by
  unfold stackregion_total_size stack.StackRegion.total_size
  have ha := UScalar.add_equiv r.size r.guard_size
  have hm : Usize.max = 2 ^ UScalarTy.Usize.numBits - 1 := by
    simp [Usize.max, UScalarTy.numBits, Usize.numBits]
  cases hr : (r.size + r.guard_size : Result Std.Usize) with
  | ok z => rw [hr] at ha; omega
  | fail e => exact ⟨e, rfl⟩
  | div => rw [hr] at ha; exact ha.elim

/-- A per CPU kernel stack, 64 KiB with a one page guard, tops out exactly
64 KiB above its base, and `get_guard_regions` takes its upper guard to start
there. -/
theorem stackregion_stack_top_of_a_kernel_stack_is_its_base_plus_64_kib
    (b : Std.U64) (c : Std.U32) (hb : b.val + 0x10000 ≤ U64.max) :
    ∃ k t, stackregion_per_cpu b 0x10000#usize 0x1000#usize c = ok k ∧
      stackregion_stack_top k = ok t ∧ t.val = b.val + 0x10000 := by
  obtain ⟨t, ht, hv⟩ := stackregion_stack_top_succeeds_when_it_fits
    ⟨b, 0x10000#usize, 0x1000#usize, some c, none⟩ (by simpa using hb)
  exact ⟨_, t, rfl, ht, by simpa using hv⟩

/-- The kernel stack's upper guard page is unmapped: with the kernel stack at
slot 0 of a CPU's stack area and the first IST stack at slot 1, as
`get_all_stack_regions` places them through `stack_slot_offset`, the kernel
stack's top lies exactly one page below the IST stack's base. The layout used
to put the first IST stack at `stack_base + KSTACK_SIZE`, which is the kernel
stack's top, so the page `get_guard_regions` treated as the kernel stack's
upper guard was the IST stack's first page. -/
theorem a_kernel_stack_ends_one_guard_page_below_the_first_ist_stack
    (area : Std.U64) (c : Std.U32) (ha : area.val + 73728 ≤ U64.max) :
    ∃ o0 o1 : Std.U64,
      nonos_x_layout_stack_slots.stack_slot_offset 0#usize = ok o0 ∧
      nonos_x_layout_stack_slots.stack_slot_offset 1#usize = ok o1 ∧
      ∀ b : Std.U64, b.val = area.val + o0.val →
        ∃ k t, stackregion_per_cpu b 0x10000#usize 0x1000#usize c = ok k ∧
          stackregion_stack_top k = ok t ∧ t.val + 4096 = area.val + o1.val := by
  obtain ⟨o0, h0, hv0⟩ := WP.spec_imp_exists
    (NonosExtraction.LayoutStackSlots.stack_slot_offset_spec 0#usize (by decide))
  obtain ⟨o1, h1, hv1⟩ := WP.spec_imp_exists
    (NonosExtraction.LayoutStackSlots.stack_slot_offset_spec 1#usize (by decide))
  have e0 : (0#usize : Std.Usize).val = 0 := rfl
  have e1 : (1#usize : Std.Usize).val = 1 := rfl
  rw [e0, if_pos rfl] at hv0
  rw [e1, if_neg (by decide)] at hv1
  refine ⟨o0, o1, h0, h1, fun b hb => ?_⟩
  obtain ⟨k, t, hk, ht, htv⟩ :=
    stackregion_stack_top_of_a_kernel_stack_is_its_base_plus_64_kib b c (by omega)
  exact ⟨k, t, hk, ht, by omega⟩

/-! ### Axiom profile -/

#print axioms NonosExtraction.TypesStack.the_stackregion_new_wrapper_is_its_method
#print axioms NonosExtraction.TypesStack.the_stackregion_per_cpu_wrapper_is_its_method
#print axioms NonosExtraction.TypesStack.the_stackregion_total_size_wrapper_is_its_method
#print axioms NonosExtraction.TypesStack.the_stackregion_stack_top_wrapper_is_its_method
#print axioms NonosExtraction.TypesStack.stackregion_new_keeps_its_arguments_and_is_unowned
#print axioms NonosExtraction.TypesStack.stackregion_per_cpu_is_stackregion_new_tagged_with_its_cpu
#print axioms NonosExtraction.TypesStack.stackregion_stack_top_is_base_plus_size_when_it_fits
#print axioms NonosExtraction.TypesStack.stackregion_stack_top_succeeds_when_it_fits
#print axioms NonosExtraction.TypesStack.stackregion_stack_top_refuses_a_top_past_the_address_space
#print axioms NonosExtraction.TypesStack.stackregion_stack_top_refuses_a_stack_ending_at_two_to_the_64
#print axioms NonosExtraction.TypesStack.stackregion_total_size_is_size_plus_one_guard_when_it_fits
#print axioms NonosExtraction.TypesStack.stackregion_total_size_refuses_a_footprint_past_usize_max
#print axioms NonosExtraction.TypesStack.stackregion_stack_top_of_a_kernel_stack_is_its_base_plus_64_kib
#print axioms NonosExtraction.TypesStack.a_kernel_stack_ends_one_guard_page_below_the_first_ist_stack

end NonosExtraction.TypesStack
