/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

types, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.UtilsTypes

open Aeneas Aeneas.Std Result
open nonos_x_utils_types

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.UtilsTypes

/-! ### The forwarding functions add nothing -/

theorem the_scanconfig_new_wrapper_is_its_method :
    scanconfig_new = types.ScanConfig.new := rfl

theorem the_scanconfig_with_max_depth_wrapper_is_its_method (a : types.ScanConfig) (b : Std.Usize) :
    scanconfig_with_max_depth a b = types.ScanConfig.with_max_depth a b := rfl

theorem the_scanconfig_hidden_only_wrapper_is_its_method (a : types.ScanConfig) :
    scanconfig_hidden_only a = types.ScanConfig.hidden_only a := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.UtilsTypes.the_scanconfig_new_wrapper_is_its_method
#print axioms NonosExtraction.UtilsTypes.the_scanconfig_with_max_depth_wrapper_is_its_method
#print axioms NonosExtraction.UtilsTypes.the_scanconfig_hidden_only_wrapper_is_its_method

end NonosExtraction.UtilsTypes
