/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

caps_bits, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.VerifyCapsBits

open Aeneas Aeneas.Std Result
open nonos_x_verify_caps_bits

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.VerifyCapsBits

/-! ### The forwarding functions add nothing -/

theorem the_within_ceiling_wrapper_is_its_method (a : Std.U64) (b : Std.U64) (c : Std.U64) :
    within_ceiling a b c = caps_bits.within_ceiling a b c := rfl

theorem the_grant_within_manifest_wrapper_is_its_method (a : Std.U64) (b : Std.U64) (c : Std.U64) :
    grant_within_manifest a b c = caps_bits.grant_within_manifest a b c := rfl

theorem the_install_caps_wrapper_is_its_method (a : Std.U64) (b : Std.U64) (c : Std.U64) :
    install_caps a b c = caps_bits.install_caps a b c := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.VerifyCapsBits.the_within_ceiling_wrapper_is_its_method
#print axioms NonosExtraction.VerifyCapsBits.the_grant_within_manifest_wrapper_is_its_method
#print axioms NonosExtraction.VerifyCapsBits.the_install_caps_wrapper_is_its_method

end NonosExtraction.VerifyCapsBits
