-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [nonos_x_vga_constants]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace nonos_x_vga_constants

/-- [nonos_x_vga_constants::constants::Color]
    Source: 'src/../../../../../src/arch/x86_64/vga/constants.rs', lines 38:0-55:1
    Visibility: public -/
@[discriminant u8]
inductive constants.Color where
| Black : constants.Color
| Blue : constants.Color
| Green : constants.Color
| Cyan : constants.Color
| Red : constants.Color
| Magenta : constants.Color
| Brown : constants.Color
| LightGray : constants.Color
| DarkGray : constants.Color
| LightBlue : constants.Color
| LightGreen : constants.Color
| LightCyan : constants.Color
| LightRed : constants.Color
| Pink : constants.Color
| Yellow : constants.Color
| White : constants.Color

/-- [nonos_x_vga_constants::constants::ColorCode]
    Source: 'src/../../../../../src/arch/x86_64/vga/constants.rs', lines 82:0-82:25
    Visibility: public -/
@[reducible]
def constants.ColorCode := Std.U8

/-- [nonos_x_vga_constants::constants::{nonos_x_vga_constants::constants::ColorCode}::new]:
    Source: 'src/../../../../../src/arch/x86_64/vga/constants.rs', lines 88:4-90:5
    Visibility: public -/
def constants.ColorCode.new
  (foreground : constants.Color) (background : constants.Color) :
  Result constants.ColorCode
  := do
  let background1 := read_discriminant background
  let i ← lift (UScalar.cast .U8 background1)
  let i1 ← lift (i &&& 7#u8)
  let i2 ← i1 <<< 4#i32
  let foreground1 := read_discriminant foreground
  let i3 ← lift (UScalar.cast .U8 foreground1)
  let i4 ← lift (i2 ||| i3)
  ok i4

/-- [nonos_x_vga_constants::constants::{nonos_x_vga_constants::constants::ColorCode}::foreground]:
    Source: 'src/../../../../../src/arch/x86_64/vga/constants.rs', lines 96:4-98:5
    Visibility: public -/
def constants.ColorCode.foreground
  (self : constants.ColorCode) : Result Std.U8 := do
  ok (self &&& 15#u8)

/-- [nonos_x_vga_constants::constants::{nonos_x_vga_constants::constants::ColorCode}::background]:
    Source: 'src/../../../../../src/arch/x86_64/vga/constants.rs', lines 100:4-102:5
    Visibility: public -/
def constants.ColorCode.background
  (self : constants.ColorCode) : Result Std.U8 := do
  let i ← self >>> 4#i32
  ok (i &&& 7#u8)

/-- [nonos_x_vga_constants::constants::{nonos_x_vga_constants::constants::ColorCode}::is_blinking]:
    Source: 'src/../../../../../src/arch/x86_64/vga/constants.rs', lines 104:4-106:5
    Visibility: public -/
def constants.ColorCode.is_blinking
  (self : constants.ColorCode) : Result Bool := do
  let i ← lift (self &&& 128#u8)
  ok (i != 0#u8)

/-- [nonos_x_vga_constants::constants::{nonos_x_vga_constants::constants::ColorCode}::value]:
    Source: 'src/../../../../../src/arch/x86_64/vga/constants.rs', lines 108:4-110:5
    Visibility: public -/
def constants.ColorCode.value
  (self : constants.ColorCode) : Result Std.U8 := do
  ok self

/-- [nonos_x_vga_constants::constants::ScreenChar]
    Source: 'src/../../../../../src/arch/x86_64/vga/constants.rs', lines 121:0-124:1
    Visibility: public -/
structure constants.ScreenChar where
  character : Std.U8
  color : constants.ColorCode

/-- [nonos_x_vga_constants::constants::{nonos_x_vga_constants::constants::ScreenChar}::as_u16]:
    Source: 'src/../../../../../src/arch/x86_64/vga/constants.rs', lines 135:4-137:5
    Visibility: public -/
def constants.ScreenChar.as_u16
  (self : constants.ScreenChar) : Result Std.U16 := do
  let i ← constants.ColorCode.value self.color
  let i1 ← lift (UScalar.cast .U16 i)
  let i2 ← i1 <<< 8#i32
  let i3 ← lift (UScalar.cast .U16 self.character)
  ok (i2 ||| i3)

/-- [nonos_x_vga_constants::colorcode_foreground]:
    Source: 'src/lib.rs', lines 10:0-12:1
    Visibility: public -/
def colorcode_foreground (this : constants.ColorCode) : Result Std.U8 := do
  constants.ColorCode.foreground this

/-- [nonos_x_vga_constants::colorcode_background]:
    Source: 'src/lib.rs', lines 14:0-16:1
    Visibility: public -/
def colorcode_background (this : constants.ColorCode) : Result Std.U8 := do
  constants.ColorCode.background this

/-- [nonos_x_vga_constants::colorcode_is_blinking]:
    Source: 'src/lib.rs', lines 18:0-20:1
    Visibility: public -/
def colorcode_is_blinking (this : constants.ColorCode) : Result Bool := do
  constants.ColorCode.is_blinking this

/-- [nonos_x_vga_constants::colorcode_value]:
    Source: 'src/lib.rs', lines 22:0-24:1
    Visibility: public -/
def colorcode_value (this : constants.ColorCode) : Result Std.U8 := do
  constants.ColorCode.value this

/-- [nonos_x_vga_constants::screenchar_as_u16]:
    Source: 'src/lib.rs', lines 26:0-28:1
    Visibility: public -/
def screenchar_as_u16 (this : constants.ScreenChar) : Result Std.U16 := do
  constants.ScreenChar.as_u16 this

/-- [nonos_x_vga_constants::colorcode_new]:
    Source: 'src/lib.rs', lines 31:0-33:1
    Visibility: public -/
def colorcode_new
  (foreground : constants.Color) (background : constants.Color) :
  Result constants.ColorCode
  := do
  constants.ColorCode.new foreground background

end nonos_x_vga_constants
