/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

colors, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.VgaColors

open Aeneas Aeneas.Std Result
open nonos_x_vga_colors

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.VgaColors

/-! ### The forwarding functions add nothing -/

theorem the_make_attr_wrapper_is_its_method (a : Std.U8) (b : Std.U8) :
    make_attr a b = colors.make_attr a b := rfl

theorem the_fg_color_wrapper_is_its_method (a : Std.U8) :
    fg_color a = colors.fg_color a := rfl

theorem the_bg_color_wrapper_is_its_method (a : Std.U8) :
    bg_color a = colors.bg_color a := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.VgaColors.the_make_attr_wrapper_is_its_method
#print axioms NonosExtraction.VgaColors.the_fg_color_wrapper_is_its_method
#print axioms NonosExtraction.VgaColors.the_bg_color_wrapper_is_its_method

end NonosExtraction.VgaColors
