/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

constants, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.VgaConstants

open Aeneas Aeneas.Std Result
open nonos_x_vga_constants

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.VgaConstants

/-! ### The forwarding functions add nothing -/

theorem the_colorcode_foreground_wrapper_is_its_method (a : constants.ColorCode) :
    colorcode_foreground a = constants.ColorCode.foreground a := rfl

theorem the_colorcode_background_wrapper_is_its_method (a : constants.ColorCode) :
    colorcode_background a = constants.ColorCode.background a := rfl

theorem the_colorcode_is_blinking_wrapper_is_its_method (a : constants.ColorCode) :
    colorcode_is_blinking a = constants.ColorCode.is_blinking a := rfl

theorem the_colorcode_value_wrapper_is_its_method (a : constants.ColorCode) :
    colorcode_value a = constants.ColorCode.value a := rfl

theorem the_screenchar_as_u16_wrapper_is_its_method (a : constants.ScreenChar) :
    screenchar_as_u16 a = constants.ScreenChar.as_u16 a := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.VgaConstants.the_colorcode_foreground_wrapper_is_its_method
#print axioms NonosExtraction.VgaConstants.the_colorcode_background_wrapper_is_its_method
#print axioms NonosExtraction.VgaConstants.the_colorcode_is_blinking_wrapper_is_its_method
#print axioms NonosExtraction.VgaConstants.the_colorcode_value_wrapper_is_its_method
#print axioms NonosExtraction.VgaConstants.the_screenchar_as_u16_wrapper_is_its_method

end NonosExtraction.VgaConstants
