/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

variable, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.X8664UefiVariableVariable

open Aeneas Aeneas.Std Result
open nonos_x_x86_64_uefi_variable_variable

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.X8664UefiVariableVariable

/-! ### The forwarding functions add nothing -/

theorem the_uefivariable_data_len_wrapper_is_its_method (a : arch.x86_64.uefi.variable.variable.UefiVariable) :
    uefivariable_data_len a = arch.x86_64.uefi.variable.variable.UefiVariable.data_len a := rfl

theorem the_uefivariable_is_empty_wrapper_is_its_method (a : arch.x86_64.uefi.variable.variable.UefiVariable) :
    uefivariable_is_empty a = arch.x86_64.uefi.variable.variable.UefiVariable.is_empty a := rfl

theorem the_uefivariable_is_non_volatile_wrapper_is_its_method (a : arch.x86_64.uefi.variable.variable.UefiVariable) :
    uefivariable_is_non_volatile a = arch.x86_64.uefi.variable.variable.UefiVariable.is_non_volatile a := rfl

theorem the_uefivariable_is_runtime_accessible_wrapper_is_its_method (a : arch.x86_64.uefi.variable.variable.UefiVariable) :
    uefivariable_is_runtime_accessible a = arch.x86_64.uefi.variable.variable.UefiVariable.is_runtime_accessible a := rfl

theorem the_uefivariable_as_bool_wrapper_is_its_method (a : arch.x86_64.uefi.variable.variable.UefiVariable) :
    uefivariable_as_bool a = arch.x86_64.uefi.variable.variable.UefiVariable.as_bool a := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.X8664UefiVariableVariable.the_uefivariable_data_len_wrapper_is_its_method
#print axioms NonosExtraction.X8664UefiVariableVariable.the_uefivariable_is_empty_wrapper_is_its_method
#print axioms NonosExtraction.X8664UefiVariableVariable.the_uefivariable_is_non_volatile_wrapper_is_its_method
#print axioms NonosExtraction.X8664UefiVariableVariable.the_uefivariable_is_runtime_accessible_wrapper_is_its_method
#print axioms NonosExtraction.X8664UefiVariableVariable.the_uefivariable_as_bool_wrapper_is_its_method

end NonosExtraction.X8664UefiVariableVariable
