-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [nonos_x_x86_64_vga_ops_lock]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace nonos_x_x86_64_vga_ops_lock

/-- [core::hint::spin_loop]:
    Source: '/rustc/library/core/src/hint.rs', lines 270:0-270:18
    Name pattern: [core::hint::spin_loop]
    Visibility: public -/
@[rust_fun "core::hint::spin_loop"] axiom core.hint.spin_loop : Result Unit

/-- [core::result::{core::result::Result<T, E>}::is_err]:
    Source: '/rustc/library/core/src/result.rs', lines 646:4-646:38
    Name pattern: [core::result::{core::result::Result<@T, @E>}::is_err]
    Visibility: public -/
@[rust_fun "core::result::{core::result::Result<@T, @E>}::is_err"]
axiom core.result.Result.is_err
  {T : Type} {E : Type} : core.result.Result T E → Result Bool

/-- [core::sync::atomic::private::Align1]
    Source: '/rustc/library/core/src/sync/atomic.rs', lines 264:4-264:24
    Name pattern: [core::sync::atomic::private::Align1]
    Visibility: public -/
@[rust_type "core::sync::atomic::private::Align1"]
axiom core.sync.atomic.private.Align1 (T : Type) : Type

/-- [core::sync::atomic::Atomic]
    Source: '/rustc/library/core/src/sync/atomic.rs', lines 366:0-366:37
    Name pattern: [core::sync::atomic::Atomic]
    Visibility: public -/
@[rust_type "core::sync::atomic::Atomic"]
axiom core.sync.atomic.Atomic (T : Type) (Clause0_Storage : Type) : Type

/-- [core::sync::atomic::Ordering]
    Source: '/rustc/library/core/src/sync/atomic.rs', lines 447:0-447:17
    Name pattern: [core::sync::atomic::Ordering]
    Visibility: public -/
@[discriminant isize, rust_type "core::sync::atomic::Ordering"]
inductive core.sync.atomic.Ordering where
| Relaxed : core.sync.atomic.Ordering
| Release : core.sync.atomic.Ordering
| Acquire : core.sync.atomic.Ordering
| AcqRel : core.sync.atomic.Ordering
| SeqCst : core.sync.atomic.Ordering

/-- [core::sync::atomic::{core::sync::atomic::Atomic<bool, core::sync::atomic::private::Align1<u8>>}::new]:
    Source: '/rustc/library/core/src/sync/atomic.rs', lines 536:4-536:43
    Name pattern: [core::sync::atomic::{core::sync::atomic::Atomic<bool, core::sync::atomic::private::Align1<u8>>}::new]
    Visibility: public -/
@[rust_fun
  "core::sync::atomic::{core::sync::atomic::Atomic<bool, core::sync::atomic::private::Align1<u8>>}::new"]
axiom core.sync.atomic.AtomicBoolAlign1U8.new
  :
  Bool → Result (core.sync.atomic.Atomic Bool
    (core.sync.atomic.private.Align1 Std.U8))

/-- [core::sync::atomic::{core::sync::atomic::Atomic<bool, core::sync::atomic::private::Align1<u8>>}::load]:
    Source: '/rustc/library/core/src/sync/atomic.rs', lines 738:4-738:47
    Name pattern: [core::sync::atomic::{core::sync::atomic::Atomic<bool, core::sync::atomic::private::Align1<u8>>}::load]
    Visibility: public -/
@[rust_fun
  "core::sync::atomic::{core::sync::atomic::Atomic<bool, core::sync::atomic::private::Align1<u8>>}::load"]
axiom core.sync.atomic.AtomicBoolAlign1U8.load
  :
  core.sync.atomic.Atomic Bool (core.sync.atomic.private.Align1 Std.U8) →
    core.sync.atomic.Ordering → Result Bool

/-- [core::sync::atomic::{core::sync::atomic::Atomic<bool, core::sync::atomic::private::Align1<u8>>}::store]:
    Source: '/rustc/library/core/src/sync/atomic.rs', lines 767:4-767:51
    Name pattern: [core::sync::atomic::{core::sync::atomic::Atomic<bool, core::sync::atomic::private::Align1<u8>>}::store]
    Visibility: public -/
@[rust_fun
  "core::sync::atomic::{core::sync::atomic::Atomic<bool, core::sync::atomic::private::Align1<u8>>}::store"]
axiom core.sync.atomic.AtomicBoolAlign1U8.store
  :
  core.sync.atomic.Atomic Bool (core.sync.atomic.private.Align1 Std.U8) →
    Bool → core.sync.atomic.Ordering → Result Unit

/-- [core::sync::atomic::{core::sync::atomic::Atomic<bool, core::sync::atomic::private::Align1<u8>>}::compare_exchange_weak]:
    Source: '/rustc/library/core/src/sync/atomic.rs', lines 1032:4-1038:27
    Name pattern: [core::sync::atomic::{core::sync::atomic::Atomic<bool, core::sync::atomic::private::Align1<u8>>}::compare_exchange_weak]
    Visibility: public -/
@[rust_fun
  "core::sync::atomic::{core::sync::atomic::Atomic<bool, core::sync::atomic::private::Align1<u8>>}::compare_exchange_weak"]
axiom core.sync.atomic.AtomicBoolAlign1U8.compare_exchange_weak
  :
  core.sync.atomic.Atomic Bool (core.sync.atomic.private.Align1 Std.U8) →
    Bool → Bool → core.sync.atomic.Ordering → core.sync.atomic.Ordering
    → Result (core.result.Result Bool Bool)

/-- [nonos_x_x86_64_vga_ops_lock::arch::x86_64::vga::state::VGA_LOCK]
    Source: 'src/arch/x86_64/vga/../../../../../../../../src/arch/x86_64/vga/state.rs', lines 26:0-26:64 -/
@[global_simps, irreducible]
def arch.x86_64.vga.state.VGA_LOCK
  :
  Result (core.sync.atomic.Atomic Bool (core.sync.atomic.private.Align1
    Std.U8))
  :=
  core.sync.atomic.AtomicBoolAlign1U8.new false

/-- [nonos_x_x86_64_vga_ops_lock::arch::x86_64::vga::state::PANIC_MODE]
    Source: 'src/arch/x86_64/vga/../../../../../../../../src/arch/x86_64/vga/state.rs', lines 27:0-27:66 -/
@[global_simps, irreducible]
def arch.x86_64.vga.state.PANIC_MODE
  :
  Result (core.sync.atomic.Atomic Bool (core.sync.atomic.private.Align1
    Std.U8))
  :=
  core.sync.atomic.AtomicBoolAlign1U8.new false

/-- [nonos_x_x86_64_vga_ops_lock::arch::x86_64::vga::ops::lock::acquire_lock]: loop body 0:
    Source: 'src/arch/x86_64/vga/ops/../../../../../../../../../src/arch/x86_64/vga/ops/lock.rs', lines 26:4-35:1
    Visibility: public -/
@[rust_loop_body]
def arch.x86_64.vga.ops.lock.acquire_lock_loop.body
  (attempts : Std.I32) : Result (ControlFlow Std.I32 Bool) := do
  let a ← arch.x86_64.vga.state.VGA_LOCK
  let r ←
    core.sync.atomic.AtomicBoolAlign1U8.compare_exchange_weak a false true
      core.sync.atomic.Ordering.Acquire core.sync.atomic.Ordering.Relaxed
  let b ← core.result.Result.is_err r
  if b
  then
    let attempts1 ← attempts + 1#i32
    if attempts1 > 1000#i32
    then ok (done false)
    else core.hint.spin_loop
         ok (cont attempts1)
  else ok (done true)

/-- [nonos_x_x86_64_vga_ops_lock::arch::x86_64::vga::ops::lock::acquire_lock]: loop 0:
    Source: 'src/arch/x86_64/vga/ops/../../../../../../../../../src/arch/x86_64/vga/ops/lock.rs', lines 26:4-35:1
    Visibility: public -/
@[rust_loop]
def arch.x86_64.vga.ops.lock.acquire_lock_loop
  (attempts : Std.I32) : Result Bool := do
  loop
    (fun attempts1 => arch.x86_64.vga.ops.lock.acquire_lock_loop.body
      attempts1)
    attempts

/-- [nonos_x_x86_64_vga_ops_lock::arch::x86_64::vga::ops::lock::acquire_lock]:
    Source: 'src/arch/x86_64/vga/ops/../../../../../../../../../src/arch/x86_64/vga/ops/lock.rs', lines 20:0-35:1
    Visibility: public -/
def arch.x86_64.vga.ops.lock.acquire_lock : Result Bool := do
  let a ← arch.x86_64.vga.state.PANIC_MODE
  let b ←
    core.sync.atomic.AtomicBoolAlign1U8.load a
      core.sync.atomic.Ordering.Relaxed
  if b
  then ok true
  else arch.x86_64.vga.ops.lock.acquire_lock_loop 0#i32

/-- [nonos_x_x86_64_vga_ops_lock::arch::x86_64::vga::ops::lock::release_lock]:
    Source: 'src/arch/x86_64/vga/ops/../../../../../../../../../src/arch/x86_64/vga/ops/lock.rs', lines 37:0-41:1
    Visibility: public -/
def arch.x86_64.vga.ops.lock.release_lock : Result Unit := do
  let a ← arch.x86_64.vga.state.PANIC_MODE
  let b ←
    core.sync.atomic.AtomicBoolAlign1U8.load a
      core.sync.atomic.Ordering.Relaxed
  if b
  then ok ()
  else
    let a1 ← arch.x86_64.vga.state.VGA_LOCK
    core.sync.atomic.AtomicBoolAlign1U8.store a1 false
      core.sync.atomic.Ordering.Release

/-- [nonos_x_x86_64_vga_ops_lock::acquire_lock]:
    Source: 'src/lib.rs', lines 11:0-13:1
    Visibility: public -/
def acquire_lock : Result Bool := do
  arch.x86_64.vga.ops.lock.acquire_lock

/-- [nonos_x_x86_64_vga_ops_lock::release_lock]:
    Source: 'src/lib.rs', lines 15:0-17:1
    Visibility: public -/
def release_lock : Result Unit := do
  arch.x86_64.vga.ops.lock.release_lock

end nonos_x_x86_64_vga_ops_lock
