/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

mcfg_types, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.X8664AcpiTablesMcfgTypes

open Aeneas Aeneas.Std Result
open nonos_x_x86_64_acpi_tables_mcfg_types

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.X8664AcpiTablesMcfgTypes

/-! ### The forwarding functions add nothing -/

theorem the_mcfg_entry_count_wrapper_is_its_method (a : arch.x86_64.acpi.tables.mcfg_types.Mcfg) :
    mcfg_entry_count a = arch.x86_64.acpi.tables.mcfg_types.Mcfg.entry_count a := rfl

theorem the_mcfg_entries_offset_wrapper_is_its_method (a : arch.x86_64.acpi.tables.mcfg_types.Mcfg) :
    mcfg_entries_offset a = arch.x86_64.acpi.tables.mcfg_types.Mcfg.entries_offset a := rfl

theorem the_mcfgentry_bus_count_wrapper_is_its_method (a : arch.x86_64.acpi.tables.mcfg_types.McfgEntry) :
    mcfgentry_bus_count a = arch.x86_64.acpi.tables.mcfg_types.McfgEntry.bus_count a := rfl

theorem the_mcfgentry_contains_bus_wrapper_is_its_method (a : arch.x86_64.acpi.tables.mcfg_types.McfgEntry) (b : Std.U8) :
    mcfgentry_contains_bus a b = arch.x86_64.acpi.tables.mcfg_types.McfgEntry.contains_bus a b := rfl

theorem the_mcfgentry_memory_size_wrapper_is_its_method (a : arch.x86_64.acpi.tables.mcfg_types.McfgEntry) :
    mcfgentry_memory_size a = arch.x86_64.acpi.tables.mcfg_types.McfgEntry.memory_size a := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.X8664AcpiTablesMcfgTypes.the_mcfg_entry_count_wrapper_is_its_method
#print axioms NonosExtraction.X8664AcpiTablesMcfgTypes.the_mcfg_entries_offset_wrapper_is_its_method
#print axioms NonosExtraction.X8664AcpiTablesMcfgTypes.the_mcfgentry_bus_count_wrapper_is_its_method
#print axioms NonosExtraction.X8664AcpiTablesMcfgTypes.the_mcfgentry_contains_bus_wrapper_is_its_method
#print axioms NonosExtraction.X8664AcpiTablesMcfgTypes.the_mcfgentry_memory_size_wrapper_is_its_method

end NonosExtraction.X8664AcpiTablesMcfgTypes
