/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

types, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.X8664UefiSignatureTypes

open Aeneas Aeneas.Std Result
open nonos_x_x86_64_uefi_signature_types

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.X8664UefiSignatureTypes

/-! ### The forwarding functions add nothing -/

theorem the_signatureentry_data_len_wrapper_is_its_method (a : arch.x86_64.uefi.signature.types.SignatureEntry) :
    signatureentry_data_len a = arch.x86_64.uefi.signature.types.SignatureEntry.data_len a := rfl

theorem the_signatureentry_total_size_wrapper_is_its_method (a : arch.x86_64.uefi.signature.types.SignatureEntry) :
    signatureentry_total_size a = arch.x86_64.uefi.signature.types.SignatureEntry.total_size a := rfl

theorem the_signaturelist_entry_count_wrapper_is_its_method (a : arch.x86_64.uefi.signature.types.SignatureList) :
    signaturelist_entry_count a = arch.x86_64.uefi.signature.types.SignatureList.entry_count a := rfl

theorem the_signaturelist_is_empty_wrapper_is_its_method (a : arch.x86_64.uefi.signature.types.SignatureList) :
    signaturelist_is_empty a = arch.x86_64.uefi.signature.types.SignatureList.is_empty a := rfl

theorem the_signaturelist_signature_size_wrapper_is_its_method (a : arch.x86_64.uefi.signature.types.SignatureList) :
    signaturelist_signature_size a = arch.x86_64.uefi.signature.types.SignatureList.signature_size a := rfl

theorem the_signaturelist_total_size_wrapper_is_its_method (a : arch.x86_64.uefi.signature.types.SignatureList) :
    signaturelist_total_size a = arch.x86_64.uefi.signature.types.SignatureList.total_size a := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.X8664UefiSignatureTypes.the_signatureentry_data_len_wrapper_is_its_method
#print axioms NonosExtraction.X8664UefiSignatureTypes.the_signatureentry_total_size_wrapper_is_its_method
#print axioms NonosExtraction.X8664UefiSignatureTypes.the_signaturelist_entry_count_wrapper_is_its_method
#print axioms NonosExtraction.X8664UefiSignatureTypes.the_signaturelist_is_empty_wrapper_is_its_method
#print axioms NonosExtraction.X8664UefiSignatureTypes.the_signaturelist_signature_size_wrapper_is_its_method
#print axioms NonosExtraction.X8664UefiSignatureTypes.the_signaturelist_total_size_wrapper_is_its_method

end NonosExtraction.X8664UefiSignatureTypes
