/-
NONOS Operating System
Copyright (C) 2026 NONOS Contributors

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU Affero General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option) any
later version. See <https://www.gnu.org/licenses/>.

channel, on the extracted code.

Charon cannot take an inherent method as an entry point, so the crate root
carries a free function per method and those are the names the manifest counts.
A wrapper that quietly did something other than call through would make every
theorem about the method a statement about code nobody runs, so each one is
proven to be its method below.

These are generated by tools/extraction/mirror_crate.py and are the floor, not
the point. The properties that matter go beneath them, and the shapes most of
them take are stated once in NonosExtraction.Shapes.
-/

import NonosExtraction.X8664TimePitChannel

open Aeneas Aeneas.Std Result
open nonos_x_x86_64_time_pit_channel

set_option linter.hashCommand false
set_option maxRecDepth 100000

namespace NonosExtraction.X8664TimePitChannel

/-! ### The forwarding functions add nothing -/

theorem the_channel_data_port_wrapper_is_its_method (a : arch.x86_64.time.pit.channel.Channel) :
    channel_data_port a = arch.x86_64.time.pit.channel.Channel.data_port a := rfl

theorem the_channel_select_bits_wrapper_is_its_method (a : arch.x86_64.time.pit.channel.Channel) :
    channel_select_bits a = arch.x86_64.time.pit.channel.Channel.select_bits a := rfl

theorem the_channel_readback_bit_wrapper_is_its_method (a : arch.x86_64.time.pit.channel.Channel) :
    channel_readback_bit a = arch.x86_64.time.pit.channel.Channel.readback_bit a := rfl

/-! ### Axiom profile -/

#print axioms NonosExtraction.X8664TimePitChannel.the_channel_data_port_wrapper_is_its_method
#print axioms NonosExtraction.X8664TimePitChannel.the_channel_select_bits_wrapper_is_its_method
#print axioms NonosExtraction.X8664TimePitChannel.the_channel_readback_bit_wrapper_is_its_method

end NonosExtraction.X8664TimePitChannel
