// NONOS Operating System (AGPL-3.0-or-later)

pub mod gdt;

pub use gdt::{IST_DEBUG, IST_DOUBLE_FAULT, IST_GP, IST_MACHINE_CHECK, IST_NMI, IST_PAGE_FAULT, SEL_KERNEL_CODE, SEL_KERNEL_DATA, SEL_NULL, SEL_TSS, SEL_USER_CODE, SEL_USER_DATA};
