pub mod appearance;
mod appearance_rows;
mod apps;
mod commit;
mod dispatch;
mod host;
pub mod keyboard;
pub mod keyboard_live;
pub mod local_software;
pub mod mode;
mod name;
mod network;
mod network_lines;
pub mod privacy;
mod qwen;
mod qwen_rows;
pub mod review;
pub mod route;
mod review_lines;
pub mod timezone;
pub mod unsaved;

pub use dispatch::{draw, on_key};
